# Seed content source for Grade 7. Run build_curriculum.py to regenerate curriculum.json.
from grade6 import Q, EX

GRADE7 = {"grade": 7, "subjects": [
 {"name": "Mathematics", "icon": "🔢", "chapters": [
  {"name": "Integers",
   "explanation": "Integers are the whole numbers together with their negatives: ..., −3, −2, −1, 0, 1, 2, 3, .... On a number line, numbers to the right are bigger. Adding a positive number moves right, and adding a negative number moves left. Subtracting a number is the same as adding its opposite. When multiplying or dividing, two numbers with the same sign give a positive answer, and two numbers with different signs give a negative answer.",
   "keyPoints": ["Integers include negative numbers, zero and positive numbers.",
                 "On a number line, right is bigger.",
                 "Subtracting is adding the opposite: 5 − (−2) = 5 + 2.",
                 "Same signs multiply to positive.",
                 "Different signs multiply to negative."],
   "examples": [EX("Number line", "−3 is to the left of 2, so −3 < 2.", "−3 −2 −1  0  1  2  3"),
                EX("Adding negatives", "4 + (−6) = −2. Start at 4 and move 6 steps left.", "4 → 3 → 2 → 1 → 0 → −1 → −2"),
                EX("Multiplying signs", "(−3) × (−4) = 12, but (−3) × 4 = −12.")],
   "activity": "Record the temperature in two cities on a cold day and find the difference.",
   "questions": [
     Q("EASY", "Which is greater: −5 or 2?", ["−5", "2"], "2", "Which is further right on the number line?", "Positive numbers are always greater than negative numbers."),
     Q("EASY", "What is 7 + (−3)?", [], "4", "Adding a negative means moving left.", "7 − 3 = 4."),
     Q("MEDIUM", "What is (−4) × (−5)?", [], "20", "Same signs give a positive answer.", "4 × 5 = 20, and the signs are the same, so +20."),
     Q("MEDIUM", "What is 3 − (−6)?", [], "9", "Subtracting a negative is adding.", "3 − (−6) = 3 + 6 = 9."),
     Q("HARD", "What is (−48) ÷ 6?", [], "-8|−8", "Different signs give a negative answer.", "48 ÷ 6 = 8; different signs, so −8."),
     Q("HARD", "The temperature was −2°C and dropped by 5°C. What is it now (°C)?", [], "-7|−7|-7°c|−7°c", "Dropping means subtracting.", "−2 − 5 = −7°C.")]},
  {"name": "Fractions and Decimals",
   "explanation": "A fraction shows part of a whole, written as numerator over denominator. To add or subtract fractions with the same denominator, add or subtract the numerators. With different denominators, first make them equal using the LCM. To multiply fractions, multiply the numerators and multiply the denominators. To divide by a fraction, multiply by its reciprocal (flip it). Decimals are another way to write fractions with denominators like 10 or 100: 0.5 = 5/10.",
   "keyPoints": ["A fraction is part of a whole.",
                 "Same denominators: just add the tops.",
                 "Multiply fractions: top × top, bottom × bottom.",
                 "Divide by a fraction: flip it and multiply.",
                 "0.5 is the same as 5/10 or 1/2."],
   "examples": [EX("Adding fractions", "1/4 + 2/4 = 3/4.", "🍕🍕⬜⬜ + ... → 3 of 4 slices"),
                EX("Multiplying fractions", "2/3 × 3/5 = 6/15 = 2/5."),
                EX("Decimal to fraction", "0.25 = 25/100 = 1/4.")],
   "activity": "Cut a paper into 8 equal parts. Shade 3/8 and write it as a decimal.",
   "questions": [
     Q("EASY", "What is 1/5 + 2/5?", ["3/5", "3/10", "2/5", "1/5"], "3/5", "The denominators are the same.", "Add the numerators: 1 + 2 = 3, so 3/5."),
     Q("EASY", "Write 0.5 as a fraction in simplest form.", ["1/2", "5/1", "1/5", "5/100"], "1/2", "0.5 = 5/10.", "5/10 simplifies to 1/2."),
     Q("MEDIUM", "What is 2/3 × 3/4?", ["1/2", "6/7", "5/7", "2/4"], "1/2", "Multiply tops and bottoms, then simplify.", "6/12 = 1/2."),
     Q("MEDIUM", "What is 1/2 + 1/3?", ["2/5", "5/6", "1/6", "2/6"], "5/6", "Make the denominators 6.", "3/6 + 2/6 = 5/6."),
     Q("HARD", "What is 3/4 ÷ 1/2?", ["3/8", "3/2", "2/3", "1/2"], "3/2", "Flip the second fraction and multiply.", "3/4 × 2/1 = 6/4 = 3/2."),
     Q("HARD", "What is 2.5 × 0.4?", [], "1|1.0", "25 × 4 = 100; count the decimal places.", "2.5 × 0.4 = 1.00 = 1.")]},
  {"name": "Simple Equations",
   "explanation": "An equation is a statement that two expressions are equal, such as x + 3 = 7. The letter x is a variable, an unknown number. To solve an equation, we find the value of the variable that makes it true. Whatever we do to one side, we must do to the other side to keep it balanced, just like a weighing scale. We can add, subtract, multiply or divide both sides by the same number (except dividing by zero).",
   "keyPoints": ["An equation says two sides are equal.",
                 "The variable is the unknown number.",
                 "Do the same thing to both sides.",
                 "Undo addition with subtraction.",
                 "Undo multiplication with division."],
   "examples": [EX("Balancing", "x + 3 = 7. Take 3 from both sides: x = 4.", "⚖️  x + 3 | 7  →  x | 4"),
                EX("Division", "4x = 20. Divide both sides by 4: x = 5."),
                EX("Two steps", "2x + 1 = 11 → 2x = 10 → x = 5.")],
   "activity": "Think of a number, double it and add 3. Ask a friend to find your number from the result.",
   "questions": [
     Q("EASY", "Solve: x + 5 = 9. x = ?", [], "4", "Take 5 from both sides.", "9 − 5 = 4."),
     Q("EASY", "Solve: 3x = 12. x = ?", [], "4", "Divide both sides by 3.", "12 ÷ 3 = 4."),
     Q("MEDIUM", "Solve: x − 7 = 10. x = ?", [], "17", "Add 7 to both sides.", "10 + 7 = 17."),
     Q("MEDIUM", "Solve: x/4 = 5. x = ?", [], "20", "Multiply both sides by 4.", "5 × 4 = 20."),
     Q("HARD", "Solve: 2x + 3 = 15. x = ?", [], "6", "First subtract 3, then divide by 2.", "2x = 12, so x = 6."),
     Q("HARD", "Three times a number minus 4 is 11. What is the number?", [], "5", "Write 3x − 4 = 11.", "3x = 15, so x = 5.")]}]},
 {"name": "Science", "icon": "🔬", "chapters": [
  {"name": "Nutrition in Plants",
   "explanation": "Green plants make their own food, so they are called autotrophs. They do this through photosynthesis, which happens mainly in the leaves. Leaves contain a green pigment called chlorophyll that captures sunlight. Using sunlight, plants combine carbon dioxide from the air and water from the soil to make glucose (food), and they release oxygen. Carbon dioxide enters through tiny pores called stomata. Some plants, like Cuscuta, cannot make their own food and are parasites.",
   "keyPoints": ["Plants make their own food: they are autotrophs.",
                 "Food is made in leaves by photosynthesis.",
                 "Chlorophyll is the green pigment that traps sunlight.",
                 "Plants take in carbon dioxide and give out oxygen.",
                 "Stomata are tiny pores on leaves."],
   "examples": [EX("Photosynthesis", "Carbon dioxide + water → (sunlight, chlorophyll) → glucose + oxygen.", "☀️ + 🌿 + 💧 + CO₂ → 🍬 + O₂"),
                EX("Starch test on a leaf", "A leaf kept in sunlight turns blue-black with iodine, showing starch was made."),
                EX("Parasite plant", "Cuscuta (amarbel) takes food from the host plant it wraps around.")],
   "activity": "Cover part of a potted plant's leaf with black paper for two days, then compare it with an uncovered leaf.",
   "questions": [
     Q("EASY", "Where does photosynthesis mainly take place?", ["Roots", "Leaves", "Flowers", "Stem"], "Leaves", "Which part is green and flat?", "Leaves are the food factories of the plant."),
     Q("EASY", "Which gas do plants take in for photosynthesis?", ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], "Carbon dioxide", "We breathe this gas out.", "Plants use carbon dioxide to make food."),
     Q("MEDIUM", "What is the green pigment in leaves called?", [], "chlorophyll", "It starts with 'chloro-'.", "Chlorophyll traps sunlight."),
     Q("MEDIUM", "Tiny pores on leaves are called ___.", ["Stomata", "Roots", "Veins", "Petals"], "Stomata", "Gases pass through them.", "Stomata let gases in and out."),
     Q("HARD", "Plants that make their own food are called ___.", ["Heterotrophs", "Autotrophs", "Parasites", "Saprotrophs"], "Autotrophs", "'Auto' means self.", "Autotrophs make their own food."),
     Q("HARD", "Cuscuta is an example of a ___ plant.", ["Parasitic", "Insectivorous", "Autotrophic", "Symbiotic"], "Parasitic", "It lives on another plant and takes its food.", "Cuscuta is a parasite on its host plant.")]},
  {"name": "Heat",
   "explanation": "Heat is a form of energy that flows from a hotter object to a colder object. Temperature tells us how hot or cold something is and is measured with a thermometer in degrees Celsius (°C). Normal human body temperature is about 37°C. Heat moves in three ways: conduction through solids, convection through liquids and gases, and radiation, which needs no medium. Metals are good conductors of heat, while wood and plastic are poor conductors, also called insulators.",
   "keyPoints": ["Heat flows from hot to cold.",
                 "A thermometer measures temperature.",
                 "Normal body temperature is about 37°C.",
                 "Conduction, convection and radiation move heat.",
                 "Metals conduct heat. Wood and plastic insulate."],
   "examples": [EX("Conduction", "A metal spoon in hot tea becomes hot at the handle.", "🔥 → 🥄 → ✋"),
                EX("Convection", "Hot water rises and cold water sinks, making a current in a pot.", "⬆️ hot  ⬇️ cold"),
                EX("Radiation", "We feel the Sun's heat even through empty space.", "☀️ ~~~> 🌍")],
   "activity": "Touch a steel spoon and a wooden spoon kept in the same place. Which feels colder and why?",
   "questions": [
     Q("EASY", "Which instrument measures temperature?", ["Barometer", "Thermometer", "Ruler", "Compass"], "Thermometer", "'Thermo' means heat.", "A thermometer measures temperature."),
     Q("EASY", "Heat flows from a ___ object to a ___ object.", ["hot, cold", "cold, hot", "big, small", "small, big"], "hot, cold", "Think of ice melting in your hand.", "Heat always flows from hotter to colder."),
     Q("MEDIUM", "Normal human body temperature is about ___ °C.", [], "37", "It is between 36 and 38.", "Normal body temperature is about 37°C."),
     Q("MEDIUM", "Which is a good conductor of heat?", ["Wood", "Plastic", "Copper", "Cloth"], "Copper", "Cooking pots are often made of it.", "Metals like copper conduct heat well."),
     Q("HARD", "How does heat from the Sun reach the Earth?", ["Conduction", "Convection", "Radiation", "Evaporation"], "Radiation", "There is no air in space.", "Radiation does not need a medium."),
     Q("HARD", "Sea breeze during the day is an example of ___.", ["Conduction", "Convection", "Radiation", "Insulation"], "Convection", "Warm air over land rises; cool air from the sea moves in.", "Moving air currents carry heat: convection.")]},
  {"name": "Acids, Bases and Salts",
   "explanation": "Acids taste sour, like lemon juice and vinegar. Bases taste bitter and feel soapy, like baking soda and soap. We should never taste unknown substances; instead we use indicators. Litmus is a natural indicator: acids turn blue litmus red, and bases turn red litmus blue. Turmeric turns red with bases. When an acid and a base react, they cancel each other out in a reaction called neutralisation, forming salt and water.",
   "keyPoints": ["Acids taste sour.",
                 "Bases taste bitter and feel soapy.",
                 "Acids turn blue litmus red.",
                 "Bases turn red litmus blue.",
                 "Acid + base → salt + water (neutralisation)."],
   "examples": [EX("Everyday acids", "Lemon juice (citric acid), curd (lactic acid), vinegar (acetic acid).", "🍋 🥛 🫙 → sour"),
                EX("Litmus test", "Dip blue litmus paper in lemon juice: it turns red.", "🔵 + 🍋 → 🔴"),
                EX("Neutralisation", "An ant sting is acidic; applying baking soda (a base) relieves it.")],
   "activity": "Rub turmeric on a paper and put a drop of soap solution on it. What colour do you see?",
   "questions": [
     Q("EASY", "Acids taste ___.", ["Sour", "Bitter", "Sweet", "Salty"], "Sour", "Think of lemon.", "Acids taste sour."),
     Q("EASY", "Which of these is a base?", ["Lemon juice", "Vinegar", "Baking soda", "Curd"], "Baking soda", "Bases feel soapy.", "Baking soda is a base."),
     Q("MEDIUM", "Acids turn blue litmus ___.", ["Red", "Green", "Yellow", "Blue"], "Red", "Acid → red.", "Acids turn blue litmus red."),
     Q("MEDIUM", "Turmeric turns ___ with a base.", ["Red", "Blue", "Green", "White"], "Red", "Try soap on a turmeric stain.", "Turmeric turns red in a base."),
     Q("HARD", "An acid reacting with a base is called ___.", [], "neutralisation|neutralization", "They cancel each other out.", "Acid + base → salt + water is neutralisation."),
     Q("HARD", "Which acid is found in curd?", ["Citric acid", "Lactic acid", "Acetic acid", "Tartaric acid"], "Lactic acid", "It is linked to milk.", "Curd contains lactic acid.")]}]},
 {"name": "English", "icon": "📖", "chapters": [
  {"name": "Adverbs",
   "explanation": "An adverb tells us more about a verb, an adjective or another adverb. Adverbs answer questions like how, when, where and how often. Adverbs of manner tell how (slowly, carefully). Adverbs of time tell when (now, yesterday). Adverbs of place tell where (here, outside). Adverbs of frequency tell how often (always, never, sometimes). Many adverbs of manner end in -ly.",
   "keyPoints": ["An adverb tells more about a verb.",
                 "How: slowly, carefully.",
                 "When: now, yesterday.",
                 "Where: here, outside.",
                 "How often: always, never, sometimes."],
   "examples": [EX("Manner", "She sings sweetly. (How does she sing? Sweetly.)"),
                EX("Time", "We will leave tomorrow. (When? Tomorrow.)"),
                EX("Frequency", "He always brushes his teeth. (How often? Always.)")],
   "activity": "Write three sentences about your morning using an adverb of manner, time and frequency.",
   "questions": [
     Q("EASY", "Find the adverb: 'The tortoise walked slowly.'", ["tortoise", "walked", "slowly", "the"], "slowly", "How did it walk?", "'Slowly' tells how it walked."),
     Q("EASY", "Which word is an adverb of time?", ["quickly", "yesterday", "here", "happy"], "yesterday", "It answers 'when?'.", "'Yesterday' tells when."),
     Q("MEDIUM", "Make an adverb from 'careful'.", [], "carefully", "Add -ly.", "careful → carefully."),
     Q("MEDIUM", "'She never eats meat.' What kind of adverb is 'never'?", ["Manner", "Place", "Frequency", "Time"], "Frequency", "It answers 'how often?'.", "'Never' is an adverb of frequency."),
     Q("HARD", "Find the adverb: 'The movie was extremely long.'", ["movie", "was", "extremely", "long"], "extremely", "Which word describes the adjective 'long'?", "'Extremely' tells how long — it modifies an adjective."),
     Q("HARD", "Choose the correct sentence.", ["He runs quick.", "He runs quickly.", "He quick runs.", "He runs quicker."], "He runs quickly.", "Use an adverb to describe the verb 'runs'.", "'Quickly' is the adverb that describes 'runs'.")]},
  {"name": "Prepositions",
   "explanation": "A preposition shows the relationship between a noun or pronoun and another word in the sentence. Prepositions often tell us about position (on, under, between), direction (to, into, towards) or time (at, on, in). We use 'at' for exact times (at 5 o'clock), 'on' for days and dates (on Monday), and 'in' for months, years and longer periods (in May, in 2020).",
   "keyPoints": ["A preposition shows position, direction or time.",
                 "Position: on, under, between, behind.",
                 "Direction: to, into, towards.",
                 "'at' for times, 'on' for days, 'in' for months and years.",
                 "A preposition comes before a noun or pronoun."],
   "examples": [EX("Position", "The cat is under the table.", "🐈 ⬇ 🪑"),
                EX("Direction", "She walked into the room."),
                EX("Time", "at 7 a.m. / on Sunday / in July")],
   "activity": "Describe where five objects are in your room using different prepositions.",
   "questions": [
     Q("EASY", "The book is ___ the table.", ["on", "at", "in", "to"], "on", "It is resting on top.", "'On' shows the book is on the surface."),
     Q("EASY", "Which word is a preposition?", ["under", "run", "blue", "happy"], "under", "It shows position.", "'Under' shows position."),
     Q("MEDIUM", "My birthday is ___ May.", ["at", "on", "in", "to"], "in", "Use this for months.", "We use 'in' for months."),
     Q("MEDIUM", "The train leaves ___ 6 o'clock.", ["in", "on", "at", "by"], "at", "Use this for exact times.", "We use 'at' for exact times."),
     Q("HARD", "Divide the sweets ___ the two children.", ["among", "between", "in", "with"], "between", "Use this for two people.", "'Between' is used for two; 'among' for more than two."),
     Q("HARD", "She jumped ___ the pool.", ["in", "into", "at", "on"], "into", "It shows movement from outside to inside.", "'Into' shows movement inside something.")]},
  {"name": "Active and Passive Voice",
   "explanation": "In the active voice, the subject does the action: 'Ravi wrote a letter.' In the passive voice, the subject receives the action: 'A letter was written by Ravi.' To change active to passive, move the object to the front, use a form of 'be' with the past participle of the verb, and add 'by' + the doer if needed. The passive voice is useful when the doer is unknown or less important.",
   "keyPoints": ["Active: the subject does the action.",
                 "Passive: the subject receives the action.",
                 "Passive uses 'be' + past participle (was written).",
                 "The doer comes after 'by'.",
                 "Use passive when the doer is unknown."],
   "examples": [EX("Active to passive", "The cat chased the mouse. → The mouse was chased by the cat.", "🐈 → 🐭   becomes   🐭 ← by 🐈"),
                EX("Present tense", "She cleans the room. → The room is cleaned by her."),
                EX("Unknown doer", "My bicycle was stolen. (We don't know who stole it.)")],
   "activity": "Find two passive sentences in a newspaper and rewrite them in the active voice.",
   "questions": [
     Q("EASY", "'Mira sings a song.' Is this active or passive?", ["Active", "Passive"], "Active", "Does the subject do the action?", "Mira (the subject) does the action, so it is active."),
     Q("EASY", "'The cake was eaten by Tom.' Is this active or passive?", ["Active", "Passive"], "Passive", "Look for 'was' + past participle and 'by'.", "The cake receives the action — passive."),
     Q("MEDIUM", "Passive of 'The boy kicked the ball'?", ["The ball kicked the boy.", "The ball was kicked by the boy.", "The ball is kicked by the boy.", "The boy was kicked by the ball."], "The ball was kicked by the boy.", "The past tense uses 'was'.", "Object first, then 'was kicked', then 'by the boy'."),
     Q("MEDIUM", "Passive of 'She writes a letter'?", ["A letter was written by her.", "A letter is written by her.", "A letter is wrote by her.", "Her writes a letter."], "A letter is written by her.", "Present tense uses 'is'.", "Present tense → 'is written'; 'she' becomes 'her'."),
     Q("HARD", "Active of 'The window was broken by Sam'?", ["Sam breaks the window.", "Sam broke the window.", "Sam has broken the window.", "The window broke Sam."], "Sam broke the window.", "'Was broken' is past tense.", "The doer Sam comes first; past tense 'broke'."),
     Q("HARD", "Past participle of 'write' used in the passive voice?", [], "written", "It is irregular: write → wrote → ?", "write → wrote → written.")]}]}]}

SOCIAL_SCIENCE_7 = {"name": "Social Science", "icon": "🌍", "chapters": [
  {"name": "Environment",
   "explanation": "The environment is everything around us: living things like plants, animals and people, and non-living things like air, water and land. The natural environment includes the lithosphere (land), hydrosphere (water), atmosphere (air) and biosphere (the zone where life exists). The human-made environment includes buildings, roads and bridges. An ecosystem is a system in which living things interact with each other and with their surroundings. Humans change the environment, so we must protect it.",
   "keyPoints": ["The environment is everything around us.",
                 "Land, water and air are natural parts of the environment.",
                 "The biosphere is where life exists.",
                 "Roads and buildings are human-made environment.",
                 "An ecosystem is living and non-living things working together."],
   "examples": [EX("Four spheres", "Mountains (lithosphere), oceans (hydrosphere), air (atmosphere), living things (biosphere).", "⛰️ 🌊 💨 🌳"),
                EX("Ecosystem", "In a pond, fish, frogs, plants, water and sunlight all depend on each other.", "🐟 🐸 🌿 💧 ☀️"),
                EX("Human-made", "A bridge over a river is part of the human-made environment.", "🌉")],
   "activity": "List five natural and five human-made things you can see from your window.",
   "questions": [
     Q("EASY", "Which of these is human-made?", ["River", "Mountain", "Bridge", "Forest"], "Bridge", "People built it.", "A bridge is made by humans."),
     Q("EASY", "The layer of air around the Earth is the ___.", ["Lithosphere", "Hydrosphere", "Atmosphere", "Biosphere"], "Atmosphere", "'Atmo' refers to air/vapour.", "The atmosphere is the air around us."),
     Q("MEDIUM", "The water part of the Earth is called the ___.", ["Hydrosphere", "Lithosphere", "Biosphere", "Atmosphere"], "Hydrosphere", "'Hydro' means water.", "The hydrosphere includes oceans, rivers and lakes."),
     Q("MEDIUM", "The zone where land, water and air meet to support life is the ___.", ["Biosphere", "Lithosphere", "Hydrosphere", "Stratosphere"], "Biosphere", "'Bio' means life.", "The biosphere is where life exists."),
     Q("HARD", "A system where living things interact with each other and their surroundings is called an ___.", [], "ecosystem", "It starts with 'eco'.", "That system is an ecosystem."),
     Q("HARD", "Which is the best way to protect the environment?", ["Cutting more trees", "Reducing, reusing and recycling", "Burning plastic", "Wasting water"], "Reducing, reusing and recycling", "The three Rs.", "Reduce, reuse and recycle lowers waste and pollution.")]},
  {"name": "Inside Our Earth",
   "explanation": "The Earth is made of three main layers. The outermost layer is the crust, which is thin and on which we live. Below it is the mantle, a thick layer of very hot, partly molten rock. At the centre is the core, made mostly of nickel and iron and extremely hot. Rocks found in the crust are of three types: igneous rocks form when molten magma cools, sedimentary rocks form from layers of small particles pressed together, and metamorphic rocks form when other rocks change under great heat and pressure.",
   "keyPoints": ["The Earth has three layers: crust, mantle and core.",
                 "We live on the crust.",
                 "The core is made of nickel and iron.",
                 "Igneous rocks form from cooled magma.",
                 "Heat and pressure change rocks into metamorphic rocks."],
   "examples": [EX("Layers like a peach", "The skin is the crust, the fruit is the mantle and the seed is the core.", "🍑 skin = crust | fruit = mantle | seed = core"),
                EX("Rock cycle", "Granite is igneous, sandstone is sedimentary and marble is metamorphic (from limestone)."),
                EX("Volcano", "Magma rising through the crust and coming out is called lava.", "🌋")],
   "activity": "Collect three different stones and compare their colour, weight and texture.",
   "questions": [
     Q("EASY", "The outermost layer of the Earth is the ___.", ["Core", "Mantle", "Crust", "Atmosphere"], "Crust", "It is the layer we live on.", "The crust is the outer layer."),
     Q("EASY", "The innermost layer of the Earth is the ___.", ["Core", "Crust", "Mantle", "Surface"], "Core", "It is at the centre.", "The core is at the centre."),
     Q("MEDIUM", "Rocks formed when molten magma cools are called ___ rocks.", ["Igneous", "Sedimentary", "Metamorphic", "Fossil"], "Igneous", "'Ignis' means fire.", "Cooled magma forms igneous rocks."),
     Q("MEDIUM", "The core is made mainly of ___.", ["Silica and aluminium", "Nickel and iron", "Gold and silver", "Water and air"], "Nickel and iron", "Its short name is 'nife'.", "The core is mainly nickel (Ni) and iron (Fe)."),
     Q("HARD", "Marble is an example of which type of rock?", ["Igneous", "Sedimentary", "Metamorphic"], "Metamorphic", "It forms when limestone is changed by heat and pressure.", "Limestone changes into marble — metamorphic rock."),
     Q("HARD", "Rocks formed from layers of small particles pressed together are ___ rocks.", [], "sedimentary", "The particles are called sediments.", "Sediments compressed over time form sedimentary rocks.")]},
  {"name": "On Equality",
   "explanation": "Equality means every person is treated with the same respect and has the same rights, whatever their religion, caste, gender or whether they are rich or poor. In a democracy like India, every adult citizen has one vote, which is called universal adult franchise. The Constitution of India says that all persons are equal before the law. The government runs programmes such as the mid-day meal scheme to help reduce inequality. Even so, many people still face unfair treatment, so we must keep working towards equality.",
   "keyPoints": ["Equality means the same respect and rights for everyone.",
                 "Every adult citizen has one vote.",
                 "This is called universal adult franchise.",
                 "The Constitution says all are equal before the law.",
                 "Schemes like the mid-day meal help reduce inequality."],
   "examples": [EX("One person, one vote", "A rich businessperson and a farmer each have exactly one vote.", "🗳️ = 🗳️"),
                EX("Mid-day meal", "Free lunch in government schools helps children from poor families attend school."),
                EX("Equal before the law", "The same law applies to a minister and to an ordinary citizen.", "⚖️")],
   "activity": "Discuss with your family: can you think of a time when someone was treated unfairly? What could have been done?",
   "questions": [
     Q("EASY", "In India, how many votes does each adult citizen have?", [], "1|one", "Rich or poor, it's the same.", "Each adult citizen has one vote."),
     Q("EASY", "Equality means everyone gets ___.", ["The same respect and rights", "The same clothes", "The same job", "The same house"], "The same respect and rights", "It is about fairness.", "Equality is about equal dignity and rights."),
     Q("MEDIUM", "The right of every adult to vote is called ___.", ["Universal adult franchise", "Monarchy", "Reservation", "Taxation"], "Universal adult franchise", "'Franchise' means the right to vote.", "Every adult voting is universal adult franchise."),
     Q("MEDIUM", "Which scheme gives free lunch to children in government schools?", ["Mid-day meal scheme", "Pension scheme", "Crop insurance", "Road scheme"], "Mid-day meal scheme", "It is served in the middle of the school day.", "The mid-day meal scheme provides cooked lunch."),
     Q("HARD", "Which document says all persons are equal before the law in India?", ["The Constitution", "A newspaper", "A school timetable", "A textbook"], "The Constitution", "It is the supreme law of the country.", "The Constitution of India guarantees equality."),
     Q("HARD", "At what age can Indian citizens vote?", [], "18", "It is the age when you become an adult legally.", "The voting age in India is 18.")]}]}

GRADE7["subjects"].append(SOCIAL_SCIENCE_7)
