# Seed content source for Grade 6. Run build_curriculum.py to regenerate curriculum.json.
# Q(difficulty, prompt, options, answer, hint, explanation) — options=[] means typed answer.

def Q(d, prompt, options, answer, hint, explanation):
    return {"difficulty": d, "prompt": prompt, "options": options, "answer": answer, "hint": hint, "explanation": explanation}

def EX(title, content, visual=""):
    return {"title": title, "content": content, "visual": visual}

GRADE6 = {"grade": 6, "subjects": [
 {"name": "Mathematics", "icon": "🔢", "chapters": [
  {"name": "Knowing Our Numbers",
   "explanation": "Numbers help us count and compare things. Every digit in a number has a place value, such as ones, tens, hundreds and thousands. To compare two numbers, first count their digits: the number with more digits is bigger. If they have the same number of digits, compare them digit by digit from the left. We can also write numbers in ascending order (smallest to largest) or descending order (largest to smallest). Estimation means rounding a number to a nearby, easier number.",
   "keyPoints": ["Each digit has a place: ones, tens, hundreds, thousands.",
                 "More digits means a bigger number.",
                 "Same number of digits? Compare from the left.",
                 "Ascending means small to big. Descending means big to small.",
                 "Rounding gives a nearby, easy number."],
   "examples": [EX("Place value", "In 4,582 the digit 5 is in the hundreds place, so its value is 500.", "4 thousands | 5 hundreds | 8 tens | 2 ones"),
                EX("Comparing numbers", "Compare 7,289 and 7,298. The thousands and hundreds are the same. In the tens place 8 < 9, so 7,289 < 7,298."),
                EX("Rounding", "Round 67 to the nearest ten. 67 is closer to 70 than to 60, so it rounds to 70.", "60 ... 65 ... 67 → 70")],
   "activity": "Write the ages of three family members and arrange them in ascending and descending order.",
   "questions": [
     Q("EASY", "Which number is the biggest?", ["899", "1,002", "998", "989"], "1,002", "Count the digits in each number first.", "1,002 has four digits; the others have three, so 1,002 is the biggest."),
     Q("EASY", "What is the place value of 3 in 4,315?", ["3", "30", "300", "3,000"], "300", "Is 3 in the ones, tens, or hundreds place?", "3 is in the hundreds place, so its value is 3 × 100 = 300."),
     Q("EASY", "Write 'two thousand five' in numbers.", [], "2005|2,005", "Two thousand is 2000. Then add 5.", "Two thousand five = 2000 + 5 = 2005."),
     Q("MEDIUM", "Arrange in ascending order: 5,432; 5,423; 5,342", ["5,342; 5,423; 5,432", "5,432; 5,423; 5,342", "5,423; 5,342; 5,432", "5,342; 5,432; 5,423"], "5,342; 5,423; 5,432", "Ascending means smallest first. Compare the hundreds digits.", "Hundreds digits are 4, 4 and 3, so 5,342 is smallest. Then 5,423 < 5,432 because 2 < 3 in the tens place."),
     Q("MEDIUM", "Round 4,768 to the nearest hundred.", ["4,700", "4,800", "5,000", "4,760"], "4,800", "Look at the tens digit. Is it 5 or more?", "The tens digit is 6 (5 or more), so we round up: 4,768 → 4,800."),
     Q("MEDIUM", "What is the smallest 4-digit number?", [], "1000|1,000", "A 4-digit number cannot start with 0.", "The smallest 4-digit number is 1,000; 999 has only three digits."),
     Q("HARD", "Using the digits 3, 8, 1, 6 once each, what is the greatest 4-digit number?", [], "8631|8,631", "Put the biggest digit in the thousands place, then the next biggest.", "Arrange digits from biggest to smallest: 8, 6, 3, 1 → 8,631."),
     Q("HARD", "How many thousands make one lakh?", [], "100", "1 lakh = 1,00,000.", "1,00,000 ÷ 1,000 = 100, so 100 thousands make one lakh."),
     Q("HARD", "Estimate 389 + 512 by rounding each number to the nearest hundred.", ["800", "900", "1,000", "901"], "900", "389 rounds to 400 and 512 rounds to 500.", "400 + 500 = 900. The exact answer 901 is very close.")]},
  {"name": "Whole Numbers",
   "explanation": "Whole numbers are 0, 1, 2, 3 and so on. They are the natural numbers together with zero. Every whole number has a successor (the number just after it) and every whole number except 0 has a predecessor (the number just before it). Whole numbers can be shown on a number line. Addition and multiplication of whole numbers follow useful properties: order does not matter (commutative), grouping does not matter (associative), and multiplication distributes over addition.",
   "keyPoints": ["Whole numbers start at 0: 0, 1, 2, 3 ...",
                 "Successor means the next number. Predecessor means the number before.",
                 "0 has no whole-number predecessor.",
                 "a + b = b + a and a × b = b × a.",
                 "a × (b + c) = a × b + a × c."],
   "examples": [EX("Successor and predecessor", "The successor of 19 is 20. The predecessor of 19 is 18.", "18 ← 19 → 20"),
                EX("Order does not matter", "3 + 5 = 8 and 5 + 3 = 8. Same answer!", "🍎🍎🍎 + 🍎🍎🍎🍎🍎 = 🍎🍎🍎🍎🍎 + 🍎🍎🍎"),
                EX("Distributive property", "6 × 102 = 6 × (100 + 2) = 600 + 12 = 612.")],
   "activity": "Draw a number line from 0 to 10 and jump in steps of 2. Which numbers do you land on?",
   "questions": [
     Q("EASY", "What is the successor of 99?", [], "100", "Successor means add 1.", "99 + 1 = 100."),
     Q("EASY", "What is the smallest whole number?", ["1", "0", "-1", "10"], "0", "Whole numbers include zero.", "Whole numbers start at 0."),
     Q("EASY", "What is the predecessor of 50?", [], "49", "Predecessor means subtract 1.", "50 − 1 = 49."),
     Q("MEDIUM", "Which property is shown: 7 + 4 = 4 + 7?", ["Commutative", "Associative", "Distributive", "Identity"], "Commutative", "Only the order of the numbers changed.", "Changing the order without changing the answer is the commutative property."),
     Q("MEDIUM", "What is 25 × 4 × 7? (Hint: group smartly)", [], "700", "Multiply 25 × 4 first.", "25 × 4 = 100, and 100 × 7 = 700."),
     Q("MEDIUM", "How many whole numbers are there between 10 and 15?", [], "4", "List them: 11, 12, ...", "11, 12, 13 and 14 are between 10 and 15 — that is 4 numbers."),
     Q("HARD", "Use the distributive property: 9 × 105 = ?", [], "945", "9 × 105 = 9 × 100 + 9 × 5.", "900 + 45 = 945."),
     Q("HARD", "What is 854 × 102 using 854 × (100 + 2)?", [], "87108|87,108", "Find 854 × 100 and 854 × 2, then add.", "85,400 + 1,708 = 87,108."),
     Q("HARD", "Which number, when multiplied by any whole number, always gives 0?", ["1", "0", "10", "No such number"], "0", "Think about 0 × 5, 0 × 100 ...", "Any number times 0 is 0.")]},
  {"name": "Playing With Numbers",
   "explanation": "A factor of a number divides it exactly with no remainder. A multiple of a number is what you get when you multiply it by 1, 2, 3 and so on. A prime number has exactly two factors: 1 and itself. A composite number has more than two factors. The number 1 is neither prime nor composite. Divisibility rules help us check quickly: a number is divisible by 2 if it is even, by 5 if it ends in 0 or 5, by 3 if the sum of its digits is divisible by 3, and by 10 if it ends in 0.",
   "keyPoints": ["A factor divides a number exactly.",
                 "A multiple is the number times 1, 2, 3 ...",
                 "A prime number has only two factors: 1 and itself.",
                 "1 is neither prime nor composite.",
                 "Divisible by 3: add the digits and check."],
   "examples": [EX("Factors of 12", "1, 2, 3, 4, 6 and 12 all divide 12 exactly.", "12 = 1×12 = 2×6 = 3×4"),
                EX("Multiples of 4", "4, 8, 12, 16, 20 ... are multiples of 4.", "4 → 8 → 12 → 16 → 20"),
                EX("Divisibility by 3", "Is 312 divisible by 3? 3 + 1 + 2 = 6, and 6 is divisible by 3, so yes.")],
   "activity": "Find all the prime numbers between 1 and 20 by crossing out multiples of 2, 3 and 5.",
   "questions": [
     Q("EASY", "Which of these is a factor of 10?", ["3", "4", "5", "6"], "5", "Which number divides 10 with no remainder?", "10 ÷ 5 = 2 exactly, so 5 is a factor of 10."),
     Q("EASY", "Which of these is a prime number?", ["4", "7", "9", "15"], "7", "A prime has only two factors.", "7 has only the factors 1 and 7."),
     Q("EASY", "What is the 3rd multiple of 6?", [], "18", "Multiply 6 by 3.", "6 × 3 = 18."),
     Q("MEDIUM", "Is 1,236 divisible by 3?", ["Yes", "No"], "Yes", "Add the digits: 1 + 2 + 3 + 6.", "1 + 2 + 3 + 6 = 12, which is divisible by 3, so 1,236 is divisible by 3."),
     Q("MEDIUM", "How many factors does 16 have?", [], "5", "List them in pairs: 1 × 16, 2 × 8 ...", "1, 2, 4, 8 and 16 — five factors."),
     Q("MEDIUM", "What is the HCF of 12 and 18?", [], "6", "Find the biggest number that divides both.", "Common factors are 1, 2, 3, 6. The highest is 6."),
     Q("HARD", "What is the LCM of 4 and 6?", [], "12", "List multiples of each until they match.", "Multiples of 4: 4, 8, 12. Multiples of 6: 6, 12. The lowest common one is 12."),
     Q("HARD", "Write the prime factorisation of 36.", ["2 × 2 × 3 × 3", "4 × 9", "6 × 6", "2 × 3 × 6"], "2 × 2 × 3 × 3", "Keep dividing by prime numbers until you reach 1.", "36 = 2 × 18 = 2 × 2 × 9 = 2 × 2 × 3 × 3. Only primes are used."),
     Q("HARD", "Which number is neither prime nor composite?", ["0", "1", "2", "Both 0 and 1"], "Both 0 and 1", "Think about how many factors each number has.", "1 has only one factor, and 0 is not counted as prime or composite either.")]},
  {"name": "Basic Geometrical Ideas",
   "explanation": "Geometry studies shapes and space. A point marks an exact location. A line segment is the straight path between two points and has a fixed length. A line goes on forever in both directions, while a ray starts at one point and goes on forever in one direction. Two lines that meet are called intersecting lines; lines that never meet are parallel. A polygon is a closed shape made of line segments, such as a triangle (3 sides) or a quadrilateral (4 sides). A circle is a shape where every point is the same distance from the centre.",
   "keyPoints": ["A point shows an exact place.",
                 "A line segment has two end points.",
                 "A ray has one end point and goes on forever.",
                 "Parallel lines never meet.",
                 "Triangle: 3 sides. Quadrilateral: 4 sides."],
   "examples": [EX("Line, segment, ray", "A segment AB stops at A and B. A ray AB starts at A and goes past B forever.", "A●———●B   (segment)\nA●———→    (ray)"),
                EX("Parallel lines", "Railway tracks are parallel — they never meet.", "════════\n════════"),
                EX("Circle parts", "The radius goes from the centre to the edge. The diameter goes across through the centre and is twice the radius.", "◯  diameter = 2 × radius")],
   "activity": "Look around your room. Find one example each of parallel lines, a triangle and a circle.",
   "questions": [
     Q("EASY", "How many sides does a triangle have?", [], "3|three", "'Tri' means three.", "A triangle has 3 sides."),
     Q("EASY", "Which one has two end points?", ["Line", "Ray", "Line segment", "Circle"], "Line segment", "Which one stops at both ends?", "A line segment stops at two end points."),
     Q("EASY", "Lines that never meet are called ___ lines.", ["Parallel", "Intersecting", "Curved", "Crossing"], "Parallel", "Think of railway tracks.", "Parallel lines never meet."),
     Q("MEDIUM", "If the radius of a circle is 5 cm, what is its diameter in cm?", [], "10|10 cm", "Diameter = 2 × radius.", "2 × 5 = 10 cm."),
     Q("MEDIUM", "A ray has how many end points?", [], "1|one", "It starts somewhere but never stops.", "A ray has exactly one end point."),
     Q("MEDIUM", "What is a polygon with 4 sides called?", ["Pentagon", "Quadrilateral", "Hexagon", "Triangle"], "Quadrilateral", "'Quad' means four.", "A 4-sided polygon is a quadrilateral."),
     Q("HARD", "How many line segments can be drawn through 3 points that are not in a straight line (joining every pair)?", [], "3|three", "Join each pair: AB, BC, ...", "AB, BC and CA — 3 segments, which form a triangle."),
     Q("HARD", "How many diagonals does a quadrilateral have?", [], "2|two", "A diagonal joins two corners that are not next to each other.", "In ABCD the diagonals are AC and BD — 2 diagonals."),
     Q("HARD", "Is a circle a polygon?", ["Yes", "No"], "No", "A polygon is made only of straight line segments.", "A circle is curved, so it is not a polygon.")]}]},
 {"name": "Science", "icon": "🔬", "chapters": [
  {"name": "Components of Food",
   "explanation": "Food contains nutrients that our body needs. The main nutrients are carbohydrates, proteins, fats, vitamins and minerals. Carbohydrates and fats give us energy. Proteins help the body grow and repair itself. Vitamins and minerals protect us from diseases. Food also contains dietary fibre (roughage), which helps digestion, and water. A balanced diet has all these nutrients in the right amounts. Not getting enough of a nutrient for a long time can cause deficiency diseases.",
   "keyPoints": ["Carbohydrates and fats give energy.",
                 "Proteins help us grow and repair.",
                 "Vitamins and minerals keep us healthy.",
                 "Roughage helps digestion.",
                 "A balanced diet has all nutrients."],
   "examples": [EX("Energy foods", "Rice, wheat and potatoes are rich in carbohydrates.", "🍚 🍞 🥔 → ⚡ energy"),
                EX("Body-building foods", "Dal, eggs, milk and fish are rich in proteins.", "🥚 🥛 🐟 → 💪 growth"),
                EX("Protective foods", "Fruits and vegetables give vitamins and minerals.", "🍊 🥕 🥦 → 🛡️ protection")],
   "activity": "Write down what you ate yesterday. Mark each food as energy, body-building or protective.",
   "questions": [
     Q("EASY", "Which nutrient mainly gives us energy?", ["Carbohydrates", "Vitamins", "Minerals", "Water"], "Carbohydrates", "Think of rice and bread.", "Carbohydrates are the body's main energy source."),
     Q("EASY", "Which food is rich in protein?", ["Rice", "Dal", "Sugar", "Butter"], "Dal", "Proteins are body-building foods.", "Dal (pulses) is rich in protein."),
     Q("EASY", "Roughage helps in ___.", ["Digestion", "Seeing", "Hearing", "Breathing"], "Digestion", "Roughage is also called dietary fibre.", "Roughage helps food move through the gut and supports digestion."),
     Q("MEDIUM", "Which vitamin do we get from sunlight?", ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], "Vitamin D", "It helps keep bones strong.", "Our skin makes Vitamin D in sunlight."),
     Q("MEDIUM", "Iodine solution turns ___ when starch is present.", ["Red", "Blue-black", "Yellow", "Green"], "Blue-black", "This is the starch test.", "Starch turns iodine blue-black."),
     Q("MEDIUM", "Scurvy is caused by lack of which vitamin?", ["Vitamin A", "Vitamin B1", "Vitamin C", "Vitamin D"], "Vitamin C", "Citrus fruits prevent it.", "Scurvy (bleeding gums) is due to lack of Vitamin C."),
     Q("HARD", "Night blindness is caused by lack of which vitamin?", ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], "Vitamin A", "Carrots are rich in this vitamin.", "Vitamin A deficiency causes poor vision in dim light."),
     Q("HARD", "Goitre is caused by lack of which mineral?", ["Iron", "Calcium", "Iodine", "Sodium"], "Iodine", "Iodised salt prevents it.", "Lack of iodine makes the thyroid gland swell (goitre)."),
     Q("HARD", "Which nutrient gives the MOST energy per gram?", ["Carbohydrates", "Proteins", "Fats", "Vitamins"], "Fats", "Think of butter and oil.", "Fats give about twice as much energy per gram as carbohydrates.")]},
  {"name": "Separation of Substances",
   "explanation": "We often need to separate mixtures to remove unwanted parts or collect useful ones. Handpicking removes large impurities like stones from grain. Threshing separates grain from stalks, and winnowing uses wind to separate light husk from heavier grain. Sieving separates particles of different sizes. Sedimentation lets heavy particles settle, decantation pours off the clear liquid, and filtration passes a liquid through a filter to remove solids. Evaporation turns water into vapour and leaves the dissolved solid, such as salt, behind.",
   "keyPoints": ["Handpicking removes stones by hand.",
                 "Winnowing uses wind to remove husk.",
                 "Sieving separates big and small pieces.",
                 "Filtration removes solids from liquid.",
                 "Evaporation leaves salt behind."],
   "examples": [EX("Sieving flour", "A sieve lets fine flour through and keeps bran and bigger bits on top.", "🌾 → [sieve] → fine flour ⬇"),
                EX("Making tea", "We use a strainer to filter tea leaves out of the tea.", "☕ + 🍃 → strainer → ☕"),
                EX("Salt from sea water", "Sea water is left in shallow pits. The sun evaporates the water, leaving salt.", "🌊 + ☀️ → 🧂")],
   "activity": "Mix sand and water in a glass. Wait 10 minutes and observe. Then gently pour the top water into another glass.",
   "questions": [
     Q("EASY", "Which method removes small stones from rice?", ["Handpicking", "Evaporation", "Filtration", "Boiling"], "Handpicking", "You can see and pick the stones.", "Stones are big and easy to see, so we pick them out by hand."),
     Q("EASY", "Which method separates tea leaves from tea?", ["Winnowing", "Filtration", "Evaporation", "Threshing"], "Filtration", "We use a strainer.", "A strainer is a filter: liquid passes through, leaves stay behind."),
     Q("EASY", "Which method uses wind to separate husk from grain?", ["Sieving", "Winnowing", "Sedimentation", "Handpicking"], "Winnowing", "Farmers drop grain from a height on a windy day.", "Wind blows the light husk away; heavy grain falls in a heap."),
     Q("MEDIUM", "How do we get salt from sea water?", ["Filtration", "Evaporation", "Sieving", "Decantation"], "Evaporation", "The sun heats the water.", "Water evaporates and salt is left behind."),
     Q("MEDIUM", "When heavier particles settle at the bottom of a liquid, it is called ___.", ["Sedimentation", "Decantation", "Condensation", "Winnowing"], "Sedimentation", "'Sediment' is the stuff at the bottom.", "Settling of heavy particles is sedimentation."),
     Q("MEDIUM", "Pouring off clear water without disturbing the sediment is called ___.", ["Filtration", "Decantation", "Evaporation", "Sieving"], "Decantation", "It usually comes after sedimentation.", "Carefully pouring off the liquid is decantation."),
     Q("HARD", "Which is the best order to separate sand and salt?", ["Dissolve in water → filter → evaporate", "Evaporate → filter → dissolve", "Sieve → winnow → filter", "Filter → dissolve → sieve"], "Dissolve in water → filter → evaporate", "Salt dissolves in water but sand does not.", "Salt dissolves; filtering removes sand; evaporating the salty water gives back the salt."),
     Q("HARD", "Water vapour changing back to liquid water is called ___.", ["Evaporation", "Condensation", "Sedimentation", "Melting"], "Condensation", "Think of water drops on a cold glass.", "Vapour cooling into liquid is condensation."),
     Q("HARD", "A solution that cannot dissolve any more of a substance is called ___.", ["Saturated", "Diluted", "Filtered", "Mixed"], "Saturated", "It is 'full'.", "A saturated solution holds as much solute as it can at that temperature.")]},
  {"name": "Motion and Measurement of Distances",
   "explanation": "Measurement means comparing a quantity with a standard unit. The standard unit of length is the metre (m). 1 metre = 100 centimetres, 1 centimetre = 10 millimetres, and 1 kilometre = 1000 metres. Using body parts like hand spans gives different results for different people, which is why standard units are needed. Motion means change in position over time. In rectilinear motion an object moves in a straight line, in circular motion it moves along a circle, and in periodic motion it repeats its movement after a fixed time.",
   "keyPoints": ["1 m = 100 cm.",
                 "1 km = 1000 m.",
                 "1 cm = 10 mm.",
                 "Straight line motion is rectilinear.",
                 "Repeating motion is periodic."],
   "examples": [EX("Converting units", "2.5 m = 2.5 × 100 = 250 cm.", "1 m = 📏📏📏... 100 cm"),
                EX("Circular motion", "The tip of a clock's hand moves in a circle.", "🕐 ↻"),
                EX("Periodic motion", "A swing goes back and forth again and again.", "↔ 🎠 ↔")],
   "activity": "Measure the length of your table using your hand span and then a ruler. Compare the results.",
   "questions": [
     Q("EASY", "What is the SI unit of length?", ["Kilogram", "Metre", "Second", "Litre"], "Metre", "Rulers show this unit.", "The metre (m) is the standard unit of length."),
     Q("EASY", "How many centimetres are in 1 metre?", [], "100", "Centi means hundredth.", "1 m = 100 cm."),
     Q("EASY", "A car moving on a straight road shows ___ motion.", ["Circular", "Rectilinear", "Periodic", "No"], "Rectilinear", "'Rectilinear' means along a straight line.", "Straight-line motion is rectilinear motion."),
     Q("MEDIUM", "Convert 3 km into metres.", [], "3000|3,000|3000 m", "1 km = 1000 m.", "3 × 1000 = 3000 m."),
     Q("MEDIUM", "The motion of a pendulum is ___.", ["Rectilinear", "Periodic", "Random", "None"], "Periodic", "It repeats after a fixed time.", "A pendulum repeats its swing — periodic motion."),
     Q("MEDIUM", "Convert 45 mm into cm.", [], "4.5|4.5 cm", "10 mm = 1 cm. Divide by 10.", "45 ÷ 10 = 4.5 cm."),
     Q("HARD", "Why is a hand span not a good unit for measuring?", ["It is too small", "It differs from person to person", "It is too heavy", "It is not straight"], "It differs from person to person", "Compare your hand with a friend's.", "Different people have different span lengths, so the results don't match."),
     Q("HARD", "A wheel rolling on a road shows which two motions?", ["Rectilinear and circular", "Only periodic", "Only circular", "Random and periodic"], "Rectilinear and circular", "The wheel spins AND moves forward.", "The wheel spins (circular) while moving forward in a line (rectilinear)."),
     Q("HARD", "A distance of 1.2 km is how many cm?", [], "120000|1,20,000|120,000", "Convert km to m first, then m to cm.", "1.2 km = 1200 m = 1200 × 100 = 1,20,000 cm.")]},
  {"name": "Fun with Magnets",
   "explanation": "A magnet attracts materials like iron, nickel and cobalt; these are called magnetic materials. Materials like wood, plastic and paper are non-magnetic. Every magnet has two poles, a north pole and a south pole, and its attraction is strongest at the poles. Like poles repel each other and unlike poles attract. A freely suspended magnet always comes to rest in the north–south direction, which is how a compass works. Magnets lose their magnetism if they are heated, hammered or dropped.",
   "keyPoints": ["Magnets pull iron, nickel and cobalt.",
                 "Every magnet has a north and a south pole.",
                 "Same poles push away. Opposite poles pull together.",
                 "A hanging magnet points north–south.",
                 "Heating or dropping a magnet weakens it."],
   "examples": [EX("Attract or repel", "N facing S → they stick together. N facing N → they push apart.", "[N S] → ← [N S]  attract\n[S N] ← → [N S]  repel"),
                EX("Magnetic or not", "A steel pin sticks to a magnet. A plastic spoon does not.", "🧲 + 📎 = ✅   🧲 + 🥄(plastic) = ❌"),
                EX("Compass", "A compass needle is a tiny magnet that points north.", "🧭 → N")],
   "activity": "Test 5 things at home with a fridge magnet. List which ones stick.",
   "questions": [
     Q("EASY", "Which material does a magnet attract?", ["Wood", "Iron", "Plastic", "Paper"], "Iron", "Think of iron nails.", "Iron is a magnetic material."),
     Q("EASY", "How many poles does a magnet have?", [], "2|two", "North and ...?", "Every magnet has two poles: north and south."),
     Q("EASY", "Where is the attraction of a magnet strongest?", ["At the middle", "At the poles", "Everywhere equal", "Nowhere"], "At the poles", "Iron filings collect mostly at the ends.", "The pull is strongest at the poles."),
     Q("MEDIUM", "What happens when two north poles face each other?", ["They attract", "They repel", "Nothing", "They break"], "They repel", "Like poles ...", "Like poles repel each other."),
     Q("MEDIUM", "A freely hanging magnet points in which direction?", ["East–West", "North–South", "Up–Down", "Any direction"], "North–South", "This is how a compass works.", "A suspended magnet rests along the north–south line."),
     Q("MEDIUM", "Which of these is NOT a magnetic material?", ["Nickel", "Cobalt", "Copper", "Iron"], "Copper", "Copper is used in wires but does not stick to magnets.", "Copper is non-magnetic."),
     Q("HARD", "Which is the surest test that an object is a magnet?", ["Attraction", "Repulsion", "Colour", "Weight"], "Repulsion", "Iron is attracted by a magnet but can never repel it.", "Only a magnet can repel another magnet, so repulsion is the sure test."),
     Q("HARD", "Which action can make a magnet lose its magnetism?", ["Keeping it with a keeper", "Heating it strongly", "Storing in pairs", "Painting it"], "Heating it strongly", "Rough handling or heat hurts magnets.", "Heating, hammering or dropping weakens a magnet."),
     Q("HARD", "If a bar magnet is cut into two pieces, each piece will have ___.", ["Only a north pole", "Only a south pole", "Both north and south poles", "No poles"], "Both north and south poles", "Poles always come in pairs.", "Each piece becomes a complete magnet with two poles.")]}]},
 {"name": "English", "icon": "📖", "chapters": [
  {"name": "Nouns",
   "explanation": "A noun is a naming word. It names a person, place, animal, thing or idea. Proper nouns name a particular person, place or thing and always begin with a capital letter, like Riya or Delhi. Common nouns name any person, place or thing, like girl or city. Collective nouns name a group, like a flock of birds. Abstract nouns name ideas or feelings that we cannot touch, like happiness or honesty. Most nouns form their plural by adding -s or -es.",
   "keyPoints": ["A noun is a naming word.",
                 "Proper nouns start with a capital letter.",
                 "Common nouns name any person, place or thing.",
                 "Collective nouns name a group.",
                 "Abstract nouns name feelings or ideas."],
   "examples": [EX("Proper vs common", "Riya (proper) is a girl (common). She lives in Chennai (proper), a city (common)."),
                EX("Collective nouns", "A herd of cows. A bunch of flowers. A team of players.", "🐄🐄🐄 = a herd"),
                EX("Plurals", "box → boxes, cat → cats, baby → babies.")],
   "activity": "Look around you and write five nouns: one person, one place, one animal, one thing and one feeling.",
   "questions": [
     Q("EASY", "Which word is a noun?", ["run", "happy", "table", "quickly"], "table", "A noun names a thing.", "'Table' names a thing."),
     Q("EASY", "Which is a proper noun?", ["city", "Mumbai", "river", "boy"], "Mumbai", "Proper nouns start with a capital letter.", "Mumbai is the name of a particular city."),
     Q("EASY", "What is the plural of 'box'?", [], "boxes", "Words ending in x add -es.", "box → boxes."),
     Q("MEDIUM", "A ___ of birds.", ["herd", "flock", "team", "bunch"], "flock", "Think of birds flying together.", "A group of birds is a flock."),
     Q("MEDIUM", "Which is an abstract noun?", ["chair", "kindness", "teacher", "garden"], "kindness", "You cannot touch it.", "Kindness is a quality, not a thing you can touch."),
     Q("MEDIUM", "What is the plural of 'baby'?", [], "babies", "Consonant + y → change y to i and add -es.", "baby → babies."),
     Q("HARD", "Find the collective noun: 'The army marched through the town.'", ["army", "marched", "town", "the"], "army", "Which word names a group of people?", "An army is a group of soldiers."),
     Q("HARD", "What is the plural of 'child'?", [], "children", "This is an irregular plural.", "child → children."),
     Q("HARD", "Which abstract noun comes from the adjective 'brave'?", ["bravely", "bravery", "braver", "braves"], "bravery", "Add a suffix that makes it a quality.", "brave → bravery (the quality of being brave).")]},
  {"name": "Pronouns",
   "explanation": "A pronoun is a word used in place of a noun so that we do not repeat the same noun again and again. Personal pronouns include I, you, he, she, it, we and they. Subject pronouns (I, he, she, we, they) do the action. Object pronouns (me, him, her, us, them) receive the action. Possessive pronouns (mine, yours, his, hers, ours, theirs) show ownership. A reflexive pronoun such as myself or themselves refers back to the subject.",
   "keyPoints": ["A pronoun takes the place of a noun.",
                 "Subject pronouns: I, he, she, we, they.",
                 "Object pronouns: me, him, her, us, them.",
                 "Possessive pronouns: mine, yours, his, hers.",
                 "Reflexive pronouns end in -self or -selves."],
   "examples": [EX("Avoiding repetition", "Aman likes cricket. Aman plays daily. → Aman likes cricket. He plays daily."),
                EX("Subject and object", "She called him. ('She' does the action; 'him' receives it.)"),
                EX("Possessive", "This book is mine. That pen is yours.")],
   "activity": "Write three sentences about a friend without using their name — use pronouns instead.",
   "questions": [
     Q("EASY", "Which word is a pronoun?", ["dog", "she", "run", "blue"], "she", "It can replace a girl's name.", "'She' is a pronoun."),
     Q("EASY", "Riya is my friend. ___ is kind.", ["He", "She", "It", "They"], "She", "Riya is a girl.", "We use 'she' for Riya."),
     Q("EASY", "The dog is hungry. Give ___ some food.", ["it", "he", "we", "I"], "it", "We usually use this for animals and things.", "'It' replaces 'the dog'."),
     Q("MEDIUM", "Choose the correct pronoun: 'Mother called ___ for dinner.' (us/we)", ["us", "we"], "us", "The pronoun receives the action.", "'Us' is the object pronoun."),
     Q("MEDIUM", "This bag belongs to me. It is ___.", ["my", "mine", "me", "I"], "mine", "Use the possessive pronoun that stands alone.", "'Mine' shows ownership and stands alone."),
     Q("MEDIUM", "Which is a reflexive pronoun?", ["them", "their", "themselves", "they"], "themselves", "It ends in -selves.", "'Themselves' refers back to the subject."),
     Q("HARD", "Fill in: 'The children enjoyed ___ at the fair.'", ["themselves", "theirselves", "them", "their"], "themselves", "'Theirselves' is not a real word.", "The correct reflexive pronoun is 'themselves'."),
     Q("HARD", "Which sentence is correct?", ["Me and Ravi went home.", "Ravi and I went home.", "Ravi and me went home.", "I and Ravi went home."], "Ravi and I went home.", "Who went? Use the subject pronoun, and mention yourself last.", "'I' is the subject pronoun, and politely we mention others first."),
     Q("HARD", "Find the pronoun: 'Is this umbrella yours?'", ["this", "umbrella", "yours", "is"], "yours", "Which word shows ownership?", "'Yours' is a possessive pronoun.")]},
  {"name": "Verbs and Tenses",
   "explanation": "A verb is an action or doing word, like run, eat or write. Some verbs show a state, like is, am, are. Tense tells us when an action happens. Present tense shows an action happening now or regularly (she walks). Past tense shows an action that already happened (she walked). Future tense shows an action that will happen (she will walk). Many verbs form the past tense by adding -ed, but irregular verbs change in other ways, like go → went and eat → ate.",
   "keyPoints": ["A verb is a doing word.",
                 "Present: happening now or every day.",
                 "Past: already happened.",
                 "Future: will happen.",
                 "Some verbs are irregular: go → went."],
   "examples": [EX("Three tenses", "I play (present). I played (past). I will play (future).", "⏪ played  |  ▶️ play  |  ⏩ will play"),
                EX("Irregular verbs", "eat → ate, see → saw, write → wrote."),
                EX("Finding the verb", "The bird sings sweetly. → 'sings' is the verb.")],
   "activity": "Write what you did yesterday, what you are doing today and what you will do tomorrow.",
   "questions": [
     Q("EASY", "Which word is a verb?", ["jump", "happy", "school", "blue"], "jump", "Which one is an action?", "'Jump' is an action word."),
     Q("EASY", "What is the past tense of 'play'?", [], "played", "Add -ed.", "play → played."),
     Q("EASY", "'She will sing tomorrow.' Which tense is this?", ["Past", "Present", "Future"], "Future", "Look for 'will'.", "'Will sing' shows the future."),
     Q("MEDIUM", "What is the past tense of 'go'?", ["goed", "went", "gone", "going"], "went", "It is an irregular verb.", "go → went."),
     Q("MEDIUM", "Choose the correct verb: 'He ___ to school every day.'", ["go", "goes", "going", "gone"], "goes", "He/she/it takes -s or -es in the present.", "With 'he' we use 'goes'."),
     Q("MEDIUM", "Find the verb: 'The children laughed loudly.'", ["children", "laughed", "loudly", "the"], "laughed", "What did the children do?", "'Laughed' is the action."),
     Q("HARD", "Change to past tense: 'I write a letter.'", ["I wrote a letter.", "I writed a letter.", "I will write a letter.", "I written a letter."], "I wrote a letter.", "'Write' is irregular.", "write → wrote."),
     Q("HARD", "Which sentence is in the present continuous tense?", ["She reads.", "She is reading.", "She read.", "She will read."], "She is reading.", "Look for is/am/are + -ing.", "'Is reading' shows an action happening right now."),
     Q("HARD", "What is the past tense of 'teach'?", [], "taught", "It is irregular and sounds like 'caught'.", "teach → taught.")]},
  {"name": "Adjectives",
   "explanation": "An adjective is a describing word. It tells us more about a noun: what kind, how many or which one. For example, in 'a red ball', the word red describes the ball. Adjectives can show size, colour, shape, number and quality. We use degrees of comparison to compare things: positive (tall), comparative (taller) for two things, and superlative (tallest) for three or more. Some adjectives change completely, like good → better → best.",
   "keyPoints": ["An adjective describes a noun.",
                 "It can tell colour, size, number or quality.",
                 "Comparing two things: add -er (taller).",
                 "Comparing three or more: add -est (tallest).",
                 "good → better → best."],
   "examples": [EX("Describing words", "A big, brown dog. ('big' and 'brown' describe the dog.)", "🐕 big + brown"),
                EX("Comparison", "Raj is tall. Sam is taller. Ali is the tallest.", "🧍 < 🧍‍♂️ < 🧍‍♂️⬆"),
                EX("Irregular comparison", "good → better → best; bad → worse → worst.")],
   "activity": "Describe your favourite fruit using three adjectives.",
   "questions": [
     Q("EASY", "Which word is an adjective?", ["run", "beautiful", "quickly", "table"], "beautiful", "Which word describes something?", "'Beautiful' describes a noun."),
     Q("EASY", "Find the adjective: 'She has a red bag.'", ["She", "has", "red", "bag"], "red", "Which word tells the colour?", "'Red' describes the bag."),
     Q("EASY", "Comparative form of 'tall'?", [], "taller", "Comparing two things: add -er.", "tall → taller."),
     Q("MEDIUM", "Superlative form of 'big'?", [], "biggest", "Double the last letter, then add -est.", "big → biggest."),
     Q("MEDIUM", "This is the ___ day of my life!", ["good", "better", "best", "goodest"], "best", "Comparing with all other days.", "good → better → best; 'best' compares with all."),
     Q("MEDIUM", "'Three apples are on the table.' Which word is an adjective of number?", ["Three", "apples", "table", "on"], "Three", "Which word tells how many?", "'Three' tells us how many apples."),
     Q("HARD", "Comparative form of 'beautiful'?", ["beautifuller", "more beautiful", "most beautiful", "beautifulest"], "more beautiful", "Long adjectives use 'more'.", "Long adjectives use 'more' for comparative: more beautiful."),
     Q("HARD", "Choose the correct sentence.", ["He is more taller than me.", "He is taller than me.", "He is tallest than me.", "He is most tall than me."], "He is taller than me.", "Do not use 'more' with -er.", "'Taller than' is correct; 'more taller' doubles the comparison."),
     Q("HARD", "Superlative form of 'bad'?", [], "worst", "bad → worse → ?", "bad → worse → worst.")]}]}]}

SOCIAL_SCIENCE_6 = {"name": "Social Science", "icon": "🌍", "chapters": [
  {"name": "The Earth in the Solar System",
   "explanation": "The solar system is made up of the Sun and everything that moves around it: eight planets, their moons, asteroids and comets. The Sun is a star that gives heat and light. The eight planets in order from the Sun are Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus and Neptune. Earth is the third planet and the only one known to support life, because it has air, water and the right temperature. The Moon is Earth's only natural satellite and takes about 27 days to go around the Earth.",
   "keyPoints": ["The Sun is a star at the centre of the solar system.",
                 "There are eight planets.",
                 "Earth is the third planet from the Sun.",
                 "Earth has air, water and the right temperature for life.",
                 "The Moon is Earth's natural satellite."],
   "examples": [EX("Planet order", "A memory trick: My Very Efficient Mother Just Served Us Nachos = Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune.", "☀️ ● ● 🌍 ● ◉ ◎ ● ●"),
                EX("Star vs planet", "A star makes its own light (the Sun). A planet does not; it reflects the Sun's light."),
                EX("Satellite", "The Moon goes around the Earth, so it is Earth's satellite.", "🌍 ↻ 🌙")],
   "activity": "On a clear night, look at the Moon every day for a week and draw how its shape changes.",
   "questions": [
     Q("EASY", "Which is the third planet from the Sun?", ["Mars", "Earth", "Venus", "Jupiter"], "Earth", "Mercury, Venus, then ...", "Earth is third after Mercury and Venus."),
     Q("EASY", "The Sun is a ___.", ["Planet", "Star", "Satellite", "Comet"], "Star", "It makes its own light and heat.", "The Sun is a star."),
     Q("MEDIUM", "How many planets are there in our solar system?", [], "8|eight", "Pluto is no longer counted as a planet.", "There are eight planets."),
     Q("MEDIUM", "Which is the largest planet?", ["Earth", "Saturn", "Jupiter", "Neptune"], "Jupiter", "It is a giant gas planet, fifth from the Sun.", "Jupiter is the largest planet."),
     Q("HARD", "Why is Earth called a unique planet?", ["It is the biggest", "It supports life", "It has rings", "It is closest to the Sun"], "It supports life", "Think about air and water.", "Earth is the only known planet with conditions for life."),
     Q("HARD", "About how many days does the Moon take to go around the Earth?", ["7", "27", "100", "365"], "27", "It is a little less than a month.", "The Moon takes about 27 days to revolve around the Earth.")]},
  {"name": "Globe: Latitudes and Longitudes",
   "explanation": "A globe is a small model of the Earth. Imaginary lines drawn on the globe help us find places. Lines running east to west are called latitudes, or parallels. The most important latitude is the Equator at 0°, which divides the Earth into the Northern and Southern Hemispheres. Lines running from the North Pole to the South Pole are called longitudes, or meridians. The Prime Meridian at 0° passes through Greenwich in England. Together, latitudes and longitudes form a grid to locate any place.",
   "keyPoints": ["A globe is a model of the Earth.",
                 "Latitudes run east–west.",
                 "The Equator is 0° latitude.",
                 "Longitudes run from pole to pole.",
                 "The Prime Meridian is 0° longitude."],
   "examples": [EX("Hemispheres", "The Equator cuts the Earth into a northern half and a southern half.", "  N\n——— Equator ———\n  S"),
                EX("Finding a place", "India lies north of the Equator and east of the Prime Meridian."),
                EX("Time zones", "Moving 15° of longitude changes local time by 1 hour.")],
   "activity": "Take a ball and draw the Equator and the Prime Meridian on it with a marker.",
   "questions": [
     Q("EASY", "What is the latitude of the Equator?", ["0°", "90°", "45°", "180°"], "0°", "It is the starting line for latitudes.", "The Equator is 0° latitude."),
     Q("EASY", "Lines running from the North Pole to the South Pole are ___.", ["Latitudes", "Longitudes", "Equators", "Tropics"], "Longitudes", "They are also called meridians.", "Longitudes (meridians) join the two poles."),
     Q("MEDIUM", "The Prime Meridian passes through ___.", ["Delhi", "Greenwich", "Paris", "New York"], "Greenwich", "It is a place near London.", "0° longitude passes through Greenwich, England."),
     Q("MEDIUM", "The Equator divides the Earth into Northern and ___ Hemispheres.", ["Eastern", "Western", "Southern", "Upper"], "Southern", "Opposite of northern.", "North and south of the Equator."),
     Q("HARD", "What is the latitude of the North Pole?", ["0°", "45° N", "90° N", "180°"], "90° N", "It is as far north as possible.", "The North Pole is 90° N."),
     Q("HARD", "How many hours of time difference does 15° of longitude make?", [], "1|one", "Earth turns 360° in 24 hours.", "360 ÷ 24 = 15° per hour.")]},
  {"name": "Early Humans: From Hunting to Farming",
   "explanation": "Long ago, early humans lived as hunter-gatherers. They hunted animals, caught fish and gathered fruits, roots and nuts. They moved from place to place in search of food and water. They made tools from stone, wood and bone, and discovered how to use fire for warmth, light and cooking. Slowly, people began to grow crops and tame animals. Farming allowed them to stay in one place, so they built homes and formed the first villages.",
   "keyPoints": ["Early humans hunted and gathered food.",
                 "They moved around to find food.",
                 "They made stone tools and used fire.",
                 "Later they learned to grow crops and tame animals.",
                 "Farming led to the first villages."],
   "examples": [EX("Hunter-gatherer life", "A group follows a herd of deer and collects berries along the way.", "🏹 🦌 🫐"),
                EX("Using fire", "Fire kept animals away, gave warmth and was used to cook meat.", "🔥"),
                EX("Settling down", "Once wheat and barley were grown, families built mud houses near their fields.", "🌾 🏠")],
   "activity": "Make a list of tools you use at home and think which ones early humans might have made from stone.",
   "questions": [
     Q("EASY", "Early humans who hunted animals and collected plants were called ___.", ["Farmers", "Hunter-gatherers", "Traders", "Kings"], "Hunter-gatherers", "They hunted and gathered.", "They are called hunter-gatherers."),
     Q("EASY", "Early humans mostly made their tools from ___.", ["Plastic", "Stone", "Iron", "Gold"], "Stone", "This age is called the Stone Age.", "Stone was the main tool material."),
     Q("MEDIUM", "Why did hunter-gatherers keep moving?", ["To find food and water", "To visit cities", "To trade gold", "To go to school"], "To find food and water", "Animals and plants change with seasons.", "They followed food and water sources."),
     Q("MEDIUM", "Taming animals so they live with humans is called ___.", ["Hunting", "Domestication", "Migration", "Irrigation"], "Domestication", "Dogs and goats were among the first.", "Taming animals and plants is domestication."),
     Q("HARD", "What was the biggest change farming brought?", ["People settled in one place", "People stopped eating", "People moved more", "People stopped using tools"], "People settled in one place", "Crops need looking after.", "Farming allowed permanent settlements and villages."),
     Q("HARD", "Which discovery helped early humans cook food and stay warm?", ["Wheel", "Fire", "Iron", "Writing"], "Fire", "It also scared away wild animals.", "Controlling fire changed daily life.")]}]}

GRADE6["subjects"].append(SOCIAL_SCIENCE_6)
