# Seed content source for Grade 10.
from grade6 import Q, EX

GRADE10 = {"grade": 10, "subjects": [
 {"name": "Mathematics", "icon": "🔢", "chapters": [
  {"name": "Real Numbers",
   "explanation": "The Fundamental Theorem of Arithmetic says every composite number can be written as a product of primes in exactly one way, apart from the order. We use prime factorisation to find the HCF (product of the smallest powers of common primes) and the LCM (product of the greatest powers of all primes). For any two positive integers a and b, HCF(a, b) × LCM(a, b) = a × b. We can also prove that numbers such as √2, √3 and √5 are irrational. A rational number p/q has a terminating decimal only if q has no prime factors other than 2 and 5.",
   "keyPoints": ["Every composite number has a unique prime factorisation.",
                 "HCF: smallest powers of common primes.",
                 "LCM: greatest powers of all primes.",
                 "HCF × LCM = product of the two numbers.",
                 "p/q terminates only if q = 2ⁿ5ᵐ."],
   "examples": [EX("Prime factorisation", "120 = 2³ × 3 × 5."),
                EX("HCF and LCM", "12 = 2² × 3 and 18 = 2 × 3². HCF = 2 × 3 = 6, LCM = 2² × 3² = 36."),
                EX("Check", "6 × 36 = 216 = 12 × 18 ✓")],
   "activity": "Find the HCF and LCM of your age and a parent's age using prime factorisation.",
   "questions": [
     Q("EASY", "Prime factorisation of 60?", ["2² × 3 × 5", "2 × 3 × 10", "4 × 15", "2 × 30"], "2² × 3 × 5", "Use only prime numbers.", "60 = 2 × 2 × 3 × 5."),
     Q("EASY", "HCF of 8 and 12?", [], "4", "Largest number dividing both.", "8 = 2³, 12 = 2² × 3 → HCF = 2² = 4."),
     Q("MEDIUM", "LCM of 6 and 20?", [], "60", "6 = 2 × 3, 20 = 2² × 5.", "2² × 3 × 5 = 60."),
     Q("MEDIUM", "HCF of two numbers is 4 and their product is 96. What is their LCM?", [], "24", "HCF × LCM = product.", "96 ÷ 4 = 24."),
     Q("HARD", "Which fraction has a terminating decimal expansion?", ["1/3", "7/12", "3/40", "2/7"], "3/40", "Look at the prime factors of the denominator.", "40 = 2³ × 5, so 3/40 = 0.075 terminates."),
     Q("HARD", "Which number is irrational?", ["√49", "0.25", "3 + √2", "22/7"], "3 + √2", "A rational plus an irrational is irrational.", "√2 is irrational, so 3 + √2 is irrational.")]},
  {"name": "Quadratic Equations",
   "explanation": "A quadratic equation has the standard form ax² + bx + c = 0, where a ≠ 0. It can have at most two roots. We can solve it by factorisation, by completing the square, or by the quadratic formula x = [−b ± √(b² − 4ac)] / 2a. The expression D = b² − 4ac is called the discriminant. If D > 0 there are two distinct real roots, if D = 0 there are two equal real roots, and if D < 0 there are no real roots.",
   "keyPoints": ["Standard form: ax² + bx + c = 0, a ≠ 0.",
                 "A quadratic has at most two roots.",
                 "x = [−b ± √(b² − 4ac)] / 2a.",
                 "Discriminant D = b² − 4ac.",
                 "D > 0: two roots; D = 0: equal roots; D < 0: no real roots."],
   "examples": [EX("Factorisation", "x² − 5x + 6 = 0 → (x − 2)(x − 3) = 0 → x = 2 or 3."),
                EX("Formula", "x² + 2x − 3 = 0: D = 4 + 12 = 16, x = (−2 ± 4)/2 = 1 or −3."),
                EX("Nature of roots", "x² + x + 1 = 0: D = 1 − 4 = −3 < 0, so no real roots.")],
   "activity": "A rectangle's length is 3 m more than its width and its area is 40 m². Form and solve a quadratic.",
   "questions": [
     Q("EASY", "Which is a quadratic equation?", ["x + 2 = 0", "x² − 4 = 0", "x³ = 1", "2x = 5"], "x² − 4 = 0", "The highest power must be 2.", "x² − 4 = 0 has degree 2."),
     Q("EASY", "The roots of (x − 1)(x − 5) = 0 are ___.", ["1 and 5", "−1 and −5", "1 and −5", "0 and 5"], "1 and 5", "Set each bracket to zero.", "x = 1 or x = 5."),
     Q("MEDIUM", "Discriminant of x² − 4x + 4 = 0?", [], "0", "D = b² − 4ac.", "16 − 16 = 0."),
     Q("MEDIUM", "Roots of x² − 7x + 12 = 0?", ["3 and 4", "2 and 6", "−3 and −4", "1 and 12"], "3 and 4", "Two numbers that multiply to 12 and add to 7.", "(x − 3)(x − 4) = 0."),
     Q("HARD", "For what value of k does x² + kx + 9 = 0 have equal roots (k > 0)?", [], "6", "Set D = 0: k² − 36 = 0.", "k² = 36, so k = 6."),
     Q("HARD", "2x² + x + 3 = 0 has ___.", ["Two distinct real roots", "Two equal real roots", "No real roots"], "No real roots", "Find D = 1 − 24.", "D = −23 < 0, so no real roots.")]},
  {"name": "Arithmetic Progressions",
   "explanation": "An arithmetic progression (AP) is a list of numbers in which each term is obtained by adding a fixed number, the common difference d, to the previous term. If the first term is a, the nth term is aₙ = a + (n − 1)d. The sum of the first n terms is Sₙ = n/2 [2a + (n − 1)d], which can also be written as n/2 (a + l), where l is the last term. APs appear in everyday situations, such as savings that increase by the same amount each month.",
   "keyPoints": ["In an AP, each term = previous term + d.",
                 "d = second term − first term.",
                 "aₙ = a + (n − 1)d.",
                 "Sₙ = n/2 [2a + (n − 1)d].",
                 "Sₙ = n/2 (first + last)."],
   "examples": [EX("Common difference", "3, 7, 11, 15 … has d = 4."),
                EX("nth term", "10th term of 2, 5, 8, …: 2 + 9 × 3 = 29."),
                EX("Sum", "1 + 2 + … + 100 = 100/2 × (1 + 100) = 5050.")],
   "activity": "If you save ₹10 in week 1, ₹15 in week 2, ₹20 in week 3 and so on, how much will you have saved after 10 weeks?",
   "questions": [
     Q("EASY", "Common difference of 5, 9, 13, 17 …?", [], "4", "Subtract a term from the next.", "9 − 5 = 4."),
     Q("EASY", "Next term of 2, 6, 10, 14 …?", [], "18", "Add the common difference.", "14 + 4 = 18."),
     Q("MEDIUM", "10th term of 3, 8, 13, …?", [], "48", "aₙ = a + (n − 1)d.", "3 + 9 × 5 = 48."),
     Q("MEDIUM", "Is 2, 4, 8, 16 an AP?", ["Yes", "No"], "No", "Check if the differences are equal.", "Differences 2, 4, 8 are not equal."),
     Q("HARD", "Sum of the first 20 natural numbers?", [], "210", "Sₙ = n/2 (first + last).", "20/2 × (1 + 20) = 210."),
     Q("HARD", "Which term of 7, 11, 15, … is 87?", [], "21|21st", "Solve 7 + (n − 1)4 = 87.", "(n − 1)4 = 80, so n = 21.")]}]},
 {"name": "Physics", "icon": "⚛️", "chapters": [
  {"name": "Light – Reflection and Refraction",
   "explanation": "Light travels in straight lines. When it bounces off a surface, it is reflected, and the angle of incidence equals the angle of reflection. Plane mirrors form virtual, upright images of the same size. Concave mirrors can form real or virtual images and are used in torches and shaving mirrors; convex mirrors always form small, upright, virtual images and are used as rear-view mirrors. Refraction is the bending of light when it passes from one medium to another because its speed changes. The refractive index n = c/v. Convex lenses converge light and concave lenses diverge it. Lens power P = 1/f (in metres) and is measured in dioptres.",
   "keyPoints": ["Angle of incidence = angle of reflection.",
                 "Convex mirrors are used as rear-view mirrors.",
                 "Refraction is bending of light between media.",
                 "Refractive index n = c/v.",
                 "Power of a lens P = 1/f (f in metres), unit dioptre."],
   "examples": [EX("Rear-view mirror", "A convex mirror gives a wider field of view.", "🚗 🪞"),
                EX("Pencil in water", "A pencil in a glass of water looks bent due to refraction.", "✏️💧"),
                EX("Lens power", "A convex lens with f = 0.5 m has P = 1/0.5 = +2 D.")],
   "activity": "Use a magnifying glass to focus sunlight on paper and measure the focal length roughly.",
   "questions": [
     Q("EASY", "Which mirror is used as a rear-view mirror in vehicles?", ["Plane", "Concave", "Convex"], "Convex", "It gives a wide view.", "Convex mirrors give a wider field of view."),
     Q("EASY", "Bending of light when it enters a new medium is called ___.", ["Reflection", "Refraction", "Dispersion", "Scattering"], "Refraction", "Think of a pencil in water.", "That is refraction."),
     Q("MEDIUM", "If the angle of incidence is 30°, the angle of reflection is ___.", ["30°", "60°", "90°", "15°"], "30°", "Law of reflection.", "They are equal."),
     Q("MEDIUM", "Power of a lens with focal length 0.25 m (in D)?", [], "4|+4|4 d|+4 d", "P = 1/f.", "1/0.25 = 4 D."),
     Q("HARD", "The speed of light in glass is 2 × 10⁸ m/s and in air 3 × 10⁸ m/s. The refractive index of glass is ___.", [], "1.5", "n = c/v.", "3/2 = 1.5."),
     Q("HARD", "A concave lens always forms an image that is ___.", ["Real and inverted", "Virtual, upright and diminished", "Real and magnified", "Same size and real"], "Virtual, upright and diminished", "It spreads light out.", "Concave lenses form virtual, erect, smaller images.")]},
  {"name": "Electricity",
   "explanation": "Electric current is the flow of electric charge, I = Q/t, measured in amperes (A). Potential difference (V) is the work done to move a unit charge between two points and is measured in volts. Ohm's law says V = IR at constant temperature, where R is resistance in ohms (Ω). Resistance depends on the length, area and material of a conductor. In a series circuit, R = R₁ + R₂ + …; in parallel, 1/R = 1/R₁ + 1/R₂ + …. Electrical power is P = VI = I²R, and energy used is often measured in kilowatt-hours (units).",
   "keyPoints": ["Current I = Q/t, in amperes.",
                 "Ohm's law: V = IR.",
                 "Series: R = R₁ + R₂.",
                 "Parallel: 1/R = 1/R₁ + 1/R₂.",
                 "Power P = VI; 1 unit = 1 kWh."],
   "examples": [EX("Ohm's law", "A 12 V battery drives 2 A through a resistor: R = 12/2 = 6 Ω."),
                EX("Series vs parallel", "Two 4 Ω resistors: series 8 Ω, parallel 2 Ω.", "—[4]—[4]—  = 8 Ω\n  ‖4‖4‖   = 2 Ω"),
                EX("Energy bill", "A 1000 W heater used for 2 hours uses 2 kWh = 2 units.")],
   "activity": "Read your home electricity bill and find how many units were used last month.",
   "questions": [
     Q("EASY", "The SI unit of electric current is the ___.", ["Volt", "Ampere", "Ohm", "Watt"], "Ampere", "Symbol A.", "Current is measured in amperes."),
     Q("EASY", "Ohm's law is ___.", ["V = IR", "P = VI", "I = V × R", "R = VI"], "V = IR", "Voltage = current × resistance.", "V = IR."),
     Q("MEDIUM", "A 6 Ω resistor carries 2 A. The voltage across it (V)?", [], "12|12 v", "V = IR.", "2 × 6 = 12 V."),
     Q("MEDIUM", "Two 10 Ω resistors in series give ___ Ω.", [], "20|20 ω", "Add them.", "10 + 10 = 20 Ω."),
     Q("HARD", "Two 6 Ω resistors in parallel give ___ Ω.", [], "3|3 ω", "1/R = 1/6 + 1/6.", "1/R = 2/6, so R = 3 Ω."),
     Q("HARD", "Power of a bulb drawing 0.5 A at 220 V (W)?", [], "110|110 w", "P = VI.", "220 × 0.5 = 110 W.")]},
  {"name": "Magnetic Effects of Electric Current",
   "explanation": "An electric current produces a magnetic field around it. The field lines around a straight wire are concentric circles, and their direction is given by the right-hand thumb rule. A long coil of wire carrying current, called a solenoid, behaves like a bar magnet, and with an iron core it becomes an electromagnet. A current-carrying conductor in a magnetic field experiences a force, whose direction is given by Fleming's left-hand rule; this is how electric motors work. Moving a magnet near a coil induces a current, called electromagnetic induction, which is the principle of the electric generator.",
   "keyPoints": ["Current produces a magnetic field.",
                 "Right-hand thumb rule gives the field direction.",
                 "A solenoid with an iron core is an electromagnet.",
                 "Fleming's left-hand rule: force on a conductor (motors).",
                 "Electromagnetic induction produces current (generators)."],
   "examples": [EX("Electromagnet", "Cranes in scrapyards use electromagnets to lift iron.", "🏗️🧲"),
                EX("Motor", "A fan turns because of the force on current-carrying coils in a magnetic field.", "🌀"),
                EX("Generator", "A bicycle dynamo turns motion into electricity to light a lamp.", "🚲💡")],
   "activity": "Wind wire around an iron nail, connect it to a battery and see how many paper clips it picks up.",
   "questions": [
     Q("EASY", "A current-carrying wire produces a ___ field.", ["Magnetic", "Gravitational", "Sound", "Light"], "Magnetic", "Oersted discovered this.", "Current creates a magnetic field."),
     Q("EASY", "A coil of wire with an iron core carrying current is an ___.", [], "electromagnet", "It is a magnet made by electricity.", "It is an electromagnet."),
     Q("MEDIUM", "Which rule gives the direction of force on a conductor in a magnetic field?", ["Fleming's left-hand rule", "Fleming's right-hand rule", "Right-hand thumb rule", "Ohm's law"], "Fleming's left-hand rule", "It is used for motors.", "Fleming's left-hand rule gives the force direction."),
     Q("MEDIUM", "An electric motor converts ___.", ["Electrical energy to mechanical energy", "Mechanical to electrical", "Heat to light", "Sound to electrical"], "Electrical energy to mechanical energy", "It makes things spin.", "Motors turn electricity into motion."),
     Q("HARD", "Producing current by changing the magnetic field in a coil is called ___.", ["Electromagnetic induction", "Electrolysis", "Conduction", "Magnetisation"], "Electromagnetic induction", "Faraday discovered it.", "This is electromagnetic induction."),
     Q("HARD", "The magnetic field lines around a straight current-carrying wire are ___.", ["Concentric circles", "Straight parallel lines", "Random", "Zig-zag"], "Concentric circles", "Use the right-hand thumb rule.", "They form circles around the wire.")]}]},
 {"name": "Chemistry", "icon": "🧪", "chapters": [
  {"name": "Chemical Reactions and Equations",
   "explanation": "A chemical reaction changes substances into new substances. Signs include a change in colour, gas evolution, temperature change or formation of a precipitate. A balanced chemical equation has the same number of atoms of each element on both sides, following the law of conservation of mass. Types of reactions include combination (A + B → AB), decomposition (AB → A + B), displacement (a more reactive element replaces a less reactive one), double displacement (exchange of ions) and redox reactions, where oxidation (gain of oxygen or loss of hydrogen) and reduction happen together.",
   "keyPoints": ["Chemical reactions form new substances.",
                 "Balanced equations have equal atoms on both sides.",
                 "Combination: A + B → AB. Decomposition: AB → A + B.",
                 "Displacement: a more reactive element replaces a less reactive one.",
                 "Oxidation and reduction happen together (redox)."],
   "examples": [EX("Balancing", "H₂ + O₂ → H₂O becomes 2H₂ + O₂ → 2H₂O."),
                EX("Displacement", "An iron nail in copper sulphate solution turns brown: Fe + CuSO₄ → FeSO₄ + Cu."),
                EX("Rusting", "Iron slowly reacts with oxygen and water to form rust — an oxidation.", "🔩→🟤")],
   "activity": "Place an iron nail in blue copper sulphate solution and observe it after 20 minutes.",
   "questions": [
     Q("EASY", "CaO + H₂O → Ca(OH)₂ is a ___ reaction.", ["Combination", "Decomposition", "Displacement", "Double displacement"], "Combination", "Two substances form one.", "Two reactants combine into one product."),
     Q("EASY", "Rusting of iron is an example of ___.", ["Oxidation", "Reduction", "Neutralisation", "Sublimation"], "Oxidation", "Iron gains oxygen.", "Rusting is oxidation."),
     Q("MEDIUM", "In 2H₂ + O₂ → 2H₂O, how many oxygen atoms are on each side?", [], "2", "Count O on both sides.", "O₂ has 2; 2H₂O has 2."),
     Q("MEDIUM", "Fe + CuSO₄ → FeSO₄ + Cu is a ___ reaction.", ["Displacement", "Combination", "Decomposition", "Neutralisation"], "Displacement", "Iron pushes copper out.", "More reactive iron displaces copper."),
     Q("HARD", "CaCO₃ → CaO + CO₂ on heating is a ___ reaction.", ["Thermal decomposition", "Combination", "Displacement", "Redox only"], "Thermal decomposition", "One substance breaks into two with heat.", "Heat breaks down calcium carbonate."),
     Q("HARD", "A reaction where a precipitate forms by exchange of ions is ___.", ["Double displacement", "Combination", "Decomposition", "Oxidation"], "Double displacement", "Na₂SO₄ + BaCl₂ → BaSO₄↓ + 2NaCl.", "Ions swap partners: double displacement.")]},
  {"name": "Acids, Bases and Salts",
   "explanation": "Acids release H⁺ ions in water, taste sour and turn blue litmus red. Bases release OH⁻ ions in water, taste bitter and turn red litmus blue; bases that dissolve in water are called alkalis. The pH scale from 0 to 14 measures how acidic or basic a solution is: below 7 is acidic, 7 is neutral and above 7 is basic. An acid reacts with a base to form a salt and water, which is neutralisation. Acids react with metals to produce hydrogen gas. Common salts include sodium chloride, baking soda (NaHCO₃), washing soda and plaster of Paris.",
   "keyPoints": ["Acids give H⁺ ions; bases give OH⁻ ions.",
                 "pH < 7 acidic, 7 neutral, > 7 basic.",
                 "Acid + base → salt + water.",
                 "Acid + metal → salt + hydrogen gas.",
                 "Baking soda is sodium hydrogen carbonate (NaHCO₃)."],
   "examples": [EX("pH values", "Lemon juice ≈ 2, pure water = 7, soap ≈ 10.", "0 🍋 —— 7 💧 —— 14 🧼"),
                EX("Antacid", "Milk of magnesia (a base) neutralises excess stomach acid."),
                EX("Hydrogen test", "Zinc + dilute HCl gives H₂, which burns with a pop sound.")],
   "activity": "Use red cabbage juice as an indicator to test lemon juice, vinegar and soap water.",
   "questions": [
     Q("EASY", "A solution with pH 7 is ___.", ["Acidic", "Neutral", "Basic"], "Neutral", "Pure water.", "pH 7 is neutral."),
     Q("EASY", "Bases turn red litmus ___.", ["Blue", "Red", "Green", "Colourless"], "Blue", "Base → blue.", "Bases turn red litmus blue."),
     Q("MEDIUM", "Which pH value is the most acidic?", ["2", "6", "8", "12"], "2", "Lower pH means more acidic.", "pH 2 is strongly acidic."),
     Q("MEDIUM", "Acid + metal produces salt and ___ gas.", ["Oxygen", "Hydrogen", "Carbon dioxide", "Nitrogen"], "Hydrogen", "It burns with a pop.", "Hydrogen gas is released."),
     Q("HARD", "The chemical formula of baking soda is ___.", ["NaCl", "NaHCO₃", "Na₂CO₃", "CaCO₃"], "NaHCO₃", "Sodium hydrogen carbonate.", "Baking soda is NaHCO₃."),
     Q("HARD", "Why is an antacid used for indigestion?", ["It neutralises excess stomach acid", "It adds more acid", "It kills all bacteria", "It increases pH to 14"], "It neutralises excess stomach acid", "Antacids are mild bases.", "The base neutralises excess HCl in the stomach.")]},
  {"name": "Carbon and its Compounds",
   "explanation": "Carbon has four valence electrons, so it forms covalent bonds by sharing electrons. Carbon shows catenation, the ability to form long chains, branches and rings, which is why it forms millions of compounds. Compounds of only carbon and hydrogen are hydrocarbons: alkanes have single bonds (saturated), while alkenes and alkynes have double and triple bonds (unsaturated). A homologous series is a family of compounds with the same functional group, where each member differs by CH₂. Functional groups such as alcohol (−OH) and carboxylic acid (−COOH) decide the chemical properties.",
   "keyPoints": ["Carbon has a valency of 4.",
                 "Carbon forms covalent bonds by sharing electrons.",
                 "Catenation: carbon links to itself in chains and rings.",
                 "Alkanes: single bonds; alkenes: double; alkynes: triple.",
                 "Members of a homologous series differ by CH₂."],
   "examples": [EX("Methane", "CH₄: one carbon shares electrons with four hydrogens.", "  H\nH–C–H\n  H"),
                EX("Homologous series", "CH₄, C₂H₆, C₃H₈ — each differs by CH₂."),
                EX("Ethanol", "C₂H₅OH is an alcohol used as a solvent and in sanitisers.")],
   "activity": "Build models of methane and ethane using clay and matchsticks.",
   "questions": [
     Q("EASY", "The valency of carbon is ___.", [], "4|four", "It has four outer electrons.", "Carbon's valency is 4."),
     Q("EASY", "Carbon forms bonds mainly by ___.", ["Sharing electrons", "Losing electrons", "Gaining electrons", "Magnetism"], "Sharing electrons", "These are covalent bonds.", "Carbon forms covalent bonds."),
     Q("MEDIUM", "The property of carbon to form long chains is called ___.", [], "catenation", "It comes from the Latin word for chain.", "This is catenation."),
     Q("MEDIUM", "Hydrocarbons with only single bonds are ___.", ["Alkanes", "Alkenes", "Alkynes", "Alcohols"], "Alkanes", "They are saturated.", "Alkanes have only single bonds."),
     Q("HARD", "The functional group −COOH belongs to ___.", ["Alcohols", "Carboxylic acids", "Aldehydes", "Ketones"], "Carboxylic acids", "Vinegar contains one.", "−COOH is the carboxylic acid group."),
     Q("HARD", "The next member after C₂H₆ in the alkane series is ___.", ["C₃H₈", "C₃H₆", "C₂H₄", "C₄H₁₀"], "C₃H₈", "Add CH₂.", "C₂H₆ + CH₂ = C₃H₈ (propane).")]}]},
 {"name": "Biology", "icon": "🧬", "chapters": [
  {"name": "Life Processes",
   "explanation": "Life processes are the basic functions that keep living things alive: nutrition, respiration, transportation and excretion. Plants make food by photosynthesis, while humans digest food in the alimentary canal with the help of enzymes. Respiration releases energy from glucose; aerobic respiration uses oxygen and produces carbon dioxide, water and a lot of energy, while anaerobic respiration happens without oxygen. In humans, blood carries substances; the heart has four chambers and keeps oxygenated and deoxygenated blood separate. The kidneys filter waste from blood through nephrons and make urine.",
   "keyPoints": ["Life processes: nutrition, respiration, transport, excretion.",
                 "Enzymes help digest food.",
                 "Aerobic respiration uses oxygen and releases more energy.",
                 "The human heart has four chambers.",
                 "Nephrons in the kidneys filter blood."],
   "examples": [EX("Respiration", "Glucose + oxygen → carbon dioxide + water + energy."),
                EX("Double circulation", "Blood passes through the heart twice in one full cycle: body → heart → lungs → heart → body.", "❤️ ⇄ 🫁"),
                EX("Anaerobic", "During hard exercise, muscles make lactic acid, causing cramps.")],
   "activity": "Count your pulse rate at rest and after two minutes of skipping. Compare the numbers.",
   "questions": [
     Q("EASY", "How many chambers does the human heart have?", [], "4|four", "Two atria and two ventricles.", "The heart has four chambers."),
     Q("EASY", "Which organ filters blood to make urine?", ["Liver", "Kidney", "Heart", "Lungs"], "Kidney", "It is bean-shaped.", "Kidneys filter blood."),
     Q("MEDIUM", "The functional unit of the kidney is the ___.", ["Neuron", "Nephron", "Alveolus", "Villus"], "Nephron", "It sounds like 'neuron' but relates to kidneys.", "Nephrons filter the blood."),
     Q("MEDIUM", "Respiration without oxygen is called ___ respiration.", [], "anaerobic", "'An' means without.", "It is anaerobic respiration."),
     Q("HARD", "Which enzyme in saliva breaks down starch?", ["Pepsin", "Salivary amylase", "Trypsin", "Lipase"], "Salivary amylase", "Also called ptyalin.", "Salivary amylase digests starch into sugar."),
     Q("HARD", "Where does gas exchange happen in the lungs?", ["Alveoli", "Trachea", "Bronchi", "Diaphragm"], "Alveoli", "Tiny air sacs with many capillaries.", "Alveoli provide a large surface for gas exchange.")]},
  {"name": "Heredity",
   "explanation": "Heredity is the passing of traits from parents to offspring. Gregor Mendel studied pea plants and found that traits are controlled by factors, now called genes, which come in pairs. One form of a gene can be dominant and hide the other, recessive, form. In a cross between pure tall (TT) and pure short (tt) plants, all first-generation plants are tall (Tt). When these are self-crossed, the second generation shows a 3 : 1 ratio of tall to short plants. In humans, sex is determined by chromosomes: females have XX and males have XY, so the father's sperm decides the sex of the child.",
   "keyPoints": ["Heredity is passing traits from parents to children.",
                 "Mendel worked with pea plants.",
                 "Dominant traits hide recessive ones.",
                 "Monohybrid cross F₂ ratio: 3 : 1.",
                 "Females XX, males XY."],
   "examples": [EX("Monohybrid cross", "TT × tt → all Tt (tall). Tt × Tt → TT, Tt, Tt, tt = 3 tall : 1 short.", " T  t\nT TT Tt\nt Tt tt"),
                EX("Dominant trait", "In peas, tall (T) is dominant over short (t)."),
                EX("Sex determination", "An egg (X) + a sperm with Y → XY → a boy.")],
   "activity": "Survey your family for earlobe type (free or attached) and see which is more common.",
   "questions": [
     Q("EASY", "Who is called the father of genetics?", ["Charles Darwin", "Gregor Mendel", "Robert Hooke", "Louis Pasteur"], "Gregor Mendel", "He studied pea plants.", "Mendel is the father of genetics."),
     Q("EASY", "Human males have which sex chromosomes?", ["XX", "XY", "YY", "X only"], "XY", "Females are XX.", "Males are XY."),
     Q("MEDIUM", "A trait that is hidden in the presence of another is ___.", ["Dominant", "Recessive"], "Recessive", "It only shows when two copies are present.", "Hidden traits are recessive."),
     Q("MEDIUM", "In the F₂ generation of a monohybrid cross, the ratio of tall to short is ___.", ["1 : 1", "3 : 1", "9 : 3 : 3 : 1", "2 : 1"], "3 : 1", "TT, Tt, Tt, tt.", "Three tall to one short."),
     Q("HARD", "TT × tt gives F₁ plants that are all ___.", ["Tt (tall)", "tt (short)", "TT (tall)", "half tall, half short"], "Tt (tall)", "Each parent gives one letter.", "All offspring are Tt and tall."),
     Q("HARD", "Which parent determines the sex of a human child?", ["Father", "Mother", "Both equally", "Neither"], "Father", "Only the father can give a Y chromosome.", "The sperm carries X or Y, so the father decides.")]},
  {"name": "Our Environment",
   "explanation": "An ecosystem includes living (biotic) components like plants, animals and microbes and non-living (abiotic) components like air, water and soil. Producers, mainly green plants, make food using sunlight. Consumers eat other organisms, and decomposers break down dead matter and return nutrients to the soil. A food chain shows who eats whom, and connected food chains form a food web. Only about 10% of energy passes from one trophic level to the next (the 10% law). Harmful chemicals can build up along a food chain, which is called biological magnification. Ozone in the upper atmosphere protects us from UV rays and is damaged by CFCs.",
   "keyPoints": ["Ecosystems have biotic and abiotic parts.",
                 "Producers make food; consumers eat; decomposers recycle.",
                 "A food chain shows who eats whom.",
                 "Only about 10% of energy passes to the next level.",
                 "CFCs damage the ozone layer."],
   "examples": [EX("Food chain", "Grass → grasshopper → frog → snake → eagle.", "🌿 → 🦗 → 🐸 → 🐍 → 🦅"),
                EX("10% law", "If plants store 1000 J, herbivores get about 100 J and carnivores about 10 J."),
                EX("Biomagnification", "Pesticide levels are highest in top predators like eagles.")],
   "activity": "Separate your household waste into biodegradable and non-biodegradable for one day.",
   "questions": [
     Q("EASY", "Green plants in a food chain are ___.", ["Producers", "Consumers", "Decomposers"], "Producers", "They make their own food.", "Plants are producers."),
     Q("EASY", "Which is non-biodegradable?", ["Vegetable peel", "Paper", "Plastic bag", "Leaves"], "Plastic bag", "It is not broken down by microbes.", "Plastic is non-biodegradable."),
     Q("MEDIUM", "About what percentage of energy passes to the next trophic level?", [], "10|10%", "It is called the ___ % law.", "Only about 10%."),
     Q("MEDIUM", "Organisms that break down dead matter are ___.", ["Producers", "Herbivores", "Decomposers", "Carnivores"], "Decomposers", "Bacteria and fungi.", "Decomposers recycle nutrients."),
     Q("HARD", "Increase in concentration of harmful chemicals along a food chain is ___.", ["Biological magnification", "Photosynthesis", "Eutrophication", "Pollination"], "Biological magnification", "It is highest in top predators.", "This is biological magnification."),
     Q("HARD", "Which chemicals are mainly responsible for ozone depletion?", ["CFCs", "Oxygen", "Nitrogen", "Water vapour"], "CFCs", "They were used in old refrigerators.", "Chlorofluorocarbons (CFCs) break down ozone.")]}]},
 {"name": "English", "icon": "📖", "chapters": [
  {"name": "Figures of Speech",
   "explanation": "Figures of speech are special ways of using words to create an effect. A simile compares two things using 'like' or 'as' (as brave as a lion). A metaphor compares directly without 'like' or 'as' (Time is money). Personification gives human qualities to non-living things (The wind whispered). Alliteration repeats the same beginning sound in nearby words (Peter Piper picked). Hyperbole is deliberate exaggeration (I've told you a million times). Onomatopoeia uses words that imitate sounds (buzz, sizzle).",
   "keyPoints": ["Simile: compares using 'like' or 'as'.",
                 "Metaphor: says one thing is another.",
                 "Personification: human qualities for non-human things.",
                 "Alliteration: repeated starting sounds.",
                 "Hyperbole: deliberate exaggeration."],
   "examples": [EX("Simile vs metaphor", "Simile: Her smile was like sunshine. Metaphor: Her smile was sunshine."),
                EX("Personification", "The old house groaned in the storm."),
                EX("Onomatopoeia", "The bees buzzed and the bacon sizzled.", "🐝 buzz")],
   "activity": "Write a short poem about rain that uses at least three figures of speech.",
   "questions": [
     Q("EASY", "'As busy as a bee' is a ___.", ["Simile", "Metaphor", "Hyperbole", "Alliteration"], "Simile", "It uses 'as'.", "Comparisons with 'as' or 'like' are similes."),
     Q("EASY", "'Buzz' and 'bang' are examples of ___.", ["Onomatopoeia", "Personification", "Metaphor", "Simile"], "Onomatopoeia", "They imitate sounds.", "Sound-imitating words are onomatopoeia."),
     Q("MEDIUM", "'The classroom was a zoo.' is a ___.", ["Simile", "Metaphor", "Alliteration", "Onomatopoeia"], "Metaphor", "No 'like' or 'as'.", "A direct comparison is a metaphor."),
     Q("MEDIUM", "'The stars danced in the sky.' is an example of ___.", ["Personification", "Hyperbole", "Simile", "Alliteration"], "Personification", "Stars cannot really dance.", "Human action given to stars: personification."),
     Q("HARD", "'I'm so hungry I could eat a horse.' is ___.", ["Hyperbole", "Metaphor", "Simile", "Personification"], "Hyperbole", "It is a huge exaggeration.", "Deliberate exaggeration is hyperbole."),
     Q("HARD", "'She sells sea shells by the sea shore.' mainly shows ___.", ["Alliteration", "Metaphor", "Hyperbole", "Simile"], "Alliteration", "Listen to the starting sounds.", "Repeated 's' sounds: alliteration.")]},
  {"name": "Formal Letter Writing",
   "explanation": "A formal letter is written for official purposes, such as to a principal, an editor or a company. It follows a fixed format: the sender's address, date, receiver's designation and address, subject line, salutation (Sir/Madam), body, complimentary close (Yours faithfully or Yours sincerely), and the sender's name. The subject line states the purpose in a few words. The body should be polite, clear and brief, usually in three parts: introduction, details, and conclusion or request. Avoid slang, contractions and emotional language.",
   "keyPoints": ["Formal letters are for official purposes.",
                 "Order: sender's address, date, receiver's address, subject, salutation.",
                 "The subject line states the purpose briefly.",
                 "Body: introduction, details, request.",
                 "Close with 'Yours faithfully' or 'Yours sincerely'."],
   "examples": [EX("Subject line", "Subject: Request for a leave of absence for two days"),
                EX("Opening", "Respected Sir, I wish to bring to your notice…"),
                EX("Closing", "Thanking you, Yours faithfully, Anika Rao")],
   "activity": "Write a formal letter to your principal requesting more books for the school library.",
   "questions": [
     Q("EASY", "Which salutation suits a formal letter?", ["Dear buddy", "Respected Sir", "Hey!", "Hi friend"], "Respected Sir", "It must be polite and official.", "'Respected Sir' or 'Dear Sir/Madam' is formal."),
     Q("EASY", "The line that states the purpose of a formal letter is the ___.", ["Subject", "Salutation", "Signature", "Postscript"], "Subject", "It comes before the salutation.", "The subject line gives the purpose."),
     Q("MEDIUM", "Which closing is used in formal letters?", ["Lots of love", "Yours faithfully", "See ya", "Cheers"], "Yours faithfully", "It is polite and official.", "'Yours faithfully' is a formal closing."),
     Q("MEDIUM", "What comes first in a formal letter?", ["Sender's address", "Subject", "Body", "Signature"], "Sender's address", "It is at the top.", "The letter begins with the sender's address."),
     Q("HARD", "Which sentence is best for a formal letter?", ["I'm super angry about the roads!!", "I wish to draw your attention to the poor condition of roads in our area.", "Roads r bad.", "Fix the roads now or else."], "I wish to draw your attention to the poor condition of roads in our area.", "Formal letters are polite and clear.", "It is polite, clear and uses no slang."),
     Q("HARD", "Which should be avoided in a formal letter?", ["A clear subject", "Contractions like 'can't' and slang", "Polite tone", "The date"], "Contractions like 'can't' and slang", "Formal writing is not casual.", "Slang and contractions are too informal.")]},
  {"name": "Tense Consistency",
   "explanation": "Tense consistency means keeping the same tense in a sentence or paragraph unless there is a real change in time. If you begin telling a story in the past tense, continue in the past tense. Switching tenses without reason confuses the reader. You may change tense when the time of the action truly changes, for example when referring to a general truth or future plan. The past perfect (had + past participle) is used for an action that happened before another past action.",
   "keyPoints": ["Keep the same tense unless the time changes.",
                 "Stories in the past should stay in the past.",
                 "General truths can stay in the present.",
                 "Past perfect: an earlier action in the past.",
                 "Check verbs when editing your writing."],
   "examples": [EX("Error", "She walked in and sits down. → She walked in and sat down."),
                EX("Past perfect", "When we reached the station, the train had left."),
                EX("General truth", "The teacher said that the Earth revolves around the Sun.")],
   "activity": "Take a paragraph from a story you wrote and underline every verb. Check that the tenses are consistent.",
   "questions": [
     Q("EASY", "Choose the consistent sentence.", ["He opened the door and walks out.", "He opened the door and walked out.", "He opens the door and walked out.", "He open the door and walked out."], "He opened the door and walked out.", "Both actions are in the past.", "Both verbs should be in the past tense."),
     Q("EASY", "Yesterday, I ___ to the market.", ["go", "went", "will go", "going"], "went", "'Yesterday' shows past time.", "Use the past tense: went."),
     Q("MEDIUM", "When I arrived, the film ___ already started.", ["has", "had", "have", "was"], "had", "It happened before another past action.", "Past perfect: had started."),
     Q("MEDIUM", "Find the error: 'She was reading when the phone rings.'", ["was", "reading", "rings", "the"], "rings", "The whole sentence is in the past.", "'rings' should be 'rang'."),
     Q("HARD", "Our teacher told us that water ___ at 100°C.", ["boils", "boiled", "had boiled", "will boil"], "boils", "This is a universal truth.", "General truths stay in the present tense."),
     Q("HARD", "Correct: 'After he finished dinner, he goes to bed.'", ["After he finished dinner, he went to bed.", "After he finishes dinner, he went to bed.", "After he finish dinner, he goes to bed.", "After he had finish dinner, he go to bed."], "After he finished dinner, he went to bed.", "Keep both actions in the past.", "Both verbs in the past: finished, went.")]}]},
 {"name": "Social Science", "icon": "🌍", "chapters": [
  {"name": "Resources and Development",
   "explanation": "Resources are classified by origin (biotic and abiotic), exhaustibility (renewable and non-renewable), ownership (individual, community, national and international) and status of development (potential, developed, stock and reserves). Soil is one of the most important resources. India has several types of soil: alluvial soil, the most widespread and very fertile; black soil, good for cotton; red and yellow soil; laterite soil; arid soil; and forest soil. Soil erosion is caused by deforestation, overgrazing and wind or water, and it can be reduced by contour ploughing, terrace farming, shelter belts and planting trees.",
   "keyPoints": ["Resources are classified by origin, exhaustibility, ownership and development.",
                 "Alluvial soil is the most widespread soil in India.",
                 "Black soil is ideal for cotton.",
                 "Deforestation and overgrazing cause soil erosion.",
                 "Terrace farming and shelter belts reduce erosion."],
   "examples": [EX("Black soil", "Maharashtra's Deccan plateau has black soil, perfect for cotton.", "⚫🌱"),
                EX("Terrace farming", "Steps are cut into hill slopes to slow down water and save soil.", "▁▂▃▄"),
                EX("Shelter belts", "Rows of trees in Rajasthan block wind and stop sand from spreading.")],
   "activity": "Collect a soil sample from near your home and describe its colour and texture.",
   "questions": [
     Q("EASY", "Which soil is most widespread in India?", ["Black soil", "Alluvial soil", "Laterite soil", "Arid soil"], "Alluvial soil", "It is found in river plains.", "Alluvial soil covers the northern plains."),
     Q("EASY", "Black soil is best suited for growing ___.", ["Cotton", "Tea", "Rice", "Apples"], "Cotton", "It is also called black cotton soil.", "Black soil is ideal for cotton."),
     Q("MEDIUM", "Cutting steps into hill slopes for farming is called ___ farming.", [], "terrace", "The steps look like terraces.", "This is terrace farming."),
     Q("MEDIUM", "Solar energy is a ___ resource.", ["Renewable", "Non-renewable"], "Renewable", "It is continuously available.", "Solar energy is renewable."),
     Q("HARD", "Resources found in a region but not yet used are ___ resources.", ["Potential", "Developed", "Stock", "Individual"], "Potential", "Rajasthan's wind energy is an example.", "Unused but available resources are potential resources."),
     Q("HARD", "Which is a major cause of soil erosion?", ["Deforestation", "Terrace farming", "Planting trees", "Shelter belts"], "Deforestation", "Roots hold the soil together.", "Removing trees exposes soil to erosion.")]},
  {"name": "Power Sharing",
   "explanation": "Power sharing means distributing power among different organs and levels of government and among social groups. It is good because it reduces conflict between groups and is the spirit of democracy. Horizontal power sharing divides power among the legislature, executive and judiciary, which check each other. Vertical power sharing divides power among central, state and local governments, which is called federalism. Power may also be shared among social groups, such as through reserved seats, and among political parties, pressure groups and movements. Belgium shared power successfully, while Sri Lanka's majoritarian approach increased tensions.",
   "keyPoints": ["Power sharing reduces conflict and suits democracy.",
                 "Horizontal: legislature, executive and judiciary.",
                 "Vertical: central, state and local governments.",
                 "Power is also shared among social groups and parties.",
                 "Belgium accommodated its groups; Sri Lanka's majoritarianism caused conflict."],
   "examples": [EX("Checks and balances", "Judges can declare a law unconstitutional, checking Parliament.", "⚖️"),
                EX("Federalism", "India has central, state and panchayat/municipal governments.", "🏛️ → 🏢 → 🏘️"),
                EX("Belgium", "Dutch and French speakers share power equally in the central government.")],
   "activity": "List the three levels of government in your area and one job done by each.",
   "questions": [
     Q("EASY", "Sharing power among the legislature, executive and judiciary is ___ power sharing.", ["Horizontal", "Vertical"], "Horizontal", "They are at the same level.", "It is horizontal power sharing."),
     Q("EASY", "Sharing power among central, state and local governments is called ___.", ["Federalism", "Monarchy", "Dictatorship", "Communism"], "Federalism", "India is a federal country.", "Vertical power sharing is federalism."),
     Q("MEDIUM", "Why is power sharing desirable?", ["It reduces conflict between social groups", "It makes one group rule", "It removes elections", "It weakens citizens"], "It reduces conflict between social groups", "Everyone feels included.", "Power sharing reduces conflict and ensures stability."),
     Q("MEDIUM", "Which country is an example of successful power sharing between language groups?", ["Belgium", "Sri Lanka", "North Korea", "Saudi Arabia"], "Belgium", "Dutch and French speakers.", "Belgium accommodated its linguistic communities."),
     Q("HARD", "A system where the majority community dominates the government is called ___.", [], "majoritarianism", "Sri Lanka followed this after 1948.", "This is majoritarianism."),
     Q("HARD", "Which is an example of power shared among social groups?", ["Reserved constituencies for SC/ST", "Army rule", "A single ruling family", "Banning political parties"], "Reserved constituencies for SC/ST", "It gives weaker groups a share of power.", "Reservations ensure representation of disadvantaged groups.")]},
  {"name": "Money and Credit",
   "explanation": "Money acts as a medium of exchange and removes the need for the 'double coincidence of wants' required in barter. Modern forms of money include currency (paper notes and coins) and bank deposits, which can be used through cheques and digital payments. Banks accept deposits and use most of them to give loans, earning interest. Credit (a loan) comes with terms of credit: interest rate, collateral, documentation and mode of repayment. Formal sources of credit are banks and cooperatives, which are regulated by the Reserve Bank of India. Informal sources, such as moneylenders, often charge very high interest and can trap borrowers in debt.",
   "keyPoints": ["Money is a medium of exchange.",
                 "Barter needs a double coincidence of wants.",
                 "Banks use deposits to give loans.",
                 "Terms of credit: interest, collateral, documents, repayment.",
                 "Formal credit is regulated by the RBI."],
   "examples": [EX("Barter problem", "A shoemaker wanting wheat must find a farmer who wants shoes.", "👞 ⇄ 🌾 ?"),
                EX("Collateral", "A farmer pledges land papers to get a bank loan."),
                EX("Self-help groups", "Women in a village save together and give small loans to members at low interest.")],
   "activity": "Ask an adult how they would get a loan for buying a bicycle and what the terms would be.",
   "questions": [
     Q("EASY", "Money mainly acts as a medium of ___.", ["Exchange", "Transport", "Entertainment", "Storage of food"], "Exchange", "It is used to buy and sell.", "Money is a medium of exchange."),
     Q("EASY", "Which is a formal source of credit?", ["Moneylender", "Bank", "Relative", "Shopkeeper"], "Bank", "It is regulated by the RBI.", "Banks are formal sources."),
     Q("MEDIUM", "An asset pledged to get a loan is called ___.", [], "collateral", "Land or gold can be used.", "It is collateral."),
     Q("MEDIUM", "Which institution regulates banks in India?", ["Reserve Bank of India", "State Bank of India", "Parliament", "Supreme Court"], "Reserve Bank of India", "It issues currency notes.", "The RBI supervises banks."),
     Q("HARD", "Why is informal credit often harmful for the poor?", ["High interest rates can lead to a debt trap", "It is always free", "It needs no repayment", "The RBI protects it"], "High interest rates can lead to a debt trap", "Moneylenders are unregulated.", "High interest can trap borrowers in debt."),
     Q("HARD", "Barter fails without a ___ of wants.", ["Double coincidence", "Single choice", "Bank account", "Currency note"], "Double coincidence", "Both people must want what the other has.", "Barter needs a double coincidence of wants.")]}]}]}
