# Seed content source for Grade 9. From Grade 9, Science is split into Physics, Chemistry and Biology.
from grade6 import Q, EX

GRADE9 = {"grade": 9, "subjects": [
 {"name": "Mathematics", "icon": "🔢", "chapters": [
  {"name": "Number Systems",
   "explanation": "Real numbers include rational and irrational numbers. A rational number can be written as p/q; its decimal form either ends (terminates) or repeats. An irrational number cannot be written as p/q, and its decimal goes on forever without repeating, like √2 or π. Every real number has a unique point on the number line. We can simplify expressions with surds using rules such as √a × √b = √(ab), and rationalise a denominator by multiplying the top and bottom by a suitable surd. Exponent laws also work for rational powers: a^m × a^n = a^(m+n).",
   "keyPoints": ["Real numbers = rational + irrational numbers.",
                 "Rational decimals terminate or repeat.",
                 "Irrational decimals never end and never repeat.",
                 "√2, √3 and π are irrational.",
                 "a^m × a^n = a^(m+n)."],
   "examples": [EX("Repeating decimal", "1/3 = 0.333… repeats, so it is rational."),
                EX("Rationalising", "1/√2 = √2/2 (multiply top and bottom by √2)."),
                EX("Exponents", "2³ × 2² = 2⁵ = 32.")],
   "activity": "Divide 22 by 7 on a calculator and compare the result with the value of π.",
   "questions": [
     Q("EASY", "Which number is irrational?", ["1/2", "0.75", "√2", "4"], "√2", "Its decimal never ends or repeats.", "√2 = 1.41421… is irrational."),
     Q("EASY", "0.666… (6 repeating) is ___.", ["Rational", "Irrational"], "Rational", "Repeating decimals can be written as fractions.", "0.666… = 2/3, which is rational."),
     Q("MEDIUM", "What is √3 × √12?", [], "6", "√3 × √12 = √36.", "√36 = 6."),
     Q("MEDIUM", "Simplify: 5² × 5³ = 5^?", [], "5", "Add the powers.", "2 + 3 = 5, so 5⁵."),
     Q("HARD", "Rationalise: 1/√5 = ?", ["√5/5", "5/√5", "1/5", "√5"], "√5/5", "Multiply top and bottom by √5.", "√5/(√5 × √5) = √5/5."),
     Q("HARD", "What is the value of 64^(1/2)?", [], "8", "Power 1/2 means square root.", "√64 = 8.")]},
  {"name": "Polynomials",
   "explanation": "A polynomial is an expression made of variables and coefficients using only addition, subtraction, multiplication and whole-number powers, like 3x² + 2x − 5. The highest power of the variable is the degree. A polynomial of degree 1 is linear, degree 2 is quadratic and degree 3 is cubic. A zero of a polynomial is a value of x that makes it equal to zero. The Remainder Theorem says that when p(x) is divided by (x − a), the remainder is p(a). If p(a) = 0, then (x − a) is a factor.",
   "keyPoints": ["A polynomial uses whole-number powers of the variable.",
                 "The degree is the highest power.",
                 "Degree 1 linear, 2 quadratic, 3 cubic.",
                 "A zero makes the polynomial equal 0.",
                 "Remainder of p(x) ÷ (x − a) is p(a)."],
   "examples": [EX("Degree", "4x³ − x + 7 has degree 3, so it is cubic."),
                EX("Finding a zero", "For p(x) = x − 4, p(4) = 0, so 4 is a zero."),
                EX("Remainder Theorem", "p(x) = x² + 1 divided by (x − 2): remainder p(2) = 5.")],
   "activity": "Write three polynomials of different degrees and find the value of each at x = 1.",
   "questions": [
     Q("EASY", "What is the degree of 5x² + 3x + 1?", [], "2|two", "Find the highest power of x.", "The highest power is 2."),
     Q("EASY", "Which is a linear polynomial?", ["x² + 1", "2x + 3", "x³", "5"], "2x + 3", "Linear means degree 1.", "2x + 3 has degree 1."),
     Q("MEDIUM", "What is the zero of p(x) = 2x − 6?", [], "3", "Solve 2x − 6 = 0.", "2x = 6, so x = 3."),
     Q("MEDIUM", "If p(x) = x² − 3x + 2, what is p(1)?", [], "0", "Put x = 1.", "1 − 3 + 2 = 0."),
     Q("HARD", "Remainder when x³ + 1 is divided by (x + 1)?", [], "0", "Use p(−1).", "(−1)³ + 1 = 0, so (x + 1) is a factor."),
     Q("HARD", "Factorise: x² − 9", ["(x − 3)(x + 3)", "(x − 9)(x + 1)", "(x − 3)²", "(x + 9)(x − 1)"], "(x − 3)(x + 3)", "Use a² − b² = (a − b)(a + b).", "x² − 3² = (x − 3)(x + 3).")]},
  {"name": "Linear Equations in Two Variables",
   "explanation": "A linear equation in two variables has the form ax + by + c = 0, where a and b are not both zero. Its solution is a pair of values (x, y) that makes the equation true. Such an equation has infinitely many solutions, and when we plot them they form a straight line. To find a solution, choose a value for one variable and solve for the other. The graph of y = kx always passes through the origin. The line x = a is vertical and y = b is horizontal.",
   "keyPoints": ["Form: ax + by + c = 0.",
                 "A solution is an ordered pair (x, y).",
                 "There are infinitely many solutions.",
                 "The graph is a straight line.",
                 "x = a is vertical; y = b is horizontal."],
   "examples": [EX("Finding solutions", "x + y = 5: (0, 5), (1, 4), (2, 3) are all solutions."),
                EX("Checking", "Is (2, 1) a solution of 2x − y = 3? 4 − 1 = 3 ✓"),
                EX("Through the origin", "y = 2x passes through (0, 0), (1, 2), (2, 4).", "  /\n /\n/ (0,0)")],
   "activity": "Plot three solutions of x + y = 6 on graph paper and join them with a ruler.",
   "questions": [
     Q("EASY", "Is (1, 2) a solution of x + y = 3?", ["Yes", "No"], "Yes", "Add x and y.", "1 + 2 = 3 ✓"),
     Q("EASY", "How many solutions does a linear equation in two variables have?", ["One", "Two", "None", "Infinitely many"], "Infinitely many", "Every point on the line works.", "It has infinitely many solutions."),
     Q("MEDIUM", "For 2x + y = 10, what is y when x = 3?", [], "4", "2(3) + y = 10.", "6 + y = 10, so y = 4."),
     Q("MEDIUM", "The graph of a linear equation in two variables is a ___.", ["Circle", "Straight line", "Curve", "Point"], "Straight line", "The word 'linear' gives a clue.", "It is a straight line."),
     Q("HARD", "The line y = 3 is ___.", ["Parallel to the x-axis", "Parallel to the y-axis", "Through the origin", "The y-axis"], "Parallel to the x-axis", "y stays the same for every x.", "y = 3 is a horizontal line."),
     Q("HARD", "If (k, 2) lies on 3x − y = 7, find k.", [], "3", "Put x = k and y = 2.", "3k − 2 = 7, so k = 3.")]}]},
 {"name": "Physics", "icon": "⚛️", "chapters": [
  {"name": "Motion",
   "explanation": "An object is in motion if its position changes with time. Distance is the total path length travelled, while displacement is the shortest distance from start to finish in a given direction. Speed is distance divided by time, and velocity is displacement divided by time, so velocity has direction. Acceleration is the rate of change of velocity: a = (v − u)/t. For uniform acceleration we use the equations v = u + at, s = ut + ½at² and v² = u² + 2as. On a distance–time graph, the slope gives speed.",
   "keyPoints": ["Distance is path length; displacement is shortest path with direction.",
                 "Speed = distance ÷ time.",
                 "Velocity is speed with direction.",
                 "Acceleration a = (v − u) ÷ t.",
                 "v = u + at, s = ut + ½at², v² = u² + 2as."],
   "examples": [EX("Distance vs displacement", "Walk 3 m east then 3 m west: distance 6 m, displacement 0 m.", "→→→ ←←← = 0"),
                EX("Speed", "A car travels 120 km in 2 hours: speed = 60 km/h."),
                EX("Acceleration", "A bike goes from 0 to 20 m/s in 5 s: a = 20/5 = 4 m/s².")],
   "activity": "Time yourself walking 20 metres and calculate your average speed in m/s.",
   "questions": [
     Q("EASY", "Speed = ___.", ["Distance × time", "Distance ÷ time", "Time ÷ distance", "Distance + time"], "Distance ÷ time", "Think of km per hour.", "Speed is distance over time."),
     Q("EASY", "The SI unit of velocity is ___.", ["m/s", "m/s²", "km", "N"], "m/s", "Metres every second.", "Velocity is measured in m/s."),
     Q("MEDIUM", "A runner covers 100 m in 20 s. What is the speed in m/s?", [], "5|5 m/s", "Divide 100 by 20.", "100 ÷ 20 = 5 m/s."),
     Q("MEDIUM", "A car goes from 10 m/s to 30 m/s in 4 s. Acceleration in m/s²?", [], "5|5 m/s²", "a = (v − u)/t.", "(30 − 10)/4 = 5 m/s²."),
     Q("HARD", "A body starts from rest with a = 2 m/s². Distance in 5 s (m)?", [], "25|25 m", "s = ut + ½at², with u = 0.", "½ × 2 × 25 = 25 m."),
     Q("HARD", "An athlete runs one full lap of a circular track. The displacement is ___.", ["Zero", "Equal to the circumference", "Twice the radius", "Equal to the radius"], "Zero", "Where do they end up?", "They finish at the start, so displacement is zero.")]},
  {"name": "Force and Laws of Motion",
   "explanation": "Newton's first law says an object stays at rest or keeps moving at constant velocity unless an unbalanced force acts on it; this property is called inertia. Heavier objects have more inertia. Momentum is mass times velocity (p = mv). Newton's second law says force equals the rate of change of momentum, which gives F = ma. The unit of force is the newton (N). Newton's third law says every action has an equal and opposite reaction, and the two forces act on different bodies.",
   "keyPoints": ["First law: objects resist changes in motion (inertia).",
                 "More mass means more inertia.",
                 "Momentum p = m × v.",
                 "Second law: F = m × a.",
                 "Third law: every action has an equal and opposite reaction."],
   "examples": [EX("Inertia", "When a bus stops suddenly, passengers lurch forward.", "🚌💨 → 🧍⬅"),
                EX("F = ma", "Force on a 2 kg ball accelerating at 3 m/s² = 6 N."),
                EX("Action–reaction", "A rocket pushes gas down; the gas pushes the rocket up.", "🚀⬆ 💨⬇")],
   "activity": "Place a coin on a card over a glass. Flick the card quickly and see where the coin goes.",
   "questions": [
     Q("EASY", "The SI unit of force is the ___.", ["Joule", "Newton", "Watt", "Pascal"], "Newton", "It is named after Isaac Newton.", "Force is measured in newtons."),
     Q("EASY", "The tendency of an object to resist a change in its motion is ___.", [], "inertia", "It is described by Newton's first law.", "This is inertia."),
     Q("MEDIUM", "What force (N) gives a 5 kg mass an acceleration of 2 m/s²?", [], "10|10 n", "F = m × a.", "5 × 2 = 10 N."),
     Q("MEDIUM", "Momentum of a 2 kg ball moving at 4 m/s (kg m/s)?", [], "8", "p = m × v.", "2 × 4 = 8 kg m/s."),
     Q("HARD", "Why does a gun recoil when fired?", ["Newton's third law", "Newton's first law", "Gravity", "Friction"], "Newton's third law", "Action and reaction.", "The bullet pushes back on the gun: equal and opposite reaction."),
     Q("HARD", "Which has more inertia?", ["A 1 kg stone", "A 10 kg stone", "Both are equal", "It depends on speed"], "A 10 kg stone", "Inertia depends on mass.", "Greater mass means greater inertia.")]},
  {"name": "Gravitation",
   "explanation": "Every object in the universe attracts every other object with a gravitational force. Newton's universal law of gravitation says F = G m₁m₂/r², so the force grows with mass and falls quickly with distance. The force of Earth's gravity gives falling objects an acceleration g of about 9.8 m/s². Mass is the amount of matter in a body and does not change, while weight is the force of gravity on it: W = mg. Your weight on the Moon is about one-sixth of your weight on Earth because the Moon's gravity is weaker.",
   "keyPoints": ["All objects attract each other.",
                 "F = G m₁m₂ / r².",
                 "g on Earth ≈ 9.8 m/s².",
                 "Weight W = m × g; mass stays the same.",
                 "Weight on the Moon ≈ 1/6 of weight on Earth."],
   "examples": [EX("Weight", "A 50 kg student weighs 50 × 9.8 = 490 N on Earth."),
                EX("Distance matters", "Double the distance → force becomes 1/4."),
                EX("Moon", "An astronaut weighing 600 N on Earth weighs about 100 N on the Moon.", "🌍 600 N → 🌙 100 N")],
   "activity": "Drop a sheet of paper and a crumpled ball of the same paper together. Which lands first and why?",
   "questions": [
     Q("EASY", "The value of g on Earth is about ___ m/s².", ["9.8", "1.6", "98", "0.98"], "9.8", "It is close to 10.", "g ≈ 9.8 m/s²."),
     Q("EASY", "Which quantity stays the same everywhere?", ["Mass", "Weight"], "Mass", "It is the amount of matter.", "Mass does not change; weight depends on gravity."),
     Q("MEDIUM", "Weight of a 10 kg object on Earth (take g = 10 m/s²), in N?", [], "100|100 n", "W = m × g.", "10 × 10 = 100 N."),
     Q("MEDIUM", "If the distance between two masses doubles, the force becomes ___.", ["Double", "Half", "One-fourth", "Four times"], "One-fourth", "Force depends on 1/r².", "1/2² = 1/4."),
     Q("HARD", "A person weighs 600 N on Earth. Weight on the Moon (N)?", [], "100|100 n", "The Moon's gravity is 1/6 of Earth's.", "600 ÷ 6 = 100 N."),
     Q("HARD", "What does G stand for in F = G m₁m₂/r²?", ["Acceleration due to gravity", "Universal gravitational constant", "Gravity on the Moon", "Weight"], "Universal gravitational constant", "It is the same everywhere in the universe.", "G is the universal gravitational constant.")]}]},
 {"name": "Chemistry", "icon": "🧪", "chapters": [
  {"name": "Matter in Our Surroundings",
   "explanation": "Matter is anything that has mass and occupies space. It is made of tiny particles that have spaces between them, are always moving, and attract each other. Matter exists mainly as solids, liquids and gases. Solids have a fixed shape and volume; liquids have a fixed volume but take the shape of the container; gases have neither. Changing temperature or pressure changes the state of matter. The temperature at which a solid melts is its melting point, and at which a liquid boils is its boiling point. Evaporation happens at the surface at any temperature and causes cooling.",
   "keyPoints": ["Matter has mass and takes up space.",
                 "Particles of matter are always moving.",
                 "Solids: fixed shape. Liquids: fixed volume. Gases: neither.",
                 "Temperature and pressure change the state.",
                 "Evaporation causes cooling."],
   "examples": [EX("States of water", "Ice (solid) → water (liquid) → steam (gas).", "🧊 → 💧 → ♨️"),
                EX("Diffusion", "The smell of incense spreads through a room because gas particles move.", "💨"),
                EX("Cooling by evaporation", "Water in an earthen pot stays cool because water evaporates through the pores.")],
   "activity": "Put a drop of ink in a glass of still water and watch how it spreads over 10 minutes.",
   "questions": [
     Q("EASY", "Which state of matter has a fixed shape?", ["Solid", "Liquid", "Gas"], "Solid", "Think of a brick.", "Solids have a fixed shape."),
     Q("EASY", "The boiling point of water is ___ °C.", [], "100", "At normal pressure.", "Water boils at 100°C."),
     Q("MEDIUM", "Changing from solid directly to gas is called ___.", ["Melting", "Sublimation", "Condensation", "Freezing"], "Sublimation", "Camphor does this.", "Solid to gas without becoming liquid is sublimation."),
     Q("MEDIUM", "Why does sweating cool our body?", ["Evaporation takes heat from the skin", "Sweat is cold", "It blocks sunlight", "It adds water"], "Evaporation takes heat from the skin", "Evaporation needs energy.", "Sweat evaporates using body heat, cooling us."),
     Q("HARD", "0°C in kelvin is ___ K.", [], "273|273.15", "Add 273 to Celsius.", "0 + 273 = 273 K."),
     Q("HARD", "Which increases the rate of evaporation?", ["Lower temperature", "Higher humidity", "Increased wind speed", "Smaller surface area"], "Increased wind speed", "Clothes dry faster on a windy day.", "Wind carries vapour away, speeding evaporation.")]},
  {"name": "Atoms and Molecules",
   "explanation": "An atom is the smallest particle of an element that can take part in a chemical reaction. A molecule is two or more atoms joined together, such as O₂ or H₂O. Elements are represented by symbols, like H for hydrogen and Na for sodium. The law of conservation of mass states that mass is neither created nor destroyed in a chemical reaction. Molecular mass is the sum of the atomic masses of all atoms in a molecule. One mole of any substance contains 6.022 × 10²³ particles (Avogadro's number).",
   "keyPoints": ["An atom is the smallest particle of an element.",
                 "A molecule is atoms joined together.",
                 "Mass is conserved in a chemical reaction.",
                 "Molecular mass = sum of atomic masses.",
                 "1 mole = 6.022 × 10²³ particles."],
   "examples": [EX("Molecular mass", "H₂O = 2(1) + 16 = 18 u."),
                EX("Symbols", "Na (sodium) comes from the Latin name 'natrium'."),
                EX("Mole", "18 g of water is 1 mole and contains 6.022 × 10²³ molecules.")],
   "activity": "Make models of H₂O and CO₂ using clay balls and toothpicks.",
   "questions": [
     Q("EASY", "The chemical symbol for sodium is ___.", ["S", "So", "Na", "N"], "Na", "It comes from the Latin 'natrium'.", "Sodium's symbol is Na."),
     Q("EASY", "The smallest particle of an element is an ___.", [], "atom", "Everything is made of these.", "It is an atom."),
     Q("MEDIUM", "Molecular mass of CO₂ (C = 12, O = 16) in u?", [], "44|44 u", "12 + 2 × 16.", "12 + 32 = 44 u."),
     Q("MEDIUM", "Avogadro's number is ___.", ["6.022 × 10²³", "3 × 10⁸", "9.8", "1.6 × 10⁻¹⁹"], "6.022 × 10²³", "It is the number of particles in one mole.", "N_A = 6.022 × 10²³."),
     Q("HARD", "How many moles are in 36 g of water (H₂O = 18 g/mol)?", [], "2", "moles = mass ÷ molar mass.", "36 ÷ 18 = 2 moles."),
     Q("HARD", "Which law says mass is neither created nor destroyed in a reaction?", ["Law of conservation of mass", "Law of constant proportions", "Newton's first law", "Ohm's law"], "Law of conservation of mass", "Total mass before = total mass after.", "It is the law of conservation of mass.")]},
  {"name": "Structure of the Atom",
   "explanation": "Atoms are made of three sub-atomic particles. Protons are positively charged and neutrons have no charge; both are in the small, dense nucleus at the centre. Electrons are negatively charged and move around the nucleus in shells (K, L, M…). The atomic number is the number of protons, and the mass number is protons plus neutrons. The maximum number of electrons in a shell is 2n², so K holds 2 and L holds 8. The electrons in the outermost shell are valence electrons. Isotopes are atoms of the same element with different mass numbers.",
   "keyPoints": ["Protons (+) and neutrons (0) are in the nucleus.",
                 "Electrons (−) move in shells around the nucleus.",
                 "Atomic number = number of protons.",
                 "Mass number = protons + neutrons.",
                 "A shell holds at most 2n² electrons."],
   "examples": [EX("Carbon", "Atomic number 6, mass number 12 → 6 protons, 6 neutrons, 6 electrons (2, 4).", "  (6p 6n)\n K:2  L:4"),
                EX("Sodium", "Na has 11 electrons: 2, 8, 1. It has 1 valence electron."),
                EX("Isotopes", "Carbon-12 and carbon-14 have 6 protons but 6 and 8 neutrons.")],
   "activity": "Draw the electron arrangement for the first 10 elements.",
   "questions": [
     Q("EASY", "Which particle has a negative charge?", ["Proton", "Neutron", "Electron", "Nucleus"], "Electron", "It moves around the nucleus.", "Electrons are negative."),
     Q("EASY", "Atomic number equals the number of ___.", ["Neutrons", "Protons", "Shells", "Molecules"], "Protons", "It identifies the element.", "Atomic number = protons."),
     Q("MEDIUM", "An atom has 11 protons and 12 neutrons. Its mass number is ___.", [], "23", "Add protons and neutrons.", "11 + 12 = 23."),
     Q("MEDIUM", "Maximum electrons in the L shell (n = 2)?", [], "8", "Use 2n².", "2 × 2² = 8."),
     Q("HARD", "Electronic configuration of chlorine (atomic number 17)?", ["2, 8, 7", "2, 8, 8", "2, 7, 8", "8, 8, 1"], "2, 8, 7", "Fill K, then L, then M.", "2 + 8 + 7 = 17."),
     Q("HARD", "Atoms of the same element with different mass numbers are ___.", ["Isotopes", "Isobars", "Ions", "Molecules"], "Isotopes", "Same protons, different neutrons.", "These are isotopes.")]}]},
 {"name": "Biology", "icon": "🧬", "chapters": [
  {"name": "The Fundamental Unit of Life",
   "explanation": "The cell is the basic structural and functional unit of all living things. Robert Hooke first saw cells in cork in 1665. Every cell has a cell membrane that controls what enters and leaves, cytoplasm, and genetic material. Prokaryotic cells, like bacteria, have no true nucleus, while eukaryotic cells have a nucleus bound by a membrane. Organelles do special jobs: mitochondria release energy and are called the powerhouse of the cell, ribosomes make proteins, and plant cells have a cell wall and chloroplasts.",
   "keyPoints": ["The cell is the basic unit of life.",
                 "Robert Hooke discovered cells in 1665.",
                 "The cell membrane controls what goes in and out.",
                 "Mitochondria are the powerhouse of the cell.",
                 "Plant cells have a cell wall and chloroplasts."],
   "examples": [EX("Plant vs animal cell", "Plant cells have a cell wall, chloroplasts and a large vacuole; animal cells do not.", "🌿 [wall | chloroplast]  vs  🐾 (membrane)"),
                EX("Prokaryote", "Bacteria have no nuclear membrane; their DNA lies in the cytoplasm."),
                EX("Osmosis", "A raisin swells in water as water moves into its cells.", "🍇💧")],
   "activity": "Look at a thin onion peel under a microscope (or at pictures) and draw the cells.",
   "questions": [
     Q("EASY", "Which organelle is called the powerhouse of the cell?", ["Nucleus", "Mitochondria", "Ribosome", "Vacuole"], "Mitochondria", "It releases energy.", "Mitochondria release energy from food."),
     Q("EASY", "Who first discovered cells?", ["Robert Hooke", "Isaac Newton", "Charles Darwin", "Gregor Mendel"], "Robert Hooke", "He looked at cork.", "Robert Hooke saw cells in cork in 1665."),
     Q("MEDIUM", "Which structure is found in plant cells but not animal cells?", ["Cell membrane", "Cell wall", "Mitochondria", "Nucleus"], "Cell wall", "It gives plants rigidity.", "Plant cells have a cellulose cell wall."),
     Q("MEDIUM", "Where are proteins made in a cell?", [], "ribosomes|ribosome", "Tiny particles attached to the ER.", "Ribosomes make proteins."),
     Q("HARD", "Cells without a true membrane-bound nucleus are ___.", ["Prokaryotic", "Eukaryotic", "Plant cells", "Nerve cells"], "Prokaryotic", "'Pro' means before, 'karyon' means nucleus.", "Bacteria are prokaryotic."),
     Q("HARD", "Movement of water through a semi-permeable membrane is called ___.", ["Diffusion", "Osmosis", "Respiration", "Transpiration"], "Osmosis", "Raisins swell in water because of it.", "That is osmosis.")]},
  {"name": "Tissues",
   "explanation": "A tissue is a group of similar cells that work together to do a particular job. Plants have meristematic tissues, which divide and help the plant grow, and permanent tissues, which have stopped dividing. Xylem carries water and minerals up from the roots, and phloem carries food from the leaves to other parts. Animals have four main tissue types: epithelial tissue covers and protects, muscular tissue helps movement, connective tissue such as blood and bone joins and supports, and nervous tissue carries messages.",
   "keyPoints": ["A tissue is a group of similar cells doing one job.",
                 "Meristematic tissue helps plants grow.",
                 "Xylem carries water; phloem carries food.",
                 "Animal tissues: epithelial, muscular, connective, nervous.",
                 "Blood is a connective tissue."],
   "examples": [EX("Xylem and phloem", "Water goes up through xylem; sugar goes down and around through phloem.", "⬆ xylem 💧   ⬇ phloem 🍬"),
                EX("Nerve cell", "A neuron carries signals from the brain to muscles very quickly."),
                EX("Muscles", "Heart muscle is cardiac muscle; it never gets tired.", "❤️")],
   "activity": "Put a white flower stem in coloured water overnight and see how the colour rises through the xylem.",
   "questions": [
     Q("EASY", "A group of similar cells doing the same job is a ___.", ["Organ", "Tissue", "System", "Organism"], "Tissue", "It is one level above cells.", "That is a tissue."),
     Q("EASY", "Which plant tissue carries water?", ["Phloem", "Xylem", "Epidermis", "Cork"], "Xylem", "It moves water up from the roots.", "Xylem carries water and minerals."),
     Q("MEDIUM", "Blood is a type of ___ tissue.", ["Epithelial", "Connective", "Nervous", "Muscular"], "Connective", "It connects parts of the body.", "Blood is a fluid connective tissue."),
     Q("MEDIUM", "Which tissue carries messages in the body?", [], "nervous|nervous tissue", "The brain and nerves are made of it.", "Nervous tissue carries signals."),
     Q("HARD", "Which tissue helps plants grow in length at the tips?", ["Apical meristem", "Xylem", "Cork", "Phloem"], "Apical meristem", "'Apex' means tip.", "Apical meristem at root and shoot tips increases length."),
     Q("HARD", "Which muscle type is found only in the heart?", ["Skeletal", "Smooth", "Cardiac", "Striated voluntary"], "Cardiac", "'Cardio' relates to the heart.", "Cardiac muscle works without tiring.")]},
  {"name": "Why Do We Fall Ill",
   "explanation": "Health is a state of physical, mental and social well-being, not just the absence of disease. Diseases can be acute, lasting a short time like a cold, or chronic, lasting a long time like diabetes. Infectious diseases are caused by microbes such as viruses, bacteria, fungi and protozoa and can spread from person to person through air, water, food, touch or carriers like mosquitoes. Non-infectious diseases, such as high blood pressure, are not spread. We can prevent infectious diseases through hygiene, clean water, good nutrition and vaccination.",
   "keyPoints": ["Health is physical, mental and social well-being.",
                 "Acute diseases are short; chronic diseases last long.",
                 "Microbes cause infectious diseases.",
                 "Infections spread by air, water, food, contact and vectors.",
                 "Vaccination prevents many diseases."],
   "examples": [EX("Air-borne", "The common cold spreads through droplets when someone sneezes.", "🤧 → 💨"),
                EX("Water-borne", "Cholera spreads through contaminated water.", "🚱"),
                EX("Vaccination", "The polio vaccine protects children from polio.", "💉")],
   "activity": "Make a poster listing five habits that help prevent infectious diseases.",
   "questions": [
     Q("EASY", "Which of these is an infectious disease?", ["Diabetes", "Common cold", "High blood pressure", "Cancer"], "Common cold", "It spreads from person to person.", "The common cold is caused by a virus and spreads."),
     Q("EASY", "Malaria is spread by ___.", ["Mosquitoes", "Water", "Handshakes", "Sunlight"], "Mosquitoes", "It is a vector-borne disease.", "Female Anopheles mosquitoes spread malaria."),
     Q("MEDIUM", "A disease that lasts a long time is called ___.", ["Acute", "Chronic"], "Chronic", "Diabetes is an example.", "Long-lasting diseases are chronic."),
     Q("MEDIUM", "Cholera usually spreads through ___.", ["Contaminated water", "Mosquito bites", "Sunlight", "Loud noise"], "Contaminated water", "Boiling water helps prevent it.", "Cholera is water-borne."),
     Q("HARD", "Which disease is caused by a virus?", ["Tuberculosis", "Typhoid", "AIDS", "Cholera"], "AIDS", "HIV is the cause.", "AIDS is caused by the HIV virus."),
     Q("HARD", "How does vaccination protect us?", ["It trains the immune system to recognise a microbe", "It kills all bacteria in the body", "It replaces blood", "It stops us from eating"], "It trains the immune system to recognise a microbe", "The body 'remembers' the germ.", "Vaccines prepare the immune system to fight the real infection.")]}]},
 {"name": "English", "icon": "📖", "chapters": [
  {"name": "Types of Sentences",
   "explanation": "Sentences can be grouped by purpose. A declarative sentence makes a statement and ends with a full stop. An interrogative sentence asks a question and ends with a question mark. An imperative sentence gives a command or request. An exclamatory sentence shows strong feeling and ends with an exclamation mark. Sentences can also be grouped by structure: a simple sentence has one independent clause, a compound sentence joins two independent clauses with a conjunction such as 'and' or 'but', and a complex sentence has an independent clause and at least one dependent clause.",
   "keyPoints": ["Declarative: a statement.",
                 "Interrogative: a question.",
                 "Imperative: a command or request.",
                 "Exclamatory: strong feeling!",
                 "Simple, compound and complex describe structure."],
   "examples": [EX("Four purposes", "I like music. / Do you like music? / Play some music. / What lovely music!"),
                EX("Compound", "I was tired, but I finished my homework."),
                EX("Complex", "When the bell rang, the students left.")],
   "activity": "Write one sentence of each type about your favourite hobby.",
   "questions": [
     Q("EASY", "'Close the window.' is ___.", ["Declarative", "Interrogative", "Imperative", "Exclamatory"], "Imperative", "It gives a command.", "Commands are imperative sentences."),
     Q("EASY", "Which sentence is interrogative?", ["It is raining.", "Is it raining?", "What rain!", "Stop the rain."], "Is it raining?", "It asks a question.", "Questions are interrogative."),
     Q("MEDIUM", "'What a beautiful sunset!' is ___.", ["Exclamatory", "Imperative", "Declarative", "Interrogative"], "Exclamatory", "It shows strong feeling.", "It is exclamatory."),
     Q("MEDIUM", "'She sings and he dances.' is a ___ sentence.", ["Simple", "Compound", "Complex"], "Compound", "Two independent clauses joined by 'and'.", "It is compound."),
     Q("HARD", "'Although it was late, we kept working.' is a ___ sentence.", ["Simple", "Compound", "Complex"], "Complex", "'Although it was late' cannot stand alone.", "It has a dependent clause, so it is complex."),
     Q("HARD", "Change to interrogative: 'You have finished the work.'", ["Have you finished the work?", "You finished the work?", "Did you have finished the work?", "Finished you the work?"], "Have you finished the work?", "Move the helping verb to the front.", "Have you finished the work?")]},
  {"name": "Determiners",
   "explanation": "Determiners are words placed before a noun to show which one, how many or how much. Articles are the most common determiners: 'a' and 'an' are indefinite, and 'the' is definite. Use 'an' before a vowel sound (an hour) and 'a' before a consonant sound (a university). Demonstratives include this, that, these and those. Quantifiers include some, any, many, much, few and little. 'Many' and 'few' go with countable nouns; 'much' and 'little' go with uncountable nouns.",
   "keyPoints": ["Determiners come before nouns.",
                 "'an' before a vowel sound; 'a' before a consonant sound.",
                 "'the' refers to something specific.",
                 "many/few for countable nouns.",
                 "much/little for uncountable nouns."],
   "examples": [EX("Sound, not spelling", "an hour (silent h), a university ('yoo' sound)."),
                EX("Countable vs uncountable", "many books, much water; few friends, little time."),
                EX("Demonstratives", "this pen (near), those trees (far, plural).")],
   "activity": "Describe your classroom using at least eight different determiners.",
   "questions": [
     Q("EASY", "I saw ___ elephant.", ["a", "an", "the", "many"], "an", "'Elephant' begins with a vowel sound.", "Use 'an' before a vowel sound."),
     Q("EASY", "___ Sun rises in the east.", ["A", "An", "The", "Some"], "The", "There is only one Sun.", "Use 'the' for unique things."),
     Q("MEDIUM", "She is ___ honest girl.", ["a", "an", "the", "much"], "an", "The 'h' in honest is silent.", "'Honest' starts with a vowel sound: an honest girl."),
     Q("MEDIUM", "How ___ sugar do you need?", ["many", "much", "few", "a"], "much", "Sugar is uncountable.", "Use 'much' with uncountable nouns."),
     Q("HARD", "There are ___ apples left, so we must buy more.", ["few", "little", "much", "a little"], "few", "Apples are countable; the meaning is 'not enough'.", "'Few' is used with countable nouns."),
     Q("HARD", "He is ___ European.", ["a", "an", "the", "some"], "a", "'European' starts with a 'yoo' sound.", "The 'yoo' sound is a consonant sound, so 'a European'.")]},
  {"name": "Conditional Sentences",
   "explanation": "Conditional sentences describe a situation and its result, usually with 'if'. The zero conditional talks about general truths: If you heat ice, it melts. The first conditional talks about real future possibilities: If it rains, I will stay home. The second conditional talks about unreal or unlikely present situations: If I had wings, I would fly. The third conditional talks about imagined past situations: If you had studied, you would have passed. In the second conditional, 'were' is often used for all subjects: If I were you, I would rest.",
   "keyPoints": ["Zero: If + present, present (facts).",
                 "First: If + present, will + verb (likely future).",
                 "Second: If + past, would + verb (unreal present).",
                 "Third: If + had + past participle, would have + past participle.",
                 "If I were you… is correct."],
   "examples": [EX("Zero", "If water reaches 100°C, it boils."),
                EX("First", "If you hurry, you will catch the bus."),
                EX("Third", "If she had left early, she would have caught the train.")],
   "activity": "Write one sentence for each of the four conditionals about school life.",
   "questions": [
     Q("EASY", "If it rains, we ___ stay inside.", ["will", "would have", "had", "were"], "will", "This is a likely future situation.", "First conditional: will + verb."),
     Q("EASY", "If you heat ice, it ___.", ["melts", "will melted", "would melted", "melting"], "melts", "This is a general fact.", "Zero conditional: present tense."),
     Q("MEDIUM", "If I ___ a bird, I would fly.", ["am", "were", "will be", "had been"], "were", "Imaginary present situation.", "Second conditional uses 'were'."),
     Q("MEDIUM", "If he studied harder, he ___ better marks.", ["will get", "would get", "gets", "had got"], "would get", "Second conditional result.", "If + past → would + verb."),
     Q("HARD", "If they had left earlier, they ___ the train.", ["would catch", "will catch", "would have caught", "caught"], "would have caught", "This is about the past.", "Third conditional: would have + past participle."),
     Q("HARD", "Which sentence is a third conditional?", ["If I see him, I will tell him.", "If I saw him, I would tell him.", "If I had seen him, I would have told him.", "If you see him, tell him."], "If I had seen him, I would have told him.", "Look for 'had' + past participle.", "It imagines a different past.")]}]},
 {"name": "Social Science", "icon": "🌍", "chapters": [
  {"name": "India – Size and Location",
   "explanation": "India lies entirely in the Northern Hemisphere. The Tropic of Cancer (23°30′N) passes through the middle of the country. The mainland extends between latitudes 8°4′N and 37°6′N and longitudes 68°7′E and 97°25′E. India is the seventh largest country in the world by area, covering about 3.28 million square kilometres. The Standard Meridian of India, 82°30′E, passes through Mirzapur in Uttar Pradesh and is used to set Indian Standard Time. India has a long coastline and shares land borders with seven countries: Pakistan, Afghanistan, China, Nepal, Bhutan, Bangladesh and Myanmar.",
   "keyPoints": ["India is in the Northern Hemisphere.",
                 "The Tropic of Cancer passes through India.",
                 "India is the 7th largest country by area.",
                 "The Standard Meridian is 82°30′E.",
                 "India shares land borders with seven countries."],
   "examples": [EX("Time difference", "Arunachal Pradesh sees sunrise about 2 hours earlier than Gujarat because of the east–west spread."),
                EX("Neighbours across the sea", "Sri Lanka and the Maldives are India's southern neighbours across the sea.", "🇮🇳 ~~ 🌊 ~~ 🇱🇰"),
                EX("Tropic of Cancer", "It passes through eight states, including Gujarat, Madhya Pradesh and West Bengal.")],
   "activity": "On a map of India, trace the Tropic of Cancer and list the states it crosses.",
   "questions": [
     Q("EASY", "India lies in which hemisphere?", ["Northern", "Southern"], "Northern", "It is north of the Equator.", "India lies entirely in the Northern Hemisphere."),
     Q("EASY", "Which line of latitude passes through the middle of India?", ["Equator", "Tropic of Cancer", "Tropic of Capricorn", "Arctic Circle"], "Tropic of Cancer", "It is at 23°30′N.", "The Tropic of Cancer divides India almost in half."),
     Q("MEDIUM", "India's rank in area in the world is ___.", ["First", "Third", "Seventh", "Tenth"], "Seventh", "Russia is first.", "India is the seventh largest country."),
     Q("MEDIUM", "The Standard Meridian of India passes through ___.", ["Mirzapur", "Delhi", "Mumbai", "Chennai"], "Mirzapur", "It is in Uttar Pradesh.", "82°30′E passes near Mirzapur."),
     Q("HARD", "Which neighbouring country is separated from India by the Palk Strait?", ["Sri Lanka", "Maldives", "Bangladesh", "Myanmar"], "Sri Lanka", "It is off the coast of Tamil Nadu.", "The Palk Strait separates India and Sri Lanka."),
     Q("HARD", "Why is there a time lag between Gujarat and Arunachal Pradesh?", ["India's large east–west extent", "Different seasons", "Different languages", "Mountains block the Sun"], "India's large east–west extent", "Longitude affects local time.", "About 30° of longitude gives roughly a 2-hour difference.")]},
  {"name": "What is Democracy?",
   "explanation": "Democracy is a form of government in which the rulers are elected by the people. In a democracy, final decision-making power rests with elected representatives. Elections must be free and fair, giving people a real choice. Each adult has one vote, and each vote has equal value. A democratic government rules within the limits set by the constitution and respects citizens' rights. Democracy is considered better than other forms because it improves the quality of decision-making, allows mistakes to be corrected, and respects the dignity of citizens.",
   "keyPoints": ["In a democracy, people elect their rulers.",
                 "Elections must be free and fair.",
                 "One person, one vote, one value.",
                 "Government works within constitutional limits.",
                 "Democracy allows mistakes to be corrected."],
   "examples": [EX("Free and fair", "People can vote for any party without fear, and votes are counted honestly.", "🗳️"),
                EX("Not democratic", "A ruler who takes power by force and cancels elections is not democratic."),
                EX("Rule of law", "Even the Prime Minister must obey the courts.", "⚖️")],
   "activity": "Hold a class election for a class monitor and discuss what made it fair.",
   "questions": [
     Q("EASY", "In a democracy, rulers are ___.", ["Chosen by the people", "Born into power", "Chosen by the army", "Appointed by other countries"], "Chosen by the people", "Think of elections.", "People elect their rulers in a democracy."),
     Q("EASY", "The principle 'one person, one vote' means ___.", ["Each adult's vote has equal value", "Only rich people vote", "Only one person votes", "Votes can be sold"], "Each adult's vote has equal value", "It is about political equality.", "Every adult's vote counts equally."),
     Q("MEDIUM", "Which is a feature of a democracy?", ["Free and fair elections", "Rule by the army", "No constitution", "Only one party allowed"], "Free and fair elections", "People must have real choice.", "Free and fair elections are essential."),
     Q("MEDIUM", "A democratic government must work within the limits of the ___.", [], "constitution", "It is the supreme law.", "Constitutional law limits the government."),
     Q("HARD", "Which is an argument FOR democracy?", ["It allows mistakes to be corrected", "Decisions are always fast", "Leaders never change", "People have no say"], "It allows mistakes to be corrected", "Public debate and elections help.", "Democracy allows correction of mistakes."),
     Q("HARD", "Why is a country where elections are held but the opposition is banned NOT fully democratic?", ["People have no real choice", "Elections are too frequent", "Too many people vote", "The courts are too strong"], "People have no real choice", "A fair election needs alternatives.", "Without a real choice, elections are not free and fair.")]},
  {"name": "The French Revolution",
   "explanation": "In 1789, France was ruled by King Louis XVI, and society was divided into three estates. The clergy and nobility (the first and second estates) enjoyed privileges and paid almost no taxes, while the third estate of peasants, workers and the middle class paid most of the taxes. Rising prices, food shortages and ideas of liberty, equality and fraternity from philosophers like Rousseau and Montesquieu led to anger. On 14 July 1789, people stormed the Bastille prison. The revolution ended absolute monarchy, declared the rights of man and citizen, and inspired democratic ideas around the world.",
   "keyPoints": ["The French Revolution began in 1789.",
                 "Society had three estates; the third estate paid most taxes.",
                 "The Bastille was stormed on 14 July 1789.",
                 "Ideas: liberty, equality and fraternity.",
                 "It ended absolute monarchy in France."],
   "examples": [EX("Three estates", "1st: clergy, 2nd: nobility, 3rd: everyone else (about 97% of people).", "⛪ 👑 👨‍🌾"),
                EX("Storming the Bastille", "The Bastille was a symbol of the king's power; its fall marked the start of the revolution."),
                EX("Philosophers", "Rousseau wrote about government based on a 'social contract' with the people.")],
   "activity": "Make a timeline of five major events of the French Revolution.",
   "questions": [
     Q("EASY", "In which year did the French Revolution begin?", [], "1789", "The Bastille fell that year.", "It began in 1789."),
     Q("EASY", "Who was the king of France at the start of the revolution?", ["Louis XIV", "Louis XVI", "Napoleon", "Charles I"], "Louis XVI", "He was later executed.", "Louis XVI ruled in 1789."),
     Q("MEDIUM", "Which estate paid most of the taxes?", ["First", "Second", "Third"], "Third", "Peasants and workers.", "The third estate paid almost all taxes."),
     Q("MEDIUM", "The prison stormed on 14 July 1789 was the ___.", ["Bastille", "Tower of London", "Versailles", "Louvre"], "Bastille", "It symbolised the king's power.", "The Bastille was stormed."),
     Q("HARD", "The slogan of the French Revolution was liberty, equality and ___.", ["Fraternity", "Monarchy", "Wealth", "Religion"], "Fraternity", "It means brotherhood.", "Liberty, equality, fraternity."),
     Q("HARD", "Which philosopher proposed the idea of a 'social contract'?", ["Rousseau", "Shakespeare", "Newton", "Darwin"], "Rousseau", "He was a French-speaking philosopher.", "Jean-Jacques Rousseau wrote 'The Social Contract'.")]}]}]}
