# Seed content source for Grade 12.
from grade6 import Q, EX

GRADE12 = {"grade": 12, "subjects": [
 {"name": "Mathematics", "icon": "🔢", "chapters": [
  {"name": "Relations and Functions",
   "explanation": "A relation from set A to set B is a subset of A × B. A relation on a set is reflexive if every element is related to itself, symmetric if aRb implies bRa, and transitive if aRb and bRc imply aRc. A relation with all three properties is an equivalence relation. A function assigns exactly one output to each input. A function is one-one (injective) if different inputs give different outputs, and onto (surjective) if every element of the codomain is an output. A function that is both one-one and onto is bijective and has an inverse. The composition (g ∘ f)(x) = g(f(x)).",
   "keyPoints": ["Equivalence relation = reflexive + symmetric + transitive.",
                 "A function gives exactly one output per input.",
                 "One-one: different inputs → different outputs.",
                 "Onto: every codomain element is an output.",
                 "(g ∘ f)(x) = g(f(x))."],
   "examples": [EX("Equivalence", "'Is equal to' on numbers is reflexive, symmetric and transitive."),
                EX("One-one", "f(x) = 2x on real numbers is one-one; f(x) = x² is not (f(2) = f(−2))."),
                EX("Composition", "f(x) = x + 1, g(x) = 2x: (g ∘ f)(3) = g(4) = 8.")],
   "activity": "Check whether 'is a sibling of' in your family is reflexive, symmetric and transitive.",
   "questions": [
     Q("EASY", "A relation that is reflexive, symmetric and transitive is called ___.", ["An equivalence relation", "A function", "An inverse", "A composition"], "An equivalence relation", "All three properties.", "It is an equivalence relation."),
     Q("EASY", "If f(x) = 3x and g(x) = x + 2, then g(f(1)) = ?", [], "5", "First f(1) = 3.", "g(3) = 5."),
     Q("MEDIUM", "Is f(x) = x² from R to R one-one?", ["Yes", "No"], "No", "Compare f(2) and f(−2).", "Both give 4, so it is not one-one."),
     Q("MEDIUM", "A function that is both one-one and onto is ___.", ["Bijective", "Constant", "Periodic", "Empty"], "Bijective", "It has an inverse.", "It is bijective."),
     Q("HARD", "If f(x) = 2x + 3, the inverse f⁻¹(x) = ?", ["(x − 3)/2", "(x + 3)/2", "2x − 3", "x/2 + 3"], "(x − 3)/2", "Solve y = 2x + 3 for x.", "x = (y − 3)/2."),
     Q("HARD", "The relation R = {(a, b) : a ≤ b} on real numbers is NOT ___.", ["Reflexive", "Symmetric", "Transitive"], "Symmetric", "2 ≤ 3 but is 3 ≤ 2?", "It is reflexive and transitive but not symmetric.")]},
  {"name": "Matrices and Determinants",
   "explanation": "A matrix is a rectangular arrangement of numbers in rows and columns; an m × n matrix has m rows and n columns. Matrices of the same order can be added. To multiply A (m × n) by B (n × p), the number of columns of A must equal the number of rows of B, and matrix multiplication is generally not commutative. The transpose Aᵀ swaps rows and columns. The determinant of a 2 × 2 matrix [[a, b], [c, d]] is ad − bc. A square matrix with a non-zero determinant is invertible, and A⁻¹ = adj(A) / |A|. Matrices can solve systems of linear equations: AX = B gives X = A⁻¹B.",
   "keyPoints": ["An m × n matrix has m rows and n columns.",
                 "AB exists if columns of A = rows of B.",
                 "AB ≠ BA in general.",
                 "|[[a, b], [c, d]]| = ad − bc.",
                 "A⁻¹ exists only if |A| ≠ 0."],
   "examples": [EX("Determinant", "|[[3, 1], [2, 4]]| = 3 × 4 − 1 × 2 = 10."),
                EX("Order", "[[1, 2, 3], [4, 5, 6]] is a 2 × 3 matrix.", "[1 2 3]\n[4 5 6]"),
                EX("Transpose", "The transpose of [[1, 2], [3, 4]] is [[1, 3], [2, 4]].")],
   "activity": "Write the marks of three friends in three subjects as a 3 × 3 matrix and find each row sum.",
   "questions": [
     Q("EASY", "A matrix with 2 rows and 3 columns has order ___.", ["2 × 3", "3 × 2", "6", "5"], "2 × 3", "Rows first, then columns.", "Order is rows × columns: 2 × 3."),
     Q("EASY", "Determinant of [[2, 0], [0, 3]]?", [], "6", "ad − bc.", "2 × 3 − 0 = 6."),
     Q("MEDIUM", "Determinant of [[4, 2], [3, 1]]?", [], "-2|−2", "4 × 1 − 2 × 3.", "4 − 6 = −2."),
     Q("MEDIUM", "If A is 2 × 3 and B is 3 × 4, AB has order ___.", ["2 × 4", "3 × 3", "4 × 2", "Not defined"], "2 × 4", "Outer numbers give the order.", "(2 × 3)(3 × 4) → 2 × 4."),
     Q("HARD", "A square matrix is invertible only if its determinant is ___.", ["Non-zero", "Zero", "Negative", "One"], "Non-zero", "A⁻¹ = adj(A)/|A|.", "Division by |A| needs |A| ≠ 0."),
     Q("HARD", "For square matrices, (AB)ᵀ = ?", ["BᵀAᵀ", "AᵀBᵀ", "AB", "BA"], "BᵀAᵀ", "The order reverses.", "(AB)ᵀ = BᵀAᵀ.")]},
  {"name": "Integrals",
   "explanation": "Integration is the reverse of differentiation. The indefinite integral ∫f(x) dx gives a family of functions F(x) + C whose derivative is f(x), where C is the constant of integration. Standard results include ∫xⁿ dx = xⁿ⁺¹/(n + 1) + C (n ≠ −1), ∫1/x dx = ln|x| + C, ∫eˣ dx = eˣ + C, ∫sin x dx = −cos x + C and ∫cos x dx = sin x + C. Methods include substitution, partial fractions and integration by parts. The definite integral ∫ₐᵇ f(x) dx = F(b) − F(a) gives the area under the curve between a and b.",
   "keyPoints": ["Integration reverses differentiation.",
                 "∫xⁿ dx = xⁿ⁺¹/(n + 1) + C.",
                 "∫eˣ dx = eˣ + C; ∫1/x dx = ln|x| + C.",
                 "∫cos x dx = sin x + C.",
                 "∫ₐᵇ f(x) dx = F(b) − F(a)."],
   "examples": [EX("Power rule", "∫x³ dx = x⁴/4 + C."),
                EX("Definite integral", "∫₀² 2x dx = [x²]₀² = 4 − 0 = 4.", "area under y = 2x from 0 to 2 = 4"),
                EX("Substitution", "∫2x cos(x²) dx: let u = x², du = 2x dx → sin(x²) + C.")],
   "activity": "Estimate the area under y = x from 0 to 4 by counting squares on graph paper, then check with integration.",
   "questions": [
     Q("EASY", "∫x dx = ?", ["x²/2 + C", "x² + C", "1 + C", "2x + C"], "x²/2 + C", "Power rule with n = 1.", "x²/2 + C."),
     Q("EASY", "∫cos x dx = ?", ["sin x + C", "−sin x + C", "cos x + C", "tan x + C"], "sin x + C", "Derivative of sin x is cos x.", "∫cos x dx = sin x + C."),
     Q("MEDIUM", "∫₀¹ 3x² dx = ?", [], "1", "Antiderivative is x³.", "1³ − 0³ = 1."),
     Q("MEDIUM", "∫eˣ dx = ?", ["eˣ + C", "xeˣ + C", "eˣ⁺¹ + C", "ln x + C"], "eˣ + C", "eˣ is its own derivative.", "∫eˣ dx = eˣ + C."),
     Q("HARD", "∫₁³ 2x dx = ?", [], "8", "Antiderivative is x².", "9 − 1 = 8."),
     Q("HARD", "For x > 0, ∫1/x dx = ?", ["ln x + C", "x⁻² + C", "1/x² + C", "x ln x + C"], "ln x + C", "The power rule fails for n = −1.", "∫1/x dx = ln|x| + C.")]}]},
 {"name": "Physics", "icon": "⚛️", "chapters": [
  {"name": "Electric Charges and Fields",
   "explanation": "Electric charge is a property of matter; like charges repel and unlike charges attract. Charge is quantised (q = ne, where e = 1.6 × 10⁻¹⁹ C) and conserved. Coulomb's law gives the force between two point charges: F = k q₁q₂ / r², with k = 9 × 10⁹ N m² C⁻². The electric field E = F/q is the force per unit positive charge, and field lines start on positive charges and end on negative ones. Gauss's law states that the total electric flux through a closed surface equals the enclosed charge divided by ε₀.",
   "keyPoints": ["Like charges repel; unlike charges attract.",
                 "Charge is quantised: q = ne.",
                 "Coulomb's law: F = kq₁q₂/r².",
                 "Electric field E = F/q.",
                 "Gauss's law: flux = q_enclosed/ε₀."],
   "examples": [EX("Coulomb's law", "Two 1 μC charges 1 m apart: F = 9 × 10⁹ × 10⁻¹² = 9 × 10⁻³ N."),
                EX("Field lines", "Lines go outward from a positive charge and inward to a negative charge.", "⊕ → → ⊖"),
                EX("Distance effect", "Tripling the distance makes the force 1/9 as large.")],
   "activity": "Rub a comb in dry hair and bring it near small paper bits. Explain what happens.",
   "questions": [
     Q("EASY", "Like charges ___ each other.", ["Attract", "Repel", "Ignore"], "Repel", "Two positives push away.", "Like charges repel."),
     Q("EASY", "The SI unit of charge is the ___.", ["Coulomb", "Ampere", "Volt", "Newton"], "Coulomb", "Symbol C.", "Charge is measured in coulombs."),
     Q("MEDIUM", "If the distance between two charges is doubled, the force becomes ___.", ["Half", "Double", "One-fourth", "Four times"], "One-fourth", "F ∝ 1/r².", "1/2² = 1/4."),
     Q("MEDIUM", "The electric field is defined as ___.", ["Force per unit charge", "Charge per unit force", "Work per unit time", "Charge × distance"], "Force per unit charge", "E = F/q.", "E is force per unit positive charge."),
     Q("HARD", "How many electrons make up a charge of 1.6 × 10⁻¹⁸ C?", [], "10", "n = q/e.", "1.6 × 10⁻¹⁸ / 1.6 × 10⁻¹⁹ = 10."),
     Q("HARD", "Gauss's law relates electric flux through a closed surface to the ___.", ["Enclosed charge", "Surface area only", "Magnetic field", "Current"], "Enclosed charge", "Φ = q/ε₀.", "Flux depends only on the enclosed charge.")]},
  {"name": "Current Electricity",
   "explanation": "Electric current is the rate of flow of charge. In a conductor, free electrons drift slowly opposite to the field with drift velocity v_d, and I = neAv_d. Ohm's law V = IR holds for ohmic conductors, and resistance R = ρL/A, where ρ is resistivity. Resistivity of metals increases with temperature. A cell has an EMF ε and internal resistance r, so the terminal voltage is V = ε − Ir. Kirchhoff's junction rule (sum of currents into a junction = sum out) follows from charge conservation, and the loop rule (sum of potential changes around a loop = 0) follows from energy conservation. The Wheatstone bridge is balanced when P/Q = R/S.",
   "keyPoints": ["I = neAv_d.",
                 "R = ρL/A.",
                 "Terminal voltage V = ε − Ir.",
                 "Kirchhoff's junction rule: current in = current out.",
                 "Kirchhoff's loop rule: sum of potential changes = 0."],
   "examples": [EX("Resistance", "Doubling a wire's length doubles its resistance."),
                EX("Internal resistance", "A 12 V cell with r = 1 Ω giving 2 A has terminal voltage 12 − 2 = 10 V."),
                EX("Junction rule", "If 5 A enters a junction and 3 A leaves by one wire, 2 A leaves by the other.", "5A → • → 3A\n       ↓ 2A")],
   "activity": "Measure the voltage of a new and an old battery with a multimeter and compare.",
   "questions": [
     Q("EASY", "Resistance R = ρL/A. If L doubles, R ___.", ["Doubles", "Halves", "Stays the same", "Quadruples"], "Doubles", "R is proportional to length.", "R ∝ L."),
     Q("EASY", "Kirchhoff's junction rule is based on conservation of ___.", ["Charge", "Energy", "Mass", "Momentum"], "Charge", "Charge cannot pile up at a junction.", "It comes from charge conservation."),
     Q("MEDIUM", "A cell of EMF 6 V and internal resistance 0.5 Ω supplies 2 A. Terminal voltage (V)?", [], "5", "V = ε − Ir.", "6 − 1 = 5 V."),
     Q("MEDIUM", "Kirchhoff's loop rule is based on conservation of ___.", ["Energy", "Charge", "Mass", "Momentum"], "Energy", "Potential around a closed loop.", "It comes from energy conservation."),
     Q("HARD", "A wire is stretched to twice its length (volume unchanged). Its resistance becomes ___ times.", [], "4|four", "Length doubles and area halves.", "R ∝ L/A → 2 ÷ (1/2) = 4."),
     Q("HARD", "A Wheatstone bridge with P = 10 Ω, Q = 20 Ω, R = 15 Ω is balanced. S = ? (Ω)", [], "30", "P/Q = R/S.", "10/20 = 15/S, so S = 30 Ω.")]},
  {"name": "Ray Optics",
   "explanation": "Mirrors and lenses form images by reflection and refraction. For spherical mirrors, 1/v + 1/u = 1/f and f = R/2. For thin lenses, 1/v − 1/u = 1/f, using the Cartesian sign convention. Magnification is the ratio of image height to object height. Total internal reflection happens when light travels from a denser to a rarer medium at an angle greater than the critical angle, where sin C = 1/n; it is used in optical fibres. A prism disperses white light into colours because the refractive index varies with wavelength. Microscopes and telescopes use combinations of lenses to magnify.",
   "keyPoints": ["Mirror formula: 1/v + 1/u = 1/f; f = R/2.",
                 "Lens formula: 1/v − 1/u = 1/f.",
                 "Total internal reflection needs angle > critical angle.",
                 "sin C = 1/n.",
                 "Optical fibres use total internal reflection."],
   "examples": [EX("Focal length", "A concave mirror with R = 30 cm has f = 15 cm."),
                EX("Optical fibre", "Light bounces inside a glass fibre by total internal reflection, carrying internet data.", "〰️💡〰️"),
                EX("Rainbow", "Water droplets disperse and reflect sunlight into a spectrum.", "🌈")],
   "activity": "Shine a torch through a glass of water at different angles and look for total internal reflection at the surface.",
   "questions": [
     Q("EASY", "The focal length of a mirror with radius of curvature 20 cm is ___ cm.", [], "10", "f = R/2.", "20 ÷ 2 = 10 cm."),
     Q("EASY", "Optical fibres work on the principle of ___.", ["Total internal reflection", "Dispersion", "Diffraction", "Polarisation"], "Total internal reflection", "Light stays trapped inside.", "They use total internal reflection."),
     Q("MEDIUM", "For total internal reflection, light must travel from ___.", ["Denser to rarer medium", "Rarer to denser medium", "Vacuum to glass", "Any medium"], "Denser to rarer medium", "Glass to air, for example.", "It occurs going from denser to rarer."),
     Q("MEDIUM", "Splitting of white light into colours by a prism is ___.", ["Dispersion", "Reflection", "Scattering", "Interference"], "Dispersion", "Newton showed this.", "This is dispersion."),
     Q("HARD", "Critical angle for a medium with n = 2 is ___.", ["30°", "45°", "60°", "90°"], "30°", "sin C = 1/n.", "sin C = 1/2, so C = 30°."),
     Q("HARD", "A convex lens has f = 20 cm. An object is at u = −30 cm. Image distance v = ? (cm)", [], "60|+60", "1/v = 1/f + 1/u.", "1/v = 1/20 − 1/30 = 1/60, so v = 60 cm.")]}]},
 {"name": "Chemistry", "icon": "🧪", "chapters": [
  {"name": "Solutions",
   "explanation": "A solution is a homogeneous mixture of a solute dissolved in a solvent. Concentration can be expressed as mass percentage, mole fraction, molarity (mol/L) or molality (mol/kg of solvent); molality does not change with temperature. Henry's law says the solubility of a gas in a liquid is proportional to its partial pressure. Raoult's law says the vapour pressure of a solvent is proportional to its mole fraction. Colligative properties depend only on the number of solute particles: relative lowering of vapour pressure, elevation of boiling point, depression of freezing point and osmotic pressure (π = CRT).",
   "keyPoints": ["Molarity = mol/L; molality = mol/kg of solvent.",
                 "Molality does not depend on temperature.",
                 "Henry's law: gas solubility ∝ pressure.",
                 "Colligative properties depend on the number of particles.",
                 "Osmotic pressure π = CRT."],
   "examples": [EX("Molality", "1 mol of glucose in 500 g of water gives 2 mol/kg."),
                EX("Freezing point depression", "Salt is spread on icy roads to lower the freezing point of water.", "🧂❄️"),
                EX("Henry's law", "Soft drinks are bottled under high CO₂ pressure; the fizz escapes when opened.", "🥤")],
   "activity": "Freeze plain water and salt water in the same freezer. Which freezes first?",
   "questions": [
     Q("EASY", "Which concentration unit does NOT change with temperature?", ["Molarity", "Molality"], "Molality", "It uses mass, not volume.", "Molality is mass-based, so it is temperature-independent."),
     Q("EASY", "Salt spread on roads in winter lowers the ___ of water.", ["Freezing point", "Boiling point", "Density", "Colour"], "Freezing point", "Ice melts at a lower temperature.", "It depresses the freezing point."),
     Q("MEDIUM", "Molality of 2 mol solute in 4 kg of water?", [], "0.5|0.5 m", "mol/kg.", "2/4 = 0.5 mol/kg."),
     Q("MEDIUM", "Colligative properties depend on the ___ of solute particles.", ["Number", "Colour", "Nature", "Shape"], "Number", "Not on what they are.", "They depend only on the number of particles."),
     Q("HARD", "Henry's law relates gas solubility to ___.", ["Partial pressure", "Temperature only", "Volume of liquid", "Colour"], "Partial pressure", "Soft drinks are bottled under pressure.", "Solubility ∝ partial pressure."),
     Q("HARD", "Osmotic pressure is given by ___.", ["π = CRT", "π = nR/T", "π = PV", "π = mgh"], "π = CRT", "C is concentration.", "Van 't Hoff equation: π = CRT.")]},
  {"name": "Electrochemistry",
   "explanation": "Electrochemistry studies the conversion between chemical and electrical energy. A galvanic (voltaic) cell, like the Daniell cell, converts chemical energy into electricity; oxidation happens at the anode and reduction at the cathode. The standard electrode potential measures a half-cell's tendency to be reduced, measured against the standard hydrogen electrode (0 V). E°cell = E°cathode − E°anode. The Nernst equation relates cell potential to concentrations. In electrolytic cells, electricity drives non-spontaneous reactions. Faraday's first law says the mass deposited is proportional to the charge passed. Corrosion, such as rusting, is an electrochemical process.",
   "keyPoints": ["Galvanic cells convert chemical energy to electrical energy.",
                 "Oxidation at the anode; reduction at the cathode.",
                 "The standard hydrogen electrode is 0 V.",
                 "E°cell = E°cathode − E°anode.",
                 "Faraday: mass deposited ∝ charge passed."],
   "examples": [EX("Daniell cell", "Zn | Zn²⁺ || Cu²⁺ | Cu: zinc is oxidised, copper ions are reduced. E° ≈ 1.1 V.", "Zn(−) ⟶ e⁻ ⟶ Cu(+)"),
                EX("Electroplating", "Silver is deposited on spoons using electrolysis."),
                EX("Corrosion", "Galvanising coats iron with zinc to protect it from rusting.")],
   "activity": "Make a lemon battery with a copper coin and a galvanised nail, and measure its voltage.",
   "questions": [
     Q("EASY", "In a galvanic cell, oxidation occurs at the ___.", ["Anode", "Cathode"], "Anode", "'An Ox' — anode oxidation.", "Oxidation happens at the anode."),
     Q("EASY", "The potential of the standard hydrogen electrode is ___ V.", [], "0|0.0|0.00", "It is the reference.", "SHE is taken as 0 V."),
     Q("MEDIUM", "E°(Cu²⁺/Cu) = +0.34 V, E°(Zn²⁺/Zn) = −0.76 V. E°cell = ? (V)", [], "1.1|1.10", "E°cathode − E°anode.", "0.34 − (−0.76) = 1.10 V."),
     Q("MEDIUM", "A cell that uses electricity to drive a non-spontaneous reaction is ___.", ["Electrolytic", "Galvanic", "Daniell", "Fuel"], "Electrolytic", "Think electrolysis.", "It is an electrolytic cell."),
     Q("HARD", "Faraday's first law: the mass deposited is proportional to the ___.", ["Charge passed", "Voltage only", "Temperature", "Volume of solution"], "Charge passed", "m = ZQ.", "Mass ∝ quantity of electricity."),
     Q("HARD", "Coating iron with zinc to prevent rusting is called ___.", [], "galvanisation|galvanization|galvanising|galvanizing", "Galvanised buckets.", "This is galvanisation.")]},
  {"name": "Chemical Kinetics",
   "explanation": "Chemical kinetics studies the rate of reactions and the factors that affect it. The rate is the change in concentration per unit time. Rate depends on concentration, temperature, catalysts and surface area. The rate law expresses rate as k[A]ˣ[B]ʸ, where k is the rate constant and x + y is the order of the reaction, found by experiment. For a first-order reaction, the half-life t½ = 0.693/k and does not depend on the initial concentration. The Arrhenius equation k = A e^(−Ea/RT) shows that raising temperature increases the rate; roughly, a 10 °C rise doubles it. Catalysts lower the activation energy.",
   "keyPoints": ["Rate = change in concentration ÷ time.",
                 "Rate law: rate = k[A]ˣ[B]ʸ; order = x + y.",
                 "First order: t½ = 0.693/k.",
                 "Higher temperature → faster reaction.",
                 "Catalysts lower activation energy."],
   "examples": [EX("Half-life", "If k = 0.0693 min⁻¹, t½ = 0.693/0.0693 = 10 min."),
                EX("Temperature", "Food spoils faster in summer because reactions speed up.", "🌡️⬆ → ⏩"),
                EX("Catalyst", "Enzymes in our body are biological catalysts.")],
   "activity": "Drop a whole antacid tablet and a crushed one in water. Which fizzes faster and why?",
   "questions": [
     Q("EASY", "A catalyst ___ the activation energy.", ["Lowers", "Raises", "Does not change"], "Lowers", "It provides an easier path.", "Catalysts lower activation energy."),
     Q("EASY", "Increasing temperature generally makes reactions ___.", ["Faster", "Slower", "Stop"], "Faster", "Particles move faster.", "Rate increases with temperature."),
     Q("MEDIUM", "For rate = k[A]²[B], the overall order is ___.", [], "3|three", "Add the powers.", "2 + 1 = 3."),
     Q("MEDIUM", "Half-life of a first-order reaction with k = 0.693 s⁻¹ (s)?", [], "1", "t½ = 0.693/k.", "0.693/0.693 = 1 s."),
     Q("HARD", "The half-life of a first-order reaction ___ initial concentration.", ["Does not depend on", "Is proportional to", "Is inversely proportional to", "Is the square of"], "Does not depend on", "t½ = 0.693/k.", "It is independent of concentration."),
     Q("HARD", "In the Arrhenius equation k = A e^(−Ea/RT), Ea is the ___.", ["Activation energy", "Enthalpy", "Entropy", "Equilibrium constant"], "Activation energy", "Minimum energy for reaction.", "Ea is the activation energy.")]}]},
 {"name": "Biology", "icon": "🧬", "chapters": [
  {"name": "Principles of Inheritance and Variation",
   "explanation": "Mendel's laws describe how traits are inherited. The law of dominance says one allele can mask another. The law of segregation says the two alleles of a gene separate during gamete formation. The law of independent assortment says genes for different traits are inherited independently, giving a 9 : 3 : 3 : 1 ratio in a dihybrid cross. Exceptions include incomplete dominance, where the heterozygote is intermediate (pink snapdragons, 1 : 2 : 1), and co-dominance, where both alleles are expressed (AB blood group). Genes on the same chromosome are linked. Sex-linked disorders such as haemophilia and colour blindness are more common in males.",
   "keyPoints": ["Law of segregation: alleles separate into gametes.",
                 "Dihybrid F₂ ratio: 9 : 3 : 3 : 1.",
                 "Incomplete dominance gives a 1 : 2 : 1 phenotype ratio.",
                 "Co-dominance: both alleles show (AB blood group).",
                 "Haemophilia and colour blindness are X-linked."],
   "examples": [EX("Incomplete dominance", "Red (RR) × white (rr) snapdragons → pink (Rr).", "🔴 × ⚪ → 🩷"),
                EX("Co-dominance", "A person with blood group AB expresses both A and B antigens."),
                EX("Sex-linked", "A carrier mother (XᴴXʰ) can pass haemophilia to half her sons.")],
   "activity": "Find out the blood groups in your family and draw a simple pedigree chart.",
   "questions": [
     Q("EASY", "The dihybrid F₂ phenotypic ratio is ___.", ["9 : 3 : 3 : 1", "3 : 1", "1 : 2 : 1", "1 : 1"], "9 : 3 : 3 : 1", "Two traits assort independently.", "Mendel's dihybrid ratio is 9 : 3 : 3 : 1."),
     Q("EASY", "AB blood group is an example of ___.", ["Co-dominance", "Incomplete dominance", "Complete dominance", "Linkage"], "Co-dominance", "Both A and B show.", "Both alleles are expressed: co-dominance."),
     Q("MEDIUM", "Pink flowers from red × white snapdragons show ___.", ["Incomplete dominance", "Co-dominance", "Dominance", "Mutation"], "Incomplete dominance", "The heterozygote is in between.", "An intermediate phenotype means incomplete dominance."),
     Q("MEDIUM", "The F₂ phenotypic ratio in incomplete dominance is ___.", ["1 : 2 : 1", "3 : 1", "9 : 3 : 3 : 1", "2 : 1"], "1 : 2 : 1", "Red : pink : white.", "Phenotype matches genotype: 1 : 2 : 1."),
     Q("HARD", "Why is haemophilia more common in males?", ["Males have only one X chromosome", "Males have two X chromosomes", "It is on the Y chromosome only", "It is not genetic"], "Males have only one X chromosome", "One recessive allele is enough for them.", "Males (XY) express an X-linked recessive allele directly."),
     Q("HARD", "Which law states that alleles separate during gamete formation?", ["Law of segregation", "Law of dominance", "Law of independent assortment", "Law of linkage"], "Law of segregation", "'Segregate' means separate.", "It is the law of segregation.")]},
  {"name": "Molecular Basis of Inheritance",
   "explanation": "DNA is the genetic material in most organisms. It is a double helix made of two antiparallel strands of nucleotides; adenine pairs with thymine by two hydrogen bonds and guanine pairs with cytosine by three. DNA replication is semi-conservative: each new DNA molecule has one old strand and one new strand, as shown by Meselson and Stahl. The central dogma describes information flow: DNA → RNA (transcription) → protein (translation). The genetic code is read in triplets called codons; AUG is the start codon. The Human Genome Project mapped the roughly 3 billion base pairs of human DNA.",
   "keyPoints": ["DNA is a double helix.",
                 "A pairs with T; G pairs with C.",
                 "Replication is semi-conservative.",
                 "Central dogma: DNA → RNA → protein.",
                 "Codons are triplets; AUG is the start codon."],
   "examples": [EX("Base pairing", "If one strand is 5′-ATGC-3′, the other is 3′-TACG-5′.", "A=T\nG≡C"),
                EX("Transcription", "DNA's code is copied into mRNA; RNA uses uracil (U) instead of thymine."),
                EX("Chargaff's rule", "In DNA, amount of A = T and G = C.")],
   "activity": "Build a paper model of a DNA ladder using four colours for A, T, G and C.",
   "questions": [
     Q("EASY", "Adenine pairs with ___ in DNA.", ["Thymine", "Guanine", "Cytosine", "Uracil"], "Thymine", "A–T.", "Adenine pairs with thymine."),
     Q("EASY", "Making RNA from DNA is called ___.", ["Transcription", "Translation", "Replication", "Mutation"], "Transcription", "It 'transcribes' the code.", "DNA → RNA is transcription."),
     Q("MEDIUM", "Which base is found in RNA but not DNA?", ["Uracil", "Thymine", "Adenine", "Guanine"], "Uracil", "It replaces thymine.", "RNA uses uracil."),
     Q("MEDIUM", "The start codon is ___.", ["AUG", "UAA", "UAG", "UGA"], "AUG", "It codes for methionine.", "AUG starts translation."),
     Q("HARD", "Meselson and Stahl proved DNA replication is ___.", ["Semi-conservative", "Conservative", "Dispersive", "Random"], "Semi-conservative", "Each daughter has one old strand.", "Replication is semi-conservative."),
     Q("HARD", "If a DNA molecule has 30% adenine, what percentage is guanine?", [], "20|20%", "A = T = 30%, so A + T = 60%.", "G + C = 40%, so G = 20%.")]},
  {"name": "Biotechnology: Principles and Processes",
   "explanation": "Biotechnology uses living organisms or their parts to make useful products. Genetic engineering changes an organism's DNA. Restriction enzymes act as molecular scissors, cutting DNA at specific sequences and often leaving sticky ends. DNA ligase joins DNA fragments. A vector, such as a plasmid, carries the desired gene into a host cell like E. coli, creating recombinant DNA. Polymerase chain reaction (PCR) makes millions of copies of a DNA segment through cycles of denaturation, annealing and extension. Gel electrophoresis separates DNA fragments by size. Bioreactors grow large quantities of cells to produce products like insulin.",
   "keyPoints": ["Restriction enzymes cut DNA at specific sites.",
                 "DNA ligase joins DNA pieces.",
                 "Plasmids are common vectors.",
                 "PCR amplifies DNA: denaturation, annealing, extension.",
                 "Gel electrophoresis separates DNA by size."],
   "examples": [EX("EcoRI", "EcoRI cuts at GAATTC, leaving sticky ends.", "G | AATTC"),
                EX("Human insulin", "The human insulin gene is inserted into bacteria, which then make insulin.", "🧬 → 🦠 → 💉"),
                EX("PCR", "Forensic labs use PCR to copy tiny amounts of DNA from a crime scene.")],
   "activity": "Draw a flow chart of the steps used to make recombinant insulin.",
   "questions": [
     Q("EASY", "Which enzymes are called 'molecular scissors'?", ["Restriction enzymes", "DNA ligase", "Amylase", "Pepsin"], "Restriction enzymes", "They cut DNA.", "Restriction enzymes cut DNA at specific sites."),
     Q("EASY", "Which enzyme joins DNA fragments?", ["DNA ligase", "Restriction enzyme", "Helicase", "Lipase"], "DNA ligase", "'Ligare' means to tie.", "DNA ligase joins fragments."),
     Q("MEDIUM", "A small circular DNA often used as a vector is a ___.", [], "plasmid", "Found in bacteria.", "Plasmids are common vectors."),
     Q("MEDIUM", "PCR is used to ___.", ["Amplify DNA", "Cut DNA", "Digest proteins", "Make RNA only"], "Amplify DNA", "It makes many copies.", "PCR makes millions of copies of DNA."),
     Q("HARD", "In gel electrophoresis, smaller DNA fragments move ___.", ["Farther", "Less far", "Not at all", "Backwards"], "Farther", "They slip through the gel more easily.", "Smaller fragments travel farther."),
     Q("HARD", "The correct order of steps in a PCR cycle is ___.", ["Denaturation, annealing, extension", "Annealing, denaturation, extension", "Extension, annealing, denaturation", "Ligation, cutting, copying"], "Denaturation, annealing, extension", "First separate the strands.", "Separate strands, bind primers, then extend.")]}]},
 {"name": "English", "icon": "📖", "chapters": [
  {"name": "Notice Writing",
   "explanation": "A notice is a short, formal written announcement put up on a notice board or published, to inform a group of people about an event, instruction or change. It is usually placed inside a box and has a standard format: name of the institution, the word NOTICE, date, a clear heading, the body, and the name and designation of the writer. The body should answer what, when, where and who to contact, in about 50 words. Notices are written in the passive voice or third person and should be brief and clear.",
   "keyPoints": ["A notice informs a group about an event or instruction.",
                 "Format: institution, NOTICE, date, heading, body, name and designation.",
                 "Answer what, when, where and whom to contact.",
                 "Keep it brief — about 50 words.",
                 "Use formal language, often the passive voice."],
   "examples": [EX("Format", "ABC PUBLIC SCHOOL\nNOTICE\n15 July\nINTER-HOUSE QUIZ\n…\nRiya Sen, Secretary, Quiz Club", "┌──────────┐\n│  NOTICE  │\n└──────────┘"),
                EX("Passive voice", "Students are informed that the library will remain closed on Friday."),
                EX("Contact", "For details, contact the undersigned.")],
   "activity": "Write a notice inviting students to join a new photography club.",
   "questions": [
     Q("EASY", "A notice is usually written inside a ___.", ["Box", "Circle", "Table", "Poem"], "Box", "It is framed.", "Notices are written in a box."),
     Q("EASY", "The ideal word limit for a notice is about ___ words.", ["50", "200", "500", "10"], "50", "It must be short.", "Around 50 words."),
     Q("MEDIUM", "Which is NOT part of a notice?", ["Heading", "Date", "Salutation like 'Dear friend'", "Name and designation"], "Salutation like 'Dear friend'", "Notices are for groups, not letters.", "Notices do not have salutations."),
     Q("MEDIUM", "Which sentence suits a notice?", ["All students are informed that the sports meet will be held on 5 March.", "Hey guys, sports meet soon!", "I think the sports meet may happen.", "Come play with me!"], "All students are informed that the sports meet will be held on 5 March.", "Formal and clear.", "It is formal, clear and in the passive voice."),
     Q("HARD", "A notice should mainly answer ___.", ["What, when, where and whom to contact", "Why the writer is happy", "The history of the school", "A list of jokes"], "What, when, where and whom to contact", "Readers need key facts.", "These are the essential details."),
     Q("HARD", "Where does the name and designation of the writer appear?", ["At the bottom", "At the very top", "In the heading", "Nowhere"], "At the bottom", "After the body.", "It comes at the end of the notice.")]},
  {"name": "Vocabulary in Context",
   "explanation": "Understanding a word from its context means using the surrounding words and sentences to work out its meaning. Clues can be a definition, a synonym (a word with a similar meaning), an antonym (a word with the opposite meaning), an example or the general sense of the passage. Knowing prefixes and suffixes also helps: 'un-', 'dis-' and 'in-' often mean 'not', while '-ful' means 'full of' and '-less' means 'without'. A good vocabulary makes reading easier and writing more precise.",
   "keyPoints": ["Use nearby words to guess a word's meaning.",
                 "Synonym: similar meaning. Antonym: opposite meaning.",
                 "un-, dis-, in- often mean 'not'.",
                 "-ful = full of; -less = without.",
                 "Examples in a sentence are strong clues."],
   "examples": [EX("Synonym clue", "The garden was verdant, green and full of life. (verdant = green)"),
                EX("Antonym clue", "Unlike his gregarious sister, Arjun was shy. (gregarious = sociable)"),
                EX("Prefix", "'Dishonest' = not honest; 'fearless' = without fear.")],
   "activity": "Pick five new words from a newspaper article and guess their meanings from context before checking a dictionary.",
   "questions": [
     Q("EASY", "A word with a similar meaning is a ___.", ["Synonym", "Antonym", "Homophone", "Prefix"], "Synonym", "'Syn' means same.", "It is a synonym."),
     Q("EASY", "The antonym of 'ancient' is ___.", ["Old", "Modern", "Historic", "Aged"], "Modern", "Opposite meaning.", "Ancient ↔ modern."),
     Q("MEDIUM", "'Fearless' means ___.", ["Without fear", "Full of fear", "Causing fear", "Fear again"], "Without fear", "'-less' means without.", "Fearless = without fear."),
     Q("MEDIUM", "'The medicine alleviated his pain; he felt much better.' 'Alleviated' means ___.", ["Reduced", "Increased", "Caused", "Ignored"], "Reduced", "He felt better afterwards.", "Alleviate means to lessen."),
     Q("HARD", "'Unlike her loquacious brother, Mira spoke very little.' 'Loquacious' means ___.", ["Talkative", "Quiet", "Angry", "Clever"], "Talkative", "The contrast is with speaking little.", "Loquacious means talkative."),
     Q("HARD", "'The scarcity of water forced people to ration it.' 'Scarcity' means ___.", ["Shortage", "Abundance", "Cleanliness", "Coldness"], "Shortage", "They had to ration it.", "Scarcity means shortage.")]},
  {"name": "Common Errors in English",
   "explanation": "Some mistakes appear often in writing. Confusing homophones is common: 'their' (belonging to them), 'there' (a place) and 'they're' (they are); 'its' (belonging to it) and 'it's' (it is). Other errors include wrong subject–verb agreement, using 'less' instead of 'fewer' with countable nouns, double negatives such as 'I don't know nothing', and incorrect prepositions, such as 'discuss about' instead of 'discuss'. Careful proofreading helps catch these errors.",
   "keyPoints": ["their = belonging to them; there = place; they're = they are.",
                 "its = belonging to it; it's = it is.",
                 "fewer with countable nouns; less with uncountable.",
                 "Avoid double negatives.",
                 "Say 'discuss the plan', not 'discuss about the plan'."],
   "examples": [EX("Homophones", "They're putting their bags over there."),
                EX("Its vs it's", "It's raining, and the dog is wagging its tail."),
                EX("Fewer vs less", "Fewer students, less noise.")],
   "activity": "Proofread a paragraph you wrote earlier and correct any of these common errors.",
   "questions": [
     Q("EASY", "___ going to the park after school.", ["Their", "There", "They're"], "They're", "It means 'they are'.", "They're = they are."),
     Q("EASY", "The cat licked ___ paw.", ["its", "it's"], "its", "Belonging to it.", "'Its' shows possession."),
     Q("MEDIUM", "There were ___ people at the event than last year.", ["less", "fewer"], "fewer", "People are countable.", "Use 'fewer' with countable nouns."),
     Q("MEDIUM", "Which sentence is correct?", ["I don't know nothing.", "I don't know anything.", "I not know anything.", "I doesn't know nothing."], "I don't know anything.", "Avoid double negatives.", "'I don't know anything' is correct."),
     Q("HARD", "Which sentence is correct?", ["We discussed about the plan.", "We discussed the plan.", "We discussed on the plan.", "We discussion the plan."], "We discussed the plan.", "'Discuss' takes a direct object.", "'Discuss' needs no preposition."),
     Q("HARD", "Choose the correct sentence.", ["Each of the students have a book.", "Each of the students has a book.", "Each of the student has books.", "Each students have a book."], "Each of the students has a book.", "'Each' is singular.", "'Each' takes a singular verb: has.")]}]},
 {"name": "Computer Science", "icon": "💻", "chapters": [
  {"name": "Functions in Python",
   "explanation": "A function is a named block of code that performs a task and can be reused. In Python, it is defined with def, followed by the function name and parameters in brackets. Values passed when calling the function are arguments. The return statement sends a value back to the caller; without it, the function returns None. Parameters can have default values, and arguments can be passed by keyword. Variables created inside a function are local and cannot be used outside it, while variables defined outside are global. Functions make programs shorter, clearer and easier to test.",
   "keyPoints": ["Define functions with def.",
                 "Parameters receive arguments.",
                 "return sends a value back; otherwise None.",
                 "Default parameters: def greet(name='friend').",
                 "Local variables exist only inside the function."],
   "examples": [EX("Define and call", "def square(n):\n    return n * n\n\nprint(square(4))   # 16"),
                EX("Default parameter", "def greet(name='friend'):\n    print('Hello', name)\n\ngreet()        # Hello friend"),
                EX("Scope", "def f():\n    x = 5   # local\nf()\nprint(x)   # NameError")],
   "activity": "Write a function is_prime(n) that returns True if n is prime, and test it for numbers 1 to 20.",
   "questions": [
     Q("EASY", "Which keyword defines a function in Python?", ["def", "func", "function", "define"], "def", "Short for define.", "Functions start with def."),
     Q("EASY", "Which statement sends a value back from a function?", ["return", "print", "break", "pass"], "return", "It 'returns' the value.", "return sends a value to the caller."),
     Q("MEDIUM", "What does a function return if it has no return statement?", ["None", "0", "False", "An error"], "None", "Python's 'nothing' value.", "It returns None."),
     Q("MEDIUM", "Output: def add(a, b=2): return a + b; print(add(3))", [], "5", "b takes its default value.", "3 + 2 = 5."),
     Q("HARD", "A variable created inside a function is ___.", ["Local", "Global", "Constant", "Built-in"], "Local", "It exists only inside the function.", "It is local to that function."),
     Q("HARD", "Output: def f(x): return x * 2; print(f(f(3)))", [], "12", "Work from the inside out.", "f(3) = 6, f(6) = 12.")]},
  {"name": "File Handling",
   "explanation": "File handling lets programs store data permanently. In Python, open(filename, mode) opens a file. Common modes are 'r' (read), 'w' (write, which overwrites or creates the file), 'a' (append to the end) and 'rb'/'wb' for binary files. read() reads the whole file, readline() reads one line and readlines() returns a list of lines. write() writes a string. Files should be closed after use; the 'with' statement closes them automatically. Text files store readable characters, binary files store data in bytes (for example with the pickle module), and CSV files store table data separated by commas.",
   "keyPoints": ["open(filename, mode) opens a file.",
                 "'r' read, 'w' write (overwrites), 'a' append.",
                 "read(), readline(), readlines() read data.",
                 "'with open(...) as f:' closes the file automatically.",
                 "CSV files store comma-separated table data."],
   "examples": [EX("Write", "with open('notes.txt', 'w') as f:\n    f.write('Hello\\n')"),
                EX("Read lines", "with open('notes.txt') as f:\n    for line in f:\n        print(line.strip())"),
                EX("Append", "with open('log.txt', 'a') as f:\n    f.write('New entry\\n')")],
   "activity": "Write a program that saves five friends' names to a file and then reads and prints them in alphabetical order.",
   "questions": [
     Q("EASY", "Which mode opens a file for reading?", ["'r'", "'w'", "'a'", "'x'"], "'r'", "r for read.", "'r' opens for reading."),
     Q("EASY", "Which mode adds data to the end of a file?", ["'a'", "'w'", "'r'", "'rb'"], "'a'", "a for append.", "'a' appends."),
     Q("MEDIUM", "What happens when an existing file is opened in 'w' mode?", ["Its contents are erased", "Data is added to the end", "It becomes read-only", "An error occurs"], "Its contents are erased", "Write mode starts fresh.", "'w' overwrites the file."),
     Q("MEDIUM", "Which method returns all lines of a file as a list?", ["readlines()", "read()", "readline()", "write()"], "readlines()", "Plural 'lines'.", "readlines() returns a list of lines."),
     Q("HARD", "Why is 'with open(...) as f:' preferred?", ["It closes the file automatically", "It makes files faster", "It encrypts files", "It deletes the file after use"], "It closes the file automatically", "Even if an error occurs.", "The with statement closes the file automatically."),
     Q("HARD", "Which module is used to store Python objects in binary files?", ["pickle", "math", "random", "os.path"], "pickle", "It 'preserves' objects.", "pickle serialises objects to binary files.")]},
  {"name": "Database Concepts and SQL",
   "explanation": "A database is an organised collection of data. In a relational database, data is stored in tables (relations) made of rows (tuples or records) and columns (attributes or fields). A primary key uniquely identifies each row, and a foreign key links one table to another. SQL (Structured Query Language) is used to manage relational databases. DDL commands like CREATE TABLE define structure; DML commands like INSERT, UPDATE and DELETE change data; and SELECT retrieves data. WHERE filters rows, ORDER BY sorts them, and aggregate functions like COUNT, SUM and AVG summarise data, often with GROUP BY.",
   "keyPoints": ["Tables have rows (records) and columns (fields).",
                 "A primary key uniquely identifies each row.",
                 "A foreign key links tables.",
                 "SELECT retrieves data; WHERE filters it.",
                 "COUNT, SUM and AVG are aggregate functions."],
   "examples": [EX("Select", "SELECT name, marks FROM student WHERE marks > 80 ORDER BY marks DESC;"),
                EX("Insert", "INSERT INTO student (id, name, marks) VALUES (1, 'Asha', 92);"),
                EX("Aggregate", "SELECT class, AVG(marks) FROM student GROUP BY class;", "class | avg\n  11  | 78.5")],
   "activity": "Design a table to store your class timetable. Choose a primary key and write the CREATE TABLE command.",
   "questions": [
     Q("EASY", "Which SQL command retrieves data?", ["SELECT", "INSERT", "DELETE", "CREATE"], "SELECT", "You 'select' what you want to see.", "SELECT reads data."),
     Q("EASY", "A column that uniquely identifies each row is the ___ key.", [], "primary", "Every table should have one.", "It is the primary key."),
     Q("MEDIUM", "Which clause filters rows in SQL?", ["WHERE", "ORDER BY", "GROUP BY", "FROM"], "WHERE", "It sets a condition.", "WHERE filters rows."),
     Q("MEDIUM", "Which command adds a new row to a table?", ["INSERT", "UPDATE", "ALTER", "SELECT"], "INSERT", "INSERT INTO ...", "INSERT adds rows."),
     Q("HARD", "A key in one table that refers to the primary key of another table is a ___ key.", ["Foreign", "Candidate", "Alternate", "Super"], "Foreign", "It comes from another table.", "It is a foreign key."),
     Q("HARD", "Which query counts all rows in table 'student'?", ["SELECT COUNT(*) FROM student;", "SELECT SUM(*) FROM student;", "COUNT student;", "SELECT * COUNT student;"], "SELECT COUNT(*) FROM student;", "COUNT is an aggregate function.", "COUNT(*) counts all rows.")]}]},
 {"name": "Economics", "icon": "📈", "chapters": [
  {"name": "Introduction to Macroeconomics",
   "explanation": "Macroeconomics studies the economy as a whole, including total output, employment, inflation and the general price level. It became important after the Great Depression of 1929, when unemployment rose sharply; John Maynard Keynes's ideas shaped modern macroeconomics. An economy has four sectors: households, firms, government and the external sector (rest of the world). In the circular flow of income, households supply factors of production to firms and receive factor income (rent, wages, interest and profit), and spend it on goods and services produced by firms. Goods can be final goods, used for consumption or investment, or intermediate goods, used up in producing other goods.",
   "keyPoints": ["Macroeconomics studies the whole economy.",
                 "The Great Depression (1929) led to its growth; Keynes was key.",
                 "Sectors: households, firms, government, external.",
                 "Factor incomes: rent, wages, interest, profit.",
                 "Final goods vs intermediate goods."],
   "examples": [EX("Circular flow", "Households → labour → firms → wages → households → spending → firms.", "🏠 ⇄ 🏭"),
                EX("Final vs intermediate", "Bread bought by a family is final; flour bought by a baker is intermediate."),
                EX("Capital goods", "A machine used in a factory for years is a final (capital) good.")],
   "activity": "Draw the circular flow of income for your household: where money comes from and where it goes.",
   "questions": [
     Q("EASY", "Macroeconomics studies ___.", ["The economy as a whole", "One consumer", "One firm", "One product's price"], "The economy as a whole", "'Macro' means big.", "It studies aggregates like national income."),
     Q("EASY", "Wages are the reward for which factor?", ["Labour", "Land", "Capital", "Entrepreneurship"], "Labour", "Workers earn them.", "Labour earns wages."),
     Q("MEDIUM", "Flour bought by a baker to make bread is a(n) ___ good.", ["Intermediate", "Final", "Capital", "Public"], "Intermediate", "It is used up in production.", "It is an intermediate good."),
     Q("MEDIUM", "Which economist is associated with modern macroeconomics?", ["John Maynard Keynes", "Adam Smith", "Karl Marx", "Alfred Marshall"], "John Maynard Keynes", "His General Theory was published in 1936.", "Keynes founded modern macroeconomics."),
     Q("HARD", "Which event led to the development of macroeconomics as a separate branch?", ["The Great Depression of 1929", "The Industrial Revolution", "The French Revolution", "World War II"], "The Great Depression of 1929", "Mass unemployment in the 1930s.", "The Great Depression highlighted economy-wide problems."),
     Q("HARD", "The reward for entrepreneurship is ___.", ["Profit", "Rent", "Wages", "Interest"], "Profit", "It rewards risk-taking.", "Entrepreneurs earn profit.")]},
  {"name": "National Income Accounting",
   "explanation": "National income measures the total value of final goods and services produced in a country during a year. GDP (Gross Domestic Product) is the market value of all final goods and services produced within a country's borders. GNP adds net factor income from abroad to GDP. Net values subtract depreciation (the wearing out of capital). Only final goods are counted to avoid double counting. National income can be measured by three methods: the value added (product) method, the income method and the expenditure method, and all three should give the same result. Real GDP is measured at constant prices, removing the effect of inflation.",
   "keyPoints": ["GDP = value of final goods and services produced within a country.",
                 "GNP = GDP + net factor income from abroad.",
                 "Net = Gross − depreciation.",
                 "Count only final goods to avoid double counting.",
                 "Three methods: value added, income, expenditure."],
   "examples": [EX("Double counting", "Wheat ₹100 → flour ₹150 → bread ₹200. Only ₹200 (the final value) is counted.", "🌾 → 🥣 → 🍞"),
                EX("GNP", "GDP ₹1000 cr + net factor income from abroad ₹50 cr = GNP ₹1050 cr."),
                EX("Real vs nominal", "If prices double but output stays the same, nominal GDP doubles while real GDP is unchanged.")],
   "activity": "Trace a product you use (like a T-shirt) from raw material to final sale and list the value added at each stage.",
   "questions": [
     Q("EASY", "GDP measures output produced ___.", ["Within a country's borders", "By citizens abroad only", "By the government only", "In one household"], "Within a country's borders", "'Domestic'.", "GDP is domestic production."),
     Q("EASY", "Wearing out of capital goods is called ___.", [], "depreciation", "Net = Gross − this.", "It is depreciation."),
     Q("MEDIUM", "GNP = GDP + ___.", ["Net factor income from abroad", "Depreciation", "Indirect taxes", "Subsidies"], "Net factor income from abroad", "National includes citizens' income from abroad.", "GNP = GDP + NFIA."),
     Q("MEDIUM", "Why are only final goods counted in national income?", ["To avoid double counting", "Because they are cheaper", "Because they are imported", "To include depreciation"], "To avoid double counting", "Intermediate goods are already in the final price.", "It avoids counting the same value twice."),
     Q("HARD", "GDP at market price is ₹500 cr and depreciation is ₹50 cr. NDP at market price = ? (₹ cr)", [], "450", "Net = Gross − depreciation.", "500 − 50 = 450."),
     Q("HARD", "GDP measured at constant (base-year) prices is ___ GDP.", ["Real", "Nominal", "Gross", "Net"], "Real", "It removes the effect of inflation.", "Constant-price GDP is real GDP.")]},
  {"name": "Money and Banking",
   "explanation": "Money is anything widely accepted as a medium of exchange; it also serves as a measure of value, a store of value and a standard of deferred payment. Commercial banks accept deposits and give loans, and through this process they create credit. The money multiplier equals 1 divided by the legal reserve ratio (LRR). The Reserve Bank of India (RBI) is India's central bank. It issues currency, acts as banker to the government and to other banks, and is the lender of last resort. The RBI controls the money supply with tools such as the repo rate, reverse repo rate, cash reserve ratio (CRR), statutory liquidity ratio (SLR) and open market operations.",
   "keyPoints": ["Money: medium of exchange, measure of value, store of value.",
                 "Banks create credit through deposits and loans.",
                 "Money multiplier = 1 / LRR.",
                 "The RBI is India's central bank.",
                 "Tools: repo rate, CRR, SLR, open market operations."],
   "examples": [EX("Money multiplier", "If LRR = 20%, the multiplier = 1/0.2 = 5, so ₹1000 of new deposits can create ₹5000 of total deposits."),
                EX("Repo rate", "When the RBI raises the repo rate, loans become costlier and spending slows.", "🏦 % ⬆ → 💸 ⬇"),
                EX("Lender of last resort", "The RBI can lend to a bank facing a sudden cash shortage.")],
   "activity": "Find the current repo rate on the RBI website and discuss how it affects home loans.",
   "questions": [
     Q("EASY", "India's central bank is the ___.", ["Reserve Bank of India", "State Bank of India", "World Bank", "NABARD"], "Reserve Bank of India", "It issues currency notes.", "The RBI is the central bank."),
     Q("EASY", "The main function of money is to act as a medium of ___.", ["Exchange", "Transport", "Production", "Taxation"], "Exchange", "It removes barter.", "Money is a medium of exchange."),
     Q("MEDIUM", "If the legal reserve ratio is 10%, the money multiplier is ___.", [], "10", "Multiplier = 1/LRR.", "1/0.1 = 10."),
     Q("MEDIUM", "The rate at which the RBI lends to commercial banks is the ___ rate.", ["Repo", "Reverse repo", "Savings", "Tax"], "Repo", "Banks 'repurchase' securities.", "It is the repo rate."),
     Q("HARD", "To reduce inflation, the RBI is likely to ___ the repo rate.", ["Increase", "Decrease", "Remove", "Ignore"], "Increase", "Costlier loans reduce spending.", "Raising the repo rate reduces money supply."),
     Q("HARD", "Initial deposit ₹2000 and LRR 25%. Total deposits created = ? (₹)", [], "8000|8,000", "Multiplier = 1/0.25 = 4.", "2000 × 4 = 8000.")]}]}]}
