# Seed content source for Grade 11 (senior secondary: adds Computer Science and Economics).
from grade6 import Q, EX

GRADE11 = {"grade": 11, "subjects": [
 {"name": "Mathematics", "icon": "🔢", "chapters": [
  {"name": "Sets",
   "explanation": "A set is a well-defined collection of distinct objects, called elements. Sets can be written in roster form, like {1, 2, 3}, or set-builder form, like {x : x is a natural number less than 4}. The empty set ∅ has no elements. A is a subset of B if every element of A is in B. The union A ∪ B contains elements in A or B, the intersection A ∩ B contains elements in both, and the difference A − B contains elements in A but not in B. A set with n elements has 2ⁿ subsets, and n(A ∪ B) = n(A) + n(B) − n(A ∩ B).",
   "keyPoints": ["A set is a well-defined collection of distinct objects.",
                 "Roster form lists elements; set-builder form states a rule.",
                 "A ∪ B: in A or B. A ∩ B: in both.",
                 "A set with n elements has 2ⁿ subsets.",
                 "n(A ∪ B) = n(A) + n(B) − n(A ∩ B)."],
   "examples": [EX("Union and intersection", "A = {1, 2, 3}, B = {2, 3, 4}: A ∪ B = {1, 2, 3, 4}, A ∩ B = {2, 3}.", "(1 (2 3) 4)"),
                EX("Subsets", "{a, b} has 2² = 4 subsets: ∅, {a}, {b}, {a, b}."),
                EX("Counting", "In a class, 20 like tea, 15 like coffee, 5 like both: 20 + 15 − 5 = 30 like at least one.")],
   "activity": "Survey 10 friends about two sports and draw a Venn diagram of the results.",
   "questions": [
     Q("EASY", "If A = {1, 2, 3} and B = {3, 4}, A ∩ B = ?", ["{3}", "{1, 2, 3, 4}", "{1, 2}", "∅"], "{3}", "Common elements only.", "Only 3 is in both."),
     Q("EASY", "A set with no elements is called the ___ set.", [], "empty|null|empty set|null set", "Its symbol is ∅.", "It is the empty (null) set."),
     Q("MEDIUM", "How many subsets does a set with 3 elements have?", [], "8", "Use 2ⁿ.", "2³ = 8."),
     Q("MEDIUM", "A = {1, 2, 3, 4}, B = {2, 4}. A − B = ?", ["{1, 3}", "{2, 4}", "{1, 2, 3, 4}", "∅"], "{1, 3}", "Remove B's elements from A.", "A − B = {1, 3}."),
     Q("HARD", "n(A) = 25, n(B) = 18, n(A ∩ B) = 7. n(A ∪ B) = ?", [], "36", "n(A) + n(B) − n(A ∩ B).", "25 + 18 − 7 = 36."),
     Q("HARD", "Which is NOT a well-defined set?", ["Vowels in English", "Prime numbers below 10", "Good students in a class", "Months with 31 days"], "Good students in a class", "'Good' depends on opinion.", "'Good' is not well-defined."),
   ]},
  {"name": "Trigonometric Functions",
   "explanation": "Angles can be measured in degrees or radians, where π radians = 180°. For an angle θ, sin θ, cos θ and tan θ are defined using the unit circle, where tan θ = sin θ / cos θ. The basic identity is sin²θ + cos²θ = 1. The signs of the functions depend on the quadrant: all are positive in the first quadrant, only sine in the second, only tangent in the third, and only cosine in the fourth (All–Sin–Tan–Cos). Sine and cosine have period 2π. Compound angle formulas include sin(A + B) = sin A cos B + cos A sin B.",
   "keyPoints": ["π radians = 180°.",
                 "tan θ = sin θ / cos θ.",
                 "sin²θ + cos²θ = 1.",
                 "Quadrant signs: All, Sin, Tan, Cos.",
                 "sin and cos have period 2π."],
   "examples": [EX("Conversion", "60° = 60 × π/180 = π/3 radians."),
                EX("Standard values", "sin 30° = 1/2, cos 60° = 1/2, tan 45° = 1."),
                EX("Quadrant sign", "cos 120° is negative because 120° is in the second quadrant.", " S | A\n———+———\n T | C")],
   "activity": "Draw a unit circle and mark the coordinates for 0°, 30°, 45°, 60° and 90°.",
   "questions": [
     Q("EASY", "π radians equals ___ degrees.", [], "180|180°", "Half a full turn.", "π rad = 180°."),
     Q("EASY", "sin 30° = ?", ["1/2", "√3/2", "1", "0"], "1/2", "A standard value.", "sin 30° = 1/2."),
     Q("MEDIUM", "sin²θ + cos²θ = ?", [], "1", "The basic Pythagorean identity.", "It always equals 1."),
     Q("MEDIUM", "Convert 90° to radians.", ["π/2", "π", "π/4", "2π"], "π/2", "Multiply by π/180.", "90 × π/180 = π/2."),
     Q("HARD", "In which quadrant are both sin and cos negative?", ["First", "Second", "Third", "Fourth"], "Third", "Only tan is positive there.", "In the third quadrant, sin and cos are negative."),
     Q("HARD", "sin(A + B) = ?", ["sin A cos B + cos A sin B", "sin A + sin B", "cos A cos B − sin A sin B", "sin A sin B + cos A cos B"], "sin A cos B + cos A sin B", "It mixes sin and cos.", "This is the compound angle formula.")]},
  {"name": "Permutations and Combinations",
   "explanation": "The fundamental principle of counting says that if one event can happen in m ways and another in n ways, both can happen in m × n ways. n! (n factorial) is the product 1 × 2 × … × n, and 0! = 1. A permutation is an arrangement where order matters: ⁿPᵣ = n! / (n − r)!. A combination is a selection where order does not matter: ⁿCᵣ = n! / [r!(n − r)!]. Choosing a team is a combination, while arranging people in a line is a permutation. Note that ⁿCᵣ = ⁿCₙ₋ᵣ.",
   "keyPoints": ["Counting principle: m ways × n ways.",
                 "n! = 1 × 2 × … × n; 0! = 1.",
                 "Permutation (order matters): ⁿPᵣ = n!/(n − r)!.",
                 "Combination (order doesn't matter): ⁿCᵣ = n!/[r!(n − r)!].",
                 "ⁿCᵣ = ⁿCₙ₋ᵣ."],
   "examples": [EX("Counting principle", "3 shirts and 4 trousers give 3 × 4 = 12 outfits.", "👕×3 · 👖×4 = 12"),
                EX("Permutation", "Arranging 3 books out of 5 on a shelf: ⁵P₃ = 60."),
                EX("Combination", "Choosing 2 students out of 5: ⁵C₂ = 10.")],
   "activity": "Find how many different 3-letter 'words' can be made from the letters of your first name without repeating letters.",
   "questions": [
     Q("EASY", "What is 4!?", [], "24", "1 × 2 × 3 × 4.", "4! = 24."),
     Q("EASY", "What is 0!?", [], "1", "It is defined by convention.", "0! = 1."),
     Q("MEDIUM", "⁵P₂ = ?", [], "20", "5!/3!.", "5 × 4 = 20."),
     Q("MEDIUM", "⁶C₂ = ?", [], "15", "6!/(2! × 4!).", "(6 × 5)/2 = 15."),
     Q("HARD", "In how many ways can the letters of 'CAT' be arranged?", [], "6", "3 distinct letters: 3!.", "3! = 6."),
     Q("HARD", "A committee of 3 is chosen from 7 people. How many ways?", [], "35", "Order does not matter: ⁷C₃.", "(7 × 6 × 5)/(3 × 2 × 1) = 35.")]}]},
 {"name": "Physics", "icon": "⚛️", "chapters": [
  {"name": "Units and Measurements",
   "explanation": "A physical quantity is expressed as a number times a unit. The International System of Units (SI) has seven base units: metre (length), kilogram (mass), second (time), ampere (current), kelvin (temperature), mole (amount of substance) and candela (luminous intensity). Other units are derived from these, like the newton (kg m s⁻²). Dimensional analysis expresses quantities in terms of base dimensions such as [M], [L] and [T]; it helps check equations and convert units. Significant figures show the precision of a measurement, and every measurement has some error.",
   "keyPoints": ["SI has seven base units.",
                 "Derived units come from base units.",
                 "Newton = kg m s⁻².",
                 "Dimensions help check equations.",
                 "Significant figures show precision."],
   "examples": [EX("Dimensions of force", "F = ma → [M][L T⁻²] = [M L T⁻²]."),
                EX("Checking an equation", "v = u + at: [L T⁻¹] = [L T⁻¹] + [L T⁻²][T] ✓"),
                EX("Significant figures", "0.00450 has 3 significant figures (4, 5, 0).")],
   "activity": "Measure the thickness of one page of a book by measuring 100 pages and dividing.",
   "questions": [
     Q("EASY", "The SI unit of mass is the ___.", ["Gram", "Kilogram", "Pound", "Tonne"], "Kilogram", "Symbol kg.", "The SI unit of mass is the kilogram."),
     Q("EASY", "How many SI base units are there?", [], "7|seven", "Metre, kilogram, second …", "There are seven base units."),
     Q("MEDIUM", "The dimensional formula of velocity is ___.", ["[L T⁻¹]", "[M L T⁻²]", "[L T⁻²]", "[M L²]"], "[L T⁻¹]", "Velocity = length/time.", "[L]/[T] = [L T⁻¹]."),
     Q("MEDIUM", "How many significant figures are in 2.050?", [], "4", "Trailing zeros after a decimal point count.", "2, 0, 5, 0 → 4 significant figures."),
     Q("HARD", "The dimensional formula of force is ___.", ["[M L T⁻²]", "[M L² T⁻²]", "[M L T⁻¹]", "[L T⁻²]"], "[M L T⁻²]", "F = ma.", "[M][L T⁻²] = [M L T⁻²]."),
     Q("HARD", "Which is the SI unit of temperature?", ["Celsius", "Fahrenheit", "Kelvin", "Joule"], "Kelvin", "It starts from absolute zero.", "The kelvin is the SI unit.")]},
  {"name": "Motion in a Straight Line",
   "explanation": "Motion along a straight line is described by position, displacement, velocity and acceleration. Average velocity is total displacement divided by total time, while instantaneous velocity is the velocity at a particular moment, given by v = dx/dt. Acceleration is the rate of change of velocity, a = dv/dt. For uniformly accelerated motion: v = u + at, s = ut + ½at², and v² = u² + 2as. On a position–time graph the slope is velocity, and on a velocity–time graph the slope is acceleration and the area under the curve is displacement. Freely falling bodies have acceleration g ≈ 9.8 m/s² downward.",
   "keyPoints": ["Average velocity = total displacement ÷ total time.",
                 "v = dx/dt; a = dv/dt.",
                 "v = u + at, s = ut + ½at², v² = u² + 2as.",
                 "Slope of v–t graph = acceleration; area = displacement.",
                 "Free fall acceleration g ≈ 9.8 m/s²."],
   "examples": [EX("Free fall", "A stone dropped from rest falls 4.9 m in the first second: s = ½ × 9.8 × 1²."),
                EX("Braking", "A car at 20 m/s stops in 4 s: a = −5 m/s²."),
                EX("v–t graph", "A horizontal line on a v–t graph means constant velocity (zero acceleration).", "v |———— \n  |_____ t")],
   "activity": "Drop a ball from a known height and time its fall. Use s = ½gt² to estimate g.",
   "questions": [
     Q("EASY", "The slope of a position–time graph gives ___.", ["Velocity", "Acceleration", "Displacement", "Force"], "Velocity", "Change in position over time.", "Slope of x–t is velocity."),
     Q("EASY", "The area under a velocity–time graph gives ___.", ["Displacement", "Acceleration", "Force", "Mass"], "Displacement", "velocity × time.", "Area under v–t is displacement."),
     Q("MEDIUM", "A car accelerates from 0 to 30 m/s in 6 s. a = ? (m/s²)", [], "5", "a = (v − u)/t.", "30/6 = 5 m/s²."),
     Q("MEDIUM", "A body moves with u = 10 m/s and a = 2 m/s². Velocity after 5 s (m/s)?", [], "20", "v = u + at.", "10 + 2 × 5 = 20 m/s."),
     Q("HARD", "A ball is thrown up at 20 m/s (g = 10 m/s²). Maximum height (m)?", [], "20", "At the top v = 0: v² = u² − 2gh.", "0 = 400 − 20h, so h = 20 m."),
     Q("HARD", "If x = 3t² + 2t (metres), the velocity at t = 1 s is ___ m/s.", [], "8", "v = dx/dt = 6t + 2.", "6(1) + 2 = 8 m/s.")]},
  {"name": "Laws of Motion",
   "explanation": "Newton's first law defines inertia: a body continues in its state of rest or uniform motion unless acted on by a net external force. The second law states that the net force equals the rate of change of momentum, F = dp/dt = ma for constant mass. Impulse is force × time and equals the change in momentum. Newton's third law says forces always occur in equal and opposite pairs acting on different bodies. The law of conservation of momentum states that the total momentum of an isolated system stays constant. Friction opposes relative motion; static friction is usually greater than kinetic friction. For circular motion, a centripetal force mv²/r is needed.",
   "keyPoints": ["First law: inertia.",
                 "Second law: F = dp/dt = ma.",
                 "Impulse = F × t = change in momentum.",
                 "Momentum is conserved in an isolated system.",
                 "Centripetal force = mv²/r."],
   "examples": [EX("Catching a ball", "Pulling hands back increases the time, reducing the force for the same impulse.", "🏏✋⬅"),
                EX("Recoil", "A 4 kg gun fires a 0.02 kg bullet at 400 m/s; recoil speed = 0.02 × 400 / 4 = 2 m/s."),
                EX("Circular motion", "A car turning on a road needs friction to supply the centripetal force.")],
   "activity": "Blow up a balloon, tape it to a straw on a string, and release it. Explain the motion using Newton's third law.",
   "questions": [
     Q("EASY", "F = ma is Newton's ___ law.", ["First", "Second", "Third"], "Second", "It links force and acceleration.", "It is the second law."),
     Q("EASY", "Impulse equals change in ___.", ["Momentum", "Mass", "Energy", "Velocity only"], "Momentum", "Impulse = F × t.", "Impulse = Δp."),
     Q("MEDIUM", "A 2 kg body has acceleration 3 m/s². Net force (N)?", [], "6", "F = ma.", "2 × 3 = 6 N."),
     Q("MEDIUM", "A 5 kg gun fires a 0.01 kg bullet at 500 m/s. Recoil speed (m/s)?", [], "1", "Momentum is conserved: mv = MV.", "0.01 × 500 / 5 = 1 m/s."),
     Q("HARD", "Centripetal force on a 2 kg mass moving at 4 m/s in a circle of radius 2 m (N)?", [], "16", "F = mv²/r.", "2 × 16 / 2 = 16 N."),
     Q("HARD", "Why do cricket players pull their hands back while catching?", ["To increase time and reduce force", "To increase force", "To reduce momentum to zero instantly", "To add impulse"], "To increase time and reduce force", "Impulse = F × t is fixed.", "Longer time means smaller force.")]}]},
 {"name": "Chemistry", "icon": "🧪", "chapters": [
  {"name": "Some Basic Concepts of Chemistry",
   "explanation": "Chemistry studies matter and its changes. The mole is the SI unit for amount of substance; one mole contains 6.022 × 10²³ particles. Molar mass is the mass of one mole in grams. Stoichiometry uses balanced equations to calculate amounts of reactants and products. The limiting reagent is the reactant that runs out first and decides how much product forms. Concentration of solutions can be expressed as molarity (moles of solute per litre of solution) or molality (moles of solute per kg of solvent). The empirical formula gives the simplest ratio of atoms, and the molecular formula gives the actual number.",
   "keyPoints": ["1 mole = 6.022 × 10²³ particles.",
                 "Moles = mass ÷ molar mass.",
                 "The limiting reagent is used up first.",
                 "Molarity = moles of solute ÷ litres of solution.",
                 "Empirical formula = simplest whole-number ratio."],
   "examples": [EX("Moles", "44 g of CO₂ (molar mass 44 g/mol) is 1 mole."),
                EX("Molarity", "0.5 mol NaCl in 250 mL of solution: M = 0.5/0.25 = 2 M."),
                EX("Empirical formula", "Glucose C₆H₁₂O₆ has empirical formula CH₂O.")],
   "activity": "Calculate how many moles of water you drink in a day if you drink 2 litres (2000 g).",
   "questions": [
     Q("EASY", "Number of particles in one mole?", ["6.022 × 10²³", "3 × 10⁸", "1.6 × 10⁻¹⁹", "9.8"], "6.022 × 10²³", "Avogadro's number.", "N_A = 6.022 × 10²³."),
     Q("EASY", "Moles in 32 g of O₂ (molar mass 32 g/mol)?", [], "1", "moles = mass/molar mass.", "32/32 = 1 mol."),
     Q("MEDIUM", "Molarity of 2 mol solute in 4 L of solution?", [], "0.5|0.5 m", "M = mol/L.", "2/4 = 0.5 M."),
     Q("MEDIUM", "The reactant that is completely used up first is the ___ reagent.", [], "limiting", "It limits the product.", "It is the limiting reagent."),
     Q("HARD", "Empirical formula of C₂H₄?", ["CH₂", "C₂H₄", "CH", "C₂H₂"], "CH₂", "Divide by the common factor.", "C₂H₄ ÷ 2 = CH₂."),
     Q("HARD", "Mass of 0.5 mol of NaOH (molar mass 40 g/mol) in grams?", [], "20|20 g", "mass = moles × molar mass.", "0.5 × 40 = 20 g.")]},
  {"name": "Structure of Atom",
   "explanation": "Thomson proposed the plum pudding model, and Rutherford's gold foil experiment showed that an atom has a tiny, dense, positive nucleus. Bohr's model said electrons move in fixed energy levels and emit or absorb energy when they jump between them. The modern quantum mechanical model describes electrons by orbitals and four quantum numbers: principal (n), azimuthal (l), magnetic (m) and spin (s). Electrons fill orbitals by the Aufbau principle (lowest energy first), Pauli's exclusion principle (at most two electrons with opposite spins per orbital) and Hund's rule (orbitals of the same energy are filled singly first).",
   "keyPoints": ["Rutherford discovered the nucleus.",
                 "Bohr: electrons in fixed energy levels.",
                 "Four quantum numbers: n, l, m, s.",
                 "Pauli: max two electrons per orbital, opposite spins.",
                 "Aufbau order: 1s 2s 2p 3s 3p 4s 3d …"],
   "examples": [EX("Configuration", "Oxygen (Z = 8): 1s² 2s² 2p⁴."),
                EX("Hund's rule", "Nitrogen's 2p³ electrons occupy three separate orbitals: ↑ ↑ ↑.", "2p: [↑][↑][↑]"),
                EX("Orbitals", "For l = 1 (p), m can be −1, 0, +1, so there are 3 p orbitals.")],
   "activity": "Write the electronic configurations of the first 20 elements using the Aufbau order.",
   "questions": [
     Q("EASY", "Which experiment revealed the atomic nucleus?", ["Rutherford's gold foil experiment", "Millikan's oil drop", "Thomson's cathode ray", "Mendel's pea experiment"], "Rutherford's gold foil experiment", "Alpha particles bounced back.", "Rutherford's experiment showed a dense nucleus."),
     Q("EASY", "Maximum electrons in one orbital?", [], "2|two", "Pauli's principle.", "An orbital holds at most 2 electrons."),
     Q("MEDIUM", "Electronic configuration of sodium (Z = 11)?", ["1s² 2s² 2p⁶ 3s¹", "1s² 2s² 2p⁷", "1s² 2s² 2p⁵ 3s²", "1s² 2p⁶ 3s³"], "1s² 2s² 2p⁶ 3s¹", "Fill 1s, 2s, 2p, then 3s.", "2 + 2 + 6 + 1 = 11."),
     Q("MEDIUM", "The quantum number l = 1 corresponds to which orbital?", ["s", "p", "d", "f"], "p", "l = 0 is s.", "l = 1 is a p orbital."),
     Q("HARD", "Which rule says orbitals of equal energy are singly filled first?", ["Hund's rule", "Aufbau principle", "Pauli exclusion principle", "Heisenberg principle"], "Hund's rule", "Electrons 'spread out' first.", "This is Hund's rule of maximum multiplicity."),
     Q("HARD", "How many orbitals are in the d subshell?", [], "5|five", "m ranges from −2 to +2.", "There are 5 d orbitals.")]},
  {"name": "Chemical Bonding and Molecular Structure",
   "explanation": "Atoms bond to achieve a stable electron arrangement, often an octet. Ionic bonds form when electrons are transferred from a metal to a non-metal, creating oppositely charged ions, as in NaCl. Covalent bonds form when atoms share electron pairs, as in H₂ and Cl₂. Lewis structures show valence electrons as dots. VSEPR theory predicts molecular shape from electron-pair repulsion: CO₂ is linear, BF₃ is trigonal planar, CH₄ is tetrahedral and H₂O is bent. Hybridisation mixes atomic orbitals, for example sp³ in methane. Hydrogen bonding explains water's high boiling point.",
   "keyPoints": ["Atoms bond to get a stable octet.",
                 "Ionic: electron transfer. Covalent: electron sharing.",
                 "VSEPR predicts shape from electron repulsion.",
                 "CH₄ is tetrahedral (sp³); H₂O is bent.",
                 "Hydrogen bonds raise water's boiling point."],
   "examples": [EX("Ionic bond", "Na gives one electron to Cl → Na⁺Cl⁻.", "Na• + •Cl → Na⁺ Cl⁻"),
                EX("Shapes", "CO₂ linear (180°), CH₄ tetrahedral (109.5°), H₂O bent (104.5°)."),
                EX("Hydrogen bonding", "Ice floats because hydrogen bonds hold water molecules in an open structure.")],
   "activity": "Use balloons tied together to model linear, trigonal planar and tetrahedral shapes.",
   "questions": [
     Q("EASY", "A bond formed by sharing electrons is ___.", ["Ionic", "Covalent", "Metallic", "Hydrogen"], "Covalent", "Atoms share pairs.", "Sharing forms a covalent bond."),
     Q("EASY", "NaCl has which type of bond?", ["Ionic", "Covalent", "Metallic", "Hydrogen"], "Ionic", "A metal and a non-metal.", "Electron transfer forms an ionic bond."),
     Q("MEDIUM", "The shape of CH₄ is ___.", ["Linear", "Tetrahedral", "Bent", "Trigonal planar"], "Tetrahedral", "Four bond pairs, no lone pairs.", "CH₄ is tetrahedral."),
     Q("MEDIUM", "The hybridisation of carbon in CH₄ is ___.", ["sp", "sp²", "sp³", "dsp²"], "sp³", "Four equivalent bonds.", "Carbon is sp³ hybridised."),
     Q("HARD", "Why is the H₂O molecule bent?", ["Two lone pairs on oxygen repel the bonds", "Oxygen is large", "Hydrogen is heavy", "It has double bonds"], "Two lone pairs on oxygen repel the bonds", "Use VSEPR theory.", "Lone-pair repulsion bends the molecule."),
     Q("HARD", "The bond angle in CO₂ is ___.", ["180°", "109.5°", "120°", "90°"], "180°", "It is linear.", "CO₂ is linear with a 180° angle.")]}]},
 {"name": "Biology", "icon": "🧬", "chapters": [
  {"name": "The Living World",
   "explanation": "Living organisms grow, reproduce, respond to their surroundings and carry out metabolism. Because there are millions of species, scientists classify them. Taxonomy is the science of identifying, naming and classifying organisms. Binomial nomenclature, introduced by Carolus Linnaeus, gives each organism a two-part scientific name: genus followed by species, such as Homo sapiens. The taxonomic hierarchy from highest to lowest is kingdom, phylum (or division), class, order, family, genus and species. Herbaria, museums, zoos and botanical gardens help in taxonomic study.",
   "keyPoints": ["Living things grow, reproduce, respond and metabolise.",
                 "Taxonomy names and classifies organisms.",
                 "Binomial names: Genus species (e.g. Homo sapiens).",
                 "Linnaeus introduced binomial nomenclature.",
                 "Hierarchy: kingdom → phylum → class → order → family → genus → species."],
   "examples": [EX("Scientific name", "Mango is Mangifera indica; the genus is written with a capital letter and both words are italicised."),
                EX("Hierarchy", "Human: Animalia → Chordata → Mammalia → Primates → Hominidae → Homo → sapiens."),
                EX("Herbarium", "Dried, pressed plant specimens are stored on sheets with labels.", "🌿📄")],
   "activity": "Find the scientific names of five plants and five animals around your home.",
   "questions": [
     Q("EASY", "Who introduced binomial nomenclature?", ["Charles Darwin", "Carolus Linnaeus", "Gregor Mendel", "Robert Hooke"], "Carolus Linnaeus", "A Swedish botanist.", "Linnaeus introduced two-part names."),
     Q("EASY", "The scientific name of humans is ___.", ["Homo sapiens", "Felis catus", "Panthera leo", "Mangifera indica"], "Homo sapiens", "'Wise man'.", "Humans are Homo sapiens."),
     Q("MEDIUM", "The basic unit of classification is the ___.", [], "species", "It is the lowest rank.", "Species is the basic unit."),
     Q("MEDIUM", "In a binomial name, the first word is the ___.", ["Genus", "Species", "Family", "Kingdom"], "Genus", "It starts with a capital letter.", "The first word is the genus."),
     Q("HARD", "Which is the correct order (highest to lowest)?", ["Kingdom, phylum, class, order, family, genus, species", "Species, genus, family, order, class, phylum, kingdom", "Kingdom, class, phylum, order, family, genus, species", "Phylum, kingdom, class, order, family, species, genus"], "Kingdom, phylum, class, order, family, genus, species", "Kingdom is the broadest.", "This is the taxonomic hierarchy."),
     Q("HARD", "A collection of dried, pressed plant specimens is a ___.", ["Herbarium", "Zoo", "Museum of animals", "Aquarium"], "Herbarium", "'Herb' means plant.", "It is a herbarium.")]},
  {"name": "Cell Cycle and Cell Division",
   "explanation": "The cell cycle is the sequence of events in which a cell grows and divides. It has interphase, where the cell grows and copies its DNA (G₁, S and G₂ phases), and the M phase, where division occurs. Mitosis produces two genetically identical daughter cells and has four stages: prophase, metaphase, anaphase and telophase, followed by cytokinesis. Mitosis helps growth and repair. Meiosis happens in reproductive cells, involves two divisions and produces four haploid cells with half the chromosome number. Crossing over during meiosis creates genetic variation.",
   "keyPoints": ["Interphase: G₁, S (DNA copying) and G₂.",
                 "Mitosis: prophase, metaphase, anaphase, telophase.",
                 "Mitosis gives two identical cells for growth and repair.",
                 "Meiosis gives four haploid cells for reproduction.",
                 "Crossing over in meiosis creates variation."],
   "examples": [EX("Mitosis stages", "Chromosomes condense (prophase) → line up (metaphase) → separate (anaphase) → new nuclei form (telophase).", "| → ≡ → ⇤⇥ → ◯◯"),
                EX("Human cells", "Body cells have 46 chromosomes; gametes made by meiosis have 23."),
                EX("Repair", "A cut on your skin heals as cells divide by mitosis.")],
   "activity": "Make a flip book showing the four stages of mitosis.",
   "questions": [
     Q("EASY", "Mitosis produces how many daughter cells?", [], "2|two", "One cell divides once.", "Mitosis gives two identical cells."),
     Q("EASY", "DNA is copied during which phase?", ["G₁", "S", "G₂", "M"], "S", "S stands for synthesis.", "DNA replication occurs in the S phase."),
     Q("MEDIUM", "In which stage of mitosis do chromosomes line up at the centre?", ["Prophase", "Metaphase", "Anaphase", "Telophase"], "Metaphase", "'Meta' — middle.", "They align at the metaphase plate."),
     Q("MEDIUM", "Meiosis produces cells that are ___.", ["Diploid", "Haploid"], "Haploid", "Gametes have half the chromosomes.", "Meiosis produces haploid cells."),
     Q("HARD", "Crossing over occurs during ___.", ["Prophase I of meiosis", "Metaphase of mitosis", "Interphase", "Telophase of mitosis"], "Prophase I of meiosis", "Homologous chromosomes pair up.", "Crossing over happens in prophase I."),
     Q("HARD", "A human gamete contains how many chromosomes?", [], "23", "Half of 46.", "Gametes have 23 chromosomes.")]},
  {"name": "Photosynthesis in Higher Plants",
   "explanation": "Photosynthesis converts light energy into chemical energy stored in glucose. It happens in chloroplasts, which contain chlorophyll. The process has two parts. The light reactions take place in the thylakoid membranes: water is split (photolysis), oxygen is released, and ATP and NADPH are produced. The dark reactions, or Calvin cycle, take place in the stroma: CO₂ is fixed using ATP and NADPH to make sugars. The first stable product in C₃ plants is 3-phosphoglycerate (PGA). C₄ plants like maize have special adaptations that make them efficient in hot conditions.",
   "keyPoints": ["Photosynthesis happens in chloroplasts.",
                 "Light reactions occur in the thylakoids.",
                 "Water splitting releases oxygen.",
                 "The Calvin cycle in the stroma fixes CO₂.",
                 "C₄ plants like maize are efficient in hot climates."],
   "examples": [EX("Overall equation", "6CO₂ + 12H₂O → C₆H₁₂O₆ + 6O₂ + 6H₂O (in light)."),
                EX("Where", "Thylakoid = light reactions; stroma = Calvin cycle.", "🟢 thylakoid ⟶ ATP, NADPH ⟶ stroma"),
                EX("Source of oxygen", "Experiments with labelled water showed that the O₂ released comes from water, not CO₂.")],
   "activity": "Place a water plant in water under a lamp and count the oxygen bubbles at different distances.",
   "questions": [
     Q("EASY", "Photosynthesis takes place in the ___.", ["Mitochondria", "Chloroplast", "Nucleus", "Ribosome"], "Chloroplast", "It contains chlorophyll.", "Chloroplasts are the site of photosynthesis."),
     Q("EASY", "Which gas is released during photosynthesis?", ["CO₂", "O₂", "N₂", "H₂"], "O₂", "We breathe it in.", "Oxygen is released."),
     Q("MEDIUM", "The Calvin cycle takes place in the ___.", ["Thylakoid", "Stroma", "Cytoplasm", "Nucleus"], "Stroma", "It is the fluid part of the chloroplast.", "The Calvin cycle happens in the stroma."),
     Q("MEDIUM", "The oxygen released in photosynthesis comes from ___.", ["Water", "Carbon dioxide", "Glucose", "Soil"], "Water", "Photolysis splits this molecule.", "O₂ comes from splitting water."),
     Q("HARD", "The first stable product of CO₂ fixation in C₃ plants is ___.", ["3-phosphoglycerate", "Oxaloacetate", "Glucose", "Pyruvate"], "3-phosphoglycerate", "It is a 3-carbon compound.", "C₃ plants form 3-PGA first."),
     Q("HARD", "Which of these is a C₄ plant?", ["Maize", "Wheat", "Rice", "Pea"], "Maize", "It thrives in hot conditions.", "Maize and sugarcane are C₄ plants.")]}]},
 {"name": "English", "icon": "📖", "chapters": [
  {"name": "Clauses",
   "explanation": "A clause is a group of words that has a subject and a verb. An independent (main) clause expresses a complete thought and can stand alone. A dependent (subordinate) clause cannot stand alone. Dependent clauses are of three kinds. A noun clause works as a noun (What she said surprised me). An adjective (relative) clause describes a noun and often begins with who, which or that (The boy who won is my cousin). An adverb clause tells when, why, where or how and begins with words like because, although, when and if (I stayed home because it rained).",
   "keyPoints": ["A clause has a subject and a verb.",
                 "An independent clause can stand alone.",
                 "Noun clauses act as nouns.",
                 "Adjective clauses describe nouns (who, which, that).",
                 "Adverb clauses show time, reason, condition (because, when, if)."],
   "examples": [EX("Noun clause", "I know that you are honest."),
                EX("Adjective clause", "The book which I borrowed is interesting."),
                EX("Adverb clause", "Although it was cold, we went swimming.")],
   "activity": "Take five sentences from a newspaper and identify the independent and dependent clauses.",
   "questions": [
     Q("EASY", "A clause must contain a subject and a ___.", ["Verb", "Adjective", "Preposition", "Article"], "Verb", "It needs an action or state.", "Every clause has a subject and a verb."),
     Q("EASY", "Which can stand alone as a sentence?", ["Independent clause", "Dependent clause"], "Independent clause", "It is complete by itself.", "Independent clauses express a complete thought."),
     Q("MEDIUM", "In 'The girl who sings well is my sister', 'who sings well' is a(n) ___ clause.", ["Noun", "Adjective", "Adverb"], "Adjective", "It describes 'the girl'.", "It is an adjective (relative) clause."),
     Q("MEDIUM", "'I left early because I was tired.' 'because I was tired' is a(n) ___ clause.", ["Noun", "Adjective", "Adverb"], "Adverb", "It tells why.", "It gives a reason: adverb clause."),
     Q("HARD", "'What you said is true.' 'What you said' is a(n) ___ clause.", ["Noun", "Adjective", "Adverb"], "Noun", "It is the subject of the sentence.", "It works as a noun."),
     Q("HARD", "Which word usually introduces an adjective clause?", ["which", "because", "although", "if"], "which", "Relative pronouns.", "Who, which and that introduce relative clauses.")]},
  {"name": "Idioms and Phrases",
   "explanation": "An idiom is a group of words whose meaning is different from the meanings of the individual words. For example, 'break the ice' means to start a conversation in an awkward situation, not to break real ice. Idioms make language colourful and natural, but they should be used carefully in formal writing. Some common idioms are 'once in a blue moon' (very rarely), 'a piece of cake' (very easy), 'hit the nail on the head' (to be exactly right), 'burn the midnight oil' (to work late at night) and 'under the weather' (feeling ill).",
   "keyPoints": ["An idiom's meaning differs from its words.",
                 "'Once in a blue moon' = very rarely.",
                 "'A piece of cake' = very easy.",
                 "'Burn the midnight oil' = work late at night.",
                 "'Under the weather' = feeling unwell."],
   "examples": [EX("In context", "The exam was a piece of cake — I finished early."),
                EX("Break the ice", "The teacher told a joke to break the ice on the first day.", "🧊🔨"),
                EX("Hit the nail on the head", "You hit the nail on the head: the problem is lack of practice.")],
   "activity": "Write a short dialogue between two friends using at least four idioms.",
   "questions": [
     Q("EASY", "'A piece of cake' means ___.", ["Very easy", "Delicious", "Very small", "Expensive"], "Very easy", "Not about food.", "It means something very easy."),
     Q("EASY", "'Once in a blue moon' means ___.", ["Very rarely", "Every night", "At midnight", "Often"], "Very rarely", "Blue moons are rare.", "It means very rarely."),
     Q("MEDIUM", "'Burn the midnight oil' means ___.", ["Work late at night", "Waste oil", "Start a fire", "Sleep early"], "Work late at night", "Old lamps used oil.", "It means working or studying late."),
     Q("MEDIUM", "'Under the weather' means ___.", ["Feeling ill", "Outside in the rain", "Very happy", "Watching the sky"], "Feeling ill", "It describes health.", "It means feeling unwell."),
     Q("HARD", "'Hit the nail on the head' means ___.", ["Describe something exactly right", "Hurt someone", "Do carpentry", "Make a mistake"], "Describe something exactly right", "Think of a perfect hammer strike.", "It means being exactly correct."),
     Q("HARD", "'Let the cat out of the bag' means ___.", ["Reveal a secret", "Free an animal", "Go shopping", "Lose something"], "Reveal a secret", "Something hidden comes out.", "It means revealing a secret by mistake.")]},
  {"name": "Report Writing",
   "explanation": "A report is a factual account of an event, such as a school function, and is often written for a school magazine or newspaper. It has a clear heading, a byline with the writer's name, and sometimes the place and date. The first paragraph answers the key questions: what, when, where, who and why. The following paragraphs give details in the order they happened, and the last paragraph gives the outcome or conclusion. Reports are written in the past tense, often in the passive voice, and in a formal, objective style.",
   "keyPoints": ["A report is a factual account of an event.",
                 "It has a heading and a byline.",
                 "The opening answers what, when, where, who and why.",
                 "Details follow in order; end with the outcome.",
                 "Use the past tense and a formal, objective tone."],
   "examples": [EX("Heading and byline", "ANNUAL SPORTS DAY CELEBRATED — by Kavya Nair, Sports Secretary"),
                EX("Opening", "The Annual Sports Day was held on 12 January in the school ground. The Chief Guest was…"),
                EX("Passive voice", "Prizes were distributed by the Principal.")],
   "activity": "Write a 120-word report on a recent event at your school.",
   "questions": [
     Q("EASY", "Reports are usually written in which tense?", ["Past", "Present", "Future"], "Past", "They describe events that already happened.", "Reports use the past tense."),
     Q("EASY", "The writer's name below the heading is the ___.", ["Byline", "Subject", "Salutation", "Signature"], "Byline", "'By' the writer.", "It is the byline."),
     Q("MEDIUM", "The first paragraph of a report should answer ___.", ["What, when, where, who and why", "Only the writer's opinion", "Future plans", "A joke"], "What, when, where, who and why", "The five Ws.", "The opening gives the key facts."),
     Q("MEDIUM", "Which sentence suits a report?", ["The event was inaugurated by the Chief Guest.", "OMG the event was awesome!!", "I think maybe it was nice?", "You should have come!"], "The event was inaugurated by the Chief Guest.", "Formal and objective.", "It is formal, factual and in the passive voice."),
     Q("HARD", "The tone of a report should be ___.", ["Formal and objective", "Emotional and personal", "Humorous", "Persuasive"], "Formal and objective", "It presents facts.", "Reports are formal and objective."),
     Q("HARD", "What should the final paragraph of a report contain?", ["The outcome or conclusion", "The heading", "The byline", "A list of questions"], "The outcome or conclusion", "End the report clearly.", "The last paragraph gives the outcome.")]}]},
 {"name": "Computer Science", "icon": "💻", "chapters": [
  {"name": "Number Systems and Computer Basics",
   "explanation": "A computer system has hardware (physical parts) and software (programs). The CPU processes data using the ALU and control unit, memory stores data, and input and output devices let us interact with the computer. Computers use the binary number system (base 2), which has only the digits 0 and 1. Other systems include decimal (base 10), octal (base 8) and hexadecimal (base 16, using 0–9 and A–F). To convert decimal to binary, divide repeatedly by 2 and read the remainders from bottom to top. 8 bits make 1 byte, and 1 KB = 1024 bytes.",
   "keyPoints": ["Hardware is physical; software is programs.",
                 "The CPU contains the ALU and control unit.",
                 "Binary uses only 0 and 1 (base 2).",
                 "Hexadecimal uses 0–9 and A–F (base 16).",
                 "8 bits = 1 byte; 1 KB = 1024 bytes."],
   "examples": [EX("Decimal to binary", "13 → 13/2 = 6 r1, 6/2 = 3 r0, 3/2 = 1 r1, 1/2 = 0 r1 → 1101.", "8 4 2 1\n1 1 0 1 = 13"),
                EX("Binary to decimal", "1010₂ = 8 + 0 + 2 + 0 = 10."),
                EX("Hexadecimal", "F in hexadecimal = 15 in decimal; FF = 255.")],
   "activity": "Write your age and roll number in binary.",
   "questions": [
     Q("EASY", "Binary numbers use which digits?", ["0 and 1", "0 to 9", "1 and 2", "A to F"], "0 and 1", "Base 2.", "Binary uses only 0 and 1."),
     Q("EASY", "How many bits make one byte?", [], "8|eight", "A byte is a group of bits.", "8 bits = 1 byte."),
     Q("MEDIUM", "Convert 1011₂ to decimal.", [], "11", "8 + 0 + 2 + 1.", "1011₂ = 11."),
     Q("MEDIUM", "Convert 6 to binary.", [], "110", "6 = 4 + 2.", "6 = 110₂."),
     Q("HARD", "The hexadecimal digit A equals ___ in decimal.", [], "10", "After 9 comes A.", "A = 10."),
     Q("HARD", "Which part of the CPU performs arithmetic and logical operations?", ["ALU", "Control unit", "RAM", "Hard disk"], "ALU", "Arithmetic Logic Unit.", "The ALU performs calculations and comparisons.")]},
  {"name": "Python Basics",
   "explanation": "Python is a popular, easy-to-read programming language. A variable stores a value, created with the assignment operator, like x = 5. Common data types include int (whole numbers), float (decimals), str (text in quotes) and bool (True or False). The print() function shows output and input() reads text from the user; input() always returns a string, so we convert it with int() or float() when needed. Python uses arithmetic operators (+, −, *, /, //, %, **), where / gives a decimal result, // gives the floor of division and % gives the remainder. Comments start with #.",
   "keyPoints": ["Variables store values: x = 5.",
                 "Types: int, float, str, bool.",
                 "input() returns a string; convert with int().",
                 "/ gives a decimal; // gives floor division; % gives the remainder.",
                 "** is power: 2 ** 3 = 8."],
   "examples": [EX("Hello", "name = input('Your name: ')\nprint('Hello', name)"),
                EX("Operators", "7 / 2 = 3.5, 7 // 2 = 3, 7 % 2 = 1, 2 ** 3 = 8."),
                EX("Type conversion", "age = int(input('Age: '))\nprint(age + 1)")],
   "activity": "Write a Python program that asks for two numbers and prints their sum, difference, product and quotient.",
   "questions": [
     Q("EASY", "Which function displays output in Python?", ["print()", "input()", "show()", "display()"], "print()", "It 'prints' to the screen.", "print() displays output."),
     Q("EASY", "What is the data type of 3.14?", ["int", "float", "str", "bool"], "float", "It has a decimal point.", "3.14 is a float."),
     Q("MEDIUM", "What is 17 % 5 in Python?", [], "2", "% gives the remainder.", "17 = 3 × 5 + 2."),
     Q("MEDIUM", "What is 17 // 5 in Python?", [], "3", "// gives the floor of the division.", "17 / 5 = 3.4, floor is 3."),
     Q("HARD", "What is the output of print(2 ** 4)?", [], "16", "** is power.", "2⁴ = 16."),
     Q("HARD", "What type does input() always return?", ["int", "float", "str", "bool"], "str", "Even if you type a number.", "input() returns a string.")]},
  {"name": "Conditional and Looping Statements",
   "explanation": "Programs make decisions using if, elif and else. The condition after 'if' must evaluate to True or False, and the indented block runs only when it is True. Comparison operators include ==, !=, <, >, <= and >=, and logical operators are and, or and not. Loops repeat code. A for loop repeats over a sequence, often using range(): range(5) gives 0, 1, 2, 3, 4. A while loop repeats as long as its condition is True. The break statement exits a loop early, and continue skips to the next iteration.",
   "keyPoints": ["if / elif / else choose what to run.",
                 "== compares; = assigns.",
                 "for loops repeat over a sequence.",
                 "range(5) gives 0 to 4.",
                 "break exits a loop; continue skips an iteration."],
   "examples": [EX("Even or odd", "n = 7\nif n % 2 == 0:\n    print('Even')\nelse:\n    print('Odd')"),
                EX("for loop", "for i in range(1, 4):\n    print(i)   # prints 1 2 3"),
                EX("while loop", "count = 3\nwhile count > 0:\n    print(count)\n    count -= 1")],
   "activity": "Write a program that prints the multiplication table of any number the user enters.",
   "questions": [
     Q("EASY", "Which operator checks equality in Python?", ["=", "==", "!=", "=>"], "==", "One '=' assigns a value.", "== compares two values."),
     Q("EASY", "Which keyword starts a conditional statement?", ["if", "for", "while", "def"], "if", "It asks a yes/no question.", "Conditions start with 'if'."),
     Q("MEDIUM", "How many numbers does range(5) produce?", [], "5", "It starts at 0.", "0, 1, 2, 3, 4 — five numbers."),
     Q("MEDIUM", "Which statement exits a loop immediately?", ["break", "continue", "pass", "exit loop"], "break", "It 'breaks' out.", "break stops the loop."),
     Q("HARD", "What is printed? for i in range(2, 8, 2): print(i)", ["2 4 6", "2 4 6 8", "2 3 4 5 6 7", "0 2 4 6"], "2 4 6", "Start 2, stop before 8, step 2.", "range(2, 8, 2) → 2, 4, 6."),
     Q("HARD", "What is the value of total after: total = 0; for i in range(1, 5): total += i", [], "10", "Add 1 + 2 + 3 + 4.", "1 + 2 + 3 + 4 = 10.")]}]},
 {"name": "Economics", "icon": "📈", "chapters": [
  {"name": "Introduction to Economics",
   "explanation": "Economics studies how people make choices when resources are scarce and wants are unlimited. Scarcity forces us to choose, and every choice has an opportunity cost: the value of the next best alternative given up. Every economy faces three central problems: what to produce, how to produce and for whom to produce. The production possibility curve (PPC) shows the combinations of two goods an economy can produce with its resources and technology. Microeconomics studies individual units like a consumer or a firm, while macroeconomics studies the economy as a whole.",
   "keyPoints": ["Economics is about choice under scarcity.",
                 "Opportunity cost = value of the next best alternative.",
                 "Central problems: what, how and for whom to produce.",
                 "The PPC shows possible production combinations.",
                 "Micro = individual units; macro = whole economy."],
   "examples": [EX("Opportunity cost", "If you spend an evening studying instead of working for ₹500, your opportunity cost is ₹500."),
                EX("PPC", "A country can make more wheat only by making less cloth once resources are fully used.", "cloth\n|\\\n| \\\n|__\\ wheat"),
                EX("Micro vs macro", "The price of onions is micro; national unemployment is macro.")],
   "activity": "List three choices you made today and the opportunity cost of each.",
   "questions": [
     Q("EASY", "The basic economic problem arises because of ___.", ["Scarcity", "Plenty", "Money", "Technology"], "Scarcity", "Resources are limited.", "Scarcity creates the need to choose."),
     Q("EASY", "Studying the whole economy is ___.", ["Microeconomics", "Macroeconomics"], "Macroeconomics", "'Macro' means large.", "Macroeconomics studies the whole economy."),
     Q("MEDIUM", "The value of the next best alternative given up is the ___ cost.", [], "opportunity", "It is the cost of the missed opportunity.", "This is opportunity cost."),
     Q("MEDIUM", "Which is a central problem of an economy?", ["What to produce", "How to vote", "Where to travel", "Which movie to watch"], "What to produce", "What, how, for whom.", "What to produce is a central problem."),
     Q("HARD", "The PPC is usually ___ to the origin.", ["Concave", "Convex", "A straight line parallel", "Circular"], "Concave", "Increasing opportunity cost.", "Rising opportunity cost makes the PPC concave."),
     Q("HARD", "A point inside the PPC shows ___.", ["Underutilisation of resources", "Full employment", "An impossible combination", "Economic growth"], "Underutilisation of resources", "The economy could produce more.", "Inside the PPC, resources are underused.")]},
  {"name": "Measures of Central Tendency",
   "explanation": "A measure of central tendency is a single value that represents a whole data set. The arithmetic mean is the sum of values divided by the number of values. The median is the middle value when the data is arranged in order; for an even number of values, it is the average of the two middle values. The mode is the value that occurs most often. The mean is affected by extreme values, while the median is not, so the median is often used for data like incomes. For a moderately skewed distribution, Mode ≈ 3 Median − 2 Mean.",
   "keyPoints": ["Mean = sum ÷ number of values.",
                 "Median = middle value of ordered data.",
                 "Mode = most frequent value.",
                 "The mean is affected by extreme values.",
                 "Median is better for skewed data like incomes."],
   "examples": [EX("Mean", "Marks 4, 6, 8: mean = 18/3 = 6."),
                EX("Median", "2, 3, 7, 9, 10 → median 7. For 2, 3, 7, 9 → (3 + 7)/2 = 5."),
                EX("Mode", "Shoe sizes 6, 7, 7, 8, 7, 9 → mode 7.")],
   "activity": "Collect the heights of five family members and find the mean, median and mode.",
   "questions": [
     Q("EASY", "Mean of 2, 4, 6?", [], "4", "Add and divide by 3.", "12 ÷ 3 = 4."),
     Q("EASY", "The value that occurs most often is the ___.", ["Mean", "Median", "Mode", "Range"], "Mode", "Most popular value.", "The mode is the most frequent value."),
     Q("MEDIUM", "Median of 5, 1, 9, 3, 7?", [], "5", "Sort first: 1, 3, 5, 7, 9.", "The middle value is 5."),
     Q("MEDIUM", "Median of 2, 4, 6, 8?", [], "5", "Average the two middle values.", "(4 + 6)/2 = 5."),
     Q("HARD", "Which measure is most affected by extreme values?", ["Mean", "Median", "Mode"], "Mean", "One very large income changes it a lot.", "The mean is pulled by extremes."),
     Q("HARD", "If mean = 20 and median = 22, mode ≈ ? (Mode = 3 Median − 2 Mean)", [], "26", "3 × 22 − 2 × 20.", "66 − 40 = 26.")]},
  {"name": "Theory of Demand",
   "explanation": "Demand is the quantity of a good that consumers are willing and able to buy at a given price during a period of time. The law of demand states that, other things remaining constant, quantity demanded falls when price rises, and rises when price falls, so the demand curve slopes downward. Demand is also affected by consumers' income, prices of related goods (substitutes and complements), tastes and expectations. A movement along the demand curve is caused by a change in the good's own price, while a shift of the curve is caused by other factors. Price elasticity of demand measures how strongly quantity responds to price.",
   "keyPoints": ["Demand = willingness and ability to buy.",
                 "Law of demand: price ↑ → quantity demanded ↓.",
                 "The demand curve slopes downward.",
                 "Own price change → movement along the curve.",
                 "Income, tastes and related goods → shift of the curve."],
   "examples": [EX("Law of demand", "When mango prices fall in summer, people buy more mangoes.", "P\n|\\\n| \\ D\n|__\\__ Q"),
                EX("Substitutes", "If tea gets costlier, demand for coffee rises."),
                EX("Complements", "If petrol prices rise, demand for cars may fall.")],
   "activity": "Ask a shopkeeper how sales of a product changed when its price went up.",
   "questions": [
     Q("EASY", "According to the law of demand, when price rises, quantity demanded ___.", ["Rises", "Falls", "Stays the same"], "Falls", "People buy less when things cost more.", "Price and quantity demanded move in opposite directions."),
     Q("EASY", "The demand curve usually slopes ___.", ["Downward", "Upward", "Horizontally", "Vertically"], "Downward", "From left-top to right-bottom.", "It slopes downward."),
     Q("MEDIUM", "Tea and coffee are ___ goods.", ["Substitute", "Complementary", "Inferior", "Giffen"], "Substitute", "One can replace the other.", "They are substitutes."),
     Q("MEDIUM", "Cars and petrol are ___ goods.", ["Substitute", "Complementary", "Unrelated", "Free"], "Complementary", "They are used together.", "They are complements."),
     Q("HARD", "A rise in consumers' income (for a normal good) causes ___.", ["A rightward shift of the demand curve", "A movement down the curve", "A leftward shift", "No change"], "A rightward shift of the demand curve", "It is not a change in the good's own price.", "Higher income shifts demand to the right."),
     Q("HARD", "A change in the good's own price causes ___.", ["Movement along the demand curve", "Shift of the demand curve", "Shift of the supply curve", "Nothing"], "Movement along the demand curve", "Other factors are constant.", "Own price changes move along the curve.")]}]}]}
