# Seed content source for Grade 8. Run build_curriculum.py to regenerate curriculum.json.
from grade6 import Q, EX

GRADE8 = {"grade": 8, "subjects": [
 {"name": "Mathematics", "icon": "🔢", "chapters": [
  {"name": "Rational Numbers",
   "explanation": "A rational number is any number that can be written as p/q, where p and q are integers and q is not zero. All integers and fractions are rational numbers. Rational numbers are closed under addition, subtraction and multiplication, which means the result is always rational. Zero is the additive identity (adding 0 changes nothing) and 1 is the multiplicative identity. The additive inverse of a/b is −a/b, and the multiplicative inverse (reciprocal) of a/b is b/a. Between any two rational numbers there are infinitely many rational numbers.",
   "keyPoints": ["A rational number can be written as p/q with q ≠ 0.",
                 "All integers and fractions are rational.",
                 "0 is the additive identity; 1 is the multiplicative identity.",
                 "The reciprocal of a/b is b/a.",
                 "There are infinitely many rationals between any two rationals."],
   "examples": [EX("Is it rational?", "5 = 5/1 and −3/4 are rational. 2/0 is not defined, so it is not rational."),
                EX("Reciprocal", "The reciprocal of −2/7 is −7/2, because (−2/7) × (−7/2) = 1."),
                EX("Numbers in between", "Between 1/4 and 1/2: write them as 2/8 and 4/8, so 3/8 lies between.", "1/4 —— 3/8 —— 1/2")],
   "activity": "Find five rational numbers between 0 and 1 and mark them on a number line.",
   "questions": [
     Q("EASY", "Which of these is NOT a rational number?", ["3/4", "−5", "0", "7/0"], "7/0", "The denominator cannot be zero.", "7/0 is undefined, so it is not rational."),
     Q("EASY", "What is the additive inverse of 5/8?", ["8/5", "−5/8", "5/8", "−8/5"], "−5/8", "What do you add to get 0?", "5/8 + (−5/8) = 0."),
     Q("MEDIUM", "What is the reciprocal of −3/5?", ["3/5", "−5/3", "5/3", "−3/5"], "−5/3", "Flip the fraction; the sign stays.", "(−3/5) × (−5/3) = 1."),
     Q("MEDIUM", "What is 2/3 + (−1/6)?", ["1/2", "1/3", "1/6", "3/6"], "1/2", "Write 2/3 as 4/6.", "4/6 − 1/6 = 3/6 = 1/2."),
     Q("HARD", "Which is the multiplicative identity for rational numbers?", ["0", "1", "−1", "It does not exist"], "1", "Multiplying by it changes nothing.", "a × 1 = a, so 1 is the multiplicative identity."),
     Q("HARD", "What is (−2/3) × (9/4)?", ["−3/2", "3/2", "−18/7", "−2/3"], "−3/2", "Multiply and simplify: 18/12.", "−18/12 = −3/2.")]},
  {"name": "Linear Equations in One Variable",
   "explanation": "A linear equation in one variable has a single unknown with power 1, like 3x + 5 = 20. To solve it, we keep the equation balanced and move terms: whatever we do to one side we do to the other. When variables appear on both sides, collect the variable terms on one side and the numbers on the other. Many word problems, such as ages, perimeters and money, can be turned into linear equations. Always check your answer by putting it back into the original equation.",
   "keyPoints": ["A linear equation has the variable only to the power 1.",
                 "Keep the equation balanced.",
                 "Bring variable terms to one side, numbers to the other.",
                 "Word problems can be written as equations.",
                 "Check the answer by substituting it back."],
   "examples": [EX("Variables on both sides", "5x − 3 = 2x + 9 → 3x = 12 → x = 4."),
                EX("Word problem", "A number plus twice itself is 36. x + 2x = 36, so x = 12."),
                EX("Check", "For x = 4: 5(4) − 3 = 17 and 2(4) + 9 = 17. ✓")],
   "activity": "Write an equation for this: your age after 5 years will be twice your age 5 years ago. Solve it.",
   "questions": [
     Q("EASY", "Solve: x + 12 = 20. x = ?", [], "8", "Subtract 12 from both sides.", "20 − 12 = 8."),
     Q("EASY", "Solve: 5x = 35. x = ?", [], "7", "Divide both sides by 5.", "35 ÷ 5 = 7."),
     Q("MEDIUM", "Solve: 3x − 7 = 2x + 5. x = ?", [], "12", "Subtract 2x from both sides.", "x − 7 = 5, so x = 12."),
     Q("MEDIUM", "Solve: (x/3) + 4 = 10. x = ?", [], "18", "Subtract 4, then multiply by 3.", "x/3 = 6, so x = 18."),
     Q("HARD", "The sum of two consecutive numbers is 51. What is the smaller number?", [], "25", "Let them be x and x + 1.", "2x + 1 = 51, so x = 25."),
     Q("HARD", "Solve: 2(x − 3) = x + 4. x = ?", [], "10", "Expand the bracket first.", "2x − 6 = x + 4, so x = 10.")]},
  {"name": "Squares and Square Roots",
   "explanation": "The square of a number is the number multiplied by itself: 7² = 49. Numbers like 1, 4, 9, 16 and 25 are perfect squares. A perfect square never ends in 2, 3, 7 or 8. The square root is the opposite of squaring: √49 = 7. We can find square roots by prime factorisation, pairing equal prime factors, or by long division for bigger numbers. Three whole numbers a, b and c with a² + b² = c² form a Pythagorean triplet, such as 3, 4, 5.",
   "keyPoints": ["Square: a number times itself.",
                 "Square root undoes squaring.",
                 "Perfect squares never end in 2, 3, 7 or 8.",
                 "Pair prime factors to find a square root.",
                 "3, 4, 5 is a Pythagorean triplet."],
   "examples": [EX("Square", "12² = 12 × 12 = 144.", "■■■ \n■■■  3² = 9\n■■■"),
                EX("Square root by factors", "144 = 2×2 × 2×2 × 3×3. Take one from each pair: 2 × 2 × 3 = 12."),
                EX("Triplet", "6² + 8² = 36 + 64 = 100 = 10², so 6, 8, 10 is a triplet.")],
   "activity": "Arrange coins or buttons in square shapes. Which numbers of coins make perfect squares?",
   "questions": [
     Q("EASY", "What is 9²?", [], "81", "9 × 9.", "9 × 9 = 81."),
     Q("EASY", "What is √64?", [], "8", "Which number times itself gives 64?", "8 × 8 = 64."),
     Q("MEDIUM", "Which of these can NOT be a perfect square?", ["144", "225", "1057", "196"], "1057", "Look at the last digit.", "Perfect squares never end in 7."),
     Q("MEDIUM", "What is √324?", [], "18", "324 = 2×2 × 3×3 × 3×3.", "2 × 3 × 3 = 18."),
     Q("HARD", "Which set is a Pythagorean triplet?", ["2, 3, 4", "5, 12, 13", "4, 5, 6", "6, 7, 8"], "5, 12, 13", "Check a² + b² = c².", "25 + 144 = 169 = 13²."),
     Q("HARD", "What is the smallest number to multiply 72 by to make it a perfect square?", [], "2", "72 = 2×2×2 × 3×3. Which prime has no pair?", "One 2 is unpaired, so multiply by 2 → 144 = 12².")]}]},
 {"name": "Science", "icon": "🔬", "chapters": [
  {"name": "Crop Production and Management",
   "explanation": "Crops are plants of the same kind grown on a large scale. In India, kharif crops such as rice and maize are sown in the rainy season, and rabi crops such as wheat and mustard are sown in winter. Farming involves several steps: preparing the soil by ploughing, sowing good-quality seeds, adding manure and fertilisers, irrigation, weeding to remove unwanted plants, harvesting, and safe storage of grains. Manure is organic and improves soil texture, while fertilisers are chemicals that supply specific nutrients.",
   "keyPoints": ["Kharif crops grow in the rainy season (rice, maize).",
                 "Rabi crops grow in winter (wheat, mustard).",
                 "Ploughing loosens the soil.",
                 "Manure is natural; fertilisers are chemical.",
                 "Weeding removes unwanted plants."],
   "examples": [EX("Steps of farming", "Plough → sow → manure → irrigate → weed → harvest → store.", "🚜 → 🌱 → 💧 → 🌾 → 🏚️"),
                EX("Irrigation", "Drip irrigation gives water drop by drop to roots and saves water."),
                EX("Storage", "Dried neem leaves are used to protect stored grain from insects.")],
   "activity": "Sprout some moong seeds in wet cloth and record their growth for five days.",
   "questions": [
     Q("EASY", "Which of these is a kharif crop?", ["Wheat", "Rice", "Mustard", "Gram"], "Rice", "It needs a lot of water.", "Rice is sown in the rainy season."),
     Q("EASY", "Loosening and turning the soil is called ___.", ["Sowing", "Ploughing", "Harvesting", "Weeding"], "Ploughing", "It is done with a plough or tractor.", "Ploughing (tilling) loosens the soil."),
     Q("MEDIUM", "Unwanted plants growing with a crop are called ___.", [], "weeds|weed", "They are removed by weeding.", "They are weeds."),
     Q("MEDIUM", "Which is an organic source of nutrients?", ["Urea", "Manure", "NPK", "Ammonium sulphate"], "Manure", "It comes from plant and animal waste.", "Manure is organic."),
     Q("HARD", "Which irrigation method saves the most water?", ["Flooding", "Drip irrigation", "Moat", "Chain pump"], "Drip irrigation", "Water is given drop by drop.", "Drip irrigation delivers water directly to roots."),
     Q("HARD", "Why are fields left fallow or crops rotated?", ["To make the soil fertile again", "To attract pests", "To save seeds", "To reduce sunlight"], "To make the soil fertile again", "Leguminous plants add nitrogen.", "Rotation and fallowing restore soil nutrients.")]},
  {"name": "Force and Pressure",
   "explanation": "A force is a push or a pull. Forces can make objects move, stop, change direction or change shape. Contact forces, such as muscular force and friction, need touch. Non-contact forces, such as magnetic, electrostatic and gravitational forces, act from a distance. Pressure is the force acting on a unit area: pressure = force ÷ area. The same force gives more pressure on a smaller area, which is why knives are sharp. Liquids and gases also exert pressure, and the air around us exerts atmospheric pressure.",
   "keyPoints": ["A force is a push or a pull.",
                 "Forces can change speed, direction or shape.",
                 "Friction and muscular force are contact forces.",
                 "Gravity and magnetism act without touching.",
                 "Pressure = force ÷ area."],
   "examples": [EX("Sharp knife", "A sharp edge has a tiny area, so the pressure is high and it cuts easily.", "🔪 small area → high pressure"),
                EX("Wide straps", "School bags have wide straps to spread the force and reduce pressure on shoulders.", "🎒"),
                EX("Non-contact", "A magnet pulls an iron pin without touching it.", "🧲 ← 📌")],
   "activity": "Press your palm and then your fingertip into soft clay with the same force. Which makes a deeper mark?",
   "questions": [
     Q("EASY", "A force is a ___.", ["Push or pull", "Colour", "Sound", "Smell"], "Push or pull", "Think of opening a door.", "Every force is a push or a pull."),
     Q("EASY", "Which is a non-contact force?", ["Friction", "Muscular force", "Magnetic force", "Pushing a cart"], "Magnetic force", "It acts from a distance.", "Magnets attract without touching."),
     Q("MEDIUM", "Pressure = ___.", ["Force × area", "Force ÷ area", "Area ÷ force", "Force + area"], "Force ÷ area", "Smaller area means more pressure.", "Pressure is force per unit area."),
     Q("MEDIUM", "A force of 100 N acts on an area of 2 m². What is the pressure in N/m²?", [], "50|50 n/m²|50 pa", "Divide force by area.", "100 ÷ 2 = 50 N/m²."),
     Q("HARD", "Why do camels walk easily on sand?", ["Their feet are wide, so pressure is less", "They are light", "Sand is hard", "They walk fast"], "Their feet are wide, so pressure is less", "Think of area and pressure.", "Large feet spread the weight over a big area."),
     Q("HARD", "The force that opposes motion between two surfaces is ___.", [], "friction", "It makes a rolling ball slow down.", "Friction opposes relative motion.")]},
  {"name": "Microorganisms: Friend and Foe",
   "explanation": "Microorganisms are living things too small to be seen without a microscope. The main groups are bacteria, fungi, protozoa, algae and viruses. Many are useful: yeast makes bread rise, bacteria turn milk into curd, and some microbes make medicines called antibiotics. Some bacteria in the roots of pea plants fix nitrogen and make the soil fertile. Harmful microbes called pathogens cause diseases such as cholera, typhoid and malaria. Food can be preserved from microbes by heating, refrigeration, salting and using preservatives.",
   "keyPoints": ["Microorganisms are too small to see without a microscope.",
                 "Groups: bacteria, fungi, protozoa, algae and viruses.",
                 "Yeast makes bread rise; bacteria make curd.",
                 "Pathogens cause diseases.",
                 "Cooling, salting and heating preserve food."],
   "examples": [EX("Curd", "Lactobacillus bacteria change milk into curd.", "🥛 + 🦠 → curd"),
                EX("Antibiotic", "Penicillin, made from a fungus, kills disease-causing bacteria.", "💊"),
                EX("Disease", "The malaria parasite (a protozoan) is carried by female Anopheles mosquitoes.", "🦟")],
   "activity": "Keep one slice of bread in the fridge and one outside for four days. Compare them.",
   "questions": [
     Q("EASY", "Which microorganism helps make bread rise?", ["Yeast", "Virus", "Algae", "Protozoa"], "Yeast", "It is a fungus used in baking.", "Yeast releases carbon dioxide that makes dough rise."),
     Q("EASY", "Milk changes into curd because of ___.", ["Viruses", "Bacteria", "Algae", "Insects"], "Bacteria", "Lactobacillus.", "Lactobacillus bacteria turn milk into curd."),
     Q("MEDIUM", "Disease-causing microorganisms are called ___.", [], "pathogens|pathogen", "It starts with 'patho-'.", "Pathogens cause disease."),
     Q("MEDIUM", "Malaria is spread by ___.", ["Housefly", "Female Anopheles mosquito", "Cockroach", "Dog"], "Female Anopheles mosquito", "It bites at night.", "The female Anopheles mosquito carries the malaria parasite."),
     Q("HARD", "Which bacterium fixes nitrogen in the roots of legumes?", ["Rhizobium", "Lactobacillus", "Yeast", "Plasmodium"], "Rhizobium", "Its name contains 'rhizo', meaning root.", "Rhizobium lives in root nodules and fixes nitrogen."),
     Q("HARD", "Antibiotics do NOT work against ___.", ["Bacteria", "Viruses", "Bacterial infections", "Typhoid"], "Viruses", "Colds and flu are caused by these.", "Antibiotics kill bacteria but not viruses.")]}]},
 {"name": "English", "icon": "📖", "chapters": [
  {"name": "Reported Speech",
   "explanation": "Direct speech gives a speaker's exact words inside quotation marks: Riya said, 'I am tired.' Reported (indirect) speech tells what someone said without quoting them: Riya said that she was tired. When the reporting verb is in the past, we usually move the tense one step back: am/is becomes was, will becomes would, and the simple past becomes the past perfect. Pronouns and time words also change, for example 'today' becomes 'that day' and 'tomorrow' becomes 'the next day'.",
   "keyPoints": ["Direct speech uses the exact words in quotes.",
                 "Reported speech tells what was said, without quotes.",
                 "Move the tense one step back: is → was.",
                 "will → would; can → could.",
                 "Change pronouns and time words: today → that day."],
   "examples": [EX("Statement", "He said, 'I like tea.' → He said that he liked tea."),
                EX("Question", "She asked, 'Where do you live?' → She asked where I lived."),
                EX("Command", "The teacher said, 'Sit down.' → The teacher told us to sit down.")],
   "activity": "Write down three things a family member said today, then change them into reported speech.",
   "questions": [
     Q("EASY", "Which sentence is in direct speech?", ["She said that she was happy.", "She said, 'I am happy.'", "She told me she was happy.", "She was happy."], "She said, 'I am happy.'", "Look for quotation marks.", "Direct speech quotes the exact words."),
     Q("EASY", "In reported speech, 'is' usually changes to ___.", ["are", "was", "will", "be"], "was", "Move the tense one step back.", "Present 'is' becomes past 'was'."),
     Q("MEDIUM", "He said, 'I will come.' → He said that he ___ come.", ["will", "would", "can", "shall"], "would", "'Will' moves back.", "will → would."),
     Q("MEDIUM", "In reported speech, 'tomorrow' becomes ___.", ["yesterday", "the next day", "today", "now"], "the next day", "The day after the speaking day.", "tomorrow → the next day."),
     Q("HARD", "She asked, 'Are you ready?' → She asked ___.", ["if I was ready", "are you ready", "that I am ready", "if was I ready"], "if I was ready", "Yes/no questions use 'if' or 'whether'.", "She asked if I was ready."),
     Q("HARD", "Mother said, 'Close the door.' → Mother ___ me to close the door.", ["said", "told", "asked that", "says"], "told", "Commands use 'told' or 'asked' + 'to'.", "Mother told me to close the door.")]},
  {"name": "Modal Verbs",
   "explanation": "Modal verbs are helping verbs that show ability, permission, possibility, advice or obligation. Can and could show ability (I can swim). May and can show permission (May I come in?). Might and may show possibility (It might rain). Should gives advice (You should rest). Must shows strong obligation or certainty (You must wear a helmet). After a modal verb we always use the base form of the main verb, without 'to' and without -s.",
   "keyPoints": ["Modals: can, could, may, might, should, must, will, would.",
                 "can/could = ability.",
                 "may = permission or possibility.",
                 "should = advice; must = obligation.",
                 "Modal + base verb: she can swim (not swims)."],
   "examples": [EX("Ability", "My brother can ride a bicycle."),
                EX("Advice", "You should drink more water."),
                EX("Obligation", "Students must wear their ID cards.", "⚠️ must")],
   "activity": "Write five school rules using 'must', 'should' and 'may'.",
   "questions": [
     Q("EASY", "Which word is a modal verb?", ["run", "should", "happy", "table"], "should", "It helps the main verb.", "'Should' is a modal verb."),
     Q("EASY", "___ I borrow your pen?", ["May", "Must", "Should", "Would have"], "May", "This asks for permission politely.", "'May' is used for polite permission."),
     Q("MEDIUM", "Which sentence is correct?", ["She can sings.", "She can sing.", "She can to sing.", "She cans sing."], "She can sing.", "Use the base verb after a modal.", "Modal + base form: can sing."),
     Q("MEDIUM", "You look ill. You ___ see a doctor.", ["should", "might", "can", "would"], "should", "This is advice.", "'Should' gives advice."),
     Q("HARD", "Which modal shows strong obligation?", ["might", "may", "must", "could"], "must", "Rules often use it.", "'Must' shows obligation."),
     Q("HARD", "Take an umbrella; it ___ rain later.", ["must", "might", "should", "can't"], "might", "It is only a possibility.", "'Might' shows possibility.")]},
  {"name": "Subject–Verb Agreement",
   "explanation": "The verb in a sentence must agree with its subject in number. A singular subject takes a singular verb (She plays), and a plural subject takes a plural verb (They play). Two subjects joined by 'and' are plural. With 'either…or' and 'neither…nor', the verb agrees with the nearer subject. Words like everyone, each and nobody are singular. Phrases between the subject and the verb, such as 'along with' or 'as well as', do not change the subject.",
   "keyPoints": ["Singular subject → singular verb.",
                 "Plural subject → plural verb.",
                 "A and B → plural verb.",
                 "Everyone, each, nobody → singular verb.",
                 "Neither…nor: the verb agrees with the nearer subject."],
   "examples": [EX("Basic", "The dog barks. The dogs bark."),
                EX("Everyone", "Everyone is happy today."),
                EX("Neither…nor", "Neither the teacher nor the students were late.")],
   "activity": "Find five sentences in a newspaper and check whether each subject and verb agree.",
   "questions": [
     Q("EASY", "The boy ___ football.", ["play", "plays"], "plays", "The subject is singular.", "Singular subject: plays."),
     Q("EASY", "The girls ___ singing.", ["is", "are"], "are", "The subject is plural.", "Plural subject: are."),
     Q("MEDIUM", "Everyone ___ invited to the party.", ["are", "is", "were", "have"], "is", "'Everyone' is singular.", "Everyone is invited."),
     Q("MEDIUM", "Ravi and Meena ___ friends.", ["is", "are", "was", "has"], "are", "Two people joined by 'and'.", "Ravi and Meena are friends."),
     Q("HARD", "Neither the players nor the coach ___ happy.", ["was", "were", "are", "have been"], "was", "Look at the subject nearest the verb.", "'The coach' is singular and nearer, so 'was'."),
     Q("HARD", "The teacher, along with her students, ___ going on a trip.", ["are", "is", "were", "have"], "is", "'Along with her students' does not change the subject.", "The subject is 'the teacher', so 'is'.")]}]},
 {"name": "Social Science", "icon": "🌍", "chapters": [
  {"name": "Resources",
   "explanation": "Anything that can be used to meet our needs and has value is a resource. Natural resources come from nature, such as air, water, soil and minerals. Renewable resources, like solar energy and wind, are replenished quickly. Non-renewable resources, like coal and petroleum, are limited and may run out. Human-made resources, such as buildings and machines, are made by people using natural resources. Human resource means people with knowledge and skills. Using resources carefully so they last for future generations is called sustainable development.",
   "keyPoints": ["A resource is anything useful with value.",
                 "Renewable resources are quickly replenished.",
                 "Non-renewable resources can run out.",
                 "People with skills are human resources.",
                 "Sustainable development saves resources for the future."],
   "examples": [EX("Renewable", "Sunlight and wind will not run out.", "☀️ 🌬️"),
                EX("Non-renewable", "Coal takes millions of years to form, so it is limited.", "⛏️"),
                EX("Human-made", "A dam is made by people to use river water.", "🏗️")],
   "activity": "Make a list of ways your family can save water and electricity.",
   "questions": [
     Q("EASY", "Which is a renewable resource?", ["Coal", "Petroleum", "Solar energy", "Natural gas"], "Solar energy", "The Sun keeps shining.", "Solar energy is renewable."),
     Q("EASY", "Which is a human-made resource?", ["River", "Building", "Forest", "Soil"], "Building", "People build it.", "Buildings are human-made."),
     Q("MEDIUM", "Resources that may run out are called ___ resources.", ["Renewable", "Non-renewable", "Human", "Unlimited"], "Non-renewable", "'Non' means not.", "They are non-renewable."),
     Q("MEDIUM", "People with knowledge and skills are called ___ resources.", [], "human", "They are people.", "They are human resources."),
     Q("HARD", "Using resources carefully so they last for future generations is called ___.", ["Sustainable development", "Industrialisation", "Mining", "Globalisation"], "Sustainable development", "It 'sustains' resources.", "That is sustainable development."),
     Q("HARD", "Why is technology considered important for resources?", ["It turns substances into useful resources", "It destroys all resources", "It is a natural resource", "It has no value"], "It turns substances into useful resources", "Think of how water becomes electricity.", "Technology and knowledge give substances value.")]},
  {"name": "Agriculture",
   "explanation": "Agriculture means growing crops and rearing animals. It is a primary activity because it uses natural resources directly. Farming depends on soil, climate, water and the slope of the land. Subsistence farming is done to meet the needs of the farmer's family, often with simple tools. Commercial farming grows crops on a large scale to sell, using machines and more inputs. Major crops include rice, wheat, cotton, jute and tea. Plantation agriculture grows a single crop like tea or coffee on a large estate.",
   "keyPoints": ["Agriculture is growing crops and rearing animals.",
                 "It is a primary activity.",
                 "Subsistence farming feeds the farmer's family.",
                 "Commercial farming grows crops to sell.",
                 "Plantations grow one crop like tea or coffee."],
   "examples": [EX("Subsistence", "A small family farm grows rice and vegetables for home use.", "🏡 🌾"),
                EX("Commercial", "A large farm uses tractors to grow wheat for the market.", "🚜 💰"),
                EX("Plantation", "Tea estates in Assam grow only tea.", "🍵")],
   "activity": "Visit a vegetable market and note which crops come from nearby farms.",
   "questions": [
     Q("EASY", "Growing crops and rearing animals is called ___.", ["Industry", "Agriculture", "Trade", "Mining"], "Agriculture", "Think of farms.", "That is agriculture."),
     Q("EASY", "Agriculture is a ___ activity.", ["Primary", "Secondary", "Tertiary"], "Primary", "It uses nature directly.", "Agriculture is primary."),
     Q("MEDIUM", "Farming done mainly to feed the farmer's family is ___ farming.", ["Commercial", "Subsistence", "Plantation", "Industrial"], "Subsistence", "'Subsist' means to survive.", "That is subsistence farming."),
     Q("MEDIUM", "Tea and coffee are usually grown on ___.", ["Plantations", "Rooftops", "Deserts", "Glaciers"], "Plantations", "Large estates with one crop.", "They are plantation crops."),
     Q("HARD", "Which is a fibre crop?", ["Rice", "Wheat", "Jute", "Tea"], "Jute", "It is used for sacks and ropes.", "Jute is a fibre crop, called the golden fibre."),
     Q("HARD", "Which factor does NOT directly affect farming?", ["Soil", "Climate", "Water", "Television"], "Television", "Think about what plants need.", "Soil, climate and water affect farming.")]},
  {"name": "The Indian Constitution",
   "explanation": "A constitution is a set of rules that tells how a country is governed. The Constitution of India came into effect on 26 January 1950, which we celebrate as Republic Day. Dr B. R. Ambedkar was the chairman of the Drafting Committee. The Constitution makes India a democracy where people elect their representatives. It gives citizens Fundamental Rights, such as the Right to Equality and the Right to Freedom, and also lists Fundamental Duties. It divides power between the central government and the states, and separates the legislature, executive and judiciary.",
   "keyPoints": ["A constitution is a country's rule book.",
                 "India's Constitution began on 26 January 1950.",
                 "Dr B. R. Ambedkar chaired the Drafting Committee.",
                 "It gives Fundamental Rights and Duties.",
                 "Power is shared between centre and states."],
   "examples": [EX("Republic Day", "Every 26 January we celebrate the day the Constitution came into force.", "🇮🇳"),
                EX("A Fundamental Right", "Right to Education: children aged 6–14 get free and compulsory education."),
                EX("Separation of powers", "Parliament makes laws, the government carries them out, and the courts interpret them.")],
   "activity": "Read the Preamble of the Constitution and list the values it mentions.",
   "questions": [
     Q("EASY", "When did India's Constitution come into effect?", ["15 August 1947", "26 January 1950", "2 October 1869", "26 November 1949"], "26 January 1950", "It is celebrated as Republic Day.", "It came into force on 26 January 1950."),
     Q("EASY", "Who chaired the Drafting Committee of the Constitution?", ["Mahatma Gandhi", "Dr B. R. Ambedkar", "Jawaharlal Nehru", "Sardar Patel"], "Dr B. R. Ambedkar", "He is called the architect of the Constitution.", "Dr Ambedkar chaired the committee."),
     Q("MEDIUM", "Which is a Fundamental Right?", ["Right to Equality", "Right to a car", "Right to free phones", "Right to not pay taxes"], "Right to Equality", "Everyone is equal before law.", "Right to Equality is a Fundamental Right."),
     Q("MEDIUM", "The branch of government that makes laws is the ___.", ["Judiciary", "Legislature", "Executive", "Police"], "Legislature", "Parliament is part of it.", "The legislature makes laws."),
     Q("HARD", "Dividing powers between the centre and states is called ___.", ["Federalism", "Monarchy", "Dictatorship", "Secularism"], "Federalism", "It comes from 'federation'.", "Power-sharing between levels is federalism."),
     Q("HARD", "A state that treats all religions equally and has no official religion is ___.", [], "secular", "It is in the Preamble.", "India is a secular state.")]}]}]}
