# Additional chapters for Grade 8.
from grade6 import Q, EX
from more6_7 import CH

MORE8 = {
 "Mathematics": [
  CH("Comparing Quantities",
     "Percent means 'per hundred', so 25% means 25 out of 100. To find a percentage of a number, multiply the number by the percentage and divide by 100. In buying and selling, if the selling price is more than the cost price there is a profit, and if it is less there is a loss. Profit % = (profit ÷ cost price) × 100. A discount is a reduction on the marked price. Simple interest is SI = (P × R × T) ÷ 100, where P is the principal, R the rate and T the time in years.",
     ["Percent means 'out of 100'.",
      "x% of N = N × x ÷ 100.",
      "Profit = selling price − cost price.",
      "Profit % = profit ÷ cost price × 100.",
      "Simple interest = P × R × T ÷ 100."],
     [EX("Percentage", "20% of 150 = 150 × 20 ÷ 100 = 30.", "▓▓░░░░░░░░ 20%"),
      EX("Profit", "Bought for ₹80, sold for ₹100: profit ₹20, profit % = 20/80 × 100 = 25%."),
      EX("Discount", "A ₹500 shirt with 10% off costs ₹450.", "🏷️ ₹500 → ₹450")],
     "Look at price tags in a shop or online and work out how much you save with each discount.",
     [Q("EASY", "What is 50% of 80?", [], "40", "50% is half.", "80 × 50 ÷ 100 = 40."),
      Q("EASY", "Cost ₹60, sold for ₹75. What is the profit (₹)?", [], "15", "Selling price − cost price.", "75 − 60 = ₹15."),
      Q("MEDIUM", "What is 15% of 200?", [], "30", "200 × 15 ÷ 100.", "30."),
      Q("MEDIUM", "A ₹400 bag has a 25% discount. What is the sale price (₹)?", [], "300", "25% of 400 is 100.", "400 − 100 = ₹300."),
      Q("HARD", "Simple interest on ₹1000 at 5% per year for 3 years (₹)?", [], "150", "P × R × T ÷ 100.", "1000 × 5 × 3 ÷ 100 = ₹150."),
      Q("HARD", "Bought for ₹250, sold for ₹200. What is the loss %?", [], "20|20%", "Loss ÷ cost × 100.", "50 ÷ 250 × 100 = 20%.")]),
  CH("Exponents and Powers",
     "An exponent tells how many times a number is multiplied by itself: 2⁴ = 2 × 2 × 2 × 2 = 16. The number 2 is the base and 4 is the exponent. Laws of exponents: aᵐ × aⁿ = aᵐ⁺ⁿ, aᵐ ÷ aⁿ = aᵐ⁻ⁿ, (aᵐ)ⁿ = aᵐⁿ, and a⁰ = 1. A negative exponent means the reciprocal: a⁻ⁿ = 1/aⁿ. Very large or very small numbers are written in standard form, like 3.2 × 10⁵ or 4.5 × 10⁻³.",
     ["An exponent shows repeated multiplication.",
      "aᵐ × aⁿ = aᵐ⁺ⁿ.",
      "aᵐ ÷ aⁿ = aᵐ⁻ⁿ.",
      "a⁰ = 1 (for a ≠ 0).",
      "a⁻ⁿ = 1/aⁿ."],
     [EX("Power", "3³ = 3 × 3 × 3 = 27.", "3 × 3 × 3 = 27"),
      EX("Laws", "5² × 5³ = 5⁵; 7⁶ ÷ 7² = 7⁴."),
      EX("Standard form", "The distance to the Sun, about 150,000,000 km, is 1.5 × 10⁸ km.", "☀️ ──── 1.5 × 10⁸ km ──── 🌍")],
     "Write the populations of three cities in standard form.",
     [Q("EASY", "What is 2⁵?", [], "32", "2 × 2 × 2 × 2 × 2.", "2⁵ = 32."),
      Q("EASY", "What is 9⁰?", [], "1", "Any non-zero number to the power 0.", "9⁰ = 1."),
      Q("MEDIUM", "3² × 3⁴ = 3^?", [], "6", "Add the exponents.", "2 + 4 = 6."),
      Q("MEDIUM", "What is 2⁻³ as a fraction?", ["1/8", "−8", "−6", "8"], "1/8", "Negative exponent means reciprocal.", "2⁻³ = 1/2³ = 1/8."),
      Q("HARD", "Write 45,000 in standard form.", ["4.5 × 10⁴", "45 × 10³", "4.5 × 10³", "0.45 × 10⁵"], "4.5 × 10⁴", "Move the decimal so there is one digit before it.", "45,000 = 4.5 × 10⁴."),
      Q("HARD", "(2³)² = ?", [], "64", "(aᵐ)ⁿ = aᵐⁿ.", "2⁶ = 64.")])],
 "Science": [
  CH("Metals and Non-metals",
     "Metals such as iron, copper and aluminium are usually shiny (lustrous), hard, and good conductors of heat and electricity. They are malleable, which means they can be beaten into thin sheets, and ductile, which means they can be drawn into wires. Many metals make a ringing sound when struck (sonorous). Non-metals such as sulphur, carbon and oxygen are usually dull, brittle and poor conductors. Metals react with oxygen to form basic oxides, while non-metals form acidic oxides. A more reactive metal can displace a less reactive metal from its salt solution.",
     ["Metals are shiny, hard and conduct heat and electricity.",
      "Malleable: can be beaten into sheets.",
      "Ductile: can be drawn into wires.",
      "Non-metals are dull, brittle and poor conductors.",
      "Metal oxides are basic; non-metal oxides are acidic."],
     [EX("Malleable", "Aluminium is beaten into thin foil to wrap food.", "🔨 → ▭ foil"),
      EX("Ductile", "Copper is drawn into thin wires for electric cables."),
      EX("Displacement", "An iron nail in blue copper sulphate solution turns brown as iron pushes out copper.")],
     "Collect five objects and sort them into metals and non-metals by testing shine and sound.",
     [Q("EASY", "Which is a metal?", ["Sulphur", "Carbon", "Copper", "Oxygen"], "Copper", "It is used in wires.", "Copper is a metal."),
      Q("EASY", "Metals can be beaten into thin sheets. This property is called ___.", ["Malleability", "Ductility", "Brittleness", "Sonority"], "Malleability", "Think of aluminium foil.", "It is malleability."),
      Q("MEDIUM", "Drawing metals into wires is called ___.", [], "ductility", "Wires are long and thin.", "This is ductility."),
      Q("MEDIUM", "Oxides of non-metals are usually ___.", ["Acidic", "Basic", "Neutral always", "Metallic"], "Acidic", "They turn blue litmus red.", "Non-metal oxides are acidic."),
      Q("HARD", "Which non-metal is a good conductor of electricity?", ["Graphite", "Sulphur", "Phosphorus", "Iodine"], "Graphite", "It is used in pencil 'leads' and batteries.", "Graphite (a form of carbon) conducts electricity."),
      Q("HARD", "Why does an iron nail placed in copper sulphate solution turn brown?", ["Iron displaces copper, which coats the nail", "The nail rusts instantly", "Copper sulphate is brown", "Iron dissolves completely"], "Iron displaces copper, which coats the nail", "Iron is more reactive than copper.", "More reactive iron pushes copper out of the solution.")]),
  CH("Sound",
     "Sound is produced by vibrating objects. It needs a medium — a solid, liquid or gas — to travel, so it cannot travel through a vacuum. In humans, sound is produced by the vibration of the vocal cords in the voice box (larynx), and we hear when sound makes the eardrum vibrate. The number of vibrations per second is the frequency, measured in hertz (Hz). A higher frequency gives a higher pitch, and a bigger amplitude gives a louder sound. Humans can hear roughly 20 Hz to 20,000 Hz. Unwanted loud sound is noise, which causes noise pollution.",
     ["Sound is made by vibrations.",
      "Sound needs a medium; it cannot travel in a vacuum.",
      "Frequency is vibrations per second (Hz).",
      "Higher frequency = higher pitch; bigger amplitude = louder.",
      "Humans hear about 20 Hz to 20,000 Hz."],
     [EX("Vibrations", "Pluck a stretched rubber band — it vibrates and you hear a sound.", "〰️〰️ 🔊"),
      EX("No sound in space", "Astronauts use radios because sound cannot travel through empty space.", "🚀 🔇"),
      EX("Pitch", "A whistle has a high pitch; a lion's roar has a low pitch.")],
     "Fill glasses with different amounts of water, tap them with a spoon and compare the pitch.",
     [Q("EASY", "Sound is produced by ___.", ["Vibrations", "Light", "Magnets", "Heat"], "Vibrations", "Touch your throat while humming.", "Vibrating objects produce sound."),
      Q("EASY", "Can sound travel through a vacuum?", ["Yes", "No"], "No", "It needs a medium.", "Sound needs particles to travel through."),
      Q("MEDIUM", "The unit of frequency is the ___.", ["Hertz", "Newton", "Metre", "Decibel"], "Hertz", "Symbol Hz.", "Frequency is measured in hertz."),
      Q("MEDIUM", "In humans, sound is produced by the ___.", ["Vocal cords", "Eardrum", "Lungs only", "Teeth"], "Vocal cords", "They are in the larynx.", "Vocal cords vibrate to make sound."),
      Q("HARD", "A higher frequency produces a ___ pitch.", ["Higher", "Lower", "Same", "Silent"], "Higher", "Think of a whistle.", "Pitch increases with frequency."),
      Q("HARD", "The loudness of sound depends on its ___.", ["Amplitude", "Frequency only", "Colour", "Speed"], "Amplitude", "Bigger vibrations are louder.", "Loudness depends on amplitude.")])],
 "English": [
  CH("Phrasal Verbs",
     "A phrasal verb is a verb combined with a small word such as up, off, out or on, which together have a new meaning. For example, 'give up' means to stop trying, 'look after' means to take care of, and 'put off' means to postpone. The meaning of a phrasal verb is often different from the meanings of its separate words, so it is best learned in context. Phrasal verbs are common in everyday English.",
     ["A phrasal verb = verb + small word (up, off, out, on).",
      "The meaning is often new and different.",
      "'give up' = stop trying.",
      "'look after' = take care of.",
      "'put off' = postpone."],
     [EX("In a sentence", "Please turn off the lights when you leave.", "💡 → ⚫"),
      EX("Look after", "She looks after her little brother after school."),
      EX("Run out of", "We ran out of milk, so I went to the shop.", "🥛 empty")],
     "Write a short story of five sentences using five different phrasal verbs.",
     [Q("EASY", "'Give up' means ___.", ["Stop trying", "Give a gift", "Go upstairs", "Wake up"], "Stop trying", "Never ___ on your dreams!", "'Give up' means to stop trying."),
      Q("EASY", "Please ___ the TV; it is too loud.", ["turn down", "turn up", "look after", "give up"], "turn down", "Make it quieter.", "'Turn down' reduces the volume."),
      Q("MEDIUM", "'Look after' means ___.", ["Take care of", "Look behind", "Search for", "Forget"], "Take care of", "A nurse does this for patients.", "It means to take care of."),
      Q("MEDIUM", "The match was ___ because of rain.", ["put off", "put on", "taken off", "looked up"], "put off", "It was postponed.", "'Put off' means postpone."),
      Q("HARD", "'I came across an old photo.' 'Came across' means ___.", ["Found by chance", "Crossed a road", "Lost", "Painted"], "Found by chance", "It was unexpected.", "'Come across' means to find by chance."),
      Q("HARD", "We have ___ sugar; please buy some.", ["run out of", "run into", "run over", "run after"], "run out of", "None is left.", "'Run out of' means to have none left.")]),
  CH("Prefixes and Suffixes",
     "A prefix is added to the beginning of a word to change its meaning, such as un- in unhappy (not happy), re- in rewrite (write again) and pre- in preview (see before). A suffix is added to the end of a word and often changes its word class, such as -ness in kindness (noun), -ful in helpful (adjective), -ly in quickly (adverb) and -er in teacher (a person who teaches). Knowing prefixes and suffixes helps us understand and build new words.",
     ["A prefix goes at the beginning of a word.",
      "un-, dis-, im- often mean 'not'.",
      "re- means 'again'; pre- means 'before'.",
      "A suffix goes at the end of a word.",
      "-ful, -ness, -ly, -er change the kind of word."],
     [EX("Prefix", "happy → unhappy; possible → impossible; agree → disagree.", "un + happy"),
      EX("Suffix", "kind → kindness; care → careful; quick → quickly."),
      EX("Both", "un + help + ful = unhelpful.")],
     "Make a word web: start with 'use' and add as many prefixes and suffixes as you can.",
     [Q("EASY", "Add a prefix to make the opposite of 'happy'.", [], "unhappy", "It means 'not happy'.", "un + happy = unhappy."),
      Q("EASY", "'Rewrite' means ___.", ["Write again", "Not write", "Write before", "Stop writing"], "Write again", "'re-' means again.", "Rewrite means to write again."),
      Q("MEDIUM", "Which suffix makes 'kind' into a noun?", ["-ness", "-ly", "-ful", "-er"], "-ness", "kind → kind___", "kindness is a noun."),
      Q("MEDIUM", "The opposite of 'possible' is ___.", ["impossible", "unpossible", "dispossible", "inpossible"], "impossible", "Before 'p', use im-.", "im + possible = impossible."),
      Q("HARD", "Which word has both a prefix and a suffix?", ["unhelpful", "helpful", "help", "unhelp"], "unhelpful", "Look at the beginning and the end.", "un + help + ful."),
      Q("HARD", "'Preview' means ___.", ["See before", "See again", "Not see", "See after"], "See before", "'pre-' means before.", "Preview means to see beforehand.")])],
 "Social Science": [
  CH("Industries",
     "Industries are economic activities that turn raw materials into more useful products, such as cotton into cloth or iron ore into steel. They are secondary activities. Industries can be classified by raw material (agro-based like cotton textiles, mineral-based like iron and steel), by size (small-scale and large-scale) and by ownership (private, public, joint and cooperative). Factors such as raw materials, land, water, labour, power, capital, transport and markets decide where an industry is located. Places like Jamshedpur (steel) and Bengaluru (information technology) are famous industrial centres.",
     ["Industries turn raw materials into products.",
      "Manufacturing is a secondary activity.",
      "Agro-based industries use farm products.",
      "Industries can be private, public, joint or cooperative.",
      "Raw materials, power, labour and markets affect location."],
     [EX("Cotton to cloth", "Cotton from farms → spinning → weaving → shirts in shops.", "🌱 → 🧶 → 👕"),
      EX("Steel city", "Jamshedpur grew near iron ore, coal and water, which the steel industry needs."),
      EX("IT industry", "Bengaluru has many software companies — it is called the Silicon Valley of India.", "💻")],
     "List five products in your home and find out which industry makes each one.",
     [Q("EASY", "Turning raw materials into useful products is called ___.", ["Manufacturing", "Farming", "Mining", "Fishing"], "Manufacturing", "It happens in factories.", "That is manufacturing."),
      Q("EASY", "A cotton textile mill is a(n) ___ industry.", ["Agro-based", "Mineral-based", "Marine-based", "Forest-based"], "Agro-based", "Cotton is a farm product.", "It uses a farm raw material."),
      Q("MEDIUM", "Industries owned by the government are ___ sector industries.", ["Public", "Private", "Joint", "Cooperative"], "Public", "They belong to the public.", "Government-owned industries are public sector."),
      Q("MEDIUM", "Which city is famous for its steel industry?", ["Jamshedpur", "Shimla", "Goa", "Ooty"], "Jamshedpur", "It is in Jharkhand.", "Jamshedpur is known as the steel city."),
      Q("HARD", "Which is NOT a factor for locating an industry?", ["Availability of raw materials", "Power supply", "Market", "The colour of the factory"], "The colour of the factory", "Think of what the industry needs.", "Colour does not affect location."),
      Q("HARD", "Which city is called the Silicon Valley of India?", ["Bengaluru", "Kolkata", "Jaipur", "Patna"], "Bengaluru", "Many IT companies are there.", "Bengaluru is India's IT hub.")]),
  CH("The Judiciary",
     "The judiciary is the system of courts that interprets laws and settles disputes. In India it is independent, which means the government and legislature cannot control its decisions. India has a three-level court system: the Supreme Court at the top in New Delhi, High Courts in the states, and District Courts at the district level. Civil law deals with disputes such as property or divorce, and criminal law deals with offences such as theft. The judiciary protects Fundamental Rights, and citizens can approach the courts through Public Interest Litigation (PIL) on issues affecting the public.",
     ["The judiciary is the system of courts.",
      "It interprets laws and settles disputes.",
      "India's judiciary is independent.",
      "Supreme Court → High Courts → District Courts.",
      "PIL lets citizens raise issues of public interest."],
     [EX("Court levels", "A case may start in a District Court, then go to the High Court, and finally to the Supreme Court.", "🏛️ Supreme\n   ⬆\n🏢 High\n   ⬆\n🏠 District"),
      EX("Civil vs criminal", "A dispute over land is civil; a robbery is criminal."),
      EX("PIL", "Citizens filed a PIL asking for cleaner rivers, and the court ordered action.")],
     "Read a news story about a court judgment and explain it to your family in simple words.",
     [Q("EASY", "The highest court in India is the ___.", ["Supreme Court", "High Court", "District Court", "Parliament"], "Supreme Court", "It is in New Delhi.", "The Supreme Court is the highest."),
      Q("EASY", "The system of courts is called the ___.", [], "judiciary", "Judges work in it.", "It is the judiciary."),
      Q("MEDIUM", "A dispute about property is a ___ case.", ["Civil", "Criminal"], "Civil", "No crime is involved.", "Property disputes are civil cases."),
      Q("MEDIUM", "What does 'independence of the judiciary' mean?", ["Courts are not controlled by the government or legislature", "Judges are elected every year", "Courts make all laws", "Courts collect taxes"], "Courts are not controlled by the government or legislature", "Judges must be fair.", "Courts decide freely, without pressure."),
      Q("HARD", "PIL stands for ___.", ["Public Interest Litigation", "Private Income Law", "Police Inquiry Letter", "Public Information List"], "Public Interest Litigation", "It is about the public's interest.", "PIL = Public Interest Litigation."),
      Q("HARD", "Theft is dealt with under ___ law.", ["Criminal", "Civil", "Family", "Tax"], "Criminal", "It is an offence.", "Theft is a crime, so criminal law.")])],
}
