# Additional chapters for Grade 11.
from grade6 import Q, EX
from more6_7 import CH

MORE11 = {
 "Mathematics": [
  CH("Sequences and Series",
     "A sequence is an ordered list of numbers, and a series is the sum of its terms. In a geometric progression (GP), each term is obtained by multiplying the previous term by a fixed number called the common ratio r. The nth term is aₙ = a·rⁿ⁻¹. The sum of the first n terms is Sₙ = a(rⁿ − 1)/(r − 1) for r ≠ 1. If |r| < 1, the infinite GP has a finite sum S = a/(1 − r). The arithmetic mean of a and b is (a + b)/2 and the geometric mean is √(ab); AM ≥ GM for positive numbers.",
     ["In a GP, multiply by the common ratio r each time.",
      "nth term: aₙ = a·rⁿ⁻¹.",
      "Sum: Sₙ = a(rⁿ − 1)/(r − 1).",
      "Infinite sum S = a/(1 − r) when |r| < 1.",
      "AM ≥ GM for positive numbers."],
     [EX("GP", "2, 6, 18, 54, … has a = 2 and r = 3.", "2 ×3→ 6 ×3→ 18 ×3→ 54"),
      EX("Sum", "1 + 2 + 4 + 8 + 16 = 1(2⁵ − 1)/(2 − 1) = 31."),
      EX("Infinite sum", "1 + 1/2 + 1/4 + … = 1/(1 − 1/2) = 2.")],
     "Fold a sheet of paper in half repeatedly and record the number of layers — it forms a GP.",
     [Q("EASY", "Common ratio of 3, 6, 12, 24, …?", [], "2", "Divide a term by the previous one.", "6 ÷ 3 = 2."),
      Q("EASY", "Next term of 5, 15, 45, …?", [], "135", "Multiply by 3.", "45 × 3 = 135."),
      Q("MEDIUM", "6th term of 1, 2, 4, 8, …?", [], "32", "aₙ = a·rⁿ⁻¹.", "1 × 2⁵ = 32."),
      Q("MEDIUM", "Geometric mean of 4 and 9?", [], "6", "√(ab).", "√36 = 6."),
      Q("HARD", "Sum of the first 5 terms of 3, 6, 12, …?", [], "93", "Sₙ = a(rⁿ − 1)/(r − 1).", "3(32 − 1)/1 = 93."),
      Q("HARD", "Sum to infinity of 8 + 4 + 2 + 1 + …?", [], "16", "S = a/(1 − r), r = 1/2.", "8 ÷ (1/2) = 16.")]),
  CH("Straight Lines",
     "The slope (gradient) of a line through (x₁, y₁) and (x₂, y₂) is m = (y₂ − y₁)/(x₂ − x₁); it tells how steep the line is. Parallel lines have equal slopes, and perpendicular lines have slopes whose product is −1. The equation of a line can be written in slope–intercept form y = mx + c, where c is the y-intercept, or point–slope form y − y₁ = m(x − x₁). The distance between two points is √[(x₂ − x₁)² + (y₂ − y₁)²]. A horizontal line has slope 0 and a vertical line has an undefined slope.",
     ["Slope m = (y₂ − y₁)/(x₂ − x₁).",
      "Parallel lines have equal slopes.",
      "Perpendicular slopes multiply to −1.",
      "Slope–intercept form: y = mx + c.",
      "Horizontal line: slope 0; vertical line: undefined slope."],
     [EX("Slope", "Through (1, 2) and (3, 6): m = (6 − 2)/(3 − 1) = 2.", "  /\n /  rise 4\n/___ run 2"),
      EX("Equation", "Slope 3, y-intercept −1: y = 3x − 1."),
      EX("Perpendicular", "Slopes 2 and −1/2 are perpendicular because 2 × (−1/2) = −1.")],
     "Plot the points (0, 1), (1, 3) and (2, 5) on graph paper, join them, and find the slope.",
     [Q("EASY", "Slope of the line y = 4x + 7?", [], "4", "Compare with y = mx + c.", "m = 4."),
      Q("EASY", "y-intercept of y = 2x − 5?", [], "-5|−5", "c in y = mx + c.", "c = −5."),
      Q("MEDIUM", "Slope of the line through (2, 3) and (4, 11)?", [], "4", "(11 − 3)/(4 − 2).", "8/2 = 4."),
      Q("MEDIUM", "Slope of a line perpendicular to one with slope 3?", ["−1/3", "3", "1/3", "−3"], "−1/3", "Product of slopes = −1.", "3 × (−1/3) = −1."),
      Q("HARD", "Distance between (0, 0) and (6, 8)?", [], "10", "√(6² + 8²).", "√100 = 10."),
      Q("HARD", "Equation of the line with slope 2 through (1, 5)?", ["y = 2x + 3", "y = 2x + 5", "y = 5x + 2", "y = x + 4"], "y = 2x + 3", "y − 5 = 2(x − 1).", "y = 2x + 3.")])],
 "Physics": [
  CH("Work, Energy and Power",
     "Work done by a constant force is W = F·s·cos θ, where θ is the angle between force and displacement; no work is done if they are perpendicular. The work–energy theorem says the net work done on a body equals its change in kinetic energy. Kinetic energy is ½mv², and gravitational potential energy is mgh; the elastic potential energy of a spring is ½kx². When only conservative forces act, mechanical energy is conserved. Power is the rate of doing work, P = W/t = F·v. In an elastic collision, both momentum and kinetic energy are conserved; in an inelastic collision, only momentum is conserved.",
     ["W = F·s·cos θ.",
      "Work–energy theorem: net work = change in KE.",
      "Spring PE = ½kx².",
      "Power P = W/t = F·v.",
      "Elastic collision conserves both momentum and KE."],
     [EX("Angle matters", "Pulling a box with 10 N at 60° over 4 m: W = 10 × 4 × cos 60° = 20 J.", "📦 ←↖ 60°"),
      EX("Energy conservation", "A pendulum swaps PE and KE as it swings.", "⤺ PE ↔ KE ⤻"),
      EX("Collision", "Billiard balls collide almost elastically.", "🎱 → ⚪")],
     "Drop a ball from 1 m and measure the bounce height. What fraction of energy was lost?",
     [Q("EASY", "Work done when force and displacement are perpendicular?", [], "0|zero", "cos 90° = 0.", "No work is done."),
      Q("EASY", "The SI unit of power is the ___.", ["Watt", "Joule", "Newton", "Pascal"], "Watt", "1 J/s.", "Power is in watts."),
      Q("MEDIUM", "Force 20 N at 60° to a 5 m displacement. Work (J)?", [], "50", "W = F s cos θ.", "20 × 5 × 0.5 = 50 J."),
      Q("MEDIUM", "PE stored in a spring (k = 200 N/m) stretched 0.1 m (J)?", [], "1", "½kx².", "½ × 200 × 0.01 = 1 J."),
      Q("HARD", "A 2 kg body speeds up from 2 m/s to 4 m/s. Net work done (J)?", [], "12", "ΔKE = ½m(v² − u²).", "½ × 2 × (16 − 4) = 12 J."),
      Q("HARD", "In a perfectly inelastic collision, which is conserved?", ["Momentum only", "Kinetic energy only", "Both", "Neither"], "Momentum only", "The bodies stick together.", "Momentum is conserved; KE is not.")]),
  CH("Gravitation",
     "Newton's law of universal gravitation states F = G m₁m₂/r², where G = 6.67 × 10⁻¹¹ N m²/kg². The acceleration due to gravity at the Earth's surface is g = GM/R² ≈ 9.8 m/s²; it decreases with height and depth. Kepler's laws describe planetary motion: orbits are ellipses, a planet sweeps equal areas in equal times, and T² ∝ r³. Escape velocity, the minimum speed to leave Earth's gravity, is about 11.2 km/s. The orbital speed of a satellite close to Earth is about 7.9 km/s. A geostationary satellite has a period of 24 hours.",
     ["F = G m₁m₂/r².",
      "g = GM/R² ≈ 9.8 m/s² at the surface.",
      "Kepler's third law: T² ∝ r³.",
      "Escape velocity from Earth ≈ 11.2 km/s.",
      "Geostationary satellites have a 24-hour period."],
     [EX("Distance effect", "Doubling r makes the force 1/4 as strong."),
      EX("Satellites", "Communication satellites orbit in step with Earth's rotation, staying over one place.", "🌍 ⟲ 🛰️"),
      EX("Escape", "A rocket needs about 11.2 km/s to escape Earth's gravity.", "🚀 11.2 km/s")],
     "Use a string and two pins to draw an ellipse, like a planet's orbit.",
     [Q("EASY", "Escape velocity from Earth is about ___ km/s.", ["11.2", "7.9", "3", "30"], "11.2", "It's greater than orbital speed.", "About 11.2 km/s."),
      Q("EASY", "Planets move in ___ orbits (Kepler's first law).", ["Elliptical", "Square", "Straight", "Random"], "Elliptical", "Slightly stretched circles.", "Orbits are ellipses."),
      Q("MEDIUM", "If the distance between two masses triples, the force becomes ___.", ["1/9", "1/3", "3 times", "9 times"], "1/9", "F ∝ 1/r².", "1/3² = 1/9."),
      Q("MEDIUM", "The period of a geostationary satellite is ___ hours.", [], "24", "It matches Earth's rotation.", "24 hours."),
      Q("HARD", "Kepler's third law says T² is proportional to ___.", ["r³", "r²", "r", "1/r"], "r³", "Period and orbit radius.", "T² ∝ r³."),
      Q("HARD", "How does g change as we go higher above the Earth?", ["It decreases", "It increases", "It stays the same", "It becomes zero immediately"], "It decreases", "g = GM/(R + h)².", "g decreases with height.")])],
 "Chemistry": [
  CH("Classification of Elements and Periodicity",
     "The modern periodic law states that properties of elements are a periodic function of their atomic numbers. Elements are grouped into s-, p-, d- and f-blocks based on which orbital receives the last electron. Periodic trends include: atomic radius decreases across a period and increases down a group; ionisation enthalpy (energy to remove an electron) increases across a period and decreases down a group; electronegativity (tendency to attract shared electrons) increases across a period. Fluorine is the most electronegative element. Metallic character decreases across a period and increases down a group.",
     ["Properties repeat periodically with atomic number.",
      "Blocks: s, p, d, f.",
      "Atomic radius decreases across a period.",
      "Ionisation enthalpy increases across a period.",
      "Fluorine is the most electronegative element."],
     [EX("Blocks", "Group 1–2: s-block; groups 13–18: p-block; groups 3–12: d-block.", "s | d | p\n    f"),
      EX("Radius trend", "Na is larger than Cl, though both are in period 3."),
      EX("Noble gases", "Helium has the highest ionisation enthalpy — its shell is full.")],
     "Plot atomic radius against atomic number for the first 20 elements and look for the repeating pattern.",
     [Q("EASY", "The modern periodic law is based on ___.", ["Atomic number", "Atomic mass", "Density", "Colour"], "Atomic number", "Moseley's work.", "Properties depend on atomic number."),
      Q("EASY", "The most electronegative element is ___.", ["Fluorine", "Oxygen", "Chlorine", "Caesium"], "Fluorine", "Top right of the table (excluding noble gases).", "Fluorine is the most electronegative."),
      Q("MEDIUM", "Across a period, atomic radius ___.", ["Decreases", "Increases", "Stays the same"], "Decreases", "Nuclear charge increases.", "Radius decreases across a period."),
      Q("MEDIUM", "Group 1 and 2 elements belong to the ___-block.", [], "s", "The last electron enters an s orbital.", "They are s-block elements."),
      Q("HARD", "Down a group, ionisation enthalpy generally ___.", ["Decreases", "Increases", "Stays the same"], "Decreases", "Outer electrons are farther from the nucleus.", "It decreases down a group."),
      Q("HARD", "Transition elements belong to the ___-block.", ["d", "s", "p", "f"], "d", "Groups 3 to 12.", "They are d-block elements.")]),
  CH("Thermodynamics",
     "Thermodynamics studies energy changes. A system is the part being studied and the surroundings are everything else. The first law states that energy is conserved: ΔU = q + w. Enthalpy (H) is the heat content at constant pressure; ΔH is negative for exothermic reactions (heat released) and positive for endothermic reactions (heat absorbed). Entropy (S) measures disorder. A process is spontaneous when the Gibbs free energy change is negative: ΔG = ΔH − TΔS < 0. Hess's law says the total enthalpy change is the same whatever route the reaction takes.",
     ["First law: ΔU = q + w (energy is conserved).",
      "Exothermic: ΔH negative; endothermic: ΔH positive.",
      "Entropy measures disorder.",
      "Spontaneous when ΔG = ΔH − TΔS is negative.",
      "Hess's law: ΔH does not depend on the path."],
     [EX("Exothermic", "Burning fuel releases heat: ΔH < 0.", "🔥 → heat out"),
      EX("Endothermic", "Ice melting absorbs heat: ΔH > 0.", "🧊 ← heat in"),
      EX("Entropy", "Gas spreading through a room increases disorder.")],
     "Dissolve ammonium chloride (or glucose) in water and feel whether the glass gets colder or warmer.",
     [Q("EASY", "A reaction that releases heat is ___.", ["Exothermic", "Endothermic"], "Exothermic", "'Exo' means out.", "Heat out = exothermic."),
      Q("EASY", "Entropy is a measure of ___.", ["Disorder", "Mass", "Colour", "Pressure only"], "Disorder", "Randomness.", "Entropy measures disorder."),
      Q("MEDIUM", "For an endothermic reaction, ΔH is ___.", ["Positive", "Negative", "Zero"], "Positive", "Heat is absorbed.", "ΔH > 0."),
      Q("MEDIUM", "A process is spontaneous when ΔG is ___.", ["Negative", "Positive", "Zero always"], "Negative", "Gibbs energy decreases.", "ΔG < 0 means spontaneous."),
      Q("HARD", "ΔH = −100 kJ, TΔS = +20 kJ. ΔG = ? (kJ)", [], "-120|−120", "ΔG = ΔH − TΔS.", "−100 − 20 = −120 kJ."),
      Q("HARD", "Which law says the total enthalpy change is independent of the path?", ["Hess's law", "Boyle's law", "Charles's law", "Faraday's law"], "Hess's law", "Named after Germain Hess.", "Hess's law of constant heat summation.")])],
 "Biology": [
  CH("Respiration in Plants",
     "Plants respire all the time to release energy from food. Cellular respiration begins with glycolysis in the cytoplasm, where glucose is broken into two molecules of pyruvic acid. With oxygen (aerobic respiration), pyruvate enters the mitochondria, goes through the Krebs cycle, and the electron transport system produces most of the ATP — about 36–38 ATP per glucose. Without oxygen, fermentation produces ethanol and CO₂ (in yeast) or lactic acid, giving only 2 ATP. The respiratory quotient (RQ) = CO₂ released ÷ O₂ used; it is 1 for carbohydrates.",
     ["Glycolysis happens in the cytoplasm.",
      "Krebs cycle happens in the mitochondria.",
      "Aerobic respiration gives much more ATP.",
      "Fermentation gives ethanol or lactic acid and only 2 ATP.",
      "RQ = CO₂ released ÷ O₂ used; 1 for carbohydrates."],
     [EX("Pathway", "Glucose → pyruvate (glycolysis) → Krebs cycle → ETS → ATP.", "🍬 → ⚙️ → ⚡⚡⚡"),
      EX("Fermentation", "Yeast turns sugar into alcohol and CO₂ in the absence of oxygen.", "🍞 🫧"),
      EX("RQ", "For glucose: 6 CO₂ ÷ 6 O₂ = 1.")],
     "Put yeast and sugar in warm water in a bottle with a balloon on top. Watch the balloon inflate with CO₂.",
     [Q("EASY", "Glycolysis takes place in the ___.", ["Cytoplasm", "Mitochondria", "Nucleus", "Chloroplast"], "Cytoplasm", "It doesn't need an organelle.", "Glycolysis is in the cytoplasm."),
      Q("EASY", "The Krebs cycle takes place in the ___.", ["Mitochondria", "Cytoplasm", "Ribosome", "Cell wall"], "Mitochondria", "The powerhouse.", "Krebs cycle occurs in mitochondria."),
      Q("MEDIUM", "Glycolysis breaks glucose into two molecules of ___.", ["Pyruvic acid", "Ethanol", "Starch", "Oxygen"], "Pyruvic acid", "Also called pyruvate.", "It yields two pyruvates."),
      Q("MEDIUM", "Yeast fermentation produces ethanol and ___.", [], "carbon dioxide|co2|co₂", "It makes dough rise.", "Ethanol and CO₂."),
      Q("HARD", "The RQ of carbohydrates is ___.", [], "1|1.0", "Equal CO₂ and O₂.", "RQ = 1."),
      Q("HARD", "About how many ATP does aerobic respiration yield per glucose?", ["36–38", "2", "4", "100"], "36–38", "Much more than fermentation.", "About 36–38 ATP.")]),
  CH("Breathing and Exchange of Gases",
     "Breathing brings oxygen into the body and removes carbon dioxide. Air passes through the nose, pharynx, larynx, trachea, bronchi and bronchioles to tiny air sacs called alveoli, where gas exchange happens by diffusion. Inhalation occurs when the diaphragm contracts and the chest expands, lowering pressure in the lungs; exhalation is the reverse. Oxygen is carried mainly by haemoglobin in red blood cells as oxyhaemoglobin. Carbon dioxide is carried mostly as bicarbonate. Breathing is controlled by the respiratory centre in the medulla of the brain.",
     ["Gas exchange happens in the alveoli.",
      "The diaphragm contracts during inhalation.",
      "Oxygen is carried by haemoglobin.",
      "CO₂ is carried mostly as bicarbonate.",
      "Breathing is controlled by the medulla."],
     [EX("Air path", "Nose → trachea → bronchi → bronchioles → alveoli.", "👃 → 🫁 → ○○○"),
      EX("Inhalation", "Diaphragm moves down and ribs move out; air rushes in.", "⬇ diaphragm → air in"),
      EX("High altitude", "At high altitude, less oxygen makes breathing faster.", "🏔️")],
     "Make a model lung with a bottle, two balloons and a rubber sheet to show how the diaphragm works.",
     [Q("EASY", "Gas exchange in the lungs takes place in the ___.", ["Alveoli", "Trachea", "Larynx", "Nose"], "Alveoli", "Tiny air sacs.", "Alveoli are the sites of exchange."),
      Q("EASY", "Oxygen is carried in blood mainly by ___.", ["Haemoglobin", "Plasma only", "Platelets", "White blood cells"], "Haemoglobin", "It is in red blood cells.", "Haemoglobin carries oxygen."),
      Q("MEDIUM", "During inhalation, the diaphragm ___.", ["Contracts and flattens", "Relaxes and domes up", "Disappears", "Moves sideways"], "Contracts and flattens", "It increases chest volume.", "It contracts and moves down."),
      Q("MEDIUM", "Gases move between alveoli and blood by ___.", [], "diffusion", "From high to low concentration.", "By diffusion."),
      Q("HARD", "Breathing rate is controlled by the ___ of the brain.", ["Medulla", "Cerebrum", "Cerebellum", "Hypothalamus"], "Medulla", "Part of the brain stem.", "The medulla controls breathing."),
      Q("HARD", "Most CO₂ is transported in blood as ___.", ["Bicarbonate", "Carbon monoxide", "Oxyhaemoglobin", "Glucose"], "Bicarbonate", "Formed with the help of carbonic anhydrase.", "About 70% travels as bicarbonate.")])],
 "English": [
  CH("Speech Writing",
     "A speech is written to be spoken to an audience. It begins with a greeting to the audience (Respected Principal, teachers and my dear friends), followed by an introduction of the speaker and the topic. The body develops the main points with facts, examples and rhetorical questions to engage listeners. A speech uses a direct, conversational tone and phrases like 'Let us' and 'I urge you'. It ends with a strong conclusion or call to action and a 'Thank you'.",
     ["A speech is written to be spoken.",
      "Start by greeting the audience.",
      "Introduce yourself and the topic.",
      "Use examples and rhetorical questions.",
      "End with a call to action and 'Thank you'."],
     [EX("Opening", "Good morning, respected Principal, teachers and my dear friends. I am Meera from Class XI, and today I will speak on saving water.", "🎤"),
      EX("Rhetorical question", "Can we imagine a day without clean water?"),
      EX("Call to action", "Let us turn off taps and save every drop. Thank you.")],
     "Write and practise a two-minute speech on 'The importance of reading', then present it to your family.",
     [Q("EASY", "A speech usually begins with ___.", ["Greeting the audience", "The conclusion", "A bibliography", "A signature"], "Greeting the audience", "Respected Principal…", "It opens by addressing the audience."),
      Q("EASY", "A speech usually ends with ___.", ["Thank you", "Yours faithfully", "Dear Sir", "P.S."], "Thank you", "A polite close.", "Speeches end with 'Thank you'."),
      Q("MEDIUM", "'Can we imagine a world without trees?' is a ___.", ["Rhetorical question", "Statement", "Command", "Heading"], "Rhetorical question", "No answer is expected.", "It engages the audience."),
      Q("MEDIUM", "Which phrase is best for a call to action?", ["Let us all pledge to…", "In conclusion, bye", "I don't care", "Maybe someday"], "Let us all pledge to…", "It urges the audience to act.", "It invites the audience to act."),
      Q("HARD", "The tone of a speech should be ___.", ["Direct and engaging", "Like a formal notice", "Like a dictionary", "Full of slang"], "Direct and engaging", "It is spoken to people.", "Speeches are direct and conversational."),
      Q("HARD", "Which element is NOT usually part of a speech?", ["Salutation to audience", "Introduction of topic", "Subject line", "Conclusion"], "Subject line", "Think of letters vs speeches.", "Subject lines belong in letters.")]),
  CH("Debate Writing",
     "A debate presents arguments either for (in favour of) or against (opposing) a motion, which is the topic being discussed. It begins by greeting the chairperson, judges and audience, and clearly stating whether you are for or against the motion. The body gives strong arguments supported by facts and examples, and rebuts (answers) the opposite side's points. The language is formal and persuasive, using phrases like 'I strongly believe', 'On the contrary' and 'My opponents may argue that…'. It ends by restating your stand.",
     ["A debate argues for or against a motion.",
      "Greet the chairperson, judges and audience.",
      "State your stand clearly.",
      "Support arguments with facts; rebut the other side.",
      "Use persuasive phrases and restate your stand at the end."],
     [EX("Stand", "Today I stand before you to speak against the motion 'Homework should be banned'."),
      EX("Rebuttal", "My opponents may argue that homework causes stress; however, well-planned homework builds discipline."),
      EX("Persuasive phrase", "I firmly believe that…", "⚖️")],
     "Pick a motion like 'Mobile phones should be allowed in school' and write three points for and three against.",
     [Q("EASY", "The topic of a debate is called the ___.", ["Motion", "Subject line", "Heading", "Notice"], "Motion", "Speakers are for or against it.", "It is the motion."),
      Q("EASY", "Speaking in favour of the motion means you are ___ it.", ["For", "Against", "Neutral"], "For", "In favour.", "In favour = for."),
      Q("MEDIUM", "Answering the other side's arguments is called ___.", [], "rebuttal", "You 'rebut' their points.", "It is rebuttal."),
      Q("MEDIUM", "Which phrase is persuasive?", ["I strongly believe that", "Once upon a time", "Yours sincerely", "Dear diary"], "I strongly believe that", "It shows conviction.", "It is persuasive language."),
      Q("HARD", "A debate is usually addressed first to ___.", ["The chairperson and judges", "The editor", "A friend", "The postman"], "The chairperson and judges", "They conduct the debate.", "Greet the chairperson, judges and audience."),
      Q("HARD", "Which phrase introduces a counter-argument?", ["On the contrary", "In addition", "For example", "Firstly"], "On the contrary", "It shows opposition.", "'On the contrary' contrasts ideas.")])],
 "Computer Science": [
  CH("Strings in Python",
     "A string is a sequence of characters written inside quotes, like 'hello'. Each character has an index starting from 0; negative indices count from the end, so s[-1] is the last character. Slicing s[a:b] gives characters from index a up to, but not including, b. Strings are immutable, which means they cannot be changed in place. Useful methods include len(), upper(), lower(), strip(), replace(), split() and find(). Strings can be joined with + and repeated with *.",
     ["A string is a sequence of characters in quotes.",
      "Indexing starts at 0; s[-1] is the last character.",
      "s[a:b] slices from a up to (not including) b.",
      "Strings are immutable.",
      "Methods: upper(), lower(), split(), replace(), find()."],
     [EX("Indexing", "s = 'PYTHON'; s[0] = 'P', s[-1] = 'N'.", "P Y T H O N\n0 1 2 3 4 5"),
      EX("Slicing", "s[1:4] = 'YTH'."),
      EX("Methods", "'hello world'.split() → ['hello', 'world']; 'hi'.upper() → 'HI'.")],
     "Write a program that counts the vowels in a sentence typed by the user.",
     [Q("EASY", "If s = 'HELLO', what is s[0]?", ["H", "E", "O", "L"], "H", "Indexing starts at 0.", "s[0] = 'H'."),
      Q("EASY", "What does len('code') return?", [], "4", "Count the characters.", "c, o, d, e → 4."),
      Q("MEDIUM", "If s = 'PYTHON', what is s[-1]?", ["N", "P", "O", "Y"], "N", "Negative index counts from the end.", "s[-1] = 'N'."),
      Q("MEDIUM", "If s = 'PYTHON', what is s[1:4]?", ["YTH", "PYT", "YTHO", "THO"], "YTH", "Index 1 up to 3.", "s[1:4] = 'YTH'."),
      Q("HARD", "What is 'ab' * 3?", ["ababab", "ab3", "aaabbb", "Error"], "ababab", "* repeats strings.", "'ab' repeated 3 times."),
      Q("HARD", "Strings in Python are ___.", ["Immutable", "Mutable", "Numbers", "Lists"], "Immutable", "You can't change a character in place.", "Strings cannot be modified in place.")]),
  CH("Lists and Dictionaries",
     "A list is an ordered, changeable collection written in square brackets, like [3, 7, 1]. Items are accessed by index, and lists support methods such as append(), insert(), remove(), pop(), sort() and len(). A tuple is like a list but immutable, written in round brackets. A dictionary stores key–value pairs in curly braces, like {'name': 'Asha', 'age': 16}. Values are accessed by key, keys must be unique, and methods include keys(), values(), items() and get().",
     ["Lists are ordered and changeable: [1, 2, 3].",
      "append() adds an item to the end.",
      "Tuples are like lists but immutable: (1, 2).",
      "Dictionaries store key–value pairs: {'a': 1}.",
      "Access dictionary values by key: d['a']."],
     [EX("List", "marks = [80, 92, 75]; marks.append(88) → [80, 92, 75, 88].", "[80 | 92 | 75 | 88]"),
      EX("Dictionary", "student = {'name': 'Ravi', 'grade': 11}; student['name'] → 'Ravi'."),
      EX("Loop over dict", "for k, v in student.items(): print(k, v)")],
     "Store five friends' names and birthdays in a dictionary and print whose birthday is next.",
     [Q("EASY", "Which brackets create a list?", ["[ ]", "( )", "{ }", "< >"], "[ ]", "Square brackets.", "Lists use square brackets."),
      Q("EASY", "Which method adds an item to the end of a list?", ["append()", "remove()", "pop()", "sort()"], "append()", "It 'appends'.", "append() adds to the end."),
      Q("MEDIUM", "If nums = [4, 8, 15], what is nums[1]?", [], "8", "Indexing starts at 0.", "nums[1] = 8."),
      Q("MEDIUM", "d = {'a': 1, 'b': 2}. What is d['b']?", [], "2", "Look up by key.", "d['b'] = 2."),
      Q("HARD", "Which collection is immutable?", ["Tuple", "List", "Dictionary", "Set"], "Tuple", "Round brackets.", "Tuples cannot be changed."),
      Q("HARD", "What is len([1, [2, 3], 4])?", [], "3", "The inner list counts as one item.", "Three items: 1, [2, 3], 4.")])],
 "Economics": [
  CH("Theory of Supply",
     "Supply is the quantity of a good that producers are willing and able to sell at a given price during a period. The law of supply states that, other things remaining constant, quantity supplied rises when price rises, so the supply curve slopes upward. Supply also depends on the cost of inputs, technology, prices of other goods, the number of firms, taxes and subsidies. A change in the good's own price causes a movement along the supply curve; a change in other factors shifts the curve. Price elasticity of supply measures how much quantity supplied responds to price changes.",
     ["Supply = willingness and ability to sell.",
      "Law of supply: price ↑ → quantity supplied ↑.",
      "The supply curve slopes upward.",
      "Input costs, technology and taxes shift supply.",
      "Own price change → movement along the curve."],
     [EX("Law of supply", "When mango prices rise, farmers bring more mangoes to market.", "P\n|  / S\n| /\n|/___ Q"),
      EX("Technology", "Better machines lower costs, shifting supply to the right."),
      EX("Tax", "A new tax raises costs, shifting supply to the left.")],
     "Ask a local shopkeeper what they do when the price of an item goes up — do they stock more?",
     [Q("EASY", "By the law of supply, when price rises, quantity supplied ___.", ["Rises", "Falls", "Stays the same"], "Rises", "Sellers earn more.", "Supply moves with price."),
      Q("EASY", "The supply curve usually slopes ___.", ["Upward", "Downward", "Flat", "Vertical"], "Upward", "Opposite of demand.", "It slopes upward."),
      Q("MEDIUM", "Better technology usually shifts supply to the ___.", ["Right", "Left", "Neither"], "Right", "Production becomes cheaper.", "Supply increases (right shift)."),
      Q("MEDIUM", "A rise in input costs shifts supply to the ___.", ["Left", "Right"], "Left", "Production becomes costlier.", "Supply decreases (left shift)."),
      Q("HARD", "A change in the good's own price causes ___.", ["Movement along the supply curve", "Shift of the supply curve", "Shift of demand", "No change"], "Movement along the supply curve", "Other factors are constant.", "Own price changes move along the curve."),
      Q("HARD", "A government subsidy to producers usually ___ supply.", ["Increases", "Decreases", "Does not affect"], "Increases", "It lowers costs.", "Subsidies increase supply.")]),
  CH("Market Equilibrium",
     "Market equilibrium is reached when quantity demanded equals quantity supplied. The price at this point is the equilibrium price, and the quantity is the equilibrium quantity. If the price is above equilibrium, there is excess supply (surplus), which pushes the price down. If the price is below equilibrium, there is excess demand (shortage), which pushes the price up. An increase in demand raises both equilibrium price and quantity; an increase in supply lowers price and raises quantity. Governments sometimes set a price ceiling (maximum price) or a price floor (minimum support price).",
     ["Equilibrium: quantity demanded = quantity supplied.",
      "Above equilibrium price → excess supply.",
      "Below equilibrium price → excess demand.",
      "More demand → higher price and quantity.",
      "Price ceiling = maximum; price floor = minimum."],
     [EX("Finding equilibrium", "Qd = 100 − 2P and Qs = 20 + 2P → 100 − 2P = 20 + 2P → P = 20, Q = 60.", "D ╲ ╱ S\n    ✕ E"),
      EX("Shortage", "If the price is set too low, buyers want more than sellers offer."),
      EX("Price floor", "Minimum support price for wheat protects farmers' income.", "🌾 MSP")],
     "Track the price of tomatoes for two weeks and explain the changes using demand and supply.",
     [Q("EASY", "At equilibrium, quantity demanded ___ quantity supplied.", ["Equals", "Is greater than", "Is less than"], "Equals", "The market 'clears'.", "They are equal."),
      Q("EASY", "If price is above equilibrium, there is excess ___.", ["Supply", "Demand"], "Supply", "Sellers offer more than buyers want.", "A surplus (excess supply)."),
      Q("MEDIUM", "Qd = 50 − P, Qs = 10 + P. Equilibrium price?", [], "20", "Set 50 − P = 10 + P.", "2P = 40, so P = 20."),
      Q("MEDIUM", "Excess demand usually makes the price ___.", ["Rise", "Fall", "Stay the same"], "Rise", "Buyers compete.", "Shortage pushes price up."),
      Q("HARD", "An increase in demand (supply unchanged) leads to ___.", ["Higher price and higher quantity", "Lower price and higher quantity", "Higher price and lower quantity", "No change"], "Higher price and higher quantity", "Demand curve shifts right.", "Both price and quantity rise."),
      Q("HARD", "A government-fixed maximum price is a price ___.", ["Ceiling", "Floor", "Tag", "Index"], "Ceiling", "It limits how high price can go.", "It is a price ceiling.")])],
}
