# Additional chapters for Grades 6 and 7 (appended after the existing chapters of each subject).
from grade6 import Q, EX


def CH(name, explanation, key_points, examples, activity, questions):
    return {"name": name, "explanation": explanation, "keyPoints": key_points, "examples": examples,
            "activity": activity, "questions": questions}


MORE6 = {
 "Mathematics": [
  CH("Integers",
     "Integers are the numbers ..., −3, −2, −1, 0, 1, 2, 3, .... Numbers greater than zero are positive and numbers less than zero are negative. Zero is neither positive nor negative. On a number line, numbers get bigger as we move right and smaller as we move left. We use negative numbers for things like temperatures below zero, money owed, or depths below sea level.",
     ["Integers include negative numbers, zero and positive numbers.",
      "Zero is neither positive nor negative.",
      "On a number line, numbers get bigger to the right.",
      "Negative numbers show below zero, like cold temperatures.",
      "Every negative number is smaller than zero."],
     [EX("Number line", "−2 is to the left of 1, so −2 is smaller than 1.", "−3 −2 −1  0  1  2  3\n ◀────────●────────▶"),
      EX("Temperature", "If it is 3°C colder than 0°C, the temperature is −3°C.", "🌡️ 0°C ⬇ 3 → −3°C"),
      EX("Adding on a line", "Start at −2 and move 5 steps right: you reach 3.")],
     "Draw a number line from −10 to 10 and mark the temperatures of five cold cities.",
     [Q("EASY", "Which number is negative?", ["5", "0", "−4", "7"], "−4", "Look for the minus sign.", "−4 is less than zero, so it is negative."),
      Q("EASY", "Which is bigger: −1 or −6?", ["−1", "−6"], "−1", "Which is further right on the number line?", "−1 is to the right of −6, so it is bigger."),
      Q("MEDIUM", "What is −3 + 5?", [], "2", "Start at −3 and move 5 steps right.", "−3 + 5 = 2."),
      Q("MEDIUM", "Is zero positive, negative or neither?", ["Positive", "Negative", "Neither"], "Neither", "It is in the middle.", "Zero is neither positive nor negative."),
      Q("HARD", "What is 4 − 9?", [], "-5|−5", "Start at 4 and move 9 steps left.", "4 − 9 = −5."),
      Q("HARD", "Arrange in increasing order: 2, −5, 0, −1", ["−5, −1, 0, 2", "2, 0, −1, −5", "−1, −5, 0, 2", "0, −1, 2, −5"], "−5, −1, 0, 2", "Smallest is the most negative.", "−5 < −1 < 0 < 2.")]),
  CH("Fractions",
     "A fraction shows a part of a whole. In the fraction 3/4, the top number (numerator) tells how many parts we have, and the bottom number (denominator) tells how many equal parts the whole is divided into. Equivalent fractions show the same amount, like 1/2 and 2/4. A proper fraction has a numerator smaller than the denominator. To compare fractions with the same denominator, compare the numerators.",
     ["A fraction is part of a whole.",
      "Numerator: parts we have. Denominator: total equal parts.",
      "1/2 and 2/4 are equivalent fractions.",
      "Same denominator? The bigger numerator is bigger.",
      "In a proper fraction, the top is smaller than the bottom."],
     [EX("Pizza fraction", "A pizza cut into 4 equal slices; you eat 1. You ate 1/4.", "🍕🍕🍕🍕 → eat 1 → 1/4"),
      EX("Equivalent", "1/2 = 2/4 = 3/6. Multiply top and bottom by the same number.", "■□ = ■■□□"),
      EX("Comparing", "3/8 < 5/8 because 3 < 5.")],
     "Fold a paper into 8 equal parts and colour 3/8 of it.",
     [Q("EASY", "In 3/5, what is the denominator?", [], "5", "It is the bottom number.", "The denominator is 5."),
      Q("EASY", "A cake is cut into 6 equal pieces. You eat 1. What fraction did you eat?", ["1/6", "6/1", "1/5", "5/6"], "1/6", "1 piece out of 6.", "You ate 1 of 6 pieces: 1/6."),
      Q("MEDIUM", "Which fraction is equal to 1/2?", ["2/3", "3/6", "1/4", "2/5"], "3/6", "Multiply 1 and 2 by the same number.", "1 × 3 / 2 × 3 = 3/6."),
      Q("MEDIUM", "Which is bigger: 4/9 or 7/9?", ["4/9", "7/9"], "7/9", "Same denominator — compare the tops.", "7 > 4, so 7/9 is bigger."),
      Q("HARD", "Write 12/16 in simplest form.", ["3/4", "6/8", "2/3", "4/3"], "3/4", "Divide top and bottom by 4.", "12 ÷ 4 = 3 and 16 ÷ 4 = 4, so 3/4."),
      Q("HARD", "What is 2/7 + 3/7?", ["5/7", "5/14", "6/7", "1/7"], "5/7", "Same denominator: add the tops.", "2 + 3 = 5, so 5/7.")])],
 "Science": [
  CH("Electricity and Circuits",
     "Electricity is a form of energy that lights bulbs and runs fans. An electric cell has a positive and a negative terminal. A bulb glows only when there is a complete path, called a closed circuit, from one terminal of the cell, through the bulb, and back to the other terminal. A switch opens or closes the circuit. Materials that let electricity pass through, like copper and iron, are conductors; materials that do not, like plastic, rubber and wood, are insulators.",
     ["A cell has a positive and a negative terminal.",
      "A bulb glows only in a closed circuit.",
      "A switch opens or closes the circuit.",
      "Conductors let electricity pass: copper, iron.",
      "Insulators do not: plastic, rubber, wood."],
     [EX("Closed circuit", "Cell → wire → bulb → wire → back to cell. The bulb glows.", "🔋─────💡\n │        │\n └────────┘"),
      EX("Open circuit", "If a wire is loose, the path is broken and the bulb does not glow."),
      EX("Safety", "Electricians wear rubber gloves because rubber is an insulator.", "🧤")],
     "With an adult's help, test whether a key, an eraser and a spoon let electricity pass using a simple torch circuit.",
     [Q("EASY", "A bulb glows only when the circuit is ___.", ["Open", "Closed", "Broken", "Empty"], "Closed", "The path must be complete.", "A closed circuit lets current flow."),
      Q("EASY", "Which is a conductor?", ["Plastic", "Rubber", "Copper", "Wood"], "Copper", "Wires are made of it.", "Copper conducts electricity."),
      Q("MEDIUM", "What does a switch do?", ["Opens or closes a circuit", "Makes electricity", "Stores electricity", "Changes the bulb colour"], "Opens or closes a circuit", "Think of the light switch at home.", "A switch completes or breaks the circuit."),
      Q("MEDIUM", "Materials that do not allow electricity to pass are called ___.", [], "insulators|insulator", "Rubber and plastic are examples.", "They are insulators."),
      Q("HARD", "Why are electric wires covered with plastic?", ["Plastic is an insulator and keeps us safe", "Plastic makes current faster", "Plastic is a conductor", "For colour only"], "Plastic is an insulator and keeps us safe", "Touching bare wires is dangerous.", "The plastic insulates the wire and protects us from shocks."),
      Q("HARD", "A bulb does not glow even though the circuit looks complete. What might be wrong?", ["The bulb's filament is broken", "The wire is copper", "The cell is new", "The switch is closed"], "The bulb's filament is broken", "Check the thin wire inside the bulb.", "A broken filament breaks the path, so no current flows.")]),
  CH("Light, Shadows and Reflections",
     "Light travels in straight lines. Objects that give out their own light, like the Sun, are luminous. Transparent objects such as clear glass let light pass through, translucent objects such as butter paper let some light pass, and opaque objects such as wood block light completely. A shadow forms when an opaque object blocks light. A mirror reflects light, which changes its direction; that is how we see our image in a mirror.",
     ["Light travels in straight lines.",
      "The Sun is luminous: it makes its own light.",
      "Opaque objects block light and make shadows.",
      "Transparent objects let light pass through.",
      "Mirrors reflect light."],
     [EX("Shadow", "Your body blocks sunlight, so a dark shape (shadow) appears on the ground.", "☀️ → 🧍 → ▓▓ shadow"),
      EX("Three kinds", "Glass window: transparent. Butter paper: translucent. Wooden door: opaque."),
      EX("Straight lines", "Sunlight coming through a gap in a window makes a straight beam.")],
     "Make shadow puppets on a wall using a torch and your hands.",
     [Q("EASY", "Which object gives out its own light?", ["Moon", "Sun", "Mirror", "Book"], "Sun", "It is a star.", "The Sun is luminous."),
      Q("EASY", "Light travels in ___ lines.", ["Straight", "Curved", "Zig-zag", "Circular"], "Straight", "Think of a torch beam.", "Light travels in straight lines."),
      Q("MEDIUM", "A wooden board is ___.", ["Transparent", "Translucent", "Opaque"], "Opaque", "You cannot see through it at all.", "Wood blocks light completely."),
      Q("MEDIUM", "A shadow forms when light is blocked by an ___ object.", [], "opaque", "It does not let light through.", "Opaque objects cast shadows."),
      Q("HARD", "Is the Moon luminous?", ["Yes", "No"], "No", "Where does its light come from?", "The Moon reflects sunlight; it does not make its own light."),
      Q("HARD", "What do we call the bouncing back of light from a mirror?", ["Reflection", "Refraction", "Shadow", "Absorption"], "Reflection", "It is how you see yourself.", "Light bouncing off a mirror is reflection.")])],
 "English": [
  CH("Articles",
     "Articles are small words that come before nouns: a, an and the. 'A' and 'an' are indefinite articles; we use them for any one thing that is not specific. We use 'a' before words that begin with a consonant sound and 'an' before words that begin with a vowel sound. 'The' is the definite article; we use it for something specific or already known, and for things that are one of a kind, like the Sun.",
     ["The articles are a, an and the.",
      "Use 'a' before a consonant sound: a cat.",
      "Use 'an' before a vowel sound: an apple.",
      "Use 'the' for something specific.",
      "Use 'the' for one-of-a-kind things: the Moon."],
     [EX("A or an", "a dog, a banana, an egg, an umbrella.", "a 🐕  an 🥚"),
      EX("The", "I saw a cat. The cat was black. (Now we know which cat.)"),
      EX("One of a kind", "The Sun rises in the east.", "☀️")],
     "Write five sentences about your school bag using a, an and the.",
     [Q("EASY", "I ate ___ apple.", ["a", "an", "the"], "an", "'Apple' starts with a vowel sound.", "Use 'an' before a vowel sound."),
      Q("EASY", "She has ___ cat.", ["a", "an"], "a", "'Cat' starts with a consonant sound.", "Use 'a' before a consonant sound."),
      Q("MEDIUM", "___ Moon is bright tonight.", ["A", "An", "The"], "The", "There is only one Moon.", "Use 'the' for unique things."),
      Q("MEDIUM", "He wants to be ___ engineer.", ["a", "an", "the"], "an", "'Engineer' starts with an 'e' sound.", "an engineer."),
      Q("HARD", "It took ___ hour to finish.", ["a", "an", "the"], "an", "The 'h' in hour is silent.", "'Hour' begins with a vowel sound: an hour."),
      Q("HARD", "I bought a pen. ___ pen is blue.", ["A", "An", "The"], "The", "Now we know which pen.", "The second mention is specific, so 'the'.")]),
  CH("Punctuation",
     "Punctuation marks help readers understand writing. A full stop (.) ends a statement. A question mark (?) ends a question. An exclamation mark (!) shows strong feeling. A comma (,) separates items in a list or shows a short pause. A capital letter begins every sentence and every proper noun, such as names of people and places. An apostrophe (') shows ownership, as in Riya's book.",
     ["A full stop ends a statement.",
      "A question mark ends a question.",
      "An exclamation mark shows strong feeling.",
      "Commas separate items in a list.",
      "Sentences and names start with capital letters."],
     [EX("End marks", "I like mangoes. Do you like mangoes? What a sweet mango!"),
      EX("List commas", "I bought apples, bananas, grapes and oranges.", "🍎, 🍌, 🍇 and 🍊"),
      EX("Apostrophe", "This is Aman's bicycle. (The bicycle belongs to Aman.)")],
     "Copy a short paragraph from a storybook without punctuation, then ask a friend to add it back.",
     [Q("EASY", "Which mark ends a question?", [".", "?", "!", ","], "?", "It looks like a hook.", "Questions end with a question mark."),
      Q("EASY", "Which word needs a capital letter?", ["delhi", "city", "river", "school"], "delhi", "It is the name of a place.", "Proper nouns like Delhi start with a capital."),
      Q("MEDIUM", "Which sentence is punctuated correctly?", ["what a lovely day!", "What a lovely day!", "What a lovely day?", "what a lovely day."], "What a lovely day!", "Capital letter, and strong feeling at the end.", "It starts with a capital and ends with '!'."),
      Q("MEDIUM", "Which mark separates items in a list?", ["Comma", "Full stop", "Question mark", "Apostrophe"], "Comma", "apples, bananas, grapes", "Commas separate list items."),
      Q("HARD", "Choose the correct one.", ["The dogs tail is long.", "The dog's tail is long.", "The dogs' tail is long.", "The dog,s tail is long."], "The dog's tail is long.", "The tail belongs to one dog.", "Use 's to show ownership by one dog."),
      Q("HARD", "Which sentence is correct?", ["my friend lives in mumbai.", "My friend lives in Mumbai.", "My Friend lives in mumbai.", "my Friend Lives In Mumbai."], "My friend lives in Mumbai.", "Capitalise the first word and the place name.", "Only 'My' and 'Mumbai' need capitals.")])],
 "Social Science": [
  CH("Motions of the Earth",
     "The Earth has two main motions. Rotation is the spinning of the Earth on its axis; one rotation takes about 24 hours and causes day and night. The half facing the Sun has day, while the other half has night. Revolution is the movement of the Earth around the Sun; one revolution takes about 365¼ days, which makes a year. Because the Earth's axis is tilted, different parts receive different amounts of sunlight during the year, which causes the seasons.",
     ["Rotation: the Earth spins on its axis.",
      "One rotation takes about 24 hours and causes day and night.",
      "Revolution: the Earth goes around the Sun.",
      "One revolution takes about 365¼ days — one year.",
      "The tilted axis causes seasons."],
     [EX("Day and night", "The side of the Earth facing the Sun has day; the other side has night.", "☀️ →  🌍 (day | night)"),
      EX("Leap year", "The extra ¼ day adds up to one extra day every 4 years: 29 February."),
      EX("Seasons", "When the northern half tilts towards the Sun, it has summer.", "☀️ ← 🌍 tilted")],
     "Shine a torch on a ball in a dark room and turn the ball slowly to see day and night.",
     [Q("EASY", "The spinning of the Earth on its axis is called ___.", ["Rotation", "Revolution"], "Rotation", "Think of a spinning top.", "Spinning on its axis is rotation."),
      Q("EASY", "Day and night are caused by the Earth's ___.", ["Rotation", "Revolution", "Size", "Moon"], "Rotation", "The Earth spins once a day.", "Rotation causes day and night."),
      Q("MEDIUM", "About how long does one rotation take?", ["24 hours", "7 days", "30 days", "365 days"], "24 hours", "One full day.", "One rotation is about 24 hours."),
      Q("MEDIUM", "The Earth's movement around the Sun is ___.", [], "revolution", "It takes a year.", "That is revolution."),
      Q("HARD", "Why do we have a leap year every four years?", ["The extra ¼ day adds up", "The Earth slows down", "The Moon changes", "Calendars are wrong"], "The extra ¼ day adds up", "365¼ days per revolution.", "Four quarter-days make one extra day."),
      Q("HARD", "What causes the seasons?", ["The tilt of the Earth's axis", "The Earth's distance from the Moon", "Rotation", "Clouds"], "The tilt of the Earth's axis", "Different parts get more sunlight at different times.", "The tilted axis changes how much sunlight each part receives.")]),
  CH("Understanding Diversity",
     "India is a country of great diversity. People speak many languages, follow different religions, celebrate different festivals, wear different clothes and eat different foods. Diversity comes from history, geography and the mixing of cultures over many years. For example, people living near the sea often eat fish, while people in the hills wear warm clothes. Even with so many differences, we share values and a common identity as Indians, which is called 'unity in diversity'.",
     ["India has many languages, religions and festivals.",
      "Geography and history create diversity.",
      "Food and clothes change with climate.",
      "Different people share a common identity.",
      "'Unity in diversity' means being united despite differences."],
     [EX("Festivals", "Diwali, Eid, Christmas, Pongal and Guru Nanak Jayanti are all celebrated in India.", "🪔 🌙 🎄 🌾"),
      EX("Geography", "In Kerala, many dishes use coconut and fish because the state is near the sea.", "🥥 🐟"),
      EX("National symbols", "The national flag and anthem belong to all Indians.", "🇮🇳")],
     "Ask three friends which languages they speak at home and which festivals they celebrate.",
     [Q("EASY", "Differences in language, religion and food are called ___.", ["Diversity", "Poverty", "Unity", "Equality"], "Diversity", "'Diverse' means varied.", "Such differences are diversity."),
      Q("EASY", "Which is a festival celebrated in India?", ["Diwali", "Thanksgiving only", "Halloween only", "None"], "Diwali", "Festival of lights.", "Diwali is one of many Indian festivals."),
      Q("MEDIUM", "Why do people in coastal areas often eat fish?", ["Fish is easily available near the sea", "They dislike vegetables", "It is a law", "Fish is cheap everywhere"], "Fish is easily available near the sea", "Think of geography.", "Geography shapes food habits."),
      Q("MEDIUM", "'Unity in diversity' means ___.", ["Being united despite differences", "Everyone is the same", "Living separately", "Only one language"], "Being united despite differences", "Different but together.", "We stay united while being different."),
      Q("HARD", "Which factor does NOT usually create diversity?", ["Geography", "History", "Mixing of cultures", "Having the same national flag"], "Having the same national flag", "Which one unites instead?", "The flag is a shared symbol of unity."),
      Q("HARD", "Who wrote the book 'The Discovery of India', describing unity in diversity?", ["Jawaharlal Nehru", "Rabindranath Tagore", "Mahatma Gandhi", "B. R. Ambedkar"], "Jawaharlal Nehru", "He was India's first Prime Minister.", "Nehru wrote 'The Discovery of India'.")])],
}

MORE7 = {
 "Mathematics": [
  CH("Lines and Angles",
     "An angle is formed when two rays start from the same point. Angles are measured in degrees. Two angles whose sum is 90° are complementary, and two angles whose sum is 180° are supplementary. When two lines cross, the opposite angles are called vertically opposite angles and they are equal. Angles next to each other on a straight line form a linear pair and add up to 180°. When a line crosses two parallel lines, corresponding angles are equal.",
     ["Complementary angles add up to 90°.",
      "Supplementary angles add up to 180°.",
      "Vertically opposite angles are equal.",
      "A linear pair adds up to 180°.",
      "With parallel lines, corresponding angles are equal."],
     [EX("Complementary", "30° and 60° are complementary because 30 + 60 = 90.", "∟ 30° + 60°"),
      EX("Vertically opposite", "Two crossing lines make a 'X'. The top and bottom angles are equal.", "  \\ /\n   X\n  / \\"),
      EX("Linear pair", "If one angle on a straight line is 110°, the other is 70°.")],
     "Find angles around your home: the corner of a book (90°), an open door, and clock hands at 3 o'clock.",
     [Q("EASY", "Complementary angles add up to ___°.", [], "90", "Think of a right angle.", "They add up to 90°."),
      Q("EASY", "Supplementary angles add up to ___°.", [], "180", "Think of a straight line.", "They add up to 180°."),
      Q("MEDIUM", "What is the complement of 35°?", [], "55|55°", "90 − 35.", "90 − 35 = 55°."),
      Q("MEDIUM", "What is the supplement of 120°?", [], "60|60°", "180 − 120.", "180 − 120 = 60°."),
      Q("HARD", "Two lines cross. One angle is 40°. What is its vertically opposite angle?", [], "40|40°", "Vertically opposite angles are equal.", "It is also 40°."),
      Q("HARD", "Two angles in a linear pair are x and 2x. What is x?", [], "60|60°", "x + 2x = 180.", "3x = 180, so x = 60°.")]),
  CH("Perimeter and Area",
     "Perimeter is the total distance around a closed shape. Area is the amount of surface a shape covers, measured in square units. For a rectangle, perimeter = 2 × (length + breadth) and area = length × breadth. For a square, perimeter = 4 × side and area = side × side. The area of a triangle is ½ × base × height. For a circle, the distance around is called the circumference, 2πr, and the area is πr².",
     ["Perimeter is the distance around a shape.",
      "Area is the surface covered, in square units.",
      "Rectangle: P = 2(l + b), A = l × b.",
      "Square: P = 4s, A = s × s.",
      "Triangle area = ½ × base × height."],
     [EX("Rectangle", "A 5 cm by 3 cm rectangle: P = 2(5 + 3) = 16 cm, A = 15 cm².", "┌─────┐\n│     │ 3\n└─────┘\n   5"),
      EX("Square", "A square of side 4 m: P = 16 m, A = 16 m²."),
      EX("Triangle", "Base 6 cm, height 4 cm: area = ½ × 6 × 4 = 12 cm².")],
     "Measure the length and breadth of your study table and find its perimeter and area.",
     [Q("EASY", "Perimeter of a square with side 5 cm (cm)?", [], "20", "P = 4 × side.", "4 × 5 = 20 cm."),
      Q("EASY", "Area of a rectangle 6 m by 2 m (m²)?", [], "12", "A = length × breadth.", "6 × 2 = 12 m²."),
      Q("MEDIUM", "Perimeter of a rectangle 7 cm by 3 cm (cm)?", [], "20", "P = 2(l + b).", "2 × (7 + 3) = 20 cm."),
      Q("MEDIUM", "Area of a triangle with base 10 cm and height 6 cm (cm²)?", [], "30", "½ × base × height.", "½ × 10 × 6 = 30 cm²."),
      Q("HARD", "A square has area 49 m². What is its perimeter (m)?", [], "28", "First find the side: √49.", "Side = 7 m, so P = 28 m."),
      Q("HARD", "Area of a circle with radius 7 cm (use π = 22/7), in cm²?", [], "154", "A = πr².", "22/7 × 49 = 154 cm².")])],
 "Science": [
  CH("Respiration in Organisms",
     "Respiration is the process by which living things break down food to release energy. In aerobic respiration, glucose is broken down using oxygen to give carbon dioxide, water and energy. In anaerobic respiration, food is broken down without oxygen; yeast does this to make alcohol, and our muscles do it during hard exercise, producing lactic acid that causes cramps. Breathing is taking in air (inhalation) and giving out air (exhalation). Fish breathe using gills, and insects use tiny holes called spiracles.",
     ["Respiration releases energy from food.",
      "Aerobic respiration uses oxygen.",
      "Anaerobic respiration happens without oxygen.",
      "Hard exercise can cause cramps from lactic acid.",
      "Fish breathe with gills; insects use spiracles."],
     [EX("Aerobic equation", "Glucose + oxygen → carbon dioxide + water + energy.", "🍬 + O₂ → CO₂ + 💧 + ⚡"),
      EX("Breathing in and out", "When you breathe in, your chest gets bigger; when you breathe out, it gets smaller.", "🫁 ⬆ in  ⬇ out"),
      EX("Yeast", "Yeast respires without oxygen and makes dough rise.")],
     "Count how many times you breathe in one minute while resting and after running on the spot.",
     [Q("EASY", "Respiration releases ___ from food.", ["Energy", "Water only", "Sunlight", "Soil"], "Energy", "We need it to move and grow.", "Respiration releases energy."),
      Q("EASY", "Fish breathe using ___.", ["Lungs", "Gills", "Skin only", "Spiracles"], "Gills", "They take oxygen from water.", "Fish use gills."),
      Q("MEDIUM", "Respiration without oxygen is called ___ respiration.", [], "anaerobic", "'An' means without.", "It is anaerobic respiration."),
      Q("MEDIUM", "Which gas do we breathe out more of?", ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], "Carbon dioxide", "It is made in respiration.", "We exhale more carbon dioxide."),
      Q("HARD", "Why do we get muscle cramps after heavy exercise?", ["Lactic acid builds up", "Too much oxygen", "Too much water", "Sugar disappears"], "Lactic acid builds up", "Muscles respire without enough oxygen.", "Anaerobic respiration makes lactic acid, causing cramps."),
      Q("HARD", "Insects breathe through small openings called ___.", ["Spiracles", "Gills", "Stomata", "Alveoli"], "Spiracles", "They are on the sides of the body.", "Insects use spiracles and air tubes.")]),
  CH("Electric Current and its Effects",
     "Electric current flowing through a wire can produce heat and magnetism. When current flows through a thin wire, it becomes hot; this heating effect is used in electric irons, heaters and bulbs. A fuse is a safety device with a wire that melts and breaks the circuit if too much current flows. When current flows through a wire, the wire behaves like a magnet; this magnetic effect is used in electromagnets and electric bells. We draw circuits using standard symbols for cells, switches and bulbs.",
     ["Electric current can produce heat.",
      "Heaters and irons use the heating effect.",
      "A fuse melts to stop too much current.",
      "Current in a wire produces magnetism.",
      "Electromagnets and bells use the magnetic effect."],
     [EX("Heating effect", "An electric iron gets hot because current flows through its coil.", "⚡ → 🔥"),
      EX("Fuse", "If too many appliances run at once, the fuse wire melts and breaks the circuit.", "─╳─ fuse"),
      EX("Electromagnet", "A nail wrapped with wire becomes a magnet when current flows.", "🔩 + 🔋 = 🧲")],
     "Make an electromagnet with an iron nail, a wire and a cell (with an adult) and pick up pins.",
     [Q("EASY", "An electric heater uses the ___ effect of current.", ["Heating", "Magnetic", "Sound", "Chemical"], "Heating", "It gets hot.", "Heaters use the heating effect."),
      Q("EASY", "A coil of wire carrying current acts like a ___.", ["Magnet", "Mirror", "Battery", "Lens"], "Magnet", "It can pick up pins.", "It becomes an electromagnet."),
      Q("MEDIUM", "What does a fuse do?", ["Melts and breaks the circuit when current is too high", "Increases current", "Stores electricity", "Makes light"], "Melts and breaks the circuit when current is too high", "It is a safety device.", "A fuse protects the circuit."),
      Q("MEDIUM", "Which device uses an electromagnet?", ["Electric bell", "Candle", "Mirror", "Plastic spoon"], "Electric bell", "It rings using magnetism.", "Electric bells use electromagnets."),
      Q("HARD", "Why is the fuse wire made of a material with a low melting point?", ["So it melts quickly when current is too high", "So it never melts", "So it is shiny", "So it is cheap"], "So it melts quickly when current is too high", "It must break the circuit fast.", "A low melting point lets it melt and protect the circuit."),
      Q("HARD", "Can an electromagnet be switched off?", ["Yes", "No"], "Yes", "What happens when the current stops?", "It loses its magnetism when the current stops.")])],
 "English": [
  CH("Conjunctions",
     "Conjunctions are joining words. They connect words, phrases or sentences. Common conjunctions are and, but, or, so and because. 'And' adds information, 'but' shows contrast, 'or' gives a choice, 'so' shows a result, and 'because' gives a reason. Other conjunctions, such as although, when, if and until, join a main clause with a clause that depends on it.",
     ["Conjunctions are joining words.",
      "'and' adds; 'but' contrasts; 'or' gives a choice.",
      "'so' shows a result.",
      "'because' gives a reason.",
      "although, when, if and until also join ideas."],
     [EX("Joining", "I like tea and coffee."),
      EX("Contrast", "She was tired, but she finished her homework."),
      EX("Reason", "We stayed inside because it was raining.", "🌧️ → 🏠")],
     "Write five sentences about your day, each using a different conjunction.",
     [Q("EASY", "I like apples ___ oranges.", ["and", "but", "because", "so"], "and", "It adds another fruit.", "'And' joins two things."),
      Q("EASY", "Do you want tea ___ juice?", ["or", "and", "but", "so"], "or", "It is a choice.", "'Or' gives a choice."),
      Q("MEDIUM", "He was hungry, ___ he ate a sandwich.", ["so", "but", "or", "although"], "so", "Eating is the result.", "'So' shows a result."),
      Q("MEDIUM", "She stayed home ___ she was ill.", ["because", "but", "or", "and"], "because", "It gives a reason.", "'Because' gives the reason."),
      Q("HARD", "___ it was cold, we went swimming.", ["Although", "Because", "So", "Or"], "Although", "The two ideas contrast.", "'Although' shows contrast."),
      Q("HARD", "Wait here ___ I come back.", ["until", "but", "or", "so"], "until", "It shows up to what time.", "'Until' means up to the time.")]),
  CH("Question Tags",
     "A question tag is a short question added to the end of a statement to check information or ask for agreement, like 'isn't it?'. If the statement is positive, the tag is negative: It is hot, isn't it? If the statement is negative, the tag is positive: You don't like milk, do you? The tag uses the same helping verb as the statement, or do/does/did if there is none, and a pronoun for the subject.",
     ["A question tag is added to the end of a statement.",
      "Positive statement → negative tag.",
      "Negative statement → positive tag.",
      "Use the same helping verb as the statement.",
      "No helping verb? Use do, does or did."],
     [EX("Positive statement", "She is your sister, isn't she?"),
      EX("Negative statement", "They can't swim, can they?"),
      EX("Using do/does/did", "You play football, don't you? He went home, didn't he?")],
     "Talk with a friend for two minutes and try to use five question tags.",
     [Q("EASY", "It is sunny, ___?", ["isn't it", "is it", "doesn't it", "wasn't it"], "isn't it", "Positive statement → negative tag.", "It is… isn't it?"),
      Q("EASY", "You aren't tired, ___?", ["are you", "aren't you", "do you", "were you"], "are you", "Negative statement → positive tag.", "You aren't… are you?"),
      Q("MEDIUM", "He plays cricket, ___?", ["doesn't he", "isn't he", "don't he", "does he"], "doesn't he", "No helping verb, present tense, 'he'.", "Use 'does' → doesn't he?"),
      Q("MEDIUM", "They can dance, ___?", ["can't they", "can they", "don't they", "aren't they"], "can't they", "Use the same helping verb.", "can → can't they?"),
      Q("HARD", "She went to the market, ___?", ["didn't she", "doesn't she", "wasn't she", "did she"], "didn't she", "Past tense, no helping verb.", "went → didn't she?"),
      Q("HARD", "I am late, ___?", ["aren't I", "amn't I", "am I", "isn't I"], "aren't I", "This one is special.", "The tag for 'I am' is 'aren't I?'.")])],
 "Social Science": [
  CH("Air",
     "The atmosphere is the blanket of air around the Earth. It is mainly made of nitrogen (about 78%) and oxygen (about 21%), with small amounts of carbon dioxide, argon and other gases. The atmosphere protects us from the Sun's harmful rays and keeps the Earth warm. It has layers; the lowest, the troposphere, is where weather happens. Air pressure is the weight of air pressing down, and air moves from high pressure to low pressure, which creates wind.",
     ["The atmosphere is the air around the Earth.",
      "It is about 78% nitrogen and 21% oxygen.",
      "It protects us and keeps the Earth warm.",
      "Weather happens in the troposphere.",
      "Wind blows from high to low pressure."],
     [EX("Air mixture", "Out of 100 parts of air, about 78 are nitrogen and 21 are oxygen.", "N₂ ████████ 78%\nO₂ ██ 21%"),
      EX("Wind", "On a hot day, air over land rises and cooler sea air rushes in: a sea breeze.", "🌊 → 🏖️"),
      EX("Greenhouse effect", "Carbon dioxide traps heat, keeping the Earth warm enough to live on.")],
     "Watch leaves or a flag outside for a minute and describe the direction and strength of the wind.",
     [Q("EASY", "Which gas makes up most of the air?", ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], "Nitrogen", "About 78%.", "Nitrogen is about 78% of air."),
      Q("EASY", "The layer of air around the Earth is the ___.", [], "atmosphere", "'Atmo' refers to air.", "It is the atmosphere."),
      Q("MEDIUM", "In which layer does weather happen?", ["Troposphere", "Stratosphere", "Mesosphere", "Exosphere"], "Troposphere", "It is the lowest layer.", "Weather happens in the troposphere."),
      Q("MEDIUM", "About what percentage of air is oxygen?", ["21%", "78%", "1%", "50%"], "21%", "About one-fifth.", "Oxygen is about 21%."),
      Q("HARD", "Wind blows from areas of ___ pressure to ___ pressure.", ["High, low", "Low, high", "Equal, equal", "None"], "High, low", "Air moves to fill space.", "Air moves from high to low pressure."),
      Q("HARD", "Which gas traps heat and helps keep the Earth warm?", ["Carbon dioxide", "Nitrogen", "Argon", "Neon"], "Carbon dioxide", "It is a greenhouse gas.", "Carbon dioxide traps heat.")]),
  CH("Water",
     "About three-fourths of the Earth's surface is covered with water, but most of it is salty sea water; only a small amount is fresh water we can use. Water moves in a continuous water cycle: the Sun heats water so it evaporates, the vapour cools and condenses into clouds, and it falls back as rain, snow or hail (precipitation). The oceans move in waves, tides and currents. Tides are the regular rise and fall of sea water, caused mainly by the pull of the Moon.",
     ["About three-fourths of the Earth is covered by water.",
      "Most water is salty; little is fresh.",
      "Water cycle: evaporation → condensation → precipitation.",
      "Tides are caused mainly by the Moon's pull.",
      "Oceans move in waves, tides and currents."],
     [EX("Water cycle", "Sun heats the sea → vapour rises → clouds form → rain falls → rivers flow back to the sea.", "🌊 ⬆ ☁️ ➡ 🌧️ ⬇ 🏞️"),
      EX("Tides", "Twice a day the sea rises up the beach (high tide) and goes back (low tide)."),
      EX("Saving water", "Turning off the tap while brushing can save many litres a day.", "🚰✋")],
     "Record how much water your family uses in one day and list three ways to save water.",
     [Q("EASY", "Most of the Earth's water is ___.", ["Salty", "Fresh", "Frozen only", "Underground only"], "Salty", "Think of the oceans.", "Most water is in salty oceans."),
      Q("EASY", "Water falling from clouds as rain or snow is called ___.", ["Precipitation", "Evaporation", "Condensation", "Tide"], "Precipitation", "It comes down.", "Rain, snow and hail are precipitation."),
      Q("MEDIUM", "Water changing into vapour because of heat is ___.", [], "evaporation", "The Sun heats the water.", "This is evaporation."),
      Q("MEDIUM", "About how much of the Earth's surface is covered by water?", ["One-fourth", "Half", "Three-fourths", "All"], "Three-fourths", "It is called the blue planet.", "About three-fourths is water."),
      Q("HARD", "Tides are caused mainly by the pull of the ___.", ["Moon", "Wind", "Clouds", "Mountains"], "Moon", "It is Earth's satellite.", "The Moon's gravity causes tides."),
      Q("HARD", "Vapour cooling to form clouds is called ___.", ["Condensation", "Evaporation", "Precipitation", "Transpiration"], "Condensation", "Think of drops on a cold glass.", "Vapour becoming water droplets is condensation.")])],
}
