# Additional chapters for Grade 12.
from grade6 import Q, EX
from more6_7 import CH

MORE12 = {
 "Mathematics": [
  CH("Continuity and Differentiability",
     "A function is continuous at a point if its graph has no break there: the limit exists and equals the function's value. A function is differentiable at a point if it has a well-defined derivative (slope) there; every differentiable function is continuous, but not every continuous function is differentiable (for example, |x| at 0). Important derivatives: d/dx(xⁿ) = nxⁿ⁻¹, d/dx(sin x) = cos x, d/dx(eˣ) = eˣ, d/dx(ln x) = 1/x. The chain rule says d/dx f(g(x)) = f′(g(x))·g′(x). The product rule is (uv)′ = u′v + uv′.",
     ["Continuous: no break in the graph.",
      "Differentiable ⇒ continuous, but not the reverse.",
      "d/dx(xⁿ) = nxⁿ⁻¹.",
      "Chain rule: d/dx f(g(x)) = f′(g(x))·g′(x).",
      "Product rule: (uv)′ = u′v + uv′."],
     [EX("Power rule", "d/dx(x³) = 3x².", "x³ → 3x²"),
      EX("Chain rule", "d/dx(sin 2x) = 2 cos 2x."),
      EX("Not differentiable", "y = |x| has a sharp corner at 0, so it has no derivative there.", "\\ /\n \\/")],
     "Draw y = x² and y = |x| on graph paper and compare how smooth they are at x = 0.",
     [Q("EASY", "d/dx(x²) = ?", ["2x", "x", "2", "x²"], "2x", "Power rule.", "2x."),
      Q("EASY", "d/dx(sin x) = ?", ["cos x", "−cos x", "sin x", "tan x"], "cos x", "A standard derivative.", "cos x."),
      Q("MEDIUM", "d/dx(5x³) at x = 1?", [], "15", "15x².", "15 × 1 = 15."),
      Q("MEDIUM", "d/dx(e^(3x)) = ?", ["3e^(3x)", "e^(3x)", "e^(3x)/3", "3x·e^(3x)"], "3e^(3x)", "Use the chain rule.", "The derivative of 3x is 3."),
      Q("HARD", "Is f(x) = |x| differentiable at x = 0?", ["No", "Yes"], "No", "Look at the sharp corner.", "Left and right slopes differ (−1 and +1)."),
      Q("HARD", "d/dx(x·sin x) = ?", ["sin x + x cos x", "cos x", "x cos x", "sin x − x cos x"], "sin x + x cos x", "Product rule.", "u′v + uv′ = sin x + x cos x.")]),
  CH("Probability",
     "Conditional probability is the probability of A given that B has happened: P(A|B) = P(A ∩ B) ÷ P(B). Events A and B are independent if P(A ∩ B) = P(A)·P(B). The multiplication rule is P(A ∩ B) = P(B)·P(A|B). The theorem of total probability and Bayes' theorem help update probabilities with new information: P(Eᵢ|A) = P(Eᵢ)P(A|Eᵢ) ÷ Σ P(Eⱼ)P(A|Eⱼ). A random variable assigns numbers to outcomes, and its mean (expected value) is Σ x·P(x).",
     ["P(A|B) = P(A ∩ B) ÷ P(B).",
      "Independent: P(A ∩ B) = P(A)·P(B).",
      "Bayes' theorem updates probabilities with new evidence.",
      "A random variable assigns numbers to outcomes.",
      "Expected value = Σ x·P(x)."],
     [EX("Conditional", "A die shows an even number. P(it is 6) = 1/3.", "⚁ ⚃ ⚅ → 6?"),
      EX("Independent", "Two coin tosses: P(two heads) = 1/2 × 1/2 = 1/4."),
      EX("Expected value", "A die's expected value = (1 + 2 + 3 + 4 + 5 + 6)/6 = 3.5.")],
     "Roll two dice 36 times, record sums, and compare the frequency of a sum of 7 with its probability 1/6.",
     [Q("EASY", "P(two heads) with two fair coins?", ["1/4", "1/2", "1/3", "3/4"], "1/4", "Independent events: multiply.", "1/2 × 1/2 = 1/4."),
      Q("EASY", "If P(A ∩ B) = 0.2 and P(B) = 0.5, P(A|B) = ?", [], "0.4", "Divide.", "0.2 ÷ 0.5 = 0.4."),
      Q("MEDIUM", "A die shows an odd number. P(it is 3)?", ["1/3", "1/6", "1/2", "1/4"], "1/3", "Odd outcomes: 1, 3, 5.", "One of three: 1/3."),
      Q("MEDIUM", "If A and B are independent, P(A) = 0.3, P(B) = 0.5, then P(A ∩ B) = ?", [], "0.15", "Multiply.", "0.3 × 0.5 = 0.15."),
      Q("HARD", "Expected value of a fair die roll?", [], "3.5", "Average of 1 to 6.", "21 ÷ 6 = 3.5."),
      Q("HARD", "Which theorem finds the probability of a cause given an observed effect?", ["Bayes' theorem", "Pythagoras' theorem", "Remainder theorem", "Binomial theorem"], "Bayes' theorem", "It reverses conditional probability.", "Bayes' theorem.")])],
 "Physics": [
  CH("Electromagnetic Induction",
     "Electromagnetic induction is the production of an EMF (voltage) in a circuit when the magnetic flux through it changes. Faraday's law says the induced EMF equals the rate of change of magnetic flux: ε = −dΦ/dt. Lenz's law says the induced current flows in a direction that opposes the change causing it, which is why there is a minus sign. Flux can change by moving a magnet, changing the area or rotating a coil. AC generators use this principle, and transformers use mutual induction to step voltage up or down: Vs/Vp = Ns/Np.",
     ["Changing magnetic flux induces an EMF.",
      "Faraday's law: ε = −dΦ/dt.",
      "Lenz's law: induced current opposes the change.",
      "AC generators use electromagnetic induction.",
      "Transformer: Vs/Vp = Ns/Np."],
     [EX("Magnet and coil", "Push a magnet into a coil and a galvanometer needle moves; pull it out and it moves the other way.", "🧲 → ⭕ → 📟"),
      EX("Transformer", "A phone charger steps 230 V down to about 5 V.", "230 V ⟶ 5 V"),
      EX("Generator", "In a power station, turbines rotate coils in a magnetic field to generate AC.")],
     "Look at a phone charger label and find its input and output voltages. Is it a step-up or step-down transformer?",
     [Q("EASY", "An EMF is induced when magnetic flux ___.", ["Changes", "Stays constant", "Is zero", "Is large but steady"], "Changes", "Faraday's key idea.", "Only changing flux induces EMF."),
      Q("EASY", "The induced current opposes the change that causes it. This is ___ law.", ["Lenz's", "Ohm's", "Coulomb's", "Newton's"], "Lenz's", "It explains the minus sign.", "This is Lenz's law."),
      Q("MEDIUM", "A transformer has Np = 100 and Ns = 500 turns. Vp = 20 V. Vs = ? (V)", [], "100", "Vs/Vp = Ns/Np.", "20 × 5 = 100 V."),
      Q("MEDIUM", "A transformer that increases voltage is ___.", ["Step-up", "Step-down"], "Step-up", "More secondary turns.", "It is step-up."),
      Q("HARD", "Flux changes from 0.5 Wb to 0.1 Wb in 0.2 s. Magnitude of induced EMF (V)?", [], "2", "|ΔΦ|/Δt.", "0.4 ÷ 0.2 = 2 V."),
      Q("HARD", "Transformers work on ___.", ["Mutual induction", "Static electricity", "Photoelectric effect", "Nuclear fission"], "Mutual induction", "Two coils affect each other.", "They use mutual induction.")]),
  CH("Dual Nature of Radiation and Matter",
     "Light behaves both as a wave and as a stream of particles called photons. The energy of a photon is E = hν, where h is Planck's constant. In the photoelectric effect, light of high enough frequency knocks electrons out of a metal surface. Einstein's photoelectric equation is Kmax = hν − φ, where φ is the work function. Below a threshold frequency, no electrons are emitted no matter how bright the light. Matter also behaves like waves: de Broglie wavelength λ = h/p = h/(mv), which is significant for tiny particles like electrons.",
     ["Light acts as both a wave and particles (photons).",
      "Photon energy E = hν.",
      "Photoelectric equation: Kmax = hν − φ.",
      "Below the threshold frequency, no electrons are emitted.",
      "de Broglie wavelength λ = h/(mv)."],
     [EX("Photoelectric effect", "UV light on zinc ejects electrons; red light does not, however bright.", "💡(UV) → ⚪⚪ e⁻"),
      EX("Solar cells", "Photons knock electrons loose to produce current.", "☀️ → ▦ → ⚡"),
      EX("Electron microscope", "Electrons' tiny wavelength lets us see very small objects.")],
     "Research how automatic doors or light meters use the photoelectric effect.",
     [Q("EASY", "A particle of light is called a ___.", ["Photon", "Proton", "Neutron", "Electron"], "Photon", "'Photo' means light.", "Light particles are photons."),
      Q("EASY", "Energy of a photon is E = ___.", ["hν", "mc", "mgh", "½mv²"], "hν", "Planck's relation.", "E = hν."),
      Q("MEDIUM", "In the photoelectric effect, emission depends on the light's ___.", ["Frequency", "Brightness only", "Colour name", "Direction"], "Frequency", "Below a threshold, nothing happens.", "It needs a minimum frequency."),
      Q("MEDIUM", "hν = 5 eV and work function φ = 2 eV. Kmax = ? (eV)", [], "3", "Kmax = hν − φ.", "5 − 2 = 3 eV."),
      Q("HARD", "de Broglie wavelength is λ = ___.", ["h/(mv)", "mv/h", "hν", "c/ν only"], "h/(mv)", "It depends on momentum.", "λ = h/p."),
      Q("HARD", "Increasing the intensity of light (above threshold) increases the ___.", ["Number of emitted electrons", "Maximum KE of electrons", "Work function", "Threshold frequency"], "Number of emitted electrons", "More photons, same energy each.", "More photons eject more electrons.")])],
 "Chemistry": [
  CH("The d- and f-Block Elements",
     "The d-block elements, found in groups 3 to 12, are called transition metals because their d orbitals are being filled. They show variable oxidation states, form coloured compounds (due to d–d transitions), act as good catalysts, form complexes, and are often paramagnetic because of unpaired electrons. Examples include iron, copper, chromium and manganese; potassium permanganate (KMnO₄) and potassium dichromate (K₂Cr₂O₇) are important oxidising agents. The f-block has the lanthanoids and actinoids; lanthanoid contraction is the steady decrease in size across the lanthanoid series.",
     ["d-block elements are transition metals (groups 3–12).",
      "They show variable oxidation states.",
      "They form coloured compounds and are good catalysts.",
      "Unpaired electrons make them paramagnetic.",
      "Lanthanoid contraction: size decreases across the series."],
     [EX("Colour", "Copper sulphate solution is blue because of d–d electron transitions.", "🔵 CuSO₄"),
      EX("Catalyst", "Iron is used as a catalyst in the Haber process to make ammonia."),
      EX("Oxidation states", "Manganese shows states from +2 to +7, as in KMnO₄ (+7).")],
     "Look at coloured transition-metal compounds (e.g. copper sulphate crystals) and note their colours.",
     [Q("EASY", "Transition elements belong to the ___-block.", ["d", "s", "p", "f"], "d", "Groups 3–12.", "They are d-block elements."),
      Q("EASY", "Which property is typical of transition metals?", ["Coloured compounds", "No oxidation states", "Always gases", "Never form complexes"], "Coloured compounds", "Think of blue copper sulphate.", "They form coloured compounds."),
      Q("MEDIUM", "The oxidation state of Mn in KMnO₄ is ___.", [], "+7|7", "K = +1, O = −2 each.", "1 + x − 8 = 0, so x = +7."),
      Q("MEDIUM", "Iron is a catalyst in the ___ process.", ["Haber", "Contact", "Solvay", "Ostwald"], "Haber", "It makes ammonia.", "The Haber process uses iron."),
      Q("HARD", "Transition metal ions are often paramagnetic because they have ___.", ["Unpaired electrons", "No electrons", "Only paired electrons", "Full shells"], "Unpaired electrons", "They are attracted by magnets.", "Unpaired d electrons cause paramagnetism."),
      Q("HARD", "The steady decrease in size across the lanthanoids is ___.", ["Lanthanoid contraction", "Inert pair effect", "Hydrogen bonding", "Resonance"], "Lanthanoid contraction", "It affects the elements that follow.", "It is lanthanoid contraction.")]),
  CH("Biomolecules",
     "Biomolecules are the molecules of life. Carbohydrates such as glucose, sucrose and starch provide energy; monosaccharides are the simplest sugars. Proteins are made of amino acids joined by peptide bonds and do jobs like building tissues and acting as enzymes. Enzymes are biological catalysts that speed up reactions in the body. Vitamins are needed in small amounts; fat-soluble vitamins are A, D, E and K, while B and C are water-soluble. Nucleic acids — DNA and RNA — carry genetic information and are made of nucleotides.",
     ["Carbohydrates provide energy; glucose is a monosaccharide.",
      "Proteins are chains of amino acids joined by peptide bonds.",
      "Enzymes are biological catalysts.",
      "Vitamins A, D, E and K are fat-soluble.",
      "DNA and RNA carry genetic information."],
     [EX("Sugars", "Sucrose (table sugar) = glucose + fructose.", "🍬 = G + F"),
      EX("Peptide bond", "Two amino acids join by a peptide bond (–CO–NH–) to form a dipeptide."),
      EX("Enzyme", "Amylase in saliva breaks starch into sugar.")],
     "Chew a piece of plain bread for a minute and notice it becoming sweeter — enzymes at work.",
     [Q("EASY", "Glucose is a ___.", ["Monosaccharide", "Disaccharide", "Polysaccharide", "Protein"], "Monosaccharide", "It is a simple sugar.", "Glucose is a monosaccharide."),
      Q("EASY", "Enzymes are biological ___.", ["Catalysts", "Fats", "Vitamins", "Minerals"], "Catalysts", "They speed up reactions.", "Enzymes are catalysts."),
      Q("MEDIUM", "Proteins are made of ___.", ["Amino acids", "Glucose", "Fatty acids only", "Nucleotides"], "Amino acids", "Joined by peptide bonds.", "Amino acids build proteins."),
      Q("MEDIUM", "Sucrose is made of glucose and ___.", [], "fructose", "Another simple sugar.", "Sucrose = glucose + fructose."),
      Q("HARD", "Which vitamin is water-soluble?", ["Vitamin C", "Vitamin A", "Vitamin D", "Vitamin K"], "Vitamin C", "Found in citrus fruits.", "Vitamins B and C are water-soluble."),
      Q("HARD", "The bond joining amino acids is the ___ bond.", ["Peptide", "Glycosidic", "Ionic", "Hydrogen"], "Peptide", "–CO–NH–.", "Amino acids join by peptide bonds.")])],
 "Biology": [
  CH("Evolution",
     "Evolution is the gradual change in living organisms over many generations. Evidence comes from fossils, comparative anatomy (homologous organs like the forelimbs of humans, whales and bats, which have the same structure but different functions), and molecular similarities in DNA and proteins. Analogous organs, such as the wings of birds and insects, do the same job but have different structures. Darwin's theory of natural selection states that individuals with variations that help them survive and reproduce pass on those traits. Industrial melanism in peppered moths is a classic example of natural selection.",
     ["Evolution is gradual change over generations.",
      "Fossils are evidence of evolution.",
      "Homologous organs: same structure, different function.",
      "Analogous organs: same function, different structure.",
      "Natural selection: the fittest survive and reproduce."],
     [EX("Homologous organs", "Human arm, whale flipper and bat wing share the same bone pattern.", "💪 🐋 🦇"),
      EX("Analogous organs", "Wings of a butterfly and a bird both help flying but are built differently.", "🦋 🐦"),
      EX("Peppered moths", "During industrial pollution, dark moths survived better on soot-covered trees.")],
     "Compare pictures of the forelimbs of five animals and find the common bones.",
     [Q("EASY", "Who proposed the theory of natural selection?", ["Charles Darwin", "Gregor Mendel", "Louis Pasteur", "Robert Hooke"], "Charles Darwin", "He sailed on HMS Beagle.", "Darwin proposed natural selection."),
      Q("EASY", "Preserved remains of ancient organisms are ___.", ["Fossils", "Genes", "Cells", "Seeds"], "Fossils", "Found in rocks.", "They are fossils."),
      Q("MEDIUM", "Human arms and whale flippers are ___ organs.", ["Homologous", "Analogous", "Vestigial", "Unrelated"], "Homologous", "Same structure, different function.", "They are homologous."),
      Q("MEDIUM", "Wings of birds and insects are ___ organs.", ["Analogous", "Homologous"], "Analogous", "Same function, different structure.", "They are analogous."),
      Q("HARD", "Industrial melanism in peppered moths is an example of ___.", ["Natural selection", "Mutation only", "Artificial selection", "Hybridisation"], "Natural selection", "Environment favoured dark moths.", "It shows natural selection."),
      Q("HARD", "According to Darwin, which individuals leave more offspring?", ["Those best adapted to the environment", "The largest only", "The oldest", "Random individuals always"], "Those best adapted to the environment", "'Survival of the fittest'.", "Better-adapted individuals reproduce more.")]),
  CH("Human Health and Disease",
     "Health is a state of complete physical, mental and social well-being. Diseases caused by pathogens are infectious: typhoid (bacterium Salmonella typhi), malaria (protozoan Plasmodium, spread by female Anopheles mosquitoes), common cold (rhinoviruses) and ringworm (fungi). Immunity is the body's ability to fight infection; innate immunity is present from birth, while acquired immunity develops after exposure or vaccination. Antibodies are proteins made by B-lymphocytes that fight antigens. AIDS is caused by HIV, which attacks helper T-cells. Drug and alcohol abuse seriously damage health.",
     ["Health is physical, mental and social well-being.",
      "Malaria is caused by Plasmodium, spread by mosquitoes.",
      "Typhoid is caused by Salmonella typhi.",
      "Vaccination builds acquired immunity.",
      "HIV attacks helper T-cells and causes AIDS."],
     [EX("Vaccination", "A vaccine trains the immune system with a harmless form of the pathogen.", "💉 → 🛡️"),
      EX("Antibody", "Antibodies are Y-shaped proteins that bind to antigens.", "  Y\n antibody"),
      EX("Prevention", "Using mosquito nets and removing stagnant water helps prevent malaria.", "🦟🚫")],
     "Make a chart of five diseases, their causes, how they spread and how to prevent them.",
     [Q("EASY", "Malaria is caused by ___.", ["Plasmodium", "A virus", "A fungus", "A worm"], "Plasmodium", "A protozoan.", "Plasmodium causes malaria."),
      Q("EASY", "Vaccines help the body develop ___.", ["Immunity", "Allergies", "Diseases", "Fever only"], "Immunity", "Protection against disease.", "Vaccines build immunity."),
      Q("MEDIUM", "Antibodies are produced by ___.", ["B-lymphocytes", "Red blood cells", "Platelets", "Neurons"], "B-lymphocytes", "A type of white blood cell.", "B-cells make antibodies."),
      Q("MEDIUM", "Typhoid is caused by the bacterium ___.", ["Salmonella typhi", "Plasmodium vivax", "Rhinovirus", "HIV"], "Salmonella typhi", "Named after the disease.", "Salmonella typhi causes typhoid."),
      Q("HARD", "HIV mainly attacks ___.", ["Helper T-cells", "Red blood cells", "Liver cells", "Bone cells"], "Helper T-cells", "It weakens the immune system.", "HIV targets helper T-cells."),
      Q("HARD", "Immunity present from birth is ___ immunity.", ["Innate", "Acquired", "Artificial", "Passive only"], "Innate", "You are born with it.", "It is innate immunity.")])],
 "English": [
  CH("Formal Invitations and Replies",
     "A formal invitation is a printed or written card inviting people to an official event, such as a school function or wedding. It is written in the third person (for example, 'The Principal requests the pleasure of your company…'). It includes the occasion, date, day, time, venue and RSVP details, but no salutation or signature. A formal reply, also in the third person, accepts or declines the invitation and thanks the host. Informal invitations, by contrast, are written as friendly letters in the first person.",
     ["Formal invitations are written in the third person.",
      "Include occasion, date, day, time and venue.",
      "RSVP asks the guest to reply.",
      "No salutation or signature on a formal invitation.",
      "Replies are also in the third person."],
     [EX("Invitation", "The Principal and Staff of ABC School request the pleasure of your company at the Annual Day on Friday, 10 January, at 5 p.m. in the school auditorium. RSVP: 98xxxxxx12", "💌"),
      EX("Acceptance", "Mr and Mrs Rao thank the Principal for the kind invitation and are pleased to accept."),
      EX("Refusal", "Ms Sen thanks the Principal for the invitation but regrets her inability to attend due to prior commitments.")],
     "Design a formal invitation card for your school's Science Exhibition.",
     [Q("EASY", "Formal invitations are written in the ___ person.", ["Third", "First", "Second"], "Third", "'The Principal requests…'", "They use the third person."),
      Q("EASY", "RSVP asks the guest to ___.", ["Reply", "Bring a gift", "Dress formally", "Arrive early"], "Reply", "French: 'Répondez s'il vous plaît'.", "RSVP means 'please reply'."),
      Q("MEDIUM", "Which is NOT part of a formal invitation?", ["Salutation like 'Dear Sir'", "Date and time", "Venue", "Occasion"], "Salutation like 'Dear Sir'", "It isn't a letter.", "Formal invitations have no salutation."),
      Q("MEDIUM", "Which line suits a formal invitation?", ["The Principal requests the pleasure of your company…", "Hey, come to our party!", "I want you to come.", "Please be there, buddy."], "The Principal requests the pleasure of your company…", "Third person, formal.", "It is formal and in the third person."),
      Q("HARD", "A polite formal refusal usually mentions ___.", ["Regret and a reason", "Anger", "A joke", "A demand"], "Regret and a reason", "Be gracious.", "Express regret and give a reason."),
      Q("HARD", "Informal invitations are written in the ___ person.", ["First", "Third"], "First", "'I would love you to come…'", "Informal invitations use the first person.")]),
  CH("Job Application Letter",
     "A job application letter is a formal letter written to apply for a job. It follows the formal letter format: sender's address, date, receiver's designation and address, subject line, salutation, body and complimentary close. The body refers to the advertisement, states the post applied for, briefly highlights suitable qualifications and experience, and expresses willingness for an interview. A separate résumé (bio-data) lists personal details, education, experience, skills and references. The tone is polite, confident and concise.",
     ["It follows the formal letter format.",
      "Mention the advertisement and the post.",
      "Highlight relevant qualifications briefly.",
      "Attach a résumé with education and skills.",
      "Keep the tone polite, confident and concise."],
     [EX("Subject", "Subject: Application for the post of Junior Accountant"),
      EX("Opening", "With reference to your advertisement in The Hindu dated 5 March, I wish to apply for the post of…"),
      EX("Résumé section", "Educational Qualifications: Class XII (CBSE), 2025 — 92%", "📄")],
     "Find a job advertisement in a newspaper and write an application letter with a short résumé.",
     [Q("EASY", "A job application letter is a ___ letter.", ["Formal", "Informal"], "Formal", "It's written to an employer.", "It is formal."),
      Q("EASY", "The document listing education and skills is the ___.", ["Résumé", "Notice", "Invitation", "Report"], "Résumé", "Also called bio-data or CV.", "It is the résumé."),
      Q("MEDIUM", "The body should first mention ___.", ["The advertisement and the post", "Your hobbies", "Your salary demand", "Your family"], "The advertisement and the post", "Why you are writing.", "Refer to the ad and state the post."),
      Q("MEDIUM", "Which closing suits a job application?", ["Yours faithfully", "Love", "Cheers", "Bye"], "Yours faithfully", "Formal close.", "'Yours faithfully' is formal."),
      Q("HARD", "Which sentence is best for a job application?", ["I am confident that my skills in accounting will benefit your organisation.", "I really need money, please hire me.", "I am the best person ever.", "Give me the job now."], "I am confident that my skills in accounting will benefit your organisation.", "Confident but polite.", "It is professional and specific."),
      Q("HARD", "The tone of a job application should be ___.", ["Polite and confident", "Casual and funny", "Demanding", "Emotional"], "Polite and confident", "Make a good impression.", "Polite and confident.")])],
 "Computer Science": [
  CH("Data Structures: Stacks",
     "A data structure is a way of organising data so it can be used efficiently. A stack is a linear data structure that follows LIFO — Last In, First Out — like a pile of plates. Adding an item is called push, and removing the top item is called pop. Peek returns the top item without removing it. Trying to pop from an empty stack causes underflow. In Python, a list can be used as a stack with append() for push and pop() for pop. Stacks are used for undo features, checking balanced brackets, and function calls.",
     ["A stack follows LIFO: Last In, First Out.",
      "Push adds to the top; pop removes from the top.",
      "Peek looks at the top without removing it.",
      "Popping an empty stack causes underflow.",
      "In Python, use list.append() and list.pop()."],
     [EX("Plates", "You add plates on top and take the top one first.", "🍽️ ← top\n🍽️\n🍽️"),
      EX("Python", "s = []; s.append(1); s.append(2); s.pop() → 2."),
      EX("Undo", "A text editor stores actions on a stack; undo pops the latest one.")],
     "Write a Python program that uses a stack to check whether brackets in an expression are balanced.",
     [Q("EASY", "A stack follows ___.", ["LIFO", "FIFO", "Random order", "Alphabetical order"], "LIFO", "Last In, First Out.", "Stacks are LIFO."),
      Q("EASY", "Adding an item to a stack is called ___.", ["Push", "Pop", "Peek", "Sort"], "Push", "Push it on top.", "It is push."),
      Q("MEDIUM", "After push 5, push 8, push 3, pop — which item is removed?", [], "3", "Last in, first out.", "3 was pushed last, so it is popped."),
      Q("MEDIUM", "Popping from an empty stack is called ___.", ["Underflow", "Overflow", "Push", "Peek"], "Underflow", "There is nothing to remove.", "It is underflow."),
      Q("HARD", "Which Python list method removes and returns the last item?", ["pop()", "remove()", "append()", "insert()"], "pop()", "It 'pops' the top.", "list.pop() removes the last item."),
      Q("HARD", "Which is a typical use of a stack?", ["Undo in a text editor", "Printer queue", "Sorting a phone book", "Storing images"], "Undo in a text editor", "The last action is undone first.", "Undo follows LIFO.")]),
  CH("Computer Networks",
     "A computer network connects devices so they can share data and resources. Networks are classified by size: PAN (personal), LAN (building or campus), MAN (city) and WAN (country or world; the Internet is the largest WAN). Network devices include the modem, switch, router and Wi-Fi access point. Topologies describe how devices are connected, such as star, bus, ring and mesh. Protocols are rules for communication: HTTP/HTTPS for web pages, TCP/IP for data transfer, SMTP for email and FTP for files. Every device on a network has an IP address.",
     ["A network connects devices to share data.",
      "PAN < LAN < MAN < WAN (the Internet is a WAN).",
      "A router connects different networks.",
      "Topologies: star, bus, ring, mesh.",
      "Protocols: HTTP, TCP/IP, SMTP, FTP."],
     [EX("Star topology", "All computers connect to a central switch.", "  💻\n💻-⭐-💻\n  💻"),
      EX("Router at home", "Your Wi-Fi router connects your home LAN to the Internet."),
      EX("HTTPS", "The padlock in the browser means HTTPS is encrypting your data.", "🔒")],
     "Draw the network in your home or school: which devices connect to the router and how?",
     [Q("EASY", "The Internet is an example of a ___.", ["WAN", "LAN", "PAN", "MAN"], "WAN", "It covers the world.", "It is the largest WAN."),
      Q("EASY", "A network in one school building is a ___.", ["LAN", "WAN", "MAN", "PAN"], "LAN", "Local Area Network.", "It is a LAN."),
      Q("MEDIUM", "Which device connects different networks?", ["Router", "Keyboard", "Monitor", "Printer"], "Router", "It routes data.", "A router connects networks."),
      Q("MEDIUM", "Which protocol is used to send email?", ["SMTP", "HTTP", "FTP", "HTML"], "SMTP", "Simple Mail Transfer Protocol.", "SMTP sends email."),
      Q("HARD", "In which topology are all devices connected to a central hub or switch?", ["Star", "Bus", "Ring", "Mesh"], "Star", "Like the points of a star.", "It is star topology."),
      Q("HARD", "What does the 'S' in HTTPS stand for?", ["Secure", "Simple", "Server", "System"], "Secure", "It encrypts data.", "HTTPS = HTTP Secure.")])],
 "Economics": [
  CH("Government Budget",
     "A government budget is a statement of the government's expected receipts and expenditures for a financial year (1 April to 31 March in India). Receipts are revenue receipts, such as taxes, and capital receipts, such as borrowings. Expenditures are revenue expenditure, such as salaries and interest, and capital expenditure, such as building roads and schools. Taxes can be direct (income tax, corporation tax) or indirect (GST). Fiscal deficit = total expenditure − total receipts excluding borrowings; it shows how much the government must borrow.",
     ["A budget shows expected receipts and expenditure for a year.",
      "India's financial year: 1 April to 31 March.",
      "Direct taxes: income tax. Indirect taxes: GST.",
      "Capital expenditure creates assets like roads.",
      "Fiscal deficit shows government borrowing."],
     [EX("Direct vs indirect", "Income tax is paid directly by the earner; GST is added to prices.", "💰 → 🏛️  vs  🛒 + GST"),
      EX("Capital expenditure", "Building a new metro line is capital expenditure."),
      EX("Fiscal deficit", "If spending is ₹100 cr and non-borrowed receipts are ₹80 cr, fiscal deficit = ₹20 cr.")],
     "Read a news summary of the latest Union Budget and list three new spending plans.",
     [Q("EASY", "India's financial year runs from ___.", ["1 April to 31 March", "1 January to 31 December", "1 July to 30 June", "15 August to 14 August"], "1 April to 31 March", "Budget is presented before it starts.", "1 April to 31 March."),
      Q("EASY", "Income tax is a ___ tax.", ["Direct", "Indirect"], "Direct", "Paid by the person who earns.", "Income tax is direct."),
      Q("MEDIUM", "GST is a(n) ___ tax.", ["Indirect", "Direct"], "Indirect", "It is added to prices.", "GST is indirect."),
      Q("MEDIUM", "Building a new highway is ___ expenditure.", ["Capital", "Revenue"], "Capital", "It creates an asset.", "Asset-creating spending is capital expenditure."),
      Q("HARD", "Total expenditure ₹500 cr; receipts excluding borrowings ₹420 cr. Fiscal deficit (₹ cr)?", [], "80", "Expenditure − non-borrowed receipts.", "500 − 420 = ₹80 cr."),
      Q("HARD", "A high fiscal deficit means the government ___.", ["Must borrow more", "Has extra money", "Pays no interest", "Collects more taxes automatically"], "Must borrow more", "It spends more than it earns.", "It indicates more borrowing.")]),
  CH("Balance of Payments and Exchange Rate",
     "The balance of payments (BoP) records all economic transactions between a country and the rest of the world in a year. The current account includes trade in goods (exports and imports), services, and transfers such as remittances. The capital account includes foreign investment, loans and borrowings. A trade deficit occurs when imports exceed exports. The exchange rate is the price of one currency in terms of another, such as ₹83 per US dollar. When the rupee depreciates, imports become costlier and exports become cheaper for foreigners. Exchange rates can be fixed, flexible (set by the market) or managed.",
     ["BoP records transactions with the rest of the world.",
      "Current account: goods, services and transfers.",
      "Capital account: investment and loans.",
      "Trade deficit: imports > exports.",
      "Rupee depreciation makes imports costlier and exports cheaper."],
     [EX("Trade deficit", "If India exports $400 bn and imports $600 bn of goods, the trade deficit is $200 bn.", "📦⬆ 400  📦⬇ 600"),
      EX("Exchange rate", "At ₹80 per $, a $10 book costs ₹800; at ₹85 per $, it costs ₹850.", "💵 → ₹"),
      EX("Remittances", "Money sent home by Indians working abroad is a current account receipt.")],
     "Track the rupee–dollar exchange rate for a week and note whether the rupee rose or fell.",
     [Q("EASY", "When imports exceed exports, there is a trade ___.", ["Deficit", "Surplus", "Balance", "Profit"], "Deficit", "More going out than coming in.", "It is a trade deficit."),
      Q("EASY", "The price of one currency in terms of another is the ___.", ["Exchange rate", "Interest rate", "Tax rate", "Inflation rate"], "Exchange rate", "₹ per $.", "It is the exchange rate."),
      Q("MEDIUM", "Trade in goods and services is recorded in the ___ account.", ["Current", "Capital"], "Current", "Day-to-day transactions.", "It is the current account."),
      Q("MEDIUM", "Foreign direct investment is recorded in the ___ account.", ["Capital", "Current"], "Capital", "It involves assets.", "FDI is in the capital account."),
      Q("HARD", "If the rupee depreciates, Indian exports become ___ for foreign buyers.", ["Cheaper", "Costlier", "Unchanged", "Banned"], "Cheaper", "Their currency buys more rupees.", "Depreciation makes exports cheaper abroad."),
      Q("HARD", "An exchange rate set by market demand and supply is ___.", ["Flexible", "Fixed", "Managed only by law", "Constant"], "Flexible", "It floats.", "It is a flexible (floating) rate.")])],
}
