# Additional chapters for Grade 10.
from grade6 import Q, EX
from more6_7 import CH

MORE10 = {
 "Mathematics": [
  CH("Introduction to Trigonometry",
     "Trigonometry studies the relationship between the sides and angles of a right-angled triangle. For an angle θ: sin θ = opposite ÷ hypotenuse, cos θ = adjacent ÷ hypotenuse, and tan θ = opposite ÷ adjacent. Standard values are useful: sin 30° = 1/2, cos 60° = 1/2, tan 45° = 1, sin 90° = 1 and cos 0° = 1. The identity sin²θ + cos²θ = 1 is true for every angle. Trigonometry helps find heights and distances, such as the height of a tower.",
     ["sin θ = opposite ÷ hypotenuse.",
      "cos θ = adjacent ÷ hypotenuse.",
      "tan θ = opposite ÷ adjacent.",
      "sin 30° = 1/2; tan 45° = 1.",
      "sin²θ + cos²θ = 1."],
     [EX("SOH CAH TOA", "A memory trick: Sin = Opp/Hyp, Cos = Adj/Hyp, Tan = Opp/Adj.", "   /|\nH / | O\n /θ_|\n   A"),
      EX("3-4-5 triangle", "With opposite 3, adjacent 4, hypotenuse 5: sin θ = 3/5, cos θ = 4/5, tan θ = 3/4."),
      EX("Height of a tree", "Standing 10 m away, the top is at 45°, so the height is 10 × tan 45° = 10 m.", "🌳 ↗ 45°")],
     "Use a protractor and a straw to measure the angle to the top of a pole and estimate its height.",
     [Q("EASY", "sin θ = ___ ÷ hypotenuse.", ["Opposite", "Adjacent", "Hypotenuse", "Angle"], "Opposite", "SOH.", "sin = opposite/hypotenuse."),
      Q("EASY", "tan 45° = ?", [], "1", "Opposite and adjacent are equal.", "tan 45° = 1."),
      Q("MEDIUM", "In a right triangle, opposite = 3, hypotenuse = 5. sin θ = ?", ["3/5", "4/5", "3/4", "5/3"], "3/5", "Opposite over hypotenuse.", "sin θ = 3/5."),
      Q("MEDIUM", "sin²θ + cos²θ = ?", [], "1", "A basic identity.", "It always equals 1."),
      Q("HARD", "cos 60° = ?", ["1/2", "√3/2", "1", "0"], "1/2", "Same as sin 30°.", "cos 60° = 1/2."),
      Q("HARD", "A ladder makes 60° with the ground; its foot is 2 m from the wall. Ladder length (m)?", [], "4", "cos 60° = adjacent ÷ ladder.", "2 ÷ (1/2) = 4 m.")]),
  CH("Probability",
     "Probability measures how likely an event is to happen. For equally likely outcomes, P(E) = number of favourable outcomes ÷ total number of outcomes. Probability is always between 0 and 1. An event that is certain has probability 1, and an impossible event has probability 0. The probability of an event not happening is 1 − P(E). For example, the probability of getting a head when tossing a fair coin is 1/2, and of getting a 4 on a die is 1/6.",
     ["P(E) = favourable outcomes ÷ total outcomes.",
      "Probability is between 0 and 1.",
      "Certain event = 1; impossible event = 0.",
      "P(not E) = 1 − P(E).",
      "Coin: P(head) = 1/2; die: P(4) = 1/6."],
     [EX("Coin", "A coin has 2 equally likely outcomes; P(head) = 1/2.", "🪙 H | T"),
      EX("Die", "P(even number) = 3/6 = 1/2 (2, 4, 6).", "⚀ ⚁ ⚂ ⚃ ⚄ ⚅"),
      EX("Bag of balls", "3 red and 2 blue balls: P(red) = 3/5, P(not red) = 2/5.", "🔴🔴🔴🔵🔵")],
     "Toss a coin 20 times, record heads and tails, and compare with the theoretical probability 1/2.",
     [Q("EASY", "Probability of getting a head on a fair coin?", ["1/2", "1", "0", "1/4"], "1/2", "Two equally likely outcomes.", "P(head) = 1/2."),
      Q("EASY", "The probability of an impossible event is ___.", [], "0", "It can never happen.", "Impossible events have probability 0."),
      Q("MEDIUM", "Probability of rolling a 5 on a die?", ["1/6", "1/5", "5/6", "1/2"], "1/6", "One favourable out of six.", "P(5) = 1/6."),
      Q("MEDIUM", "If P(E) = 0.3, then P(not E) = ?", [], "0.7", "1 − P(E).", "1 − 0.3 = 0.7."),
      Q("HARD", "A bag has 4 red and 6 green balls. P(green) = ?", ["3/5", "2/5", "6/4", "1/6"], "3/5", "6 out of 10.", "6/10 = 3/5."),
      Q("HARD", "Probability of getting a prime number on a die?", ["1/2", "1/3", "2/3", "1/6"], "1/2", "Primes: 2, 3, 5.", "3/6 = 1/2.")])],
 "Physics": [
  CH("The Human Eye and the Colourful World",
     "The human eye works like a camera. Light enters through the cornea, the iris controls the size of the pupil, and the eye lens focuses light on the retina, which sends signals to the brain through the optic nerve. The eye adjusts its focal length to see near and far objects; this is called accommodation. Myopia (short-sightedness) is corrected with a concave lens, and hypermetropia (long-sightedness) with a convex lens. A prism splits white light into seven colours (VIBGYOR), which is called dispersion. The sky looks blue because air molecules scatter blue light more than red.",
     ["The lens focuses light on the retina.",
      "The iris controls the pupil size.",
      "Myopia is corrected by a concave lens.",
      "Hypermetropia is corrected by a convex lens.",
      "The sky is blue because blue light scatters most."],
     [EX("Eye as a camera", "Cornea and lens = camera lens; retina = the screen.", "👁️ → 📷"),
      EX("Rainbow", "Raindrops disperse sunlight into VIBGYOR colours.", "🌈 V I B G Y O R"),
      EX("Red sunset", "At sunset, light travels a longer path; blue scatters away and red reaches us.", "🌅")],
     "Look at a CD or a glass of water in sunlight and observe the colours formed by dispersion.",
     [Q("EASY", "The part of the eye where the image forms is the ___.", ["Retina", "Iris", "Cornea", "Pupil"], "Retina", "It is like a screen.", "Images form on the retina."),
      Q("EASY", "Splitting of white light into colours is ___.", ["Dispersion", "Reflection", "Absorption", "Magnification"], "Dispersion", "A prism does this.", "It is dispersion."),
      Q("MEDIUM", "Myopia is corrected using a ___ lens.", ["Concave", "Convex", "Cylindrical", "Bifocal only"], "Concave", "It spreads light out.", "A concave lens corrects myopia."),
      Q("MEDIUM", "Which part controls the amount of light entering the eye?", ["Iris", "Retina", "Optic nerve", "Lens"], "Iris", "It is the coloured part.", "The iris adjusts the pupil."),
      Q("HARD", "Why is the sky blue?", ["Blue light is scattered more by air", "The sea reflects blue", "The Sun is blue", "Clouds are blue"], "Blue light is scattered more by air", "Shorter wavelengths scatter more.", "Air molecules scatter blue light the most."),
      Q("HARD", "The ability of the eye to change its focal length is called ___.", [], "accommodation", "It helps us see near and far.", "This is accommodation.")]),
  CH("Sources of Energy",
     "A good source of energy gives a lot of energy per unit mass, is easy to store and transport, and is affordable. Fossil fuels such as coal, petroleum and natural gas are non-renewable and cause pollution. Renewable sources include solar energy (solar panels and cookers), wind energy (windmills), hydroelectric power (dams), biogas (from animal and plant waste) and geothermal energy. Nuclear energy comes from nuclear fission and gives huge energy but produces dangerous waste. Using renewable energy and saving energy help protect the environment.",
     ["Fossil fuels are non-renewable and pollute.",
      "Solar, wind and hydro energy are renewable.",
      "Biogas comes from animal and plant waste.",
      "Nuclear fission releases huge energy.",
      "Saving energy protects the environment."],
     [EX("Solar panel", "Solar cells turn sunlight directly into electricity.", "☀️ → ▦ → ⚡"),
      EX("Wind farm", "Wind turns the blades of windmills to generate electricity.", "🌬️ → 🌀 → ⚡"),
      EX("Biogas", "Cow dung in a biogas plant produces methane gas for cooking.")],
     "List all the energy sources your home uses and suggest one way to switch to a renewable source.",
     [Q("EASY", "Which is a renewable source of energy?", ["Coal", "Petroleum", "Solar", "Natural gas"], "Solar", "The Sun keeps shining.", "Solar energy is renewable."),
      Q("EASY", "Coal and petroleum are ___ fuels.", ["Fossil", "Nuclear", "Solar", "Wind"], "Fossil", "Formed from ancient life.", "They are fossil fuels."),
      Q("MEDIUM", "Solar cells convert sunlight into ___.", ["Electricity", "Wind", "Water", "Coal"], "Electricity", "Used on rooftops.", "They produce electricity."),
      Q("MEDIUM", "The main gas in biogas is ___.", ["Methane", "Oxygen", "Nitrogen", "Hydrogen"], "Methane", "It burns with a blue flame.", "Biogas is mostly methane."),
      Q("HARD", "Nuclear power plants use ___ to release energy.", ["Nuclear fission", "Photosynthesis", "Evaporation", "Friction"], "Nuclear fission", "Splitting heavy nuclei.", "Fission splits uranium nuclei."),
      Q("HARD", "A major problem with nuclear energy is ___.", ["Safe disposal of radioactive waste", "It gives too little energy", "It needs sunlight", "It is renewable"], "Safe disposal of radioactive waste", "The waste stays dangerous for a long time.", "Radioactive waste is hard to dispose of safely.")])],
 "Chemistry": [
  CH("Metals and Non-metals",
     "Metals are generally lustrous, malleable, ductile and good conductors, while non-metals are usually dull, brittle and poor conductors. Metals lose electrons to form positive ions, and non-metals gain electrons to form negative ions; together they form ionic compounds such as NaCl, which have high melting points and conduct electricity when dissolved. The reactivity series lists metals from most reactive (potassium, sodium) to least reactive (gold, silver). Metals are extracted from ores by methods that depend on their reactivity. Corrosion, such as rusting of iron, can be prevented by painting, oiling or galvanising.",
     ["Metals lose electrons; non-metals gain electrons.",
      "Ionic compounds have high melting points.",
      "Reactivity series: K, Na, Ca, Mg, Al, Zn, Fe, … Cu, Ag, Au.",
      "Ores are processed to extract metals.",
      "Galvanising and painting prevent rusting."],
     [EX("Ionic bond", "Na gives an electron to Cl → Na⁺ and Cl⁻ attract.", "Na → e⁻ → Cl"),
      EX("Reactivity", "Sodium reacts violently with water, so it is stored in kerosene.", "🧪💥"),
      EX("Rust prevention", "Iron gates are painted to stop air and water reaching the iron.")],
     "Leave three iron nails in (a) dry air, (b) water, (c) oil-covered water for a week and compare rusting.",
     [Q("EASY", "Metals form ___ ions.", ["Positive", "Negative", "Neutral"], "Positive", "They lose electrons.", "Metals form positive ions."),
      Q("EASY", "Which metal is the least reactive?", ["Gold", "Sodium", "Iron", "Zinc"], "Gold", "It stays shiny for centuries.", "Gold is at the bottom of the reactivity series."),
      Q("MEDIUM", "Sodium is stored in kerosene because ___.", ["It reacts violently with air and water", "It is a liquid", "It is heavy", "It smells"], "It reacts violently with air and water", "It is very reactive.", "Kerosene keeps air and moisture away."),
      Q("MEDIUM", "Coating iron with zinc to prevent rusting is ___.", [], "galvanisation|galvanization|galvanising|galvanizing", "Galvanised iron buckets.", "It is galvanisation."),
      Q("HARD", "Ionic compounds conduct electricity when ___.", ["Dissolved in water or molten", "Solid", "Cold", "Powdered"], "Dissolved in water or molten", "Ions must be free to move.", "Ions move freely in solution or melt."),
      Q("HARD", "A naturally occurring mineral from which a metal is extracted profitably is an ___.", ["Ore", "Alloy", "Oxide only", "Acid"], "Ore", "Haematite for iron.", "It is an ore.")]),
  CH("Periodic Classification of Elements",
     "Scientists arranged elements to find patterns. Döbereiner grouped elements in triads, and Newlands proposed the law of octaves. Mendeleev arranged elements by increasing atomic mass and left gaps for undiscovered elements. The Modern Periodic Table, based on Moseley's work, arranges elements by increasing atomic number. It has 18 vertical groups and 7 horizontal periods. Elements in the same group have the same number of valence electrons and similar properties. Across a period, atomic size decreases and metallic character decreases; down a group, atomic size increases.",
     ["The Modern Periodic Table is arranged by atomic number.",
      "It has 18 groups and 7 periods.",
      "Same group = same valence electrons = similar properties.",
      "Across a period, atomic size decreases.",
      "Down a group, atomic size increases."],
     [EX("Group 1", "Lithium, sodium and potassium all have 1 valence electron and react with water.", "Li\nNa\nK"),
      EX("Mendeleev's gaps", "He predicted 'eka-aluminium', later discovered as gallium."),
      EX("Period trend", "In period 3, sodium is a metal and chlorine is a non-metal.", "Na Mg Al Si P S Cl →")],
     "Make a periodic-table puzzle of the first 20 elements and group them by valence electrons.",
     [Q("EASY", "The Modern Periodic Table is arranged by increasing ___.", ["Atomic number", "Atomic mass", "Colour", "Density"], "Atomic number", "Moseley showed this.", "It is ordered by atomic number."),
      Q("EASY", "How many groups are in the Modern Periodic Table?", [], "18", "Vertical columns.", "There are 18 groups."),
      Q("MEDIUM", "Who arranged elements by atomic mass and left gaps?", ["Mendeleev", "Newlands", "Döbereiner", "Moseley"], "Mendeleev", "He predicted new elements.", "Mendeleev left gaps for undiscovered elements."),
      Q("MEDIUM", "Elements in the same group have the same number of ___.", ["Valence electrons", "Neutrons", "Protons", "Shells"], "Valence electrons", "It decides chemical properties.", "They share valence electron count."),
      Q("HARD", "Across a period from left to right, atomic size ___.", ["Decreases", "Increases", "Stays the same", "Doubles"], "Decreases", "Nuclear charge pulls electrons in.", "Atomic radius decreases across a period."),
      Q("HARD", "How many periods are in the Modern Periodic Table?", [], "7|seven", "Horizontal rows.", "There are 7 periods.")])],
 "Biology": [
  CH("Control and Coordination",
     "Animals control and coordinate body activities using the nervous system and hormones. The nervous system is made of neurons that carry electrical messages. The brain and spinal cord form the central nervous system. A reflex action is a quick, automatic response, like pulling your hand away from something hot, controlled by the spinal cord through a reflex arc. Hormones are chemical messengers made by endocrine glands; for example, insulin from the pancreas controls blood sugar and adrenaline prepares the body for emergencies. Plants respond using plant hormones such as auxin, which makes shoots bend towards light (phototropism).",
     ["Neurons carry electrical messages.",
      "The brain and spinal cord form the central nervous system.",
      "A reflex action is fast and automatic.",
      "Hormones are chemical messengers.",
      "Plants bend towards light because of auxin."],
     [EX("Reflex arc", "Touch a hot pan → sensory nerve → spinal cord → motor nerve → hand pulls away.", "🔥✋ → 🧠(spinal cord) → 💪"),
      EX("Insulin", "Lack of insulin causes high blood sugar (diabetes)."),
      EX("Phototropism", "A plant on a windowsill grows towards the light.", "🪴 ↗ ☀️")],
     "Test your reflexes: have a friend drop a ruler and see how quickly you catch it.",
     [Q("EASY", "The basic unit of the nervous system is the ___.", ["Neuron", "Nephron", "Alveolus", "Villus"], "Neuron", "Nerve cell.", "Neurons carry messages."),
      Q("EASY", "Pulling your hand away from a hot object is a ___ action.", ["Reflex", "Voluntary", "Slow", "Hormonal"], "Reflex", "It happens without thinking.", "It is a reflex action."),
      Q("MEDIUM", "Which hormone controls blood sugar?", ["Insulin", "Adrenaline", "Thyroxine", "Auxin"], "Insulin", "Made by the pancreas.", "Insulin lowers blood sugar."),
      Q("MEDIUM", "The growth of plant shoots towards light is called ___.", [], "phototropism", "'Photo' means light.", "It is phototropism."),
      Q("HARD", "Which hormone prepares the body for 'fight or flight'?", ["Adrenaline", "Insulin", "Growth hormone", "Auxin"], "Adrenaline", "It speeds up the heart.", "Adrenaline prepares for emergencies."),
      Q("HARD", "Reflex actions are mainly controlled by the ___.", ["Spinal cord", "Cerebrum", "Heart", "Stomach"], "Spinal cord", "The message doesn't go to the brain first.", "The spinal cord controls reflex arcs.")]),
  CH("How Do Organisms Reproduce?",
     "Reproduction produces new individuals and keeps a species going. Asexual reproduction involves one parent and produces offspring identical to the parent; methods include binary fission (Amoeba), budding (Hydra, yeast), fragmentation (Spirogyra), spore formation (bread mould) and vegetative propagation (potato, rose cuttings). Sexual reproduction involves two parents and the fusion of male and female gametes (fertilisation), producing offspring with variation. In flowering plants, pollination transfers pollen to the stigma, and after fertilisation the ovule becomes a seed and the ovary becomes a fruit.",
     ["Asexual reproduction needs one parent.",
      "Binary fission, budding and spores are asexual methods.",
      "Sexual reproduction needs two parents.",
      "Fertilisation is the fusion of gametes.",
      "After fertilisation, the ovary becomes the fruit."],
     [EX("Binary fission", "Amoeba splits into two daughter cells.", "◯ → ◯◯"),
      EX("Budding", "A small bud grows on Hydra and breaks off as a new Hydra."),
      EX("Pollination", "Bees carry pollen from one flower to another.", "🌸 → 🐝 → 🌼")],
     "Plant a potato piece with an 'eye' and a rose cutting, and watch new plants grow.",
     [Q("EASY", "Amoeba reproduces by ___.", ["Binary fission", "Budding", "Spores", "Pollination"], "Binary fission", "It splits into two.", "Amoeba divides by binary fission."),
      Q("EASY", "Reproduction with only one parent is ___.", ["Asexual", "Sexual"], "Asexual", "No gametes needed.", "It is asexual reproduction."),
      Q("MEDIUM", "Hydra reproduces by ___.", ["Budding", "Binary fission", "Fragmentation", "Seeds"], "Budding", "A small outgrowth forms.", "Hydra reproduces by budding."),
      Q("MEDIUM", "Transfer of pollen to the stigma is ___.", [], "pollination", "Bees help with it.", "This is pollination."),
      Q("HARD", "After fertilisation, the ovary develops into the ___.", ["Fruit", "Seed", "Flower", "Leaf"], "Fruit", "Think of a mango.", "The ovary becomes the fruit."),
      Q("HARD", "Why does sexual reproduction create variation?", ["It combines genes from two parents", "It copies one parent exactly", "It happens only in plants", "It needs no gametes"], "It combines genes from two parents", "Two sets of genes mix.", "Mixing genes from two parents creates variation.")])],
 "English": [
  CH("Analytical Paragraph Writing",
     "An analytical paragraph describes and interprets data given in a chart, graph or table. It begins with an introduction that states what the data shows and its time period. The body describes the main trends — increases, decreases, highest and lowest values — using figures from the data. Comparisons are made using words like 'while', 'whereas' and 'in contrast'. It ends with a conclusion that sums up the overall pattern. The tone is formal and objective, without personal opinions.",
     ["It describes data from a chart, graph or table.",
      "Start by stating what the data shows.",
      "Describe trends with figures: rise, fall, peak.",
      "Compare using 'while', 'whereas', 'in contrast'.",
      "End with the overall pattern; stay objective."],
     [EX("Introduction", "The bar graph shows the number of students using bicycles from 2019 to 2023."),
      EX("Trend language", "The number rose steadily from 200 to 350, peaking in 2022.", "▂▃▅▇▆"),
      EX("Conclusion", "Overall, bicycle use increased over the five years.")],
     "Draw a bar graph of the hours you studied each day this week and write an analytical paragraph about it.",
     [Q("EASY", "An analytical paragraph is based on ___.", ["Data in a chart or table", "A fairy tale", "A personal diary", "A poem"], "Data in a chart or table", "It analyses information.", "It interprets given data."),
      Q("EASY", "Which word describes an increase?", ["Rose", "Fell", "Dropped", "Declined"], "Rose", "Going up.", "'Rose' shows an increase."),
      Q("MEDIUM", "The tone of an analytical paragraph should be ___.", ["Formal and objective", "Emotional", "Humorous", "Persuasive"], "Formal and objective", "Stick to the facts.", "It must be formal and objective."),
      Q("MEDIUM", "Which word is used for comparison?", ["Whereas", "Hooray", "Suddenly", "Because of me"], "Whereas", "It contrasts two things.", "'Whereas' compares."),
      Q("HARD", "Which sentence best suits an analytical paragraph?", ["Sales increased by 20% between January and March.", "I love this chart!", "Maybe sales did something.", "Sales are boring."], "Sales increased by 20% between January and March.", "Precise and factual.", "It uses data and is objective."),
      Q("HARD", "The highest point in a graph is often called the ___.", ["Peak", "Base", "Axis", "Legend"], "Peak", "Think of a mountain top.", "The highest value is the peak.")]),
  CH("Integrated Grammar: Editing",
     "Editing means finding and correcting errors in a passage. Common errors include wrong verb tense, subject–verb agreement, missing or wrong articles, incorrect prepositions, and wrong word forms. A good method is to read each sentence slowly, check the verb and its subject, then check small words like a, an, the, in, on and at. In exams, you write the incorrect word and its correction. Careful editing makes writing clear and correct.",
     ["Editing means finding and correcting errors.",
      "Check verb tense and subject–verb agreement.",
      "Check articles: a, an, the.",
      "Check prepositions: in, on, at.",
      "Read slowly, one sentence at a time."],
     [EX("Agreement", "She go to school. → She goes to school."),
      EX("Article", "He is a honest man. → He is an honest man."),
      EX("Preposition", "We met in Monday. → We met on Monday.", "✏️ in → on")],
     "Take a paragraph you wrote last week and find and correct at least three errors.",
     [Q("EASY", "Correct: 'He play football every day.'", ["He plays football every day.", "He playing football every day.", "He played football every day day.", "He plays footballs every days."], "He plays football every day.", "'He' needs a verb with -s.", "He plays."),
      Q("EASY", "Correct: 'She is a engineer.'", ["She is an engineer.", "She is the engineer an.", "She an engineer.", "She is engineer a."], "She is an engineer.", "'Engineer' starts with a vowel sound.", "Use 'an'."),
      Q("MEDIUM", "Find the error: 'They was playing in the park.'", ["They", "was", "playing", "park"], "was", "'They' is plural.", "'was' should be 'were'."),
      Q("MEDIUM", "Correct: 'I was born on 2010.'", ["I was born in 2010.", "I was born at 2010.", "I born in 2010.", "I was borned in 2010."], "I was born in 2010.", "Years take 'in'.", "Use 'in' with years."),
      Q("HARD", "Find the error: 'Each of the boys have a bicycle.'", ["Each", "boys", "have", "bicycle"], "have", "'Each' is singular.", "'have' should be 'has'."),
      Q("HARD", "Correct: 'Yesterday I go to the market and buy vegetables.'", ["Yesterday I went to the market and bought vegetables.", "Yesterday I goes to the market and buys vegetables.", "Yesterday I going to the market and buying vegetables.", "Yesterday I will go to the market and buy vegetables."], "Yesterday I went to the market and bought vegetables.", "'Yesterday' needs past tense.", "Both verbs change to the past: went, bought.")])],
 "Social Science": [
  CH("Nationalism in India",
     "Indian nationalism grew as people united against British colonial rule. Mahatma Gandhi returned from South Africa in 1915 and introduced satyagraha, a method of non-violent resistance. The Rowlatt Act of 1919 and the Jallianwala Bagh massacre caused widespread anger. The Non-Cooperation Movement (1920–22) asked people to boycott British goods, schools and courts; it was called off after the Chauri Chaura incident. The Civil Disobedience Movement began with the Salt March to Dandi in 1930, when Gandhi broke the salt law. Symbols like the tricolour flag and songs like 'Vande Mataram' built a sense of national unity.",
     ["Gandhi introduced satyagraha — non-violent resistance.",
      "Jallianwala Bagh massacre happened in 1919.",
      "Non-Cooperation Movement: 1920–22.",
      "Salt March to Dandi: 1930.",
      "Symbols and songs built national unity."],
     [EX("Satyagraha", "Protesting peacefully, without violence, for truth and justice.", "🕊️"),
      EX("Salt March", "Gandhi walked about 240 miles to Dandi and made salt from sea water, breaking British law.", "🚶 → 🌊 🧂"),
      EX("Boycott", "People burned foreign cloth and wore khadi.")],
     "Make a timeline of the major events of the Indian national movement from 1915 to 1930.",
     [Q("EASY", "Gandhi's method of non-violent resistance is called ___.", ["Satyagraha", "Swaraj", "Boycott", "Khadi"], "Satyagraha", "'Satya' means truth.", "It is satyagraha."),
      Q("EASY", "The Salt March ended at ___.", ["Dandi", "Delhi", "Mumbai", "Kolkata"], "Dandi", "A coastal village in Gujarat.", "Gandhi marched to Dandi."),
      Q("MEDIUM", "In which year did the Jallianwala Bagh massacre take place?", [], "1919", "Same year as the Rowlatt Act.", "It happened in 1919."),
      Q("MEDIUM", "Why was the Non-Cooperation Movement called off?", ["The Chauri Chaura incident turned violent", "The British left India", "Gandhi fell ill", "It succeeded fully"], "The Chauri Chaura incident turned violent", "Gandhi opposed violence.", "Violence at Chauri Chaura led Gandhi to stop it."),
      Q("HARD", "The Civil Disobedience Movement began with the ___.", ["Salt March", "Quit India call", "Partition of Bengal", "Kheda Satyagraha"], "Salt March", "1930.", "It began with the Dandi March."),
      Q("HARD", "What did people boycott during Non-Cooperation?", ["British goods, schools and courts", "Indian festivals", "Local markets", "Their own villages"], "British goods, schools and courts", "Refusing to cooperate with British rule.", "They boycotted British institutions and goods.")]),
  CH("Sectors of the Indian Economy",
     "Economic activities are grouped into three sectors. The primary sector uses natural resources directly, such as agriculture, fishing and mining. The secondary sector turns raw materials into products through manufacturing. The tertiary (service) sector provides services such as transport, banking, education and health. GDP is the value of all final goods and services produced in a year. In India, the tertiary sector produces the largest share of GDP, but the primary sector still employs the most people, which shows underemployment. Jobs can also be organised (regular, with benefits) or unorganised (irregular, low protection).",
     ["Primary sector: uses natural resources (farming, mining).",
      "Secondary sector: manufacturing.",
      "Tertiary sector: services (banking, transport, teaching).",
      "Tertiary sector gives the largest share of India's GDP.",
      "Organised jobs are regular with benefits; unorganised are not."],
     [EX("One product, three sectors", "Cotton is grown (primary), made into cloth (secondary), and sold via a shop and truck (tertiary).", "🌱 → 🏭 → 🚚🏪"),
      EX("Underemployment", "Five family members work on a small farm where three would be enough."),
      EX("Organised job", "A bank employee gets a fixed salary, paid leave and a pension.")],
     "List the jobs of five adults you know and classify each into a sector.",
     [Q("EASY", "Farming belongs to the ___ sector.", ["Primary", "Secondary", "Tertiary"], "Primary", "It uses nature directly.", "Agriculture is primary."),
      Q("EASY", "Banking belongs to the ___ sector.", ["Tertiary", "Primary", "Secondary"], "Tertiary", "It is a service.", "Banking is a service: tertiary."),
      Q("MEDIUM", "Manufacturing belongs to the ___ sector.", [], "secondary", "Factories.", "It is the secondary sector."),
      Q("MEDIUM", "Which sector contributes the largest share of India's GDP?", ["Tertiary", "Primary", "Secondary"], "Tertiary", "Services have grown fastest.", "The service sector is largest."),
      Q("HARD", "More people working on a farm than needed is called ___.", ["Underemployment (disguised unemployment)", "Full employment", "Overtime", "Retirement"], "Underemployment (disguised unemployment)", "Some workers add nothing extra.", "It is disguised unemployment."),
      Q("HARD", "Which is a feature of the organised sector?", ["Regular salary and job security", "No fixed hours or benefits", "Daily wages only", "No registration"], "Regular salary and job security", "Think of government jobs.", "Organised jobs are regular and protected.")])],
}
