# Additional chapters for Grade 9.
from grade6 import Q, EX
from more6_7 import CH

MORE9 = {
 "Mathematics": [
  CH("Triangles",
     "Two triangles are congruent if they have exactly the same shape and size. We can prove congruence using rules: SAS (two sides and the included angle), ASA (two angles and the included side), SSS (three sides), and RHS (right angle, hypotenuse and one side). Corresponding parts of congruent triangles are equal (CPCT). In an isosceles triangle, the angles opposite the equal sides are equal. The sum of the angles of any triangle is 180°.",
     ["Congruent triangles have the same shape and size.",
      "Congruence rules: SAS, ASA, SSS, RHS.",
      "CPCT: corresponding parts of congruent triangles are equal.",
      "In an isosceles triangle, base angles are equal.",
      "Angles of a triangle add up to 180°."],
     [EX("SSS", "If all three sides of △ABC equal those of △PQR, the triangles are congruent.", "  /\\      /\\\n /__\\  ≅ /__\\"),
      EX("Isosceles", "If AB = AC, then ∠B = ∠C."),
      EX("Angle sum", "If two angles are 50° and 60°, the third is 70°.")],
     "Cut two triangles from paper with the same three side lengths and check if they fit exactly on each other.",
     [Q("EASY", "The sum of the angles of a triangle is ___°.", [], "180", "A straight line's angle.", "It is always 180°."),
      Q("EASY", "Congruent triangles have the same ___.", ["Shape and size", "Colour", "Position", "Name"], "Shape and size", "They fit exactly on each other.", "They are identical in shape and size."),
      Q("MEDIUM", "Two angles of a triangle are 45° and 75°. The third angle is ___°.", [], "60", "180 − (45 + 75).", "180 − 120 = 60°."),
      Q("MEDIUM", "Which is NOT a congruence rule?", ["SAS", "SSS", "AAA", "ASA"], "AAA", "Equal angles alone don't fix the size.", "AAA only proves similarity, not congruence."),
      Q("HARD", "In △ABC, AB = AC and ∠B = 50°. What is ∠A?", [], "80|80°", "∠C = ∠B in an isosceles triangle.", "∠A = 180 − 50 − 50 = 80°."),
      Q("HARD", "RHS congruence applies only to ___ triangles.", ["Right-angled", "Equilateral", "Obtuse", "All"], "Right-angled", "R stands for right angle.", "RHS is for right-angled triangles.")]),
  CH("Heron's Formula",
     "Heron's formula finds the area of a triangle when all three sides are known, without needing the height. First find the semi-perimeter s = (a + b + c) ÷ 2. Then area = √[s(s − a)(s − b)(s − c)]. It is useful for triangular plots of land or signboards where measuring height is hard. For an equilateral triangle of side a, the area is (√3/4)a².",
     ["Use Heron's formula when you know all three sides.",
      "Semi-perimeter s = (a + b + c) ÷ 2.",
      "Area = √[s(s − a)(s − b)(s − c)].",
      "No height is needed.",
      "Equilateral triangle area = (√3/4)a²."],
     [EX("Example", "Sides 3, 4, 5: s = 6, area = √(6 × 3 × 2 × 1) = √36 = 6.", "3-4-5 △ → area 6"),
      EX("Land plot", "A triangular field with sides 13 m, 14 m, 15 m: s = 21, area = √(21 × 8 × 7 × 6) = 84 m²."),
      EX("Equilateral", "Side 2: area = (√3/4) × 4 = √3.")],
     "Measure the three sides of a triangular object (like a set square) and find its area with Heron's formula.",
     [Q("EASY", "Semi-perimeter of a triangle with sides 5, 6, 7?", [], "9", "(5 + 6 + 7) ÷ 2.", "18 ÷ 2 = 9."),
      Q("EASY", "Heron's formula needs the lengths of ___.", ["All three sides", "The height only", "Two angles", "One side"], "All three sides", "No height is needed.", "It uses all three sides."),
      Q("MEDIUM", "Area of a triangle with sides 3, 4, 5?", [], "6", "s = 6; √(6 × 3 × 2 × 1).", "√36 = 6."),
      Q("MEDIUM", "Area of a triangle with sides 6, 8, 10?", [], "24", "s = 12; √(12 × 6 × 4 × 2).", "√576 = 24."),
      Q("HARD", "Area of a triangle with sides 13, 14, 15?", [], "84", "s = 21.", "√(21 × 8 × 7 × 6) = √7056 = 84."),
      Q("HARD", "Area of an equilateral triangle with side 4 (in terms of √3)?", ["4√3", "2√3", "16√3", "8√3"], "4√3", "(√3/4) × a².", "(√3/4) × 16 = 4√3.")])],
 "Physics": [
  CH("Work and Energy",
     "In physics, work is done when a force moves an object in the direction of the force: W = F × s, measured in joules (J). Energy is the ability to do work. Kinetic energy is energy of motion, KE = ½mv². Potential energy is stored energy due to height, PE = mgh. The law of conservation of energy says energy cannot be created or destroyed, only changed from one form to another. Power is the rate of doing work, P = W ÷ t, measured in watts (W).",
     ["Work W = force × displacement, in joules.",
      "Energy is the ability to do work.",
      "Kinetic energy KE = ½mv².",
      "Potential energy PE = mgh.",
      "Power = work ÷ time, in watts."],
     [EX("Work", "Pushing a box with 10 N for 5 m does 50 J of work.", "📦 → 5 m  (10 N)"),
      EX("Falling ball", "A ball's potential energy at the top changes into kinetic energy as it falls.", "⚪ PE\n ⬇\n⚪ KE"),
      EX("No work", "Holding a heavy bag still does no work in physics, because it doesn't move.")],
     "Walk up a flight of stairs and time it. Estimate your power using P = mgh ÷ t.",
     [Q("EASY", "The SI unit of work is the ___.", ["Joule", "Watt", "Newton", "Metre"], "Joule", "Symbol J.", "Work is measured in joules."),
      Q("EASY", "Energy of a moving object is ___ energy.", ["Kinetic", "Potential", "Chemical", "Nuclear"], "Kinetic", "'Kinetic' relates to motion.", "Moving objects have kinetic energy."),
      Q("MEDIUM", "Work done when a 20 N force moves a box 3 m (J)?", [], "60", "W = F × s.", "20 × 3 = 60 J."),
      Q("MEDIUM", "PE of a 2 kg mass at 5 m height (g = 10 m/s²), in J?", [], "100", "PE = mgh.", "2 × 10 × 5 = 100 J."),
      Q("HARD", "KE of a 4 kg object moving at 3 m/s (J)?", [], "18", "KE = ½mv².", "½ × 4 × 9 = 18 J."),
      Q("HARD", "A machine does 600 J of work in 20 s. Its power (W)?", [], "30", "P = W ÷ t.", "600 ÷ 20 = 30 W.")]),
  CH("Sound",
     "Sound is a mechanical wave that travels as compressions and rarefactions of the medium, so it is a longitudinal wave. Wavelength (λ) is the distance between two compressions, frequency (f) is the number of waves per second, and speed v = f × λ. Sound travels fastest in solids and slowest in gases; in air it is about 340 m/s. An echo is a reflected sound heard after at least 0.1 s, so the reflecting surface must be at least about 17 m away. Ultrasound (above 20,000 Hz) is used in medical scans and SONAR.",
     ["Sound is a longitudinal wave.",
      "It travels as compressions and rarefactions.",
      "Speed v = frequency × wavelength.",
      "Sound is fastest in solids.",
      "An echo is reflected sound; ultrasound is above 20 kHz."],
     [EX("Wave equation", "f = 500 Hz, λ = 0.68 m → v = 340 m/s.", "|||  |||  |||  (compressions)"),
      EX("Echo", "Shout in a large empty hall or near a cliff and hear your voice come back.", "🗣️ → 🏔️ → 👂"),
      EX("SONAR", "Ships send ultrasound down and time the echo to measure sea depth.")],
     "Stand far from a big wall, clap, and listen for the echo. Estimate the distance using the speed of sound.",
     [Q("EASY", "Sound is a ___ wave.", ["Longitudinal", "Transverse", "Light", "Electromagnetic"], "Longitudinal", "Particles vibrate along the direction of travel.", "Sound is longitudinal."),
      Q("EASY", "Sound travels fastest in ___.", ["Solids", "Liquids", "Gases", "Vacuum"], "Solids", "Particles are closest.", "Solids carry sound fastest."),
      Q("MEDIUM", "v = f × λ. If f = 200 Hz and λ = 1.7 m, v = ? (m/s)", [], "340", "Multiply.", "200 × 1.7 = 340 m/s."),
      Q("MEDIUM", "Sound with frequency above 20,000 Hz is called ___.", ["Ultrasound", "Infrasound", "Echo", "Noise"], "Ultrasound", "'Ultra' means beyond.", "It is ultrasound."),
      Q("HARD", "An echo returns after 2 s. Speed of sound 340 m/s. Distance to the wall (m)?", [], "340", "Sound goes there and back: d = v × t ÷ 2.", "340 × 2 ÷ 2 = 340 m."),
      Q("HARD", "Why can't we hear an echo in a small room?", ["The reflected sound returns in less than 0.1 s", "Rooms absorb all sound", "Sound can't reflect indoors", "Air is too thin"], "The reflected sound returns in less than 0.1 s", "The brain needs a gap to hear it separately.", "The echo arrives too soon to be heard separately.")])],
 "Chemistry": [
  CH("Is Matter Around Us Pure?",
     "A pure substance has only one kind of particle, such as an element (like gold) or a compound (like water). A mixture contains two or more substances not chemically combined, such as air or salt water. Homogeneous mixtures (solutions) have a uniform composition; heterogeneous mixtures do not. A solution has a solute dissolved in a solvent. A suspension has particles that settle, and a colloid has particles that stay spread out and scatter light (the Tyndall effect). Mixtures can be separated by methods like evaporation, filtration, distillation and chromatography.",
     ["Pure substances: elements and compounds.",
      "Mixtures are not chemically combined.",
      "Homogeneous mixtures (solutions) are uniform.",
      "Colloids scatter light: the Tyndall effect.",
      "Chromatography and distillation separate mixtures."],
     [EX("Solution", "Sugar dissolved in water is a solution: sugar is the solute, water is the solvent.", "🍬 + 💧 = uniform"),
      EX("Tyndall effect", "Sunlight beams are visible in a dusty room because dust particles scatter light.", "☀️ ⟶ ░░░"),
      EX("Chromatography", "Ink on filter paper separates into different colours as water rises.", "🟣 → 🔵🔴🟡")],
     "Put a dot of black sketch-pen ink on filter paper, dip the edge in water and watch the colours separate.",
     [Q("EASY", "Which is a pure substance?", ["Air", "Salt water", "Gold", "Soil"], "Gold", "It has one kind of atom.", "Gold is an element."),
      Q("EASY", "In salt water, the salt is the ___.", ["Solute", "Solvent", "Colloid", "Suspension"], "Solute", "It is dissolved.", "The dissolved substance is the solute."),
      Q("MEDIUM", "The scattering of light by colloidal particles is the ___ effect.", [], "tyndall", "Named after a scientist.", "It is the Tyndall effect."),
      Q("MEDIUM", "A mixture with uniform composition is ___.", ["Homogeneous", "Heterogeneous"], "Homogeneous", "'Homo' means same.", "Uniform mixtures are homogeneous."),
      Q("HARD", "Which method separates the colours in ink?", ["Chromatography", "Filtration", "Sieving", "Magnetic separation"], "Chromatography", "'Chroma' means colour.", "Chromatography separates dyes."),
      Q("HARD", "Which is a colloid?", ["Milk", "Salt solution", "Sand in water", "Sugar solution"], "Milk", "Its particles don't settle but scatter light.", "Milk is a colloid.")]),
  CH("Valency and Chemical Formulae",
     "Valency is the combining capacity of an element — how many bonds it forms or electrons it gives, takes or shares to become stable. For example, hydrogen has valency 1, oxygen 2 and nitrogen 3. Ions are charged atoms or groups of atoms; polyatomic ions such as sulphate (SO₄²⁻) and nitrate (NO₃⁻) act as a unit. To write a formula, write the symbols, then cross over the valencies: aluminium (3) and oxygen (2) give Al₂O₃. Formula unit mass is the sum of the atomic masses in the formula.",
     ["Valency is the combining capacity of an element.",
      "H = 1, O = 2, N = 3, C = 4.",
      "Ions are charged atoms or groups.",
      "Criss-cross the valencies to write formulae.",
      "Polyatomic ions like SO₄²⁻ act as one unit."],
     [EX("Criss-cross", "Ca (2) and Cl (1) → CaCl₂.", "Ca² Cl¹ → Ca₁Cl₂"),
      EX("Aluminium oxide", "Al (3) and O (2) → Al₂O₃."),
      EX("Polyatomic", "Sodium (1) and sulphate (2) → Na₂SO₄.")],
     "Make flash cards with elements and their valencies, then combine pairs to write formulae.",
     [Q("EASY", "What is the valency of hydrogen?", [], "1|one", "It forms one bond.", "Hydrogen has valency 1."),
      Q("EASY", "The formula of water is ___.", ["H₂O", "HO₂", "H₂O₂", "OH"], "H₂O", "Two hydrogens, one oxygen.", "Water is H₂O."),
      Q("MEDIUM", "Formula of magnesium chloride (Mg valency 2, Cl valency 1)?", ["MgCl₂", "MgCl", "Mg₂Cl", "Mg₂Cl₃"], "MgCl₂", "Criss-cross the valencies.", "Mg¹Cl₂ → MgCl₂."),
      Q("MEDIUM", "What is the valency of oxygen?", [], "2|two", "Think of H₂O.", "Oxygen has valency 2."),
      Q("HARD", "Formula of aluminium oxide (Al 3, O 2)?", ["Al₂O₃", "Al₃O₂", "AlO", "AlO₃"], "Al₂O₃", "Criss-cross 3 and 2.", "Al₂O₃."),
      Q("HARD", "Formula unit mass of NaCl (Na = 23, Cl = 35.5), in u?", [], "58.5", "Add the atomic masses.", "23 + 35.5 = 58.5 u.")])],
 "Biology": [
  CH("Diversity in Living Organisms",
     "There are millions of kinds of living organisms, so scientists group them by shared features. Whittaker's five-kingdom classification has Monera (bacteria, with no true nucleus), Protista (single-celled organisms with a nucleus, like Amoeba), Fungi (like mushrooms, which absorb food), Plantae (plants, which make their own food) and Animalia (animals). Each organism has a scientific name in two parts, the genus and the species, such as Homo sapiens. Classification makes it easier to study living things and understand how they are related.",
     ["Organisms are grouped by shared features.",
      "Whittaker proposed five kingdoms.",
      "Monera, Protista, Fungi, Plantae, Animalia.",
      "Monera have no true nucleus.",
      "Scientific names have a genus and species."],
     [EX("Five kingdoms", "Bacteria (Monera), Amoeba (Protista), mushroom (Fungi), mango tree (Plantae), tiger (Animalia).", "🦠 🔬 🍄 🌳 🐯"),
      EX("Fungi", "Mushrooms can't make food; they absorb it from dead matter."),
      EX("Scientific name", "The tiger is Panthera tigris.")],
     "Make a chart of 10 living things around you and place each in one of the five kingdoms.",
     [Q("EASY", "Mushrooms belong to the kingdom ___.", ["Fungi", "Plantae", "Animalia", "Monera"], "Fungi", "They don't make their own food.", "Mushrooms are fungi."),
      Q("EASY", "How many kingdoms are in Whittaker's classification?", [], "5|five", "Monera, Protista, ...", "There are five kingdoms."),
      Q("MEDIUM", "Bacteria belong to the kingdom ___.", ["Monera", "Protista", "Fungi", "Plantae"], "Monera", "They have no true nucleus.", "Bacteria are Monera."),
      Q("MEDIUM", "Amoeba belongs to the kingdom ___.", ["Protista", "Monera", "Fungi", "Animalia"], "Protista", "Single-celled with a nucleus.", "Amoeba is a protist."),
      Q("HARD", "Which kingdom's members make their own food by photosynthesis?", ["Plantae", "Fungi", "Animalia", "Monera only"], "Plantae", "They are green.", "Plants photosynthesise."),
      Q("HARD", "Who proposed the five-kingdom classification?", ["R. H. Whittaker", "Carolus Linnaeus", "Charles Darwin", "Robert Hooke"], "R. H. Whittaker", "He proposed it in 1969.", "Whittaker proposed five kingdoms.")]),
  CH("Improvement in Food Resources",
     "To feed a growing population, we need to produce more food without harming the environment. Crop yield can be improved by using better seed varieties (hybridisation), good nutrient management with manure and fertilisers, proper irrigation, and protection from pests, weeds and diseases. Mixed cropping and crop rotation keep soil healthy. Animal husbandry improves the production of milk, eggs and meat through good care, feed and breeds. Fish farming (aquaculture) and bee-keeping (apiculture) are other ways to produce food.",
     ["Better seeds improve crop yield.",
      "Manure and fertilisers provide nutrients.",
      "Crop rotation keeps soil healthy.",
      "Animal husbandry is caring for farm animals.",
      "Apiculture is bee-keeping; aquaculture is fish farming."],
     [EX("Hybrid seeds", "Crossing two wheat varieties can give a new variety with higher yield and disease resistance."),
      EX("Crop rotation", "Growing peas after wheat adds nitrogen back to the soil.", "🌾 → 🫛 → 🌾"),
      EX("Apiculture", "Bee-keepers collect honey and wax from bee boxes.", "🐝🍯")],
     "Visit a local farm or market and ask which seeds, fertilisers or animal breeds the farmers prefer and why.",
     [Q("EASY", "Bee-keeping is called ___.", ["Apiculture", "Pisciculture", "Sericulture", "Horticulture"], "Apiculture", "'Apis' means bee.", "Bee-keeping is apiculture."),
      Q("EASY", "Growing different crops one after another on the same land is ___.", ["Crop rotation", "Mixed cropping", "Weeding", "Irrigation"], "Crop rotation", "Crops 'rotate'.", "That is crop rotation."),
      Q("MEDIUM", "Which is an organic source of nutrients?", ["Manure", "Urea", "NPK", "Pesticide"], "Manure", "It comes from animal and plant waste.", "Manure is organic."),
      Q("MEDIUM", "Rearing farm animals for milk, eggs and meat is ___.", [], "animal husbandry", "It involves care and feeding.", "This is animal husbandry."),
      Q("HARD", "Why do farmers grow legumes like peas in crop rotation?", ["They add nitrogen to the soil", "They need no water", "They kill all pests", "They grow fastest"], "They add nitrogen to the soil", "Root nodules have helpful bacteria.", "Legumes fix nitrogen and enrich the soil."),
      Q("HARD", "Crossing two varieties to get better features is called ___.", ["Hybridisation", "Irrigation", "Fumigation", "Mutation only"], "Hybridisation", "Hybrid seeds come from it.", "It is hybridisation.")])],
 "English": [
  CH("Gerunds and Infinitives",
     "A gerund is the -ing form of a verb used as a noun: Swimming is fun. An infinitive is 'to' + the base verb: I want to swim. Some verbs are followed by gerunds (enjoy, avoid, finish, keep), and some by infinitives (want, decide, hope, plan). A few verbs, like like, love and start, can take either. After prepositions we always use a gerund: She is good at drawing.",
     ["Gerund = verb + -ing used as a noun.",
      "Infinitive = to + base verb.",
      "enjoy, avoid, finish + gerund.",
      "want, decide, hope + infinitive.",
      "After a preposition, use a gerund."],
     [EX("Gerund as subject", "Reading improves your vocabulary.", "📖 Reading = noun"),
      EX("Infinitive", "She decided to learn French."),
      EX("After preposition", "He is interested in painting.")],
     "Write five things you enjoy doing (gerunds) and five things you want to do (infinitives).",
     [Q("EASY", "I enjoy ___ books.", ["reading", "to read", "read", "reads"], "reading", "'Enjoy' takes a gerund.", "enjoy + reading."),
      Q("EASY", "She wants ___ a doctor.", ["to become", "becoming", "become", "becomes"], "to become", "'Want' takes an infinitive.", "want + to become."),
      Q("MEDIUM", "___ is good exercise.", ["Swimming", "To swimming", "Swim", "Swims"], "Swimming", "The subject is an activity (a noun).", "The gerund 'Swimming' is the subject."),
      Q("MEDIUM", "He is good at ___.", ["drawing", "to draw", "draw", "draws"], "drawing", "After a preposition...", "Prepositions are followed by gerunds."),
      Q("HARD", "They decided ___ early.", ["to leave", "leaving", "leave", "left"], "to leave", "'Decide' takes an infinitive.", "decide + to leave."),
      Q("HARD", "Please avoid ___ in the library.", ["talking", "to talk", "talk", "talked"], "talking", "'Avoid' takes a gerund.", "avoid + talking.")]),
  CH("Paragraph Writing",
     "A paragraph is a group of sentences about one main idea. It begins with a topic sentence that states the main idea. Supporting sentences then give details, examples or reasons. A concluding sentence sums up or links to the next idea. A good paragraph is unified (every sentence is about the main idea) and coherent (ideas flow in a logical order), using linking words like first, also, however and finally.",
     ["A paragraph is about one main idea.",
      "The topic sentence states the main idea.",
      "Supporting sentences give details and examples.",
      "A concluding sentence sums up.",
      "Use linking words: first, also, however, finally."],
     [EX("Topic sentence", "Trees are very important for our planet."),
      EX("Supporting details", "They give us oxygen. They provide shade and homes for birds. They also stop soil erosion.", "🌳 → O₂, 🐦, ⛰️"),
      EX("Conclusion", "Therefore, we should plant more trees and protect forests.")],
     "Write a paragraph of 6–8 sentences about your favourite festival with a clear topic sentence.",
     [Q("EASY", "The sentence that states the main idea of a paragraph is the ___ sentence.", ["Topic", "Concluding", "Supporting", "Linking"], "Topic", "It usually comes first.", "The topic sentence gives the main idea."),
      Q("EASY", "A paragraph should be about ___.", ["One main idea", "Many unrelated ideas", "Only examples", "Only questions"], "One main idea", "It must be unified.", "One main idea per paragraph."),
      Q("MEDIUM", "Which is a linking word?", ["However", "Tree", "Blue", "Quickly run"], "However", "It connects ideas.", "'However' links contrasting ideas."),
      Q("MEDIUM", "Supporting sentences give ___.", ["Details, examples or reasons", "Only the title", "A new topic", "The date"], "Details, examples or reasons", "They support the topic sentence.", "They add details and examples."),
      Q("HARD", "In a paragraph about healthy eating, which sentence does NOT belong?", ["Fruits give us vitamins.", "Vegetables provide fibre.", "My cousin lives in Pune.", "Drinking water keeps us hydrated."], "My cousin lives in Pune.", "Unity means every sentence is on topic.", "It is not about healthy eating."),
      Q("HARD", "A paragraph whose ideas flow logically is ___.", ["Coherent", "Incoherent", "Random", "Repetitive"], "Coherent", "Ideas 'cohere' or stick together.", "Logical flow is coherence.")])],
 "Social Science": [
  CH("Physical Features of India",
     "India has six major physical divisions. The Himalayan Mountains in the north are young fold mountains with the highest peaks. The Northern Plains, formed by the Indus, Ganga and Brahmaputra rivers, are fertile and densely populated. The Peninsular Plateau is an old, stable landmass of hard rocks. The Indian Desert (Thar) lies in the west. The Coastal Plains run along the east and west coasts. The Islands include Lakshadweep in the Arabian Sea and Andaman and Nicobar in the Bay of Bengal.",
     ["The Himalayas are young fold mountains in the north.",
      "The Northern Plains are fertile river plains.",
      "The Peninsular Plateau is old and made of hard rocks.",
      "The Thar Desert lies in the west.",
      "Islands: Lakshadweep and Andaman & Nicobar."],
     [EX("Six divisions", "Mountains, plains, plateau, desert, coastal plains, islands.", "🏔️ 🌾 ⛰️ 🏜️ 🏖️ 🏝️"),
      EX("Northern Plains", "Rivers bring fertile alluvial soil, making the plains great for farming."),
      EX("Islands", "Lakshadweep islands are made of coral.")],
     "Use a physical map of India to trace each of the six divisions with a different colour.",
     [Q("EASY", "The mountains in the north of India are the ___.", ["Himalayas", "Western Ghats", "Aravalli", "Vindhya"], "Himalayas", "They have Mount Everest nearby.", "The Himalayas are in the north."),
      Q("EASY", "The Thar Desert is in the ___ of India.", ["West", "East", "South", "North-east"], "West", "It is in Rajasthan.", "The Thar is in the west."),
      Q("MEDIUM", "The Northern Plains were formed by which rivers?", ["Indus, Ganga and Brahmaputra", "Godavari and Krishna", "Narmada and Tapi", "Kaveri only"], "Indus, Ganga and Brahmaputra", "Three big Himalayan rivers.", "These rivers deposited alluvium."),
      Q("MEDIUM", "Lakshadweep islands are made of ___.", ["Coral", "Volcanic rock only", "Sand dunes", "Ice"], "Coral", "Tiny sea animals build them.", "They are coral islands."),
      Q("HARD", "Which is the oldest landmass of India?", ["Peninsular Plateau", "Himalayas", "Northern Plains", "Coastal Plains"], "Peninsular Plateau", "It is made of hard, ancient rocks.", "The Peninsular Plateau is the oldest."),
      Q("HARD", "The Himalayas are ___ mountains.", ["Young fold", "Old block", "Volcanic", "Residual"], "Young fold", "They formed when plates collided.", "They are young fold mountains.")]),
  CH("Electoral Politics",
     "In a democracy, people choose their representatives through elections. India is divided into constituencies, and each elects one representative; voters choose among candidates from different political parties. Elections are held regularly — Lok Sabha elections every five years. The Election Commission of India is an independent body that conducts free and fair elections. Every citizen aged 18 or above can vote (universal adult franchise). Some constituencies are reserved for Scheduled Castes and Scheduled Tribes so that they are fairly represented.",
     ["Elections let people choose representatives.",
      "The country is divided into constituencies.",
      "Lok Sabha elections are held every five years.",
      "The Election Commission conducts elections.",
      "Some seats are reserved for SC and ST."],
     [EX("Constituency", "A city may have one Lok Sabha constituency; its voters elect one MP.", "🗺️ → 🗳️ → 👤 MP"),
      EX("Election Commission", "It announces dates, sets rules and makes sure voting is fair."),
      EX("Reserved seats", "Only SC candidates can contest from an SC-reserved constituency, but everyone votes.")],
     "Find out the name of your Lok Sabha constituency and your current MP.",
     [Q("EASY", "Lok Sabha elections are held every ___ years.", [], "5|five", "It is the term of the Lok Sabha.", "Every five years."),
      Q("EASY", "Which body conducts elections in India?", ["Election Commission", "Supreme Court", "RBI", "Parliament"], "Election Commission", "It is independent.", "The Election Commission conducts elections."),
      Q("MEDIUM", "An area that elects one representative is a ___.", ["Constituency", "State", "Village", "District"], "Constituency", "It is an electoral area.", "It is a constituency."),
      Q("MEDIUM", "The minimum voting age in India is ___.", [], "18", "Adulthood.", "18 years."),
      Q("HARD", "Why are some constituencies reserved for SC and ST?", ["To ensure fair representation of weaker sections", "To stop people from voting", "To reduce elections", "To favour rich candidates"], "To ensure fair representation of weaker sections", "Think about equality.", "Reservation ensures these groups are represented."),
      Q("HARD", "Which is necessary for an election to be democratic?", ["Voters have a real choice", "Only one party contests", "Results are fixed", "The army picks winners"], "Voters have a real choice", "Free and fair elections.", "Real choice is essential.")])],
}
